### ISSUE TITLE
Implement render to texture, modifier volumes, fog, clipping, proper sorting... maybe framebuffer writes and reads too?

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#10]
Just some wishful thinking.

**Comment by skmp** [comment]
@MrPsyMan we need to split those to actionable tasks at some point

**Comment by asiekierka** [comment]
Framebuffer reads and writes would be useful for simple homebrew development debugging.

**Comment by skmp** [comment]
Mostly implemented, see #1523
