### ISSUE TITLE
Star Wars-Episode 1-Jedi Power Battles green floor (graphical bug)

### ISSUE THREAD

**Issue by blackman91** [reicast/reicast-emulator#1000]
http://imgur.com/oBNUu2v

Using latest dev build on android, anyone knows how to fix it?

**Comment by blackman91** [comment]
It seems this does not happen in the stable version on the play store, regression?

**Comment by WolfSama** [comment]
This matter can be solved BUT when you come to rescue the queen in teed there is no way to pass that level,he game will crash,i try with r6 official and some builds,this game is impossible to finish,i try with Qui Guon Jin,but in the end of the level the game will crash,just tell me if you have a solution for it.

**Comment by WolfSama** [comment]
Well if be possible clear this game please let me know how because he will crash in teed palace level before the level  tatooine no matter the question of fps or whatever configuration of r6,i try some builds without sucess,maybe reicast should have some more optmizatios setings.

**Comment by LoungeKatt** [comment]
@WolfSama Your issue is different, so it was moved to https://github.com/reicast/reicast-emulator/issues/1154

**Comment by blackman91** [comment]
Moved info to gamedb too.
