### ISSUE TITLE
Reicast too fast, no sound, and 4:3 video on Raspberry Pi3-RetroPie

### ISSUE THREAD

**Issue by Grondoval** [reicast/reicast-emulator#1003]
I try Marvel Vs Capcom 2, Metropolis Street Racer and Soul Calibur, Speed is too fast (FPS limit=1), there is no sound in games (audio=1) and screen like 4:3 and low resolution (overscan=1). No Overclock but CPU on raspberry shows 1.2 Ghz

¿What config should be in Reicast from Raspberry/RetroPie?

**Comment by Grondoval** [comment]
I solved sound problem using inside reicast emulator this config

reicast-audio-oss

I try changing res to 1920x1080 60Hz 16:9 in some modes but it continues showing in 4:3 :(

**Comment by skmp** [comment]
Is this still an issue? Is this using mainline reicast or some other version bundled with some other project?

**Comment by skmp** [comment]
(Closing, ticket cleanup. Please report in discord if still an issue)
