### ISSUE TITLE
Linux: buttons.png error

### ISSUE THREAD

**Issue by danboid** [reicast/reicast-emulator#1007]
When I run reicast under ARM Ubuntu I see the error:

`Error opening /home/ubuntu/.local/share/reicast/data/buttons.png`

buttons.png does exist as part of the git tree but under shell/android/assets/buttons.png and `make install` doesn't copy buttons.png anywhere. That is probably the correct behaviour as I doubt the Linux version requires the Android skin stuff, does it? Hence I don't think I should be seeing this error.

**Comment by danboid** [comment]
The error goes away if I copy the file into place but `make install` should do that, if it really is needed under (non-Android) Linux.

**Comment by baka0815** [comment]
It would be displayed as an overlay if it's present.
I wouldn't recommend using the ``buttons.png`` as it's a bit confusing on a desktop, but it might come in handy debugging.

``make install`` shouldn't copy the file as most people don't want that overlay.
