### ISSUE TITLE
Sandisk 32 gigabyte Pen drive

### ISSUE THREAD

**Issue by TheBurgerGuy** [reicast/reicast-emulator#1008]
I recently Bought a Sandisk Pen drive and all my games Run great on it, Is there a way that The reicast can Access the external drive to read games. Ppsspp allows To Go to External Drive from phone to do so. If I can run any test for you illo be up and ready.

**Comment by LoungeKatt** [comment]
What platform are you running it on? I am not sure what you mean by "Ppsspp allows To Go to External Drive from phone" because on a phone, you can access an external drive for games (just not BIOS)

**Comment by TheBurgerGuy** [comment]
Hey sorry it's been a long time I have A Samsung Galaxy S9 Now I still have the pendrive and I mean Reicast won t go past emulated Memory and won't access the External Memory, I'm sure it will if I add a SD Card but currently still have Pendrive

**Comment by TheBurgerGuy** [comment]
Also any recommendations on what Biold to use for Samsung S9.

**Comment by skmp** [comment]
Closing as this doesn't have any action items
