### ISSUE TITLE
Error in GUI with Android Nougat 7.0

### ISSUE THREAD

**Issue by fivefeet8** [reicast/reicast-emulator#1009]
The emulator will throw an error message when in the GUI.

**Comment by LoungeKatt** [comment]
Can you provide a log of the error? Or even the error message content?

**Comment by BorjaRRR** [comment]
https://www.mediafire.com/view/0c2e2k9b151g9g9/Screenshot_20170515-231057.png

**Comment by LoungeKatt** [comment]
To quote the developers at VideoLan:

> The fact that some Google engineer on a whim decided to arbitrarily
> break user space for no good reason by forbidding relocations is
> absolutely ridiculous and it affects many other software projects
> (such as FFmpeg/libav) as well.

So yeah, this is going to take a little bit to resolve.

**Comment by mattmon** [comment]
This issue prevents Reicast from running on all newer android devices, including the recent update to nVidia shield.

[Google blog post](https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html) suggest the command **scanelf -qT libdc.so** which outputs:

  `libdc.so: (memory/data?) [0x80BA34] in (optimized out: previous libwebsocket_service) [0x809D70]
  libdc.so: (memory/data?) [0x80BA38] in (optimized out: previous libwebsocket_service) [0x809D70]
  libdc.so`

So maybe building without cloud VMU (or whatever uses libwebsocket) will fix this?

**Comment by mattmon** [comment]
I rebuilt the apk without webui and with -fPIC -pie cppflags.

TEXTREL related to webui seem to be gone, but now have some others.

The command **scanelf -qT libdc.so** outputs:
`  libdc.so: (memory/data?) [0x7FB234] in (optimized out: previous Java_com_reicast_emulator_emu_JNIdc_cheatdisk) [0x189F0]
  libdc.so: (memory/data?) [0x7FB238] in (optimized out: previous Java_com_reicast_emulator_emu_JNIdc_cheatdisk) [0x189F0]
  libdc.so'

This is about as far as I can take it, hopefully helpful to someone more familiar with the code.

Here's the resulting APK - totally untested
[reicast-debug.apk.zip](https://github.com/reicast/reicast-emulator/files/1203235/reicast-debug.apk.zip)

**Comment by Luca1991** [comment]
@mattmon I received an email this morning regarding the possibility that CloudVMU is causing textrel, but I can't find the full message here on GitHub. Have you removed it?

Anyway I have to fix the CloudVMU stuff... Dropbox deprecated the API I was using, so I need to update it. I haven't the time yet, sorry :( I'll try this week if I'll find some free time.

**Comment by mattmon** [comment]
@Luca1991 

After actually looking at the code, I don't think Cloud VMU has anything to do with it.
Sorry for the confusion!

Thanks for making such a cool feature, would love to see it updated for Gdrive compatibility :)

**Comment by skmp** [comment]
This should be fixed in 3b35e6370eac5c63c7dbdc928fa9eeea4b1fa189
