### ISSUE TITLE
Reicast - Emulator Compiling in Linux ARM On Tegra TK1

### ISSUE THREAD

**Issue by aperfeito** [reicast/reicast-emulator#1011]
Hi I using 
Linux alarm 3.10.18-18-ARCH #5 SMP Mon Feb 20 14:21:15 PST 2017 armv7l GNU/Linux
Nvidia Tegra TK1

and after make I get this : 
gcc  -mfloat-abi=hard -march=armv7-a  -D TARGET_BEAGLE -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize  -I../../core -I../../core/deps -I../../core/khronos ../../core/rec-ARM/ngen_arm.S -o obj-dreamcast-armv7h/rec-ARM/ngen_arm.build_obj
../../core/rec-ARM/ngen_arm.S: Assembler messages:
../../core/rec-ARM/ngen_arm.S:268: Error: VFP single precision register expected -- `vldm r2,{d16-d24}'
../../core/rec-ARM/ngen_arm.S:271: Error: selected FPU does not support instruction -- `vmul.f32 Q2,Q8,d0[0]'
../../core/rec-ARM/ngen_arm.S:272: Error: selected FPU does not support instruction -- `vmla.f32 Q2,Q9,d0[1]'
../../core/rec-ARM/ngen_arm.S:273: Error: selected FPU does not support instruction -- `vmla.f32 Q2,Q10,d1[0]'
../../core/rec-ARM/ngen_arm.S:274: Error: selected FPU does not support instruction -- `vmla.f32 Q2,Q11,d1[1]'
../../core/rec-ARM/ngen_arm.S:294: Error: selected FPU does not support instruction -- `vmul.f32 q0,q1'
../../core/rec-ARM/ngen_arm.S:296: Error: selected processor does not support `vpadd.f32 d0,d0,d1' in ARM mode
../../core/rec-ARM/ngen_arm.S:297: Error: selected processor does not support `vpadd.f32 d0,d0,d0' in ARM mode
make: *** [Makefile:326: obj-dreamcast-armv7h/rec-ARM/ngen_arm.build_obj] Error 1

**Comment by rrrh** [comment]
Hi @aperfeito 
Is this still an issue for you?

What kind of Board, BSP and Vendor are you working on?

**Comment by aperfeito** [comment]
Hi rrrsh.

No anymore look below:

Plataform:
Linux- HP ChormeBook 14 G3
Your emulator now running under Linux distro ARCHLINUX
Kernel version:3.10.18-24-ARCH 
Processor : TegraTK1 Board Nyan-Blaze 
GPU: Keppler model GK20A
Xorg server with HW acceleration Version 17.1
4GB of Memory
________________________________________________________
Two extreme situation with your emulator:
The Worst
When I change as you said and use alsa as sound your emulator show up the window in the middle of the screen 640 X 480 the bios of the Dremacast wont start the window goes off the screen and your emulator give a dump error as below:

    https://pastebin.com/fK3SRZKw
                                         The Best:

When I change as you said and use pulse as sound your emulator show up the window in the middle of the screen 640 X 480 the bios of the Dremacast start with a beautifull sound , controle test begin, screen test begin the window stay in the screen and your emulator running like a charm

You need to fix for us LINUX-ARM users

Everything runnig here as this way look at : https://pastebin.com/g5YFkxb7

After a YEAR waiting

PS: Because that many company's not adopt linux as productive 24/7 OS

Regards
Perfeito Alexandre
