### ISSUE TITLE
Amazon fire tv analog trigger issue

### ISSUE THREAD

**Issue by pishcakes** [reicast/reicast-emulator#1013]
Hey guys, got really excited to play code veronica on the fire tv, but I can't stand using the bumpers. Any work around as of now? Thanks

**Comment by uhbandduhn** [comment]
Assuming you're using only touch as your interface.  Try to map to volume
control.  Up is R-trigger and Down is L-trigger.  Otherwise most Bluetooth
gamepads shouldn't have such a problem (I use a Sidewinder) .

**Comment by pishcakes** [comment]
I'm using the amazon game controller on newest debug build

**Comment by pishcakes** [comment]
To clarify, I can't map my triggers to L or R using amazon game controller

**Comment by pishcakes** [comment]
Also tried with a rock candy controller
