### ISSUE TITLE
Hardware inputs (volume +, -, gamepad buttons) crashes the game

### ISSUE THREAD

**Issue by adrot** [reicast/reicast-emulator#1018]
Here is the log.
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1494111830832.txt
This issue occurs when I try to play Ikaruga.gdi, on a Zenfone Laser ZE551KL, Android 5.0.1, with the v7 build, that's becoming an annoyance. After inputting the Xbox One Controller (which doesn't let me map some buttons, like the Start where I want to), it crashes every time I skip the intro by pressing any button. Same goes when I want to change volume on the phone's buttons.

**Comment by LoungeKatt** [comment]
Looks like it may be as simple as ` art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: the return type of CallIntMethod does not match boolean com.reicast.emulator.GL2JNINative.OnNativeKeyPress(int, int, int, int)`

**Comment by adrot** [comment]
Thanks, it works fine now! Also, by enabling ''Compatibilty mode'' on the Input settings, I can use Start where I originally wanted to.

**Comment by LoungeKatt** [comment]
I'll add some better labeling to the native option. It is a bit too general.
