### ISSUE TITLE
Gunlord white screen issue.

### ISSUE THREAD

**Issue by 1seam1** [reicast/reicast-emulator#1020]
When you load gunlord it just shows a white screen. You can hear the audio though and even get in game. On Nulldc you can fix this by switching video mode to RGB. I think this could be a quick and easy fix.

**Comment by blackman91** [comment]
Can confirm this happens on latest too.

**Comment by LoungeKatt** [comment]
And does switching to RGB in reicast fix it, as well?

**Comment by blackman91** [comment]
How do you switch to RGB in reicast?

**Comment by LoungeKatt** [comment]
It should be in the experimental settings section.

**Comment by 1seam1** [comment]
rgb never fixed the issue for me

**Comment by LoungeKatt** [comment]
Good enough. Thanks.

**Comment by blackman91** [comment]
I tried the 3 options vga, hdmi and component in cable types but none fix the issue, it is just a white screen but the game sound works like described by op.

**Comment by danboid** [comment]
I can confirm this issue under latest git reicast as of today running under Ubuntu 18.04 x64

**Comment by skmp** [comment]
(@reicast/testers has all information been moved to the reicast/gamedb#12?)

**Comment by blackman91** [comment]
Any idea what may be causing this? it even happens on the Retroarch core on pc and Android and no setting fixes it.

**Comment by AbandonedCart** [comment]
@blackman91 The issue was moved to (your post at) https://github.com/reicast/gamedb/issues/12

**Comment by blackman91** [comment]
Apparently to run this game properly reicast needs raw framebuffer writes:
https://youtu.be/sTOcxdEuqPo

It runs now on the libretro core, hope you can port these changes too.

**Comment by dmiller423** [comment]
It's a framebuffer game, or it reads from framebuffer for effects?

**Comment by AbandonedCart** [comment]
@dmiller423 He's talking about https://github.com/reicast/reicast-emulator/commit/e59d7eaf3db9d326098cff8fd9ff5321e5561d1a

**Comment by dmiller423** [comment]
That's definitely normal framebuffer,  i'm assuming @skmp never added it because nothing other than some homebrew uses it.  It was impl. in nullDC at least 12years ago

**Comment by AbandonedCart** [comment]
🤷‍♀️

**Comment by blackman91** [comment]
Yeah those changes fix a bunch of homebrew like beats of rage, not perfectly though:
![screenshot_20180827-221359](https://user-images.githubusercontent.com/6578180/44698785-0c444200-aa47-11e8-8b8e-6045c1ec5271.png)

**Comment by AbandonedCart** [comment]
Not sure about anyone else, but homebrew seems like last priority behind attempting to support actual games officially released for the console for me.

**Comment by baka0815** [comment]
For me too, however there are still a bunch of new games release for DC where reicast could support development.

**Comment by blackman91** [comment]
Yep like like xeno crisis:

https://www.kickstarter.com/projects/1676714319/xeno-crisis-a-new-game-for-the-sega-genesis-mega-d?lang=en
