### ISSUE TITLE
ecco the dolphin: serious grafx  problems.

### ISSUE THREAD

**Issue by 1seam1** [reicast/reicast-emulator#1021]
it only seems to render the polygons closest to ecco. wondering if its a fog issue? i have no idea.  

as seen here

https://youtu.be/2yjzTmCsoog?t=266

**Comment by skmp** [comment]
This is probably missing fog. @reicast/testers can this be moved to the reicast/gamedb#2 tracker?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#42
