### ISSUE TITLE
UWP Port

### ISSUE THREAD

**Issue by wiired24** [reicast/reicast-emulator#1024]
Hi,
I was wanting to see if it would be possible for reicast to get a UWP Port so it can be used on Xbox One?
Already a fair number of emulators have already been made/ported to the UWP Platform PPSSPP being one of the more recent ones. You can see a full list here by checking out the client that I wrote.
https://github.com/wiired24/ProjectPegasus

Sadly alot of us who really love dreamcast and would like to be able to play Dreamcast on our favorite device are not currently able to do so. At the very least I'd be more than happy to take up the effort in porting Reicast to UWP myself if someone could point me in the right direction. Thanks for the consideration.

**Comment by skmp** [comment]
Microsoft has banned emulators from their store, which makes this much harder. @wiired24 if you’re still interested in this, join our discord and poke me there :)
