### ISSUE TITLE
Odd issue with L and R triggers

### ISSUE THREAD

**Issue by whoomay** [reicast/reicast-emulator#1026]
In Reicast when I hold R or L with my Bluetooth controller and move the analog stick at the same time, it instead of holding the R or L reacts it as if I am constantly pressing and releasing it. This is visible when I enable the touch overlay. 

This makes Jet Set Radio basically unplayable.

I already tested, this is not a problem with the controller itself. 

Tried different builds of Reicast too.

Please tell me that I am not the only experiencing this odd issue.

This definitely isn't a problem with my controller.

Just tried mapping the A and B buttons on my controller as R and L in the emulator, same issue. If I move any analog stick while holding the buttons down, the input "flickers".

**Comment by LoungeKatt** [comment]
It's a known issue. I wish I could say there is an easy fix, but it is an issue with the design of Android's listeners vs the design of the Dreamcast. The trigger values have to be converted, which makes them act a bit like buttons while still clogging up motion detection.

**Comment by whoomay** [comment]
@LoungeKatt So why doesn't everyone experience this? I made a thread about this issue on the r/emulationonandroid subreddit and there were people who told me that they haven't experienced this issue.

**Comment by LoungeKatt** [comment]
Depends if the controller registers L and R as buttons or as pressure-sensitive triggers.

**Comment by beebul** [comment]
I get the same issue with RE: Code Veronica on a NES30Pro bluetooth controller. Makes attacking difficult/impossible.

**Comment by LoungeKatt** [comment]
Which mode are you using for NES30?

**Comment by beebul** [comment]
Not sure (at work) what mode would you recommend? Thanks.

**Comment by LoungeKatt** [comment]
Any mode that works with Android is fine. Mode 2 and 3 just requires custom configuration, since it uses keyboard values for the keys.

**Comment by beebul** [comment]
OK I will experiment thanks for the reply

**Comment by AbandonedCart** [comment]
Closing this in favor of https://github.com/reicast/reicast-emulator/issues/998
