### ISSUE TITLE
[game] "Silver" game unplayable

### ISSUE THREAD

**Issue by legluondunet** [reicast/reicast-emulator#1028]
Hello,
I tested two differents roms of "Silver" game with reicast, the game always crashed after the "MPEG sofdec" screen.

crash log:
https://pastebin.com/GZr1VRQC

Thank you for your help.

**Comment by blackman91** [comment]
This happens in Android too on stable r6 and latest playstore r7 beta as of today with .gdi roms:

**Comment by blackman91** [comment]
BTW .cdi rom working fine so far.

**Comment by legluondunet** [comment]
I can no more reproduce this issue with last Reicast git version.

Thanks.
