### ISSUE TITLE
Sa2 Menu crash((

### ISSUE THREAD

**Issue by d1noxd** [reicast/reicast-emulator#1029]
After selecting a VM card, the game crashes.
But if you turn off the dynamic recombiner everything is fine, but everything is very slow.

**Comment by d1noxd** [comment]
*recomplier

**Comment by d1noxd** [comment]
Srry for my bad ENG

**Comment by AbandonedCart** [comment]
Assuming this is resolved, as many recent reports are based on the game working. Please reopen if it is still an issue.
