### ISSUE TITLE
Any plans to emulate Windows CE Dreamcast games?

### ISSUE THREAD

**Issue by i30817** [reicast/reicast-emulator#1033]
The [list of them](http://segaretro.org/Windows_CE) has some high profile games. Namely the Tomb Raiders, Resident Evil 2 and some others. I don't know how Demul managed to emulate them, but i hope it's not unportable and can be lifted. Can the wine project help (as if Demul works on wine, maybe using wine derived code directly...)?

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/53
https://github.com/reicast/reicast-emulator/issues/872
https://github.com/reicast/reicast-emulator/issues/910

That is the discussion on MMU/WinCE so far.

**Comment by skmp** [comment]
After several fixes WinCE games mostly work in MMU enabled builds now.
