### ISSUE TITLE
Assign a single device ID to multiple controllers

### ISSUE THREAD

**Issue by SteelBattalion** [reicast/reicast-emulator#1035]
Are there any plans to allow this? I have a stand up arcade cabinet that sends keyboard presses to linux via a jamma interface. Both player inputs come from the same device.

**Comment by baka0815** [comment]
Could you please test with my changes mentioned in #1042?

**Comment by baka0815** [comment]
@TestSubject06 @SteelBattalion could you test with #1273 please?

**Comment by baka0815** [comment]
Fixed with #1273.
