### ISSUE TITLE
ARM 64 bit support? (Linux)

### ISSUE THREAD

**Issue by Silent-Hunter** [reicast/reicast-emulator#1038]
I was wondering if there was a way to get this to compile on the Pinebook. I tried and it said unsupported architecture, but I was wondering why. Is it just untested, or is it known not to work?

Here is output of cat /proc/cpuinfo:
```Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
Features	: fp asimd aes pmull sha1 sha2 crc32 
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: sun50iw1p1```

**Comment by rrrh** [comment]
From my understanding there is no JIT backend for aarch64. ARMv8 should be backwards compatible with ARMv7 - so compilation should be possible using the linux 32bit code-path.

**Comment by Silent-Hunter** [comment]
Ah okay. Unfortunately the battery swelled up, so I cannot test this. Sorry.

**Comment by rrrh** [comment]
Ouch - Bad news! Can I close this issue then, and you check back for an aarch64 backend in the near future?

**Comment by Silent-Hunter** [comment]
Yes, definitely! I don't know if I will have another aarch64 computer anytime soon but I will try it again if I do.

**Comment by rrrh** [comment]
Thanks. Closing this issue with the remark: "Batteries not included"
