### ISSUE TITLE
Cannot map L/R to ipega 9025

### ISSUE THREAD

**Issue by GhoulUnlimited** [reicast/reicast-emulator#1039]
Using the latest ci build on nougat, it doesn't matter what I map the L/R triggers to, they simply do nothing. Touchscreen L/R seem to be fine.

**Comment by LoungeKatt** [comment]
There are a lot of open issues about this. There is work needed for the buttons in general and chances are that Nougat made the situation even worse.

**Comment by GhoulUnlimited** [comment]
I see. I was thinking about forcing compatibility mode but the option cannot be selected (probably something to do with nougat's native libraries).

Do you know what line I have to add in the emu.cfg?

**Comment by LoungeKatt** [comment]
That option was never a part of the emu.cfg (since it can after using the emu.cfg from Android was largely bypassed). It didn't make sense to write to the cfg to be read by the core when they could be sent to the core directly and stored as Android preferences. You would have to edit the line in the com.reicast.emulator_preferences.xml that's saved in /data/data/com.reicast.emulator

**Comment by blackman91** [comment]
A fix for that:
https://www.reddit.com/r/EmulationOnAndroid/comments/6z48b6/modded_reicast_with_external_gamepad_rt_and_lt/

**Comment by GhoulUnlimited** [comment]
Ah, thanks a lot, mate. Finally, I can finish Spider-Man.

**Comment by jasiu512** [comment]
Ok. Any chance to clear how to edit this line in this. XML file? What and where to change?

**Comment by LoungeKatt** [comment]
It has been fixed as part of https://github.com/reicast/reicast-emulator/pull/1163 and I believe the specific change was already integrated into master

**Comment by jasiu512** [comment]
Ok. I will try latest.apk

**Comment by jasiu512** [comment]
After updating apk file to newest version, LT and RT buttons don't work in games.

**Comment by blackman91** [comment]
Try enabling the option in input enable custom key layout, that works for me. Also if you can't change settings try the lk/Android studio builds here:

http://builds.reicast.com/

Scroll down to find them.

**Comment by jasiu512** [comment]
Solved. Thank You very much. It is working now with lk/Android version. But there is a little delay between pushing button and action in game. But after all it is working.

**Comment by AbandonedCart** [comment]
Closing this, as it has been reported solved.
