### ISSUE TITLE
Can't play with my moga controller and reicast keeps glitching trying to find the storage

### ISSUE THREAD

**Issue by cloud98** [reicast/reicast-emulator#1041]
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1500334231730.txt
When i connect the controller without optimization setting buttons sort of detect like im rapid firing when its on it works perfectly but it doesn't detect the analog and i just got reicast running but now it's crashing and the latest build doesn't let me fiddle with any option. I can't even run the bios. When i enter rei cast it says libdc.so: text relocation

**Comment by cloud98** [comment]
I have an lg g5 so high end phone

**Comment by cloud98** [comment]
Also epsxe and other emulators detects the controller perfectly like i was looking forward to playing sa2 again

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/1009 explains the issue with relocations.

**Comment by cloud98** [comment]
Cool but how about being able to mess with the options cause it doesn't allow me to do soo. Like it keeps crashing on my phone and it shouldn't since it's an lg g5

**Comment by cloud98** [comment]
But yeah supporting moga controllers would be great

**Comment by LoungeKatt** [comment]
It does support Moga controllers. It currently doesn't support Nougat.

**Comment by blackman91** [comment]
This fixes it for android 7:
https://www.reddit.com/r/EmulationOnAndroid/comments/6z48b6/modded_reicast_with_external_gamepad_rt_and_lt/

**Comment by LoungeKatt** [comment]
Is this still an issue with the new beta versions?
