### ISSUE TITLE
Reicast crashes when two evdev_device_id_X entries match in emu.cfg

### ISSUE THREAD

**Issue by TestSubject06** [reicast/reicast-emulator#1042]
I'm attempting to get two players configured off of one input device (XArcade Tank Stick Dual if it matters), so my thought was to have two separate mappings of the device, one for each player's side, and then point them both to the same device id:

evdev_device_id_1 = 2
evdev_device_id_2 = 2
evdev_device_id_3 = -1
evdev_device_id_4 = -1
evdev_mapping_1 = /opt/retropie/configs/dreamcast/mappings/controller_XGaming XArcade.cfg
evdev_mapping_2 = /opt/retropie/configs/dreamcast/mappings/controller_XGamingXArcadeP2.cfg

np _(or nb, can't remember)_ = 2

This causes Reicast to immediately crash when opening anything. If I change one of the evdev id's, then it starts up, but the other mapping isn't used, and I can't control player 2.

Is this a bug, or am I missing something more obvious here?

**Comment by TestSubject06** [comment]
It looks like it should be possible to open the same evdev device multiple times through read-only file descriptors. Could detect that two ports share the same input device, and disable force feedback for those devices, allowing a read-only interface for both devices to work properly. 

There's nothing in linux that stops a file from being opened twice, especially if it's in read-only mode, and libevdev doesn't control clearing of any buffers as it reads new inputs from the queue.

**Comment by baka0815** [comment]
I will take a look at this in the upcoming week.

**Comment by baka0815** [comment]
Maybe related: https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/reicast/0002-Add-multiple-inputs-based-on-emu.cfg.patch

**Comment by baka0815** [comment]
Well, reicast doesn't "crash", but intentionally exists:
https://github.com/reicast/reicast-emulator/blob/055c3599b6cfa99279542dc2d29c6e5032995ded/core/linux-dist/main.cpp#L134
Just removing this however doesn't work (controller not working).
I'm further looking into this, hopefully this afternoon.

**Comment by baka0815** [comment]
@TestSubject06 @SteelBattalion could you test this with #1239?

**Comment by baka0815** [comment]
@TestSubject06 @SteelBattalion could you test with #1273 please?
