### ISSUE TITLE
Graphical Glitches on RK3288 Android Devices

### ISSUE THREAD

**Issue by ShaunMurray301** [reicast/reicast-emulator#1047]
Reicast displays some games with heavy graphical glitches. Most notably Phantasy Star Online. The feat/less-video-stuttering build is not impacted by this issue. Can a new current CI build be compiled with that feature enabled? The RK3288 runs much better with Synchronous Render enabled which was not available in the previous build in that branch.

**Comment by ShaunMurray301** [comment]
Actually this doesn't effect just RK3288 devices. The same glitching occurs on the Tegra X1 with the master branch.

**Comment by skmp** [comment]
Can you post some screenshots please? Is this game specific? I think it should be moved to the gamedb.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#100
