### ISSUE TITLE
King Boom Boo Sonic Adventure 2 Ghost Boss; graphical Bug. ANDROID

### ISSUE THREAD

**Issue by MaquinaDelMisterio** [reicast/reicast-emulator#1049]
When i hit the sand clock the ghost bury himself into the floor but the shadow doesn't appear so that i can see where is it. This is an issue 'cause i can't pass the level without the shadow. Im using a Galaxy S8 Exynos with Android 7.
![screenshot_20170912-073521](https://user-images.githubusercontent.com/4268943/30326271-a482defa-978d-11e7-9470-98288cc865c0.png)

**Comment by skmp** [comment]
Please retest using #1208. Also should be moved to gamedb.

**Comment by Deivmsr** [comment]
the problem has not been resolved in the latest version of the 1ada311 beta program. I tested both GDI and CDI versions.

**Comment by Deivmsr** [comment]
The problem hasn't been resolved in the latest version of the 1ada311 beta program. I tested both GDI and CDI versions. Why not add the volume modifier options as well as NullDCE, except in the Android version of Reicast. Would that help skmp?

**Comment by Deivmsr** [comment]
The problem hasn't been resolved in the latest version of the 1ada311 beta program. I tested both GDI and CDI versions. Why add the volume modifier options as well as NullDCE in the Android version of Reicast?Would that help skmp?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#94

**Comment by skmp** [comment]
Please continue discussion at  reicast/gamedb#94
