### ISSUE TITLE
L/R buttons not working with controllers.

### ISSUE THREAD

**Issue by MJaoune** [reicast/reicast-emulator#1052]
I have a GameSir G3s controller, and I have tried to let Reicast automatically detect the controller, but the L/R buttons don't work in-game, also tried mapping them manually, doesn't work either.

I am using Android 7.1.1, latest reicast commit (Also tried RC6).

**Comment by stodag** [comment]
try enabling compatability mode in settings, should work i think.

**Comment by LoungeKatt** [comment]
@stodag That was for a workaround for a different issue.

**Comment by stodag** [comment]
my bad man, sry

**Comment by MJaoune** [comment]
Nevermind, I didn't know I have to enable "Enable custom layout" option
after entering manual input settings, even though most checkboxes are
glitched on my 7.1.1 Android, I guess I will create a ticket about that.
You can close this.

**Comment by LoungeKatt** [comment]
There is an issue for that, in addition to a rather rude reddit user trolling my account about it. Unfortunately, it is waiting on text relocations. Once they are fixed, it will fix itself.
