### ISSUE TITLE
Lenovo K6 star app bug

### ISSUE THREAD

**Issue by jvabbdac** [reicast/reicast-emulator#1053]
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1508031060745.txt

**Comment by jvabbdac** [comment]
Detected problem with app native libraries (please consult log for detail): libdc.so: text relocations

**Comment by itornukem64** [comment]
This is a know issue and is even closed because loungekatt did changes to fix it but there is not apk, sadly

**Comment by jvabbdac** [comment]
Thank you!

**Comment by skmp** [comment]
This should be fixed in latest master. Please report in http://chat.reicast.com if still an issue.
