### ISSUE TITLE
Skies of Arcadia

### ISSUE THREAD

**Issue by Allanon41** [reicast/reicast-emulator#1054]
Love this game but it still crashes at the first harpoon ship battle. Need the vmu save file right after this point.

**Comment by Vodkanakas** [comment]
Is this on raspberry pi 3 B? If so I have the same problem but I'm going to assume it's because you can't clock it high enough. Mine is maxed out at 1375. the Raspberry Pi 3 B plus clocked at 1450 plays it just fine. You still get the wired picture but it tiles out then cyclones upward.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/1059
https://github.com/reicast/reicast-emulator/issues/1057
https://github.com/reicast/reicast-emulator/issues/1054
https://github.com/reicast/reicast-emulator/issues/250
https://github.com/reicast/reicast-emulator/issues/96

Are any of these the same issue? There seem to be a few for that game.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#88
