### ISSUE TITLE
【BUG】Resident Evil - Code:Veronica【Android】

### ISSUE THREAD

**Issue by shinobumaehara** [reicast/reicast-emulator#1056]
■Application information
1. reicast version r7 (reicast-android-debug-db284eb.apk)
2. reicast version r7 (reicast-android-debug-c3a90a6.apk)

■Download site
http://builds.reicast.com

■Change items from initial setting
Change before :
Settings > Use reios BIOS > OFF
Settings > Unstable Optimisations > OFF
Settings > DC Region > reicast
Settings > Broadcast > 4 - NTSC-U

After change :
Settings > Use reios BIOS > ON
Settings > Unstable Optimisations > ON
Settings > DC Region > NTSC-J
Settings > Broadcast > 9 - NTSC-J

■Model number
KYY23

■Android version
4.4.2

■Game title
BIOHAZARD - CODE: Veronica (Resident Evil - Code: Veronica) / Dreamcast

■Bug content
Currently, a drawing bug occurs in the status menu.
This problem started from "C3a90a6" and has not been fixed yet.

■Screenshot
1. http://fast-uploader.com/file/7064529665407/ (db284eb)
2. http://fast-uploader.com/file/7064529709908/ (c3a90a6)

**Comment by shinobumaehara** [comment]
■Application information
reicast version r7 (All version)

■Download site
http://builds.reicast.com

■Change items from initial setting
Change before :
Settings > Use reios BIOS > OFF
Settings > Unstable Optimisations > OFF
Settings > DC Region > reicast
Settings > Broadcast > 4 - NTSC-U

After change :
Settings > Use reios BIOS > ON
Settings > Unstable Optimisations > ON
Settings > DC Region > NTSC-J
Settings > Broadcast > 9 - NTSC-J

■Model number
KYY23

■Android version
4.4.2

■Game title
BIOHAZARD - CODE: Veronica (Resident Evil - Code: Veronica) / Dreamcast

■Screensho
http://fast-uploader.com/file/7064532493629/ (All version)

**Comment by skmp** [comment]
Closing this in favor of gamedb#1. Can you re-upload the screenshots there please?
