### ISSUE TITLE
Skies of arcadia crashed

### ISSUE THREAD

**Issue by Freeruny** [reicast/reicast-emulator#1057]
After defeating Rik'Talish there is a sequence of cutscenes and when the battle with The Cygnus is supposed to start, but can't and return to home screen...pls help

**Comment by metallserge** [comment]
yeah, same story, in r6 [382f2e5] build and tried to pass in PC version (build from builds.reicast.com: reicast-win_x64-slow-7ab335767579c0b6522ce8a8605ca6f430c234d5) - no luck (but saves were loaded fine)

but mine is russian version of arcadia, had problem year ago running some version from emuparadise, so, started this one. Almost no issues till this moment

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#99
