### ISSUE TITLE
LT & RT as buttons dont have the maximum value

### ISSUE THREAD

**Issue by BogdanTheGeek** [reicast/reicast-emulator#1058]
I am runing reicast on Android and trying to play crazy taxi, but the LT and RT which are used for breaking and accelerating and are mapped to buttons do not drepress all the way, which limits the speed of the taxi. This can be tested in the crazy box mode, where no matter what i do, i cant make the leap. Is there any config file where i can change the "deadzone" of the triggers?
basically i want to make it so when i press the button it send a "all the way down" command for the dreamcast triggers.

**Comment by LoungeKatt** [comment]
Oddly, the values being send when using buttons to replace the triggers are set to be fully pressed or fully released. What Android version and controller are you using? It sounds like it may be sending a different value for the button than what is expected.

**Comment by BogdanTheGeek** [comment]
Sorry for not responding, I can no longer test this.

**Comment by LoungeKatt** [comment]
Fair enough. Thanks for the report, though.
