### ISSUE TITLE
Skies of Arcadia- stopped working

### ISSUE THREAD

**Issue by Ginger933** [reicast/reicast-emulator#1059]
So I only downloaded reicast for this one game and everything was going great but I'm the part of skies of Arcadia where they Valuan Patrol Ship checks your passport instead of exiting the cutscene it just closes and goes back to reicast menu

**Comment by Ginger933** [comment]
Sorry forgot to clarify my request. I want to know what to do to get it to continue so I can beat the game

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#98
