### ISSUE TITLE
Freeze When I click on setup

### ISSUE THREAD

**Issue by boladaso** [reicast/reicast-emulator#1062]
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1510858819084.txt

The application stops responding by clicking "Settings" . 
 And a message is popping up when launching the app
 
 " Detected  problems with app Native libraries (please consult log for detail) 
Libdc.so: text relocations . 

Device: Moto x 2014
 
Snapdragon 801
Android 7.1.2
2gb Ram

**Comment by boladaso** [comment]
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1510858819084.txt

**Comment by LoungeKatt** [comment]
This is a known issue with Android 7+ that requires rewriting the core. Unfortunately, the common solution for the required code is also incompatible with the compiler. This means it requires a little more than just replacing the lines causing the issue with their compatible variants.

**Comment by AbandonedCart** [comment]
This has since been resolved by conversion to Android Studio.
