### ISSUE TITLE
Crash on Path change

### ISSUE THREAD

**Issue by Studge** [reicast/reicast-emulator#1066]
Android 7.0, Permission for storage set to allow

When I try and click the the 2 dots (..) to go up in the file directory to search my SD game for Bios and Games, Recast instant crash

It gives me Thread and Error text but cant copy paste it for posting here, have print screens.

Would like to know how to get Reicast to work

**Comment by morenillo76** [comment]
hola

**Comment by LoungeKatt** [comment]
This is fixed in the various android-studio branches. It will hit mainline once it is ready for release.
