### ISSUE TITLE
Reicast (Android) Wont locate bios

### ISSUE THREAD

**Issue by KiraECS** [reicast/reicast-emulator#1067]
i got the needed files, and i made the folders like the emulator said i need to do it, just got an error message saying the bios isnt there, and automatically makes a copy of the same folder in the folder, for example: the bios was in the folder named data, then the error showed up and another folder named data appeared in the data folder. I need help, i have been trying to get reicast to work on my device for months, if you need to know what device i have to understand if i have an issue with said device, its the samsung galaxy tab s2, with android 7.0.

**Comment by LoungeKatt** [comment]
Make sure to configure the folder as the one data is inside, not the data folder itself. If you have a directory that looks like /sdcard/Emulator/reicast/data, then the folder you set is reicast.
