### ISSUE TITLE
Ouya dpad config problem

### ISSUE THREAD

**Issue by d-holder** [reicast/reicast-emulator#1069]
Everything works fine except the quick menu is assigned to the left input on the dpad, and is unchangeable as far as i can see, making the whole dpad pretty useless.

I've only downloaded it to play my old fighting games on the go, can anyone help?

**Comment by LoungeKatt** [comment]
You should be able to edit the controller assignments using the Input menu option from the main screen.

**Comment by d-holder** [comment]
As I stated above, I have already reassigned the controller input settings, however no matter how many times I do it, the quick touch menu is still all I get when I press left on the dpad. Its not something the app seems to have a setting to change or switch off. Can anybody help beyond this?

**Comment by LoungeKatt** [comment]
You did not state that you had already tried to reassign the controller input settings. From your original post, it sounded like you were using the defaults.

What Android version is your device? What other settings have you tried?

**Comment by d-holder** [comment]
I apologise, I thought that maybe it was mildy implied that I indeed was using customised settings as I couldn't find a means of which to reassign this feature to another button.

The version of android on my Nexus 7 is 5.1.1. As of yet, the only thing I have noticed is that whatever I assign to the Select button in the configuration settings as acts as a left dpad input. However I am still unable to assign this to the left button of my dpad, it still only brings up the quick touch menu.

I hope that was a more help full way of describing my problem, thanks in advance

**Comment by LoungeKatt** [comment]
Based on the typical person reporting an issue, "couldn't find" typically only implies you looked.

I am still a bit confused about the issue. It sounds as though you are assigning something to the select button, but it instead acts as the left dpad button and no matter what you assign to the left dpad button, it acts as the quick touch menu.

Did you get the same results with the defaults? Have you tried removing any setting for the select button? It sounds like the dpad should be addressed before worrying about the select button at all.

**Comment by d-holder** [comment]
So to explain my process from installation, after setting everything up:

I go to input and sync my controller with the automatic settings. I test all the buttons and all work except left on the dpad, which acts like pressing back on the main tablet buttons.

I then use customise physical controls to set up the buttons. Again, all buttons and stick work fine, including the other 3 dpad inputs, but the left dpad input only bring up the quick menu again.

On a side note, select seems to act just like the actual left dpad input when set to any button. Except left on the dpad. 

Overall it seems the back menu button input setting is overriding all controls and can't be changed. So it will be interesting to see how this problem can be fixed. Thanks in advance

**Comment by d-holder** [comment]
To add, I tried just removing the select button setting, however that didn't work and left still opens the quick menu.

**Comment by LoungeKatt** [comment]
Seems like they just swapped those keys on the gamepad board. Shouldn't be too difficult to at least add a workaround.

**Comment by AbandonedCart** [comment]
Is this still an issue?

**Comment by skmp** [comment]
Closing as part of ticket cleanup. Please report in chat.reicast.com if still an issue
