### ISSUE TITLE
shenmue 2 random crash

### ISSUE THREAD

**Issue by cameracartwright** [reicast/reicast-emulator#107]
Shenmue 2 in game after intro video and having photo taken then after arm Wrestle with Mexican man walk towards town and game FC and returns to path directory. I had to disable dyranec initially to get the game to load then once game loaded I Saved re enabled dyranec to speed up game..I thought I'd try a load screen just before the Mexican arm wrestling man without disabling the dyranec and it didn't crash??!! Hope this makes sense

**Comment by nomadpl1** [comment]
Shenmue 2 fatal crasch. After enter guang martial arts school. Help me

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#33
