### ISSUE TITLE
WM8880 Android 4.2.1 Mali 400 -  in mush!

### ISSUE THREAD

**Issue by Karaulov** [reicast/reicast-emulator#1075]
WM8880 (2x core 1.5ghz) Android 4.2.1 Mali 400 -  in mush!

Trash, bad emulation. How to fix it ?

Game: Cannon spike 

in Windows all ok. (with nulldc)

**Comment by skmp** [comment]
Closing as part of ticket cleanup. Please report in http://chat.reicast.com if still an issue.

Should be fixed in latest master
