### ISSUE TITLE
some crash logs on android

### ISSUE THREAD

**Issue by jasper1412** [reicast/reicast-emulator#1081]
I cant find the saved log so I provided these screenshot
![img_20180310_102956_707](https://user-images.githubusercontent.com/22563129/37237459-67bd4bec-244e-11e8-80b7-5b52bdd72d3d.JPG)
![img_20180310_102942_969](https://user-images.githubusercontent.com/22563129/37237471-9a27137e-244e-11e8-995f-04c91ab4ebe5.JPG)

![img_20180310_102637_229](https://user-images.githubusercontent.com/22563129/37237420-d7edb81c-244d-11e8-80ea-11345ccdfef6.JPG)

**Comment by LoungeKatt** [comment]
This should all be addressed on the android-studio branches.
It will be fixed once these changes are added to master.

**Comment by Sarkie** [comment]
@loungekatt is there an automated build for that branch?

**Comment by LoungeKatt** [comment]
They are all available on http://builds.reicast.com/
