### ISSUE TITLE
reicast fails to read evdev_mapping_* from `mappings` folder in reicast config folder.

### ISSUE THREAD

**Issue by crocket** [reicast/reicast-emulator#1083]
Git Commit : `b4631f6715ab7ee8483ebcef37a97f6e3194602e`
OS : Gentoo Linux

`man reicast` says

> You  can  create  your own mappings with the reicast-joyconfig tool. You should either put them into the "mappings" folder inside the reicast config directory. As an alternative, you can specify an absolute path (which has to begin with a leading slash "/")

I discovered that reicast doesn't recognize `~/.config/reicast/mappings/dualshock4.cfg`.

~/.config/reicast/emu.cfg

```
[input]
enable_x11_keyboard = 1
evdev_device_id_1 = 11
evdev_device_id_2 = -1
evdev_device_id_3 = -1
evdev_device_id_4 = -1
evdev_mapping_1 = dualshock4.cfg
joystick_device_id = -1
```

~/.config/reicast/mappings/dualshock4.cfg

```
[emulator]
mapping_name = Wireless Controller
btn_escape = 312

[dreamcast]
btn_a = 305
btn_b = 306
btn_x = 304
btn_y = 307
btn_start = 313
axis_x = 0
axis_y = 1

[compat]
axis_dpad1_x = 16
axis_dpad1_x_inverted = no
axis_dpad1_y = 17
axis_dpad1_y_inverted = no
btn_trigger_left = 308
btn_trigger_right = 309
axis_x_inverted = no
axis_y_inverted = no
```

Installed files

```
$ equery f reicast
 * Searching for reicast ...
 * Contents of games-emulation/reicast-7_pre20180310:
/usr
/usr/bin
/usr/bin/reicast
/usr/bin/reicast-joyconfig
/usr/share
/usr/share/applications
/usr/share/applications/reicast.desktop
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/reicast-joyconfig.1.bz2
/usr/share/man/man1/reicast.1.bz2
/usr/share/pixmaps
/usr/share/pixmaps/reicast.png
/usr/share/reicast
/usr/share/reicast/mappings
/usr/share/reicast/mappings/controller_gcwz.cfg
/usr/share/reicast/mappings/controller_generic.cfg
/usr/share/reicast/mappings/controller_pandora.cfg
/usr/share/reicast/mappings/controller_xboxdrv.cfg
/usr/share/reicast/mappings/controller_xpad.cfg
/usr/share/reicast/mappings/keyboard.cfg
```

**Comment by baka0815** [comment]
The mappings directory is not ``~/.config/reicast/mappings/`` but ``~/.local/share/reicast/mappings/``.
I updated the man file in #1286 to make that more clear.

**Comment by AbandonedCart** [comment]
This appears to be a misunderstanding that was resolved through clearer documentation. If this is still an issue, please feel free to open it again.
