### ISSUE TITLE
issues with The Ring: Terror's Realm on Android

### ISSUE THREAD

**Issue by jasper1412** [reicast/reicast-emulator#1088]
Using `2018-03-22T15:19:12.000Z` build.

> ![20180324223600](https://user-images.githubusercontent.com/22563129/37865305-f0f5dc9a-2fb5-11e8-867a-b3d729fac199.jpeg)
black screen on in-game main menu

> ![20180324223720](https://user-images.githubusercontent.com/22563129/37865316-218802d4-2fb6-11e8-8b16-d796eb334894.jpeg)
issue with dialog

**Comment by AbandonedCart** [comment]
Moved to https://github.com/reicast/gamedb/issues/116
