### ISSUE TITLE
issues with Phantasy Star Online on Android

### ISSUE THREAD

**Issue by jasper1412** [reicast/reicast-emulator#1089]
Game flickers heavily on `2018-03-22T15:19:12.000Z` update.

**Comment by welsby** [comment]
Also noticed this on latest build, looks like the map has some sort of z-index issue going on causing black flickering on the top right of the screen.

**Comment by skmp** [comment]
Can you match that build to a git version?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#41
