### ISSUE TITLE
List of tested devices getting lengthy

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#1090]
At this point, do we still even need one?

I have 3 more phones that can be added, but it is already a page long.
If we need it, could a Google form could replace a full list in the README?

**Comment by skmp** [comment]
I think it's useful to have a list of devices actively used for development. We can probably trim the old and unused ones.

**Comment by LoungeKatt** [comment]
I can see the use of it, which is why I was thinking a Google form. It can be linked and updated free from taking up any more than 1 line of the readme. Plus we would have room for notes and such.

**Comment by LoungeKatt** [comment]
https://docs.google.com/document/d/1eOj43AqPkWUj73PPEXH2_JWwFJM7gYnHvjZrE2JtFr4/edit?usp=sharing

**Comment by skmp** [comment]
I'd still prefer a short list in the readme over a google doc I'll forget about.

**Comment by LoungeKatt** [comment]
You put the link in the README where the list currently resides. I wasn't talking about just saving the doc to your Google account and trying to remember to update it. That would be pointless. When you click it, write permission is automatically granted, so it isn't like you need to remember to launch any special tools to change it, either.
If a list is what you want, then it's not like there are any disadvantages beyond being long and requiring more work to update.
