### ISSUE TITLE
No way to bind Dreamcast controller's analog stick. 

### ISSUE THREAD

**Issue by emrebnk** [reicast/reicast-emulator#1103]
Everything is there, the dpad, the a b x y buttons, LT and RT buttons, start and select buttons. But analog stick is missing.

There is also no select button on the touch screen nor is there a way to put it there.

**Comment by emrebnk** [comment]
This analog stick. 

![sketch-1523428154238](https://user-images.githubusercontent.com/16821868/38599881-d4646246-3d6a-11e8-96e6-547624b4d5af.png)

**Comment by LoungeKatt** [comment]
You want an onscreen select button for that analog stick?

**Comment by emrebnk** [comment]
I want to bind my controller's right analog stick on that analog stick, but as you can see here, reicast's input settings menu simply doesn't have the binding options for the mentioned analog stick.

![screenshot_2018-04-11-09-35-45](https://user-images.githubusercontent.com/16821868/38600171-dde66ab6-3d6b-11e8-9b82-48364dcc6396.png)
![screenshot_2018-04-11-09-35-53](https://user-images.githubusercontent.com/16821868/38600173-e04b7436-3d6b-11e8-8370-9434de686688.png)

**Comment by LoungeKatt** [comment]
... I am very familiar with interface.

"There is also no select button on the touch screen nor is there a way to put it there."

Why do you need a select button on the touch screen?

**Comment by emrebnk** [comment]
I don't. But someone who's using the touchscreen might.

**Comment by LoungeKatt** [comment]
Someone using the touchscreen will also have a back key. The purpose of allowing select to be configured was to act as a hardware key when you **don't** have a touchscreen.

**Comment by emrebnk** [comment]
I mean yeah, that is indeed a solution, but what if this person using the touchscreen doesn't want to sacrifice one of their hardware keys when they can just have the button on their touchscreen?

Anyways, let's stick to the issue. There is no binding options for the Dreamcast controller's analog stick and there is no select button on the touchscreen and there's no option to put it there. That's all.

**Comment by LoungeKatt** [comment]
There is not going to be an onscreen select button and I will work on getting joysticks added to the configuration menu after the conversion to Android Studio.

**Comment by franky-san** [comment]
I would like you to add in the configuration the opcion of virtual control to use it with the app bt controller.

**Comment by AbandonedCart** [comment]
@franky-san I don't know that I understand what you are asking.

**Comment by AbandonedCart** [comment]
Working on joystick config @ https://github.com/reicast/reicast-emulator/pull/1319

**Comment by AbandonedCart** [comment]
https://github.com/reicast/reicast-emulator/commit/15615693c573b66283e09340984e8d9ebee69ba0
