### ISSUE TITLE
Update travis to run in external PRs

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1105]
We need travis to work on external PRs, but to not upload to the CI site.

**Comment by LoungeKatt** [comment]
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

**Comment by skmp** [comment]
Travis does the sensible thing and does not expose secrets in PR builds. Enabled PR builds and fixed .travis.yml to not fail if the encrypted envs are not set - #1106

**Comment by skmp** [comment]
Also fixed the broken wercker integration and made werkcer mandatory
