### ISSUE TITLE
Update assembly code to not generate text relocations

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1109]
The arm ngen uses automatic constant pool generation, which generates relocation entries.

This is done to get the address of a few globals
```
       ldr r8,=arm_Reg                 @load cntx
       ldr r4,=EntryPoints             @load lookup base
```

This can either be worked around by passing a context parameter (fairly easy, but the code has to be updated for all platforms) or by hand-generating GOT_PREL entries (hard and fragile, but addresses the android issue directly)

**Comment by TheComputerGuy96** [comment]
Text relocations prevent this emulator from running on newer versions of Android

**Comment by LoungeKatt** [comment]
@TheComputerGuy96 Have you tested any of the Android Studio builds?

**Comment by TheComputerGuy96** [comment]
@LoungeKatt Yes

**Comment by skmp** [comment]
@flyinghead Does this seem interesting to you?
