### ISSUE TITLE
[Android] Unable to toggle any settings options

### ISSUE THREAD

**Issue by profzelonka** [reicast/reicast-emulator#1112]
Instead of an on/off toggle button, settings menu shows a super tiny black-text and the options are unchangeable. (screenshot) Pressing on the options does nothing.
![screenshot_20180415-120024](https://user-images.githubusercontent.com/38406652/38782231-35f05488-40a5-11e8-8239-5c2af1fd17a8.png)

Phone: Galaxy S7 (Android 7.0)
Tested on latest build: dfc58ec

This issue has been around for the majority of the builds. The last working build without this issue (that doesn't crash) was 9b38bcf.

**Comment by LoungeKatt** [comment]
This is a known issue and is fixed by changes already in pull requests as part of the Android Studio conversion.

**Comment by profzelonka** [comment]
Any idea when it'll be merged into master?

**Comment by LoungeKatt** [comment]
It is in review right now, so it depends on if any edits are needed.
