### ISSUE TITLE
Update embedded libpng

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1121]
We use a vulnerable version, should update to latest.

`core/deps/libpng` is the path

**Comment by LoungeKatt** [comment]
Thanks. I had started a local branch with 1.6.33, but yours looks like it may have already been tested. 
I will rebase 1.6.33 on your 1.6.32 patch for the PR.

**Comment by LoungeKatt** [comment]
Apparently OpenCV faced the same configuration paradox with how they updated neon support
https://github.com/opencv/opencv/commit/bdaab1cee59d20916fb659fa37186af9e39da076

In previous builds, neon was implicitly disabled (`/* #undef PNG_ARM_NEON_OPT */`) but now requires that the option be explicitly disabled (`#define PNG_ARM_NEON_OPT 0`)

**Comment by mudlord** [comment]
Do you really need libpng, why not stb_image.c?

**Comment by AbandonedCart** [comment]
https://github.com/reicast/reicast-emulator/pull/1133
