### ISSUE TITLE
iOS Automated Building / CI

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#1125]
@skmp Does Amazon support folder structure?

It would probably be best on an isolated branch running through travis, but I have the basic folder structure to make a repo as long as Amazon supports 2 levels of folder structure.

**Comment by skmp** [comment]
No, amazon treats the name as an opaque string of a key-value store, so `/` or `\` are simply part of the filename. We can reconstruct folders from that if we need to, or use a different "bucket". ATM we have a bucket for android and one for windows. See [how the CI list gets built](https://github.com/reicast/reicast-builds/blob/gh-pages/builds.js#L112)

**Comment by skmp** [comment]
I do not like using a separate branch for IOS/OSX though, that sounds easy to break and hard to maintain. 

Aren't there any better solutions, like using travis in a build/platform matrix configuration, using some other service for android builds and travis for IOS/OSX, or using some other service for IOS/OSX?

**Comment by LoungeKatt** [comment]
Configuring a repo is a fairly black and white directory layout, so Amazon sounds like it wouldn't support it for distribution on cydia anyway.

**Comment by LoungeKatt** [comment]
I am still trying to figure out if deploying is viable in a CI, but I moved this to https://github.com/reicast/reicast-emulator/issues/1132 to at least add working build tests.
