### ISSUE TITLE
#1093 - Android Studio basic conversion

### ISSUE THREAD

**Issue by AbandonedCart** [reicast/reicast-emulator#1126]
Android Studio basic conversion
---
- [x] Initial Android Studio migration
- [x] Verify / update makefiles, configuration
- [x] Base on master branch
- [x] Remove Eclipse configuration
- [ ] NDK configurations
- [x] Build profiles (Debug / Release)
- [x] Migrate travis CI to gradle
- [ ] Update build instructions

**Comment by skmp** [comment]
@LoungeKatt what needs to be split in follow up taks?
