### ISSUE TITLE
#1093 - Shell Code modernization

### ISSUE THREAD

**Issue by AbandonedCart** [reicast/reicast-emulator#1127]
Shell Code modernization
---
- [x] Update libraries
- [x] Verify / implement "Best Practices"
- [ ] Verify / improve documentation
- [x] Determine minSDK
- [x] Compatibility with Android 7.0+
- [ ] Implement error tracking

**Comment by skmp** [comment]
@LoungeKatt what needs to be split in follow up tasks?
