### ISSUE TITLE
#1093 - Android UI Improvements

### ISSUE THREAD

**Issue by AbandonedCart** [reicast/reicast-emulator#1128]
Android UI Improvements
---
- [x] Fix UI Issues
- [x] Test / fix filebrowser
- [x] Test / fix controllers
- [ ] Implement joystick configuration
- [ ] Populate disk icons
- [x] UI Modernization

**Comment by LoungeKatt** [comment]
Addressed in https://github.com/reicast/reicast-emulator/tree/lk/android-studio

- [X] Fix UI Issues
- [X] Test / fix filebrowser
- [ ] Test / fix controllers
- [ ] Implement joystick configuration
- [ ] Populate disk icons
- [X] UI Modernization

**Comment by skmp** [comment]
@LoungeKatt what needs to be split in follow up tasks?
