### ISSUE TITLE
#1093 - Emulator Core Improvements

### ISSUE THREAD

**Issue by AbandonedCart** [reicast/reicast-emulator#1129]
Emulator Core Improvements
---
- [ ] Address / improve crashes and handling
- [x] Graceful teardown / closure process
- [x] Support pause / resume (Lifecycle)
- [ ] Fixup DYNACALL
- [ ] Fixup build options. (-O0 is forced, -fpic is all over)

**Comment by skmp** [comment]
@LoungeKatt what needs to be split in follow up tasks?
