### ISSUE TITLE
Shenmue notebook 

### ISSUE THREAD

**Issue by emrebnk** [reicast/reicast-emulator#1136]
Has there been any workarounds for not having the bottom half of the notebook?

**Comment by Philps** [comment]
same issue. Fire TV Gen2 - all different settings testes on/off  from UserGuide: http://reicast.com/guide/

**Comment by LoungeKatt** [comment]
@Philps If you are unable to set the BIOS time or VMU (https://github.com/reicast/reicast-emulator/issues/1137), then specific game issues can't properly be diagnosed yet.

**Comment by skmp** [comment]
(Closing this as #386 is a duplicate)
