### ISSUE TITLE
Amazon FireTv Gen2 - not able to set time or configure VMU

### ISSUE THREAD

**Issue by Philps** [reicast/reicast-emulator#1137]
Followed instructions on UserGuide, but i am unable to configure time and VMU

http://reicast.com/guide/

**Comment by Philps** [comment]
its not rooted. thx

**Comment by LoungeKatt** [comment]
Amazon Fire TV is a specialized Android device, so there is already limited support. In many cases, emulators also need a rooted device to perform low-level memory operations. When you have a specialized device that isn't rooted, functionality is hit or miss.

**Comment by AbandonedCart** [comment]
Closing this for now in hopes that it will improve over time. Unfortunately, no specific steps can be taken for that specific hardware.
