### ISSUE TITLE
(Android) Can't use touch controls/Broken checkboxes.

### ISSUE THREAD

**Issue by 1ReimuReimu1** [reicast/reicast-emulator#1149]
So I went to try out this emulator, only to find any and every checkbox was broken, just being a black square, and the touch controls not showing up, instead just a glitchy mess on either end of the screen. Have yet to try a game though. 

Device: SM-J727V
Android Version: 7.0 Nougat
Reicast build: whatever the latest Ci build was a few minutes after the writing of this was (5/13/18) 9:12 PM.

EDIT: oh, and every time I start the app it says:
```
Detected problems with naitive app libraries
Please consult log for detail:
libdc.so: text relocations

```
  EDIT2: grabbed screenshot of glitched controls![Glitched Controls](https://i.imgur.com/GbZ6ZOT.png)

**Comment by LoungeKatt** [comment]
Which branch was it?

**Comment by 1ReimuReimu1** [comment]
Let me check

**Comment by LoungeKatt** [comment]
Was the version you downloaded listed under the heading "master" (that is the branch)?

**Comment by 1ReimuReimu1** [comment]
I downloaded from http://builds.reicast.com

**Comment by LoungeKatt** [comment]
Let me try going about this a different way.
Try http://reicast-builds.s3.amazonaws.com/builds/heads/lk/android-studio-50a96cd/reicast-android-debug-50a96cd.apk

**Comment by 1ReimuReimu1** [comment]
![](https://i.imgur.com/W3qGm6W.png)

**Comment by LoungeKatt** [comment]
Click "OK"

**Comment by LoungeKatt** [comment]
Have you changed any of the settings?
Did the BIOS / game work in the past?

**Comment by 1ReimuReimu1** [comment]
First time using this emulator, so no to the question of did it work before, and im keeping away from settings because the checkboxes are broken in such a way as I dont know if they are checked or not

**Comment by 1ReimuReimu1** [comment]
I got a controler that works, so close maybe? Unless its a major issue in the future. Games work btw.

**Comment by 1ReimuReimu1** [comment]
Fixed, why is buttons.png in the data folder of the internal storage and not bios folder

**Comment by 1ReimuReimu1** [comment]
Close this
