### ISSUE TITLE
Android Reicast Improved Touch Buttons

### ISSUE THREAD

**Issue by SergeLeMenteur** [reicast/reicast-emulator#115]
Hi,here is an improved version of touch keys for Android Reicast replace the buttons.png file in dc/data
Link:https://mega.co.nz/#F!ZRUzBQRS!cdiaSGJi5HZVqbGrNJDzDA
Leave a comment and enjoy!

![buttons](https://f.cloud.github.com/assets/393266/1953952/a556b6a2-81cb-11e3-9a21-5c8374ef6841.png)

**Comment by HipsterStache** [comment]
Marcthesparta: I would like you to check this png I made for the reicast emulator. It has a xbox theme, but the dpad is quite small. But it looks FANTASTIC! Please check it out https://mega.co.nz/#!dZUHAapI!Q4TX4pQVx5rxKOHw6ag_khzhC8I3PuworLozX05_ELc

**Comment by LoungeKatt** [comment]
That does look really slick. If you were to replace the Xbox logo, you could probably convince @skmp to add it.

**Comment by Marcthesparta** [comment]
I love your graphical style but its not the dreamcast style at all.It's a
dreamcast emulator
Le 11 janv. 2015 17:36, "TwistedUmbrella" <notifications@github.com> a
écrit :

**Comment by LoungeKatt** [comment]
@Marcthesparta It's Xbox. It says it in the file name. It is still nice as an alternate.

**Comment by Marcthesparta** [comment]
Yeah why not! What can I do for you?
Le 11 janv. 2015 18:19, "TwistedUmbrella" <notifications@github.com> a
écrit :
>
> @Marcthesparta It's Xbox. It says it in the file name. It is still nice
as an alternate.

**Comment by LoungeKatt** [comment]
Why not a Playstation one? I could touch up the code to support swapping them and we could have a post in the forums for themed buttons.

**Comment by Marcthesparta** [comment]
Ok i will work on a PlayStation theme and try to give you a link next
saturday.
See you soon ;)
Le 11 janv. 2015 20:45, "TwistedUmbrella" <notifications@github.com> a
écrit :

**Comment by HipsterStache** [comment]
Thanks guys, for your feedback. I know its not that great but I will be working on a custom Dreamcast png. It will be much better than the xbox png!

**Comment by Marcthesparta** [comment]
Here it is,PlayStation theme for reicast ;) tell me if you like it,I'm
working on other themes(ouya,nes,snes...).

https://mega.co.nz/#F!ZRUzBQRS!cdiaSGJi5HZVqbGrNJDzDA

**Comment by HipsterStache** [comment]
I LOVE IT! It performs soo well! The only thing is, is that you got the d pad mixed up, but f@ck that, this a good quality theme for
the reicast app

**Comment by Marcthesparta** [comment]
Fixed ;)

**Comment by Marcthesparta** [comment]
Ouya theme is up !

**Comment by Marcthesparta** [comment]
New version of DC buttons uploaded
