### ISSUE TITLE
Graphical glitches in Sonic Shuffle

### ISSUE THREAD

**Issue by Latiosdude** [reicast/reicast-emulator#1153]
On some of the dialogue and menus in Sonic Shuffle, I get quite a few graphical glitches in the latest Android build under lk/android-studio

**Comment by Latiosdude** [comment]
https://drive.google.com/file/d/16SrlrisD0KTetiXzF_d1u9DrKwQ988Xw/view?usp=drivesdk

https://drive.google.com/file/d/1HXr5fbvq80ksBB-ebxmTce6-ePQbGIk2/view?usp=drivesdk

https://drive.google.com/file/d/1-K8qnNV-q5_T2v3P4PDuiY_OwcpzkMAz/view?usp=drivesdk
^^
Links to screenshots of the graphical glitches

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#96
