### ISSUE TITLE
Star Wars: Episode 1 - Jedi Power Battles Crash

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#1154]
From @WolfSama:

> This matter can be solved BUT when you come to rescue the queen in teed there is no way to pass that level,the game will crash,i try with r6 official and some builds,this game is impossible to finish,i try with Qui Guon Jin,but in the end of the level the game will crash,just tell me if you have a solution for it,after you meet the queen almost in the end the game bug and crash

> Well if be possible clear this game please let me know how because he will crash in teed palace level before the level tatooine no matter the question of fps or whatever configuration of r6,i try some builds without sucess,maybe reicast should have some more optmizatios setings.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#40
