### ISSUE TITLE
Issue Submission Template

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#1156]
We need something to give people an idea of what is relevant to debugging an issue.
```
description

reicast build (google play, master beta, alternate branch)

any steps tested

any logs gathered

any screenshots
```
We have a lot of "yeah, so i had this issue that I didn't have like 20 years ago and now I do have and need fixed" reports that take 10 messages getting the info and steps. It will resolve the huge gaps in getting to the issue and people getting frustrated that the first reply isn't something new to them.

**Comment by baka0815** [comment]
Is it possible to detect bad dumps? Like the hash of the rom?
Or is that impossible due to different dumping tools all producing "good" results with different hashes?

If that's possible it would be good to add that info too.

**Comment by LoungeKatt** [comment]
That is a bit beyond the scope of a general template. If it is a game issue, that would be a follow-up question or something to include in the subtext of "any steps tested" as "have you verified the game works?"

**Comment by baka0815** [comment]
Ok, fair enough.

**Comment by rcaridade145** [comment]
I agree @LoungeKatt . Personally even for a end user i find that the compat list used by xenia, cxbx-reloaded ,play! is the way to go.

**Comment by skmp** [comment]
@LoungeKatt Can you add a link to this to the readme maybe?

**Comment by LoungeKatt** [comment]
It's actually something you set up to pre-fill a new issue. https://github.com/reicast/reicast-emulator/pull/1174

**Comment by LoungeKatt** [comment]
<img width="1000" alt="screen shot 2018-06-11 at 12 39 10 pm" src="https://user-images.githubusercontent.com/1173913/41244904-8b275964-6d74-11e8-992c-9c1236e3b0b7.png">

**_BAM_**
