### ISSUE TITLE
Crash - External Storage

### ISSUE THREAD

**Issue by ElTioRata** [reicast/reicast-emulator#1158]
When I go to select the directory is my games, I tap in the "folder" called ".." then, my reicast crashes. Also, there isn't option to change language.

**Comment by LoungeKatt** [comment]
What version?
Do you have a log?

Language is automatically set by device locale.

**Comment by ElTioRata** [comment]
The latest version on Google Play.
This is the log I think.
https://www.imgur.com/HEDq8Pw
https://www.imgur.com/iprprld

**Comment by LoungeKatt** [comment]
The Google Play version is rather old. The versions on http://builds.reicast.com/ under the lk/android-studio branch are meant for newer versions of Android and have updates for external storage.

**Comment by skmp** [comment]
@ElTioRata Can you use the `Android` label instead of adding "[Android]" next time, please? :)

**Comment by skmp** [comment]
@ElTioRata can you please retest using the beta from #1208?

**Comment by AbandonedCart** [comment]
No response in over a month with no additional reports. If the issue remains, please reopen this.
