### ISSUE TITLE
GLES 3 core update

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#1162]
Many newer devices include Vulkan, but that is more a long-term support goal. As a fallback, they use EGL 3. We currently have core support for EGL 2 with an optional duct-tape EGL 3 wrapper from like 2012.

It is likely that at least half of the complaints about graphical issues that worked on the Play version are because that version explicitly limited the emulator to EGL 2. It seems like going back to that would be a step in the wrong direction, though.

With that, it would probably be good to start adding (optional) EGL 3 core support.

Possibly related to https://github.com/reicast/reicast-emulator/issues/899 and https://github.com/reicast/reicast-emulator/issues/1000

**Comment by skmp** [comment]
Yes, we definitely need gles3 support. It's probably best to write a new renderer though, as the current one is somewhat tainted by GPL. Reicast already supports multiple renderers so it shouldn't be that hard

**Comment by LoungeKatt** [comment]
The update would be universal, not just for one architecture. If it can be used, it would become available.

**Comment by skmp** [comment]
@dmiller423 has also promised me to work on a vulkan renderer. I wonder if he has time these days.

**Comment by skmp** [comment]
(Split the vulkan part to #1172)

**Comment by blackman91** [comment]
The bugs referenced in this issue are fixed in both Retroarch reicast cores, just tested it so they should be fixable in standalone too.

**Comment by LoungeKatt** [comment]
@blackman91 That doesn't really change anything for this issue, except that those two issues can be fixed another way.

**Comment by LoungeKatt** [comment]
#1227 will be a good start for this. Extending it beyond desktop will be the easy part. This can probably be closed.
