### ISSUE TITLE
How do I setup Naomi BIOS for Naomi build on Linux?

### ISSUE THREAD

**Issue by Yoshimaster96** [reicast/reicast-emulator#1164]
What the title says. Where do I put the BIOS(es), and what are their filenames?

**Comment by skmp** [comment]
Should follow the same naming as nullDC iirc. I don't think I changed that code. ~/.reicast/data/* ?

**Comment by LoungeKatt** [comment]
Sounds right. I was recently digging around in there and vaguely recall that being the case.

**Comment by skmp** [comment]
@Yoshimaster96 did you figure it out? Would be nice to update our README section about it

**Comment by barbudreadmon** [comment]
The name must be naomi_boot.bin and the file must be in data directory. The few games i tried didn't work though (they complain about "board error" on the naomi screen then send me to the cabinet service screen).

**Comment by skmp** [comment]
@barbudreadmon & @Yoshimaster96 please use the forum (http://forum.reicast.com) for this kind of questions, thanks
