### ISSUE TITLE
Reicast @ NSC2018  (01~09.09.2018)

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1171]
Hello team,

Like many of the past years I'll be organizing the nillware summer camp in 2018. At least me and possibly more reicast team members will be there, It'll happen around the first week of september in central greece. Ask here or PM for more details if interested.

Thanks

(Invitation for the event is still WIP, will update here as soon as things are more organized)

**Comment by luserx0** [comment]
Are we still doing this @skmp?

**Comment by skmp** [comment]
I guess this got ... refactored. Closing since it's no longer relevant.
