### ISSUE TITLE
Investigate a fb bot to resolve simple support questions / FAQs

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1173]
(title says it all. We could auto triage most messages)

**Comment by LoungeKatt** [comment]
By fb, are you talking Facebook?

I still recommend looking into Discord.

<img width="720" alt="screen shot 2018-06-11 at 9 16 42 am" src="https://user-images.githubusercontent.com/1173913/41233710-3946dbb8-6d58-11e8-800a-af01e07c63ea.png">

Tsubaki is a bot I put together to manage the channel when I'm not there.

**Comment by LoungeKatt** [comment]
And yes, it still includes the Github / travis integration

<img width="720" alt="screen shot 2018-06-11 at 9 19 10 am" src="https://user-images.githubusercontent.com/1173913/41233869-9e350752-6d58-11e8-8d09-68f62c3ca3c6.png">

**Comment by skmp** [comment]
I’ve setup a fb autoreply that redirects people to discord. We have enough active people there to handle the load for now
