### ISSUE TITLE
Graphic Bug in 3D Games

### ISSUE THREAD

**Issue by spielvan** [reicast/reicast-emulator#1175]
*Any information not included may be requested when diagnosing the issue*

| Platform | Branch | Hash | Buildbot |
| ------ | ------ | ---- | -------- | 
| Android 5.1.1 | Master? | 8c69dc8 | Yes? |

**_Description of the Issue_**

Games like Mortal Kombat Gold, Marvel Vs Capcom 2 ... have slight graphical bugs, in the case of Mortal Kombat Gold, when playing in the stage of Goro, Goro Lair, the 3D scenario is bugged and the part of the Parete of the layer of on the characters.

MXIII-G TV BOX  1000M LAN US PLUG 2GB + 16GB 4K x 2K H.265 Decoding WiFi HDMI Amlogic S812 Quad Core Bluetooth 4.0

- [x] Check this box to confirm you have filled in all relevant information

**Comment by LoungeKatt** [comment]
The purpose of the template was so you could fill it in. It's hard to read when it is all the default text and all of your info is thrown into the middle of it.

That aside, your issue is **EXTREMELY** vague and part of somewhere around 50 other issues. 
Do you have a specific issue that is not already a part of another one currently open?

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/292
https://github.com/reicast/reicast-emulator/issues/431

**Comment by baka0815** [comment]
@spielvan it would be nice if you could provide a screenshot showing the broken graphics.

**Comment by LoungeKatt** [comment]
@baka0815 it's best to establish if it is a duplicate **before** gathering a bunch of info here.
Rest assured, this is not my first time responding to an issue.

**Comment by spielvan** [comment]
@LoungeKatt I tried to fill in as much as possible, my apologies if I was not very objective, and my problem has basically been 100% related to graphic bugs, 90% of them in the background scenario, I do not have the related problem # 292 and # 431, how can I explain in Dreamcast 3D games Mortal Kombat Gold case scenario of Goro Lair, the player's closest part had to stay tarnsparente to be able to see the fight in the background, but is part of the layer without transparency, getting on the fighters and the backdrop background, in Soul Calibur (there are graphical bugs in the fighter's choice menu, and bug in the background scene in battles, perfect sound and speed), Virtua Striker 2 (bug in background and game score), perfect sound and speed) , The House of Dead 2 (Japan) (bug in the background and on the scoreboard of the game) ... by what I perceive it looks like a standard bug, which is repeated in several games.

**Comment by spielvan** [comment]
![2abe3c14-69b6-4d15-a139-14934128bd16](https://user-images.githubusercontent.com/17939556/41300709-c6a2ffd4-6e3c-11e8-8bbd-a2274b900b52.jpg)
![c28ee522-57b4-43d9-abc3-9e5c8370efad](https://user-images.githubusercontent.com/17939556/41300786-f3385512-6e3c-11e8-9b98-fa25060520bc.jpg)
![def1cfcd-22eb-43aa-bdfb-cd0c8c793df6](https://user-images.githubusercontent.com/17939556/41300800-fae94ee2-6e3c-11e8-9d28-b0672ae12ae8.jpg)
![b23563aa-d954-4e8e-a307-00001a47c028](https://user-images.githubusercontent.com/17939556/41300812-01bacd86-6e3d-11e8-914f-062f27716a2e.jpg)

**Comment by LoungeKatt** [comment]
The content was fine. I just had to move it into the right spots. Either way, I cleaned it up for this one.

I have a feeling this is related to https://github.com/reicast/reicast-emulator/issues/1162 if it wasn't related to the other two. It may also be related to what is happening in https://github.com/reicast/reicast-emulator/issues/898

If anything, at least there are a lot of different games to test. Thanks for getting screenshots of all of them.

**Comment by baka0815** [comment]
@LoungeKatt sorry, I thought that having the screenshots would help diagnosing if it's the same issue(s).

**Comment by LoungeKatt** [comment]
@baka0815 No worries. They ended up being needed, but the reason I held off was that if it was the same issue it would save the trouble of taking, uploading, posting, etc (especially on a data plan).

**Comment by spielvan** [comment]
@LoungeKatt I'm going to enjoy what they were talking about Cannon Spike, I'm taking the European version to put on tests with today's reicast build.

**Comment by skmp** [comment]
Can we move this to one issue per problem, in gamedb? Thanks.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#95
