### ISSUE TITLE
No options for mapping analog stick as buttons or keys.

### ISSUE THREAD

**Issue by retrobenny** [reicast/reicast-emulator#1184]
*Any information not included may be requested when diagnosing the issue*

| Platform                                                      | Branch | CIDL |
| Android Nougat Shield TV Pro OTA 6.3 | Debug | No?? |
| Installed OS and version (ie. Android 8.0) | Branch name (or Google Play) | Hashtag (delete if unknown) | Downloaded from build site? |

**_Description of the Issue_**

On a build from 6/14/2018;
There is no way to map analog stick directions,thus no way to use a keyboard for input.
(even touchscreen controls before made me ragequit because its hard to avoid bottomless pits)
I have reasons that I don't use a gamepad since I lack the one I would prefer to use but have no way of getting it due to freedom issues and cost and its potential rarity.
And maybe I just really like using a keyboard as input.

**_Debugging Steps Tested_**

* Nothing to try.

**_Logs Gathered_**

None

Paste the contents of the log / logs here

N/A

**_Screenshots_**

Not applicable.

- [x] Check this box to confirm you have filled in all relevant information

**Comment by LoungeKatt** [comment]
Duplicate of https://github.com/reicast/reicast-emulator/issues/1103

**Comment by retrobenny** [comment]
Oh sorry,I should've spent the time to dig through the mere 13 pages because it was just on page 2.

**Comment by LoungeKatt** [comment]
It's not *exactly* identical, but the end result of both will add the same functionality.
