### ISSUE TITLE
Controller Support On Android Tv Has Been Broken A While Now

### ISSUE THREAD

**Issue by zanzabarjones** [reicast/reicast-emulator#1199]
Controller support for Reicast on Android Boxes such as the nvidia sheld tv has been broken a while now,most users resort to using R7 or a 2015 version which was the last version to have controller support

**Comment by LoungeKatt** [comment]
Controller support was part of the reason to convert to Android Studio.
This should be fixed by https://github.com/reicast/reicast-emulator/pull/1163
