### ISSUE TITLE
Glitching showing in side of the screen

### ISSUE THREAD

**Issue by DivineCriminal** [reicast/reicast-emulator#1216]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 8.1 | Google Play | Hashtag (skip if unknown) | Downloaded from build site? |

**glitching showing in side of the screen**

I am trying to run sf 3rd strike and first of all there is no on screen buttons and screen in is not running in full resolution from both side screen is blank and Game is running laggy

- [x] Place an X in the box to confirm you have filled in this form

**Comment by AbandonedCart** [comment]
Should be resolved by https://github.com/reicast/reicast-emulator/pull/1299
