### ISSUE TITLE
Crashes when selecting Bios

### ISSUE THREAD

**Issue by Latiosdude** [reicast/reicast-emulator#1217]
**Please Note: This form is the minimum required information for submitting bugs.**

**Removing this form may lead to your issue being closed until it is completed.**

| Android 8.0 Snapdragon Galaxy S8+ | Branch 1493906 and ae2b5e3 | Hash | Downloaded from Build site |
| ------ | ------ | ---- | ---- |

**_Description of the Issue_**

Reicast crashes on latest Master and lk/android-studio builds when selecting Bios.

**_Debugging Steps Tested_**

  * Tried installing newer build on top of older build that already has the Bios set. Crashes when trying to start a game.

**_Logs Gathered_**

```


**_Screenshots_**


- [X] Place an X in the box to confirm you have filled in this form

**Comment by blackman91** [comment]
Try the latest google play beta:
https://github.com/reicast/reicast-emulator/issues/1208

**Comment by skmp** [comment]
(please reopen if not fixed)
