### ISSUE TITLE
Can't install reicast r7 beta from PlayStore after uninstalling it

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1220]
**Please Note: This form is the minimum required information for submitting bugs.**

**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Android 5.1 | master | N/A | N/A |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Issue Screenshot](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png)

- [ ] Place an X in the box to confirm you have filled in this form

**Comment by Emulatorer** [comment]
![screenshot_2018-07-12-19-36-48](https://user-images.githubusercontent.com/37603562/42631005-6e362a44-85c8-11e8-8759-243105cea491.png)

**Comment by LoungeKatt** [comment]
You may have left the beta. You would have to return to the original signup link and opt in for the beta again.

**Comment by skmp** [comment]
This looks like some issue on google's part. Is it resolved?

**Comment by skmp** [comment]
(Closing this - please discuss on http://forum.reicast.com if the issue persists)
