### ISSUE TITLE
Daytona USA widescreen problem

### ISSUE THREAD

**Issue by iPenguin22** [reicast/reicast-emulator#1224]
hi, the game Daytona USA 2001 doesn't display widescreen correctly on my Samsung galaxy note 3, i have the widescreen setting turn on and it only displays the usual 4:3 resolution and on start up the Dreamcast logo showed up in widescreen, and i have tried the widescreen setting in other games like Sonic adventure 1 & 2 and crazy taxi 2 and it does work for those games but not Daytona USA, please somebody help me! 

this is how the game starts
![screenshot_2018-07-17-08-47-22-1](https://user-images.githubusercontent.com/41332426/42851537-057030d6-89e2-11e8-969c-36ecb834df6a.jpg)

and this is how the game looks like
![screenshot_2018-07-17-08-47-57-1](https://user-images.githubusercontent.com/41332426/42851562-22b5d2cc-89e2-11e8-9b65-509d05878a19.jpg)

**Comment by skmp** [comment]
Sadly, the widescreen hack does not work with all games

**Comment by iPenguin22** [comment]
but, i saw a video of the game running with the widescreen hack

here's the link: https://www.youtube.com/watch?v=UfcmHSBVWgs&t=174s
