### ISSUE TITLE
Let's fix all shenmue issues

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1246]
The shenmue remaster gets released on the 21st, so we should have that game fixed by then. 

Anyone up for helping?

---

[Shenmue Issues](https://github.com/reicast/gamedb/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%8E%AE+shenmue%22)

[Shenmue II Issues](https://github.com/reicast/gamedb/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%8E%AE+shenmue-ii%22)

**Comment by luserx0** [comment]
@PsyMan Would you like to coordinate this one?

**Comment by skmp** [comment]
(This was wishful thinking on my part)
