### ISSUE TITLE
Reicast Beta - First no response and then force close when i try to open setting

### ISSUE THREAD

**Issue by dhanial** [reicast/reicast-emulator#1255]
**Please Note: This form is the minimum required information for submitting bugs.**

**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Issue Screenshot](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png)

- [ ] Place an X in the box to confirm you have filled in this form

**Comment by AbandonedCart** [comment]
Without any of the info from the form filled in, I am only guessing... have you tried using the latest version from http://enroll.reicast.com/? This was an issue a couple weeks back that was resolved.

**Comment by skmp** [comment]
@dhanial can you please amend this and add the version of reicast? We ill re-open the investigation then. You can see the version in the About section. As the form says, the fields should be completed :)

@AbandonedCart maybe we should make the version visible just also the side bar?
