### ISSUE TITLE
Broken master / Beta builds not from master

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1260]
38539a9c2fd98afd0e8fb0daa37205e6fa389337 broke master @dmiller423 I've reverted it and pushed your changes as `dm/cdi-warn-and-ngen-fixes`

**Comment by skmp** [comment]
@dmiller423 *pretty pls* can you avoid pushing to master and other such over-the-top commit approaches? You have full admin rights to the repo (it's you, me and @MrPsyMan atm) and you have a lota power to break things :1st_place_medal: 

Closing this as master is now working again :)

**Comment by skmp** [comment]
Looks like this issue is more complicated. Somehow builds with non-matching commits make it to google play (?)

**Comment by dmiller423** [comment]
...

**Comment by skmp** [comment]
Yeah, looks like you can't take the blame for this one, @dmiller423. The builds must have been broken by the tag change? How did that happen?

@AbandonedCart it looks like `./travis-deploy.sh` is not getting run during master builds now

**Comment by dmiller423** [comment]
@skmp : @AbandonedCart mentioned some issues w. travis and I knew that code shouldn't have possibly broken the emulator.   If it works on most of the platforms and not on one,  you know the bug lies elsewhere 99% of the time.

**Comment by AbandonedCart** [comment]
Both the commit and wonky travis builds have been fixed. The desired changes can now be *tested* against a verified working master.
