### ISSUE TITLE
r8 release (due 07/09/2018)

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1261]
August was vacations month, I guess we skipped one release. Oh well.

---

as per #1242, next release is scheduled for 20/08/2018.

What changes would you like to merge in for r8?

**Comment by skmp** [comment]
- Let's fix Shenmue #1246 
- Clang-format #965 
- Updated android UI

**Comment by blackman91** [comment]
Any way for this merge to work on Android?
https://github.com/reicast/reicast-emulator/pull/1234

**Comment by AbandonedCart** [comment]
@blackman91 It's being looked into and you already asked on the merge itself. Not every fix for Windows is going to fix Android, though. They are completely different platforms.

**Comment by blackman91** [comment]
It seems it works on Android now on fh branch, thanks a lot!

**Comment by skmp** [comment]
Welp, I tagged r8 as we're long overdue on this. I hope it works well enough!

The detailed release log was generated by `git log --merges --pretty=format:"- %b [%h, %an]" --abbrev-commit r7..r8`. We want to keep that handy somewhere

**Comment by skmp** [comment]
As soon as the build bots push the new apk, I will do the release in google play!

**Comment by skmp** [comment]
Of crouse, the build got broken for some random reason. 

https://travis-ci.org/reicast/reicast-emulator/builds/427559767

I'll investigate later....

**Comment by baka0815** [comment]
> * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Maybe we should use ``--info``?

And, as I said on discord, the git command only lists the one who did the merge, not the one who did the work. :-)

**Comment by skmp** [comment]
Removed the names and commit IDs from the log, fixed build.gradle, respun as r8.1. It's out now.
