### ISSUE TITLE
Reicast @ 35c3 (26~30.12.2018, Leipzig DE)

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1262]
"The 35th Chaos Communication Congress (35C3) is an annual four-day conference on technology, society and utopia. The Congress offers lectures and workshops and various events on a multitude of topics including (but not limited to) information technology and generally a critical-creative attitude towards technology and the discussion about the effects of technological advances on society. "

https://confwatch.ninja/events/ccc/editions/35c3

See #1150 for the general idea. If you want to apply for travel expenses, poke @skmp

**Comment by luserx0** [comment]
This is a great idea!

**Comment by baka0815** [comment]
So we aren't at 35c3?
