### ISSUE TITLE
Android: Data and Time not saving

### ISSUE THREAD

**Issue by SteelTitanium** [reicast/reicast-emulator#1264]
**Please Note: This form is the minimum required information for submitting bugs.**

**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 7.0 | Google Play | f43c03f | No |

**_Description of the Issue_**

Date and Time won't stick between boots.

**_Debugging Steps Tested_**

* Setting the region to 2 as suggested in a issue.
* Setting the time to 5 minutes before.

**_Logs Gathered_**

```
```

**_Screenshots_**

**Comment by AbandonedCart** [comment]
Does setting the time 1 minute ahead (ie. it is 11:15 and you set 11:16) work?

**Comment by SteelTitanium** [comment]
No, it don't @AbandonedCart

**Comment by OrtaDragoon** [comment]
Have you tried the day/month/year format?

**Comment by blackman91** [comment]
Can confirm the date doesn't save on latest Android beta after clean install, also even if you change the language on bios settings it doesn't get saved.

**Comment by blackman91** [comment]
Setting  it 5 minutes before does work on fh mymaster branch, then I uninstalled and installed normal beta again and the bios kept the same settings.

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/reicast/reicast-emulator/pull/1267
