### ISSUE TITLE
How do the disc swap feature work?

### ISSUE THREAD

**Issue by SteelTitanium** [reicast/reicast-emulator#1270]
How do it work, as touching the disc swap button does nothing.

**Comment by AbandonedCart** [comment]
https://github.com/reicast/reicast-emulator/issues/155
https://github.com/reicast/reicast-emulator/issues/454

TL;DR I don't know that it actually does anything right now.

**Comment by SteelTitanium** [comment]
So for the time being, it's impossible to play games which is on more than one disc?

**Comment by AbandonedCart** [comment]
For games like that, you could just get to where it tells you to insert the second disk and manually switch to the new ROM (if they are separate files).

**Comment by skmp** [comment]
@steeltitanium support questions should be asked at http://forums.reicast.com
