### ISSUE TITLE
Where can i find this exact build guys?

### ISSUE THREAD

**Issue by RaduNastase** [reicast/reicast-emulator#1274]
![screenshot_2018-08-10-08-12-36](https://user-images.githubusercontent.com/18061144/43951297-744bb18a-9c9b-11e8-84be-22d4f9c147d6.png)

Can't seem to find it among the builds. Thanks!!

**Comment by baka0815** [comment]
The Hash inside the brackets is the commit from which the build was generated. In this case it's https://github.com/reicast/reicast-emulator/commit/0dba81b.

**Comment by AbandonedCart** [comment]
It is not available on builds.reicast.com because it predates the creation of that page. Things like this are topics for the forum, though.

http://forum.reicast.com/
