### ISSUE TITLE
Right Stick On option not working.

### ISSUE THREAD

**Issue by blackman91** [reicast/reicast-emulator#1278]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 7 | Google Play latest beta | Hashtag (610cec1) | Downloaded from build site? No |

**_Description of the Issue_**

The Right stick on L/R, off A/B option in reicast input settings is not working if you enable it it doesn't save, if you go back to input settings after enabling it it is now disabled, also in r6 it was an option in the quick menu that appears when you press select, why was it removed from there?

**_Debugging Steps Tested_**

  * Enable Right Stick option.

- [x] Place an X in the box to confirm you have filled in this form

**Comment by AbandonedCart** [comment]
The menu popup is still there. It is assigned to the back button. hardware menu key, or Keycode.BUTTON_SELECT as defined by your platform and controller. If your controller is not registering the desired key, you also have the option to assign the select button under Input -> Customize Physical Controller.

**Comment by AbandonedCart** [comment]
This is solved by https://github.com/reicast/reicast-emulator/pull/1280

**Comment by blackman91** [comment]
I meant the option to enable the right stick for l/r was on the pop up menu in r6 and not in newest beta.

**Comment by AbandonedCart** [comment]
My apologies. Combining multiple issues and their details into a single sentence ran together when trying to read it. It was removed intentionally because there were too many issues with trying to change the controller layout dynamically at runtime.

**Comment by blackman91** [comment]
Thanks for the fix but it seems the right stick input is all wacky on latest beta, for instance in skies of arcadias after you use the right stick the camera won't stop spinning and in MvsC2 the stick does the vombined specials instead of just calling your partner for some reason.

**Comment by AbandonedCart** [comment]
The right stick options were meant to allow the right stick to work with racing games. It is converting an axis into a button, which completely contradicts its design. It's not intended to be an all purpose button and the feature is designed with racing games in mind. I recommend not using it to replace the already-working buttons.
