### ISSUE TITLE
LT and RT inputs dropped when moving the joystick

### ISSUE THREAD

**Issue by Juiss** [reicast/reicast-emulator#1292]
Moving around while pressing down either triggers will just drop the (trigger) input for a split second every time on my controller. I've tried rebinding the triggers to different buttons but it doesn't change anything. This only happens in Reicast. 

I'm on the latest beta build from the play store on Oreo 8.1

**Comment by AbandonedCart** [comment]
Moving this to https://github.com/reicast/reicast-emulator/issues/998, since the root issue is the same thing.
