### ISSUE TITLE
Skies of Arcadia Error and Freezes Delphinus, Enrique

### ISSUE THREAD

**Issue by AgentCBZ** [reicast/reicast-emulator#1293]
Android Nougat 7.1.1
Downloaded from Google Play

Game will show error and then will freeze once you get the Delphinus and Enrique for the first time.

Using the latest version from google play

Tried
Force Software Rendering 
Frameskip Value 1

Here are the VMU files just before the boss fight and the freeze:
https://drive.google.com/file/d/109fdzgXwtDesAnxxYVr9sNnoZxYSQa5Q/view?usp=drivesdk

https://drive.google.com/file/d/17WRZomLs4m7fZgv5kmeoQAF19erZ4257/view?usp=drivesdk

- [x ]

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#113

**Comment by skmp** [comment]
@AgentCBZ Please open game compat related issues in the gamedb subproject in the future. Moved this one there. Thanks for reporting :)

**Comment by AgentCBZ** [comment]
Will do. Thanks for the correction.
