### ISSUE TITLE
cdi loading is broken on some samsung devices

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#13]
Tested on our Galaxy tab 7.0 Plus. Other devices might also be affected.

**Comment by skmp** [comment]
(Closing this, we can look again into it if people report it again)

**Comment by skmp** [comment]
Actually, let's flag it as retest

**Comment by LoungeKatt** [comment]
I never had issues with cdi files on the Note 4 (as of 2017) as long as all of the files were kept together in an isolated folder. Haven't been able to test playing anything since Note 4 updated to 7.0 and stopped working with the memory configuration.

**Comment by AbandonedCart** [comment]
Have not seen any reports that it stopped working, so it should be safe to return this to closed.
