### ISSUE TITLE
Issues in the game OUTTRIGGER

### ISSUE THREAD

**Issue by Biryuk666** [reicast/reicast-emulator#1300]
Xiaomi mi 5s. Android 7.0. Emulator download from google play market (Reicast r7). Game version is 1.003 NTSC-U
1) When you try to play for Neil or Tereshkova, the game crashes in vs mode (look first screenshot)
2) The icon of the selected character is not displayed during the selection of missions in vs mode (look second screenshot)
3) Darkness does not work in night missions (look third and fourth screenshot)

![7zxx72o98wg](https://user-images.githubusercontent.com/42495055/44300561-aacaf780-a311-11e8-9015-a113ba16a254.jpg)
![umk4mz7sj1s](https://user-images.githubusercontent.com/42495055/44300410-28413880-a30f-11e8-8112-c4851cf32b81.jpg)
![d5u1ziorv8k](https://user-images.githubusercontent.com/42495055/44300412-31caa080-a30f-11e8-9868-d48679708fb3.jpg)
![ap2gpo9bmmw](https://user-images.githubusercontent.com/42495055/44300415-38f1ae80-a30f-11e8-89f9-e14817ec9395.jpg)

**Comment by AbandonedCart** [comment]
Moved to gamedb at https://github.com/reicast/gamedb/issues/115
