### ISSUE TITLE
How do I get vmu's for port 2, 3, and 4?

### ISSUE THREAD

**Issue by MasterGamingYT** [reicast/reicast-emulator#1302]
I try renaming the vmu to something like "vmu_save_B1.bin" but that didn't do anything

**Comment by baka0815** [comment]
Doesn't work currently, but support is on the way (see #1288).

**Comment by AbandonedCart** [comment]
Ill add the Android side when you give the go ahead @baka0815

**Comment by baka0815** [comment]
I hope to get the refactorong done today, but that's no promise. Need to test on Windows first.

**Comment by blackman91** [comment]
So this works now? How do you enable it on Android?

**Comment by baka0815** [comment]
It's only possible on Linux currently.

**Comment by AbandonedCart** [comment]
Not for long ;) https://github.com/reicast/reicast-emulator/pull/1312

**Comment by AbandonedCart** [comment]
To answer the original question, open "Input" and select them from the dropdown list. It does, however, currently require a controller. This is not unlike the actual hardware, though.

**Comment by blackman91** [comment]
Figured it is better to report here than open other issue:

The additional VMUs are not working on latest beta even with a second gamepad connected, also tried renaming one to "vmu_save_B1.bin"  but it still doesn't detect the vmus even when the second controller is detected:
![screenshot_20180822-160339](https://user-images.githubusercontent.com/6578180/44492448-2f778780-a62a-11e8-8caf-9d616db52c2e.png)

**Comment by blackman91** [comment]
Fixed by df2d4fa

Great works devs.
