### ISSUE TITLE
Issues in the game OUTTRIGGER. Part 2

### ISSUE THREAD

**Issue by Biryuk666** [reicast/reicast-emulator#1309]
Xiaomi mi 5s. Android 7.0. Emulator download from google play market (Reicast r7). Game version is 1.003 NTSC-U

1. Every time you start the game, you need to set the time
![1f9uima31ua](https://user-images.githubusercontent.com/42495055/44382735-d8d15700-a51e-11e8-83cc-f8ce1febec6e.jpg)

2. Incorrectly displayed widescreen image in the initial splash screen, the main menu of the game, when you start the game in Versus mode with bots. Also, when playing in the edges of the screen area, various objects disappear (first-aid kits, cartridges, etc.)
![7bg2wvpoke8](https://user-images.githubusercontent.com/42495055/44382913-7c226c00-a51f-11e8-9043-dfde46fd70de.jpg)
![4n_ckjml0v0](https://user-images.githubusercontent.com/42495055/44382916-7f1d5c80-a51f-11e8-83d3-2543a13b290e.jpg)

3. When you start the company in mission mode, the game crashes
![08c75vmhygo](https://user-images.githubusercontent.com/42495055/44382924-880e2e00-a51f-11e8-94f2-cced1093d80a.jpg)

4. At death the window with the person who killed you is incorrectly displayed 
![zrafxnk8gnq](https://user-images.githubusercontent.com/42495055/44382960-a8d68380-a51f-11e8-88cd-701cd5eef05a.jpg)
![ma6wfdsit3u](https://user-images.githubusercontent.com/42495055/44382961-a8d68380-a51f-11e8-8d84-7830f7e2e02a.jpg)
![36xq2ncfofu](https://user-images.githubusercontent.com/42495055/44382962-a96f1a00-a51f-11e8-9e17-3ec5e837c3d6.jpg)

**Comment by AbandonedCart** [comment]
Moved to https://github.com/reicast/gamedb/issues/115

@Biryuk666 Please submit future game issues to https://github.com/reicast/gamedb and try to avoid opening a second issue to add more details to an existing one.
