### ISSUE TITLE
Support switchable button.pngs

### ISSUE THREAD

**Issue by weihan1102** [reicast/reicast-emulator#132]

**Comment by blackman91** [comment]
So what does the option onscreen button theme in reicast settings do? Can you change someway your onscreen button theme from there or you have to replace them manually?

**Comment by AbandonedCart** [comment]
Make a themes folder alongside reicast's /data/ folder, put a button png in there from here, the forum, or one you designed to the specs of the one already in the folder, go to the app's settings and pick it from the themes.

**Comment by baka0815** [comment]
Should we update the documentation?
