### ISSUE TITLE
Missing symlink for libevdev.so can result in failed auto-detection

### ISSUE THREAD

**Issue by gameblabla** [reicast/reicast-emulator#1336]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Void Linux Musl | master | dunno | From source |

**_Description of the Issue_**

The evdev code expects the dynamic library to be named "libevdev.so".
https://github.com/reicast/reicast-emulator/blob/master/core/linux-dist/evdev.cpp#L29
However on some linux distributions (Void linux, Debian so far), such symlink does no exist for evdev, so it will fail the autodetect on those unless you create a symlink or modify the source code.

**_Debugging Steps Tested_**

  * Creating a symlink (seems to work)
  * Change "libevdev.so" to "libevdev.so.2"

**_Logs Gathered_**

```

```

**_Screenshots_**

None needed

- [X] Place an X in the box to confirm you have filled in this form

**Comment by baka0815** [comment]
Thanks.

**Comment by AbandonedCart** [comment]
https://www.linuxquestions.org/questions/linux-from-scratch-13/evdev_drv-so-cannot-find-libevdev-so-even-though-it-is-installed-and-shows-up-in-ldconfig-4175615549/

**Comment by AbandonedCart** [comment]
https://github.com/godotengine/godot/pull/3471/commits/29353808f0391f78627c43090f1bff882d56f11e

**Comment by baka0815** [comment]
I'm unsure what your link should help with?
``libevdev.so`` is missing on some Linux systems (at least Debian and Void musl), so we should first try ``libevdev.so.2`` before falling back to ``libevdev.so`` or vice versa.
Another possibility would be to try convincing all distibutions to provide a symlink...

**Comment by AbandonedCart** [comment]
Read the other two.

**Comment by baka0815** [comment]
Or are you suggesting removing evdev (as your link to the godot engine hints at)?

**Comment by AbandonedCart** [comment]
I posted the links so you could **read** them for possible ideas.

**Comment by baka0815** [comment]
Thanks for that, however I don't know what to do with them. The second link to freedesktop seems unrelated to me and the godot link removes evdev to support udev only and that would be a bit too much.
The issue is not that evdev is missing and needs to be replaced woth something different bll, but that the name of the shared library is different from what we expect.

**Comment by AbandonedCart** [comment]
I was led to believe libevdev.so.2 was not properly being linked to libevdev.so

I guess you are on your own then. There are no results for that.
