### ISSUE TITLE
Support for configuring graphics options, such as FXAA, CSAA and MSAA

### ISSUE THREAD

**Issue by Gamemulatorer** [reicast/reicast-emulator#1345]
**_Feature Request_**  

| Platform | GPU |
| ---- | ---- |
| ANDROID 5.1 | Mali-450 GPU |

**_Description of the Feature_**

Support for configuring graphics options, such as FXAA, CSAA and MSAA

- [X] Place an X in the box to confirm you have filled in this form

**Comment by Emulatorer** [comment]
*Sorry for my bad english 🙍

**Comment by AbandonedCart** [comment]
I believe you forgot to include any of your own information in the form.

**Comment by Emulatorer** [comment]
@AbandonedCart sorry 😅

**Comment by AbandonedCart** [comment]
This would be more appropriate for the [forums](http://forum.reicast.com/) or [discord](http://chat.reicast.com/). reicast is multithreaded, but more information would be required about which shader this is referencing.

**Comment by Emulatorer** [comment]
@Abandoned I mean a Shader like FXAA, CSAA and MSAA?

**Comment by AbandonedCart** [comment]
If I follow, you are more or less trying to get anti-aliasing?

**Comment by Emulatorer** [comment]
YES!
now I get it 😀

**Comment by AbandonedCart** [comment]
It's somewhat automatic. Specifying that you use anti-aliasing would mean that it either works or it doesn't. By not specifying it, it is used when it is supported and does not stop working when it isn't.

**Comment by Emulatorer** [comment]
![screenshot_2018-08-29-23-38-45](https://user-images.githubusercontent.com/37603562/44798848-10d13d80-aba2-11e8-857f-6beeebadd3c4.png)

filter shader like all of that can reicast support it in android in the future update?

**Comment by ghost** [comment]
Reicast is dead say hello to flycast and redream on android 🤷
