### ISSUE TITLE
Cannot modify touch config and bluetooth audio problem

### ISSUE THREAD

**Issue by Pauch1n** [reicast/reicast-emulator#1355]
Hi all. This is my first time using github to submit a problem report so please pardon me if I am missing information.

I always follow builds.reicast.com updates, but one of the updates made me unable to install over a previous version, I believe this version started from 8-25-2018. I had to uninstall the version I had and install the newer one.

Since the settings will be reset, I had to reconfigure my touch layout. The problem is that since this recent commit and onwards, I was never able to get into the layout screen, it justs display a black screen that seems to be frozen from then on. More puzzling is that even if I uninstall the newer builds and install older than 8-25-2018 builds, the same issue persists. For some reason, the fh\mymaster builds do not have this problem.

Another long standing problem that I have with this emu is that performance with bluetooth audio consistently stutters. I know my phone is not the best but I am sure it can handle Capcom vs SNK 2 very well. This stutter happens to other games too. Performance is good without bluetooth audio. I have tested 4 devices over the course of 2 years of reicast updates and same problem happens across all of them.

Sorry if this message seems a little long to read. Despite all of this, I sincerely appreciate the efforts all of you put into this emulator. Cheers!

**Comment by baka0815** [comment]
Bluetooth audio requires the CPU to do extra work which seems to be too much for your device if it's working good without bluetooth.

**Comment by AbandonedCart** [comment]
When you submit a new issue, there should be a form that pops up. This exists for two reasons. One is so that you make sure to provide the vital information required and the other is to minimize the difficulty of navigating a large paragraph to find that information.

What device is it?
Can you provide the hash number of the earliest build when you started seeing this problem (It's under the "Commit" heading on builds.reicast.com)?
Are you setting your home folder to an internal sdcard (not a hardware sdcard)?

**Comment by AbandonedCart** [comment]
It may also be important to mention that there was one build (which may have been on 8/25) that caused a corrupted buttons.png to be written. The corrupted file would pass detection, thus preventing other versions from replacing it. The solution was simply to delete the buttons.png

This would not be seen on other branches, which may not have included all of the changes from master or merged them far enough before and after the issue occurred and was resolved to not register a specific build that included it.

Again, the solution for this would simply be to make sure you are using a recent build (within the last 2 days of this post) and simply delete the 0kb buttons.png to allow a new one to be created.

**Comment by AbandonedCart** [comment]
After researching further, this issue occurred 25 days ago, not on the 25th. 
869cc56 caused the issue, a5fffb9 resolved it, and f0f1190 added a check for the 0kb image

**Comment by Pauch1n** [comment]
Hi again! Yeah, I actually saw the template and I know how useful it can be. It's just that I am on mobile and also on commute when I posted the message and with the amount of information I am trying to get across, I figured it may be better to just get the ball rolling. Sorry about that.

Regarding the Touch layout issue, I am currently using a Lenovo K8 Note phone, with stock Android 8.0. I use 2 directories for my settings, the settings themselves on the internal memory and the games on the external sdcard. I know I configured the folders right as the games loaded and the saves are being read. Sadly, as of commit 775f232, the issue is still there and deleting buttons.png did not work, it is not 0kb if youre wondering. I will try isolating the commit that caused this later. More on bluetooth audio in another post.

**Comment by Pauch1n** [comment]
As for bluetooth audio, I tested various versions of reicast on different phones. Here they are:

Asus Zenfone 2 ZE551ML - Android 5-6 - stutters
Huawei Honor 6X - Android 6-7 - stutters
Huawei P8 Lite 2017 - Android 7 - stutters
Lenovo K8 Note - Android 7-8 - stutters
Asus Zenfone Go ZB500KG - Android 5.1 - no problem

Yeah I said only 4 devices earlier, I just remembered my shortly owned zenfone go. To the guy who mentioned that bluetooth is too cpu intensive, I tend to not believe as the weakest of the phones mentioned ran with bluetooth audio nicely. Maybe I am missing a setting, but I am out of ideas honestly.

**Comment by Pauch1n** [comment]
Update, the recent commit 205affb sets the System path to default (/storage/emulated/0/) even if I manually set the folder to /storage/emulated/0/reicast 

Found about an old master build lying on my harddrive that does not have the layout problem (bcf1820), will check on later versions to see what commit I get the problem.

**Comment by AbandonedCart** [comment]
There has to be something else going on with that device. The commit you are referencing consists of two changes. One is to hide the link in the menu on Android TV and the other is to delete a variable that was not used from the native side.

**Comment by AbandonedCart** [comment]
Driver incompatibility.

**Comment by Pauch1n** [comment]
I guess that just it. Thanks for the time!
