### ISSUE TITLE
Make SDL input usable

### ISSUE THREAD

**Issue by baka0815** [reicast/reicast-emulator#1371]
The SDL input backend currently is hardcoded (like the X11 keyboard backend), caputures the mouse and only works with the first joystick.
The following tasks should be done to make the experience much nicer:

- [x] Make keyboard work (#1370)
- [ ] Configurable key/button layout
- [ ] Allow more than one joystick
- [ ] Configurable maple devices (VMU, PurupuruPack, Mouse)
- [ ] Use [GameController](https://wiki.libsdl.org/CategoryGameController) API
- [x] Rumble support (#1486)
- [ ] Split SDL GUI and SDL INPUT support
- [ ] Support hot-plugging work (support SDL_JOYDEVICEADDED and SDL_JOYDEVICEREMOVED)

**Comment by baka0815** [comment]
@flyinghead could you take a look what of the above list is done already since we merged your branch?

**Comment by flyinghead** [comment]
Everything is done except splitting GUI and input code.

**Comment by baka0815** [comment]
Ok, since @dmiller423 or @MrPsyMan said that it's unwanted to split GUI and input code, we can close this.
