### ISSUE TITLE
[BUG?] Linux Crashes with Trace Trap and SIGSEGV

### ISSUE THREAD

**Issue by knight-ryu12** [reicast/reicast-emulator#1380]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Linux | origin/master | eacbae5b | No |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Linux latest build (from git) still crashes.

**_Debugging Steps Tested_**

**_Logs Gathered_**

```
Config dir is: /home/io/.config/reicast/
Data dir is:   /home/io/.local/share/reicast/
Personality: 00000000
Updated personality: 00000000
Linux paging: 4096 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 382D0000, aram: 582d0000, vram: 3C2D0000, ram: 442D0000
Resetting mem
Mem alloc successful!
libwebsockets test server - (C) Copyright 2010-2013 Andy Green <andy@warmcat.com> - licensed under LGPL2.1
Initial logging level 7
Library version: 1.3 c11b847
IPV6 not compiled in
libev support not compiled in
 static allocation: 4488 + (16 x 1024 fds) = 20872 bytes
Malformed entry on config - ignoring @ 44(ElfFile)
Malformed entry on config - ignoring @ 47(ta.HashCheckFile)
Malformed entry on config - ignoring @ 48(ta.HashLogFile)
 canonical_hostname = antidote
 per-conn mem: 184 + 1554 headers + protocol rx buf
 Listening on port 5678
Found 10 matching FB configs.
Chosen visual ID = 0x24
Loaded /home/io/.local/share/reicast/data/dc_boot.bin as bootrom

Loaded /home/io/.local/share/reicast/data/dc_nvmem.bin as nvram

gdrom: Failed to open image "null"
Using Recompiler
Auto-selected audio backend "alsa" (Advanced Linux Sound Architecture).
Initializing audio backend "alsa" (Advanced Linux Sound Architecture)...
recSh4 Init
Freeing fpcb

	 CodeCache addr: 0x5567a8bed000 | from: 0x5567a8bed000 | addr here: 0x5567a8beb160
evdev: Trying to open device at '/dev/input/event0'
evdev: open: Permission denied
SIGSEGV @ 2838539480 (fault_handler+0x7552296) ... 0x94 -> was not in vram
Fatal error : segfault
 in fault_handler -> /home/io/build/reicast-git/src/reicast/shell/linux/../../core/linux/common.cpp : 100 
```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by knight-ryu12** [comment]
Using Archlinux AUR Build `reicast-git`, should be no problem but hmm?

**Comment by baka0815** [comment]
Have you tried setting the correct permissions for your user?
````
evdev: Trying to open device at '/dev/input/event0'
evdev: open: Permission denied
````

**Comment by knight-ryu12** [comment]
I think that's bad idea and it must be irrelevant.
it's block device. points to evdev event…


2018年9月18日(火) 19:39 Christoph <notifications@github.com>:

**Comment by baka0815** [comment]
Well, in your configuration (``emu.cfg``) you have probably set evdev_device_id to "0" which would be "event0" and you don't have permission to use this evdev device.

Try granted the user the group necessary to open the devices and see if that works or (note recommended) try running reicast with sudo to see if that works.

**Comment by knight-ryu12** [comment]
to be honest, getting this kind of error ith no cinfig edited should be
fixed.

thanks for recommendation, will try.

2018年9月18日(火) 22:48 Christoph <notifications@github.com>:

**Comment by baka0815** [comment]
In evdev.cpp we're checking if the ``fd`` is lower than 0:
https://github.com/reicast/reicast-emulator/blob/eacbae5b30bcf64f75733a4fe761df9aeb64ce71/core/linux-dist/evdev.cpp#L509
However since ``fd`` is never initialized when the controller can't be read it might be ``0`` and the code tries to happily read from an invalid device.
We should initialize fd to ``0`` to avoid this. I will look at this the coming weekend.

**Comment by baka0815** [comment]
That can't be true. If evdev was disabled, reicast wouldn't printout those messages.

Did the workaround work for you?

**Comment by knight-ryu12** [comment]
got time for test, abd it worked, thanks.
