### ISSUE TITLE
Proposal: Switching to Time-based releases & version numbers

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1381]
I think this has been discussed in the past, and there were no objections.

Proposal
---

Aim for a release on the first Monday of each month. Make milestones for 3 releases ahead, then [Mid Term Goals](https://github.com/reicast/reicast-emulator/milestone/4) for 3-9 months ahead, and [Long Term Goals](https://github.com/reicast/reicast-emulator/milestone/2) for 9+ months ahead. Plan for a soft "feature freeze" on the week before release, to allow for the beta builds to be tested via the open beta program.

I've renamed the next two [milestones](https://github.com/reicast/reicast-emulator/milestones) to "18.10" and "18.11", in yy.mm(.respin) format. The idea is to follow a similar naming to what Ubuntu uses. Respins can be used if there are issues with the original release, similar to how we handled `r8` -> `r8.1`.

Are there any objections?

Next steps
---

Assuming there are no strong opinions against this, @MrPsyMan can you go over the existing open ticket and try to categorize them into appropriate milestones?

~

**Comment by baka0815** [comment]
No objections here.

**Comment by AbandonedCart** [comment]
Might be good to start considering how many people you have with experience in a particular category when coming up with a timeline, too. Setting 600 goals for Android and 2 for Windows when you have 6 people that are experienced in Windows and only 2 1/2 for Android isn't very realistic. A large portion of the contributor list has been on hiatus for what seems like years.

**Comment by skmp** [comment]
That's a good point. I think tickets shouldn't be assigned to a milestone unless there's a willing developer to work on them.

**Comment by skmp** [comment]
Alright, will follow up within the week with an MR updating the docs for this.

**Comment by skmp** [comment]
Will follow up for documentation via #1385

**Comment by skmp** [comment]
@gigaherz FIY
