### ISSUE TITLE
Sonic Adventure 2 Crash and On-Screen Gamepad resizing issue

### ISSUE THREAD

**Issue by OGJunerenP** [reicast/reicast-emulator#1382]
> Hey, Juneren here running on Android 7.1.1 NMF26F. My Phone is Xiaomi Mi Max 2 in MIUI Global 9.6 | Stable 9.6.3.0(NDDMIFD). I have an issue with Gamepad resizing here. Now I play DC games in a weird way. And Sonic Adventure 2 (US Version) also crashes with log. My Reicast version is r8.1-11-geacbae5b installed on Google Play Store.
What are we gonna do with it?

**Comment by OGJunerenP** [comment]
![screenshot_2018-09-19-12-53-52-780_com reicast emulator](https://user-images.githubusercontent.com/36287987/45732149-a003cb00-bc0d-11e8-8d1d-992e5c76b2e5.png)
Here's the Screenshot.

**Comment by AbandonedCart** [comment]
Moved to https://github.com/reicast/gamedb/issues/80 and next time, please fill out the form. It is there to make sure you give us all the info we need and format things for you.

**Comment by OGJunerenP** [comment]
Oops, sorry about that.
