### ISSUE TITLE
Release 18.10 Discussion

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1386]
Hello team,

What do you think can be merged to master by Monday 1st of October?

What issues do you think should be resolved by then

Cheers~

**Comment by skmp** [comment]
You can see the tickets assigned right now in the [milestone](https://github.com/reicast/reicast-emulator/milestone/6)

**Comment by baka0815** [comment]
I will at least take a look at #1380.

I **might** resubmit CHDv5 (#1363) support, but I won't promise that.

**Comment by skmp** [comment]
@AbandonedCart Just got an email from google with "Action required: Update your Android targetSdkVersion by November 1st". I've noticed a lot of android PRs, so not sure if this is an issue still or not?
