### ISSUE TITLE
Latest Build has a problem with UI in Android

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1417]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
|---|---|---|---|
| Android 5.1 | Playstore Beta | | |

**_ScreenShots_**
![screenshot_2018-09-27-17-08-14](https://user-images.githubusercontent.com/37603562/46135630-297e5300-c235-11e8-861c-7fce69c1ed83.png)
![screenshot_2018-09-27-17-08-07](https://user-images.githubusercontent.com/37603562/46135647-33a05180-c235-11e8-8c90-90a3d95eedfb.png)

**Comment by AbandonedCart** [comment]
It looks like the background isn't loading for you. Unfortunately, there is not enough information in the screenshots to figure out why.

**Comment by AbandonedCart** [comment]
I was able to duplicate the issue. It appears to be specific to Android 5.0

**Comment by AbandonedCart** [comment]
Looks like while tint was made available in API 21 (5.0 is 22), the style option only works after API 24. Another one of Android's undocumented limitations, I guess. Either way, there will be a fix for this shortly that will make the theme compatible. Don't want anyone missing out ;)

**Comment by Emulatorer** [comment]
![screenshot_2018-09-28-05-04-16](https://user-images.githubusercontent.com/37603562/46174744-6419d700-c299-11e8-8e51-22d62c5cbca8.png)

it's OK now thanks!

**Comment by blackman91** [comment]
Emulatorer can you access the reicast settings?

**Comment by Emulatorer** [comment]
Yes! 😀
![screenshot_2018-09-28-10-34-04](https://user-images.githubusercontent.com/37603562/46184874-161bc800-c2c7-11e8-8dd2-d974cb1835ed.png)

**Comment by blackman91** [comment]
That's so weird when I press the settings this happen on my device on Android 7:
https://youtu.be/d4E8Ak2-nd4

Not sure what is causing it, log shows nothing.

**Comment by Emulatorer** [comment]
hmm.. maybe because of your android version?
