### ISSUE TITLE
MVC2 Lag

### ISSUE THREAD

**Issue by Gabi1117** [reicast/reicast-emulator#1432]
| Android 8.0 | Google Play |

I used to play MVC2 on an older device (Android6.0), and it ran perfectly. I recently bought a new phone running on Android8.0, and it lags now. Especially during special moves where multiple characters appear on screen.

I've tried switching on and off all graphical settings, almost all possible combinations to no avail.

Is there anything I can do about it?

**Comment by blackman91** [comment]
Are you using reicast latest beta?
Subscribe here:
http://builds.reicast.com/

**Comment by dmiller423** [comment]
Unfortunately not only do we not have enough details here,  this could also be driver/optimization related...  very likely the GLES2 driver.  There is also the possibility you're new phones hardware is actually slow than your old phone,  we don't know as you did not provide any hardware info.

I will keep this open for a while, if you'd like to provide some hardware details for both devices and let us know if this happens on other games as well or is limited to MVC2,  we might be able to provide some insight.  Or else the issue will be closed.

**Comment by Gabi1117** [comment]
I posted a few screenshots of the hardware info of my new phone and my old phone. In the meantime, what games are similar to MVC2 that I should try?

Hardware Information:
https://imgur.com/gallery/nSJTnm4

**Comment by Gabi1117** [comment]
I just tried Capcom vs SNK 2. On the newest versions of reicast, it keeps crashing. I downgraded to the builds released on september, and the game lags a bit. I downgraded again to version r7-115-g3905d6e9 released on october, and it runs perfectly. I tried MVC2 on all versions mentioned, but the game still lags using each one. To be honest, it's one of the only dreamcast games I really enjoy playing, so if someone could help me, I'd really appreciate it.

**Comment by Gabi1117** [comment]
Just tried the new release of reicast on December 1. Game still lags.

**Comment by Gabi1117** [comment]
Could you share the link to the download page? I can't seem to load the site.

**Comment by baka0815** [comment]
Not the current master debug build (there are currently very little changes), but the version from fh's tree.
He has some fixes and features which are not par of reicast master (yet), so your bug might be fixed with his changes.

**Comment by Gabi1117** [comment]
I tried the latest version from fh/mymaster, nothing seems to be different.

**Comment by dmiller423** [comment]
We have no real means of testing on various android devices,  so it's difficult to say w.o profiling on that device...  It's very likely tuning of GLES that would make a difference.  You are welcome to build from source, profile and submit info on what is causing the slowdown.   Other than that,   If you want to donate hardware,  someone might be able to look into tuning for certain device families and graphics chipsets such as Adreno...   Or else it's hit or miss unfortunately,  some features will cause slowdowns and what is an optimization on one device might slow another.

**Comment by Gabi1117** [comment]
Thank you for telling me. Is it possible that in the future updates of reicast, it will be resolved?

**Comment by Gabi1117** [comment]
The thing is, most games on the play store that I've downloaded on my new phone are either just as fast or faster than my old phone. Anyway I'll close this issue. Thanks for the help everyone.
