### ISSUE TITLE
How to run Spawn: In the Demon's Hand in reicast emulator ???

### ISSUE THREAD

**Issue by Karaulov** [reicast/reicast-emulator#1436]
How to enable dynarec after start game as in NULLDC?

**Comment by dmiller423** [comment]
Please read the documentation,  considering there was no proper issue here and he seems to be confused as to whether he is running nulldc or reicast I'm closing.

**Comment by Karaulov** [comment]
Thanks i fix all errors in this issue https://github.com/reicast/reicast-emulator/issues/1445
