### ISSUE TITLE
Games crash due to unimplemented opcode

### ISSUE THREAD

**Issue by Eds1989** [reicast/reicast-emulator#1437]
| Platform | Branch | Hash | CIDL |
RetroArch 1.7.4, Most recently available core installed through RetroArch

| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |
Windows 10

**_Description of the Issue_**

I have some games in CDI format, that when run through RetroArch using the Reicast core, causes the core/RetroArch to close after displaying the SEGA license logo just after the BIOS.
I get some kind of opcode error, and this seems to be true for multiple games.

I am unsure on how to interpret the crash text, and am not sure if the issue is with the game, the BIOS or the emulator.

**_Debugging Steps Tested_**

Other games run ok.
Have not tried any other BIOSes as not sure if there are different ones for different regions?
All games tested are NTSC anyway.

**_Logs Gathered_**

```

reios: Area symbols is: JUE
reios: Peripherals is: 0799810
reios: Product number is: T42101N 00
reios: Product version is: V1.003
reios: Release date is: 20000110
reios: Boot filename is: 0WINCEOS.BIN
reios: Software company is: ECHELON
reios: Software name is: WILD METAL                                                                                     
reios: loading ip.bin from FAD: 63512
reios: bootfile is '0WINCEOS.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 63535, len: 2048
[libretro ERROR] Failed to locate bootfile.
[libretro INFO] [LUT]: Product number: T42101N 00.
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Freeing fpcb
Get MemPtr unsupported area : addr=0x80000080
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
Freeing fpcb
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
MODEM Reset
sh4io: Invalid read access @@ 00000030
Freeing fpcb
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
Freeing fpcb
Freeing fpcb
new tactx
new tactx
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
MEM remap 0 : 0x5800 to 0xC345800
Get MemPtr unsupported area : addr=0x5B90
Get MemPtr unsupported area : addr=0x67EC


Unimplemented opcode: 00004DC8 next_pc: 000067F2 pr: 00005B94 msg: Unknown opcode
[libretro INFO] Fatal error : iNimp reached

 in cpu_iNimp -> core/hw/sh4/interpr/sh4_opcodes.cpp : 66
DEBUGBREAK!

```

**_Screenshots_**

- [X] Place an X in the box to confirm you have filled in this form

**Comment by baka0815** [comment]
Sorry, but we're not retroarch, so I'm closing this. Go to https://github.com/libretro/reicast-emulator/issues to get help.
