### ISSUE TITLE
(reicast 8.1) problems with analog stick and the L and R triggers

### ISSUE THREAD

**Issue by iPenguin22** [reicast/reicast-emulator#1450]
hi there!

i checked out the brand new version of reicast and i gotta say its really good, my favorite part is that they fixed the shadow of King Boom Boo's boss fight

but there is a problem...

i have the SN30 Pro gamepad from 8bitdo and it works fine but, i tried to set the controller for the emulator but when i do it the L and R buttons doesn't work, i checked online if this was a common issue (Link to the issue: https://github.com/reicast/reicast-emulator/issues/1052 ) it says that by activating the compatibility mode would fix the problem, it did, but it brought a brand new problem, now the analog stick is set AS...    A...    D PAD INPUT, pls somebody help me, please...

HEEEEEEEEEEEEEEEEEEEEEEEEEEELLLLLPPPPP!!!!!!!!!!!!!!

**Comment by blackman91** [comment]
Disable compatibility mode and enable just the option enable custom key layout.

**Comment by iPenguin22** [comment]
It worked thanks!

**Comment by blackman91** [comment]
Close the issue then.
