### ISSUE TITLE
No beta update in google playstore? 

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1455]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Android | PlayStore | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**
![screenshot_2018-11-04-13-03-43](https://user-images.githubusercontent.com/37603562/47960212-2a9e5f00-dfef-11e8-996d-674f1050e43f.png)

(Replace this line with any issue screenshots)

- [ X] Place an X in the box to confirm you have filled in this form

**Comment by palmeras** [comment]
Bloqueo de aplicacion reicast al intentar establecer ruta de juegos .permisos activados en android 8.1

**Comment by Emulatorer** [comment]
@palmeras speak English only please

**Comment by palmeras** [comment]
Locking the application of reicast when trying to establish route of games. Permissions activated in Android 8.1

**Comment by Emulatorer** [comment]
@skmp @AbandonedCart Sir any reason why there's a beta update in google play??

**Comment by baka0815** [comment]
Because we fixed the bug which has hindering the upload.

**Comment by Emulatorer** [comment]
@baka0815 ok sir thanks for the reply :)

**Comment by baka0815** [comment]
You're welcome.
I think we can close this?

**Comment by Emulatorer** [comment]
ok
