### ISSUE TITLE
Fix Disappearing HUD for Tokyo Xtreme Racer 2 and fix crash on Android 7.1.4

### ISSUE THREAD

**Issue by EsKecap** [reicast/reicast-emulator#1457]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [ ] Place an X in the box to confirm you have filled in this form

**Comment by baka0815** [comment]
Closing this as not even the minimum form is filled in.

See https://github.com/reicast/gamedb/issues/62 for Tokyo Xtreme Racer 2.
