### ISSUE TITLE
Sonic Adventure 2 King Boom Bio(No Shadows)Reicast

### ISSUE THREAD

**Issue by stsonic** [reicast/reicast-emulator#1463]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 5.1.1 | Google Play | All(r8.1 and latest beta| No |

Sonic Adventure 2 does not display shadows on reicast making King Boom Boo unplayable.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [X ] Place an X in the box to confirm you have filled in this form

**Comment by dmiller423** [comment]
@MrPsyMan We all know you want to test,  break out that new phone and see if it's a depth buffer or masking issue 🔢

**Comment by MrPsyMan** [comment]
That's modifier volumes.

**Comment by MrPsyMan** [comment]
I had the impression we support those.

Navigate through the reicast configuration settings. There should be an option to enable them.

**Comment by stsonic** [comment]
I already saw "Enable Modifier Volumes" in the PGC config section,but when
I turn it on and click on "Save PGC",it doesn't save.

**Comment by MrPsyMan** [comment]
I see. Probably a bug in our permission handling. For the time being, try running the game after changing the option and see if it helps.

**Comment by baka0815** [comment]
@stsonic did it help?

**Comment by stsonic** [comment]
it didnt help i cant enable PGC configuration

**Comment by stsonic64** [comment]
Works in latest Reicast version
