### ISSUE TITLE
A certain reicast menu disc read error

### ISSUE THREAD

**Issue by Tyfp** [reicast/reicast-emulator#1465]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [ ] Place an X in the box to confirm you have filled in this form

MODEL: LGMS330
DEVICE: m1
BOARD: msm8909
Lollipop (22)

Native Interface Output

--------- beginning of system
--------- beginning of main

**Comment by baka0815** [comment]
Sorry, but this doesn't tell anything.
