### ISSUE TITLE
implementation of stretch screen mode (nulldc) in android reicast.

### ISSUE THREAD

**Issue by palmeras** [reicast/reicast-emulator#1470]
I request to implement in future build of reicast android a mode of full screen (stretch) similar to the one used in the pc emulator "nulldc". With this screen mode you could play games like "soul calibur" in full screen on android devices .It is sure that many users would love to have this option available for those games that do not work well with widescreen mode. my device is: asus rog phone.android 8.1 oreo.snapdragon 845 8gb ram

**Comment by dmiller423** [comment]
Please stop opening multiple issues for the same problem.
