### ISSUE TITLE
Black screen in build 5664bfb 2018-12-13T10: 19: 28,000Z, from fh / mymaster

### ISSUE THREAD

**Issue by spielvan** [reicast/reicast-emulator#1471]
Until the build fea5f05 2018-12-13T08: 58: 13.000Z of fh / mymaster, it works normally, but from build 5664bfb 2018-12-13T10: 19: 28.000Z, when loading a game to bios of the dreamcast everything goes black only the sound of the background is heard, there appears the white screen of the SEGA with letters in blue with the introductions of the company, soon after the bios of the Dreamcast, and after that all the screens become black screen only with the background sound.

**Comment by flyinghead** [comment]
I can reproduce this. Only happens with GLES 2.0 apparently.

**Comment by spielvan** [comment]
I'm not sure if this is a good thing, but I'm not sure if it's a good thing to say. 2 GB + 16GB 4K x 2K H.265 Decoding WiFi HDMI Amlogic S812 Quad Core Bluetooth 4.0, Mali 450 GPU octa core 600mhz, Open GL 2.0, I tested several games and in your builds the result has improved greatly, especially with graphics faults that Many are migrating to open Gl 3.0, 3.1 ... but we can never forget that the vast majority have Open Gl 2.0 and hope that one day they will have a reicast running Most of the games perfectly, the Mortal Kombat gold is my game that more testo and this practically perfect, I noticed that in the build fea5f05, the fps of Cgs videos that before was in 22fps, went to 25 fps which improved a lot, in the buld master cps fps videos Mortal Kombat gold stands at 30 or 31 fps.

**Comment by spielvan** [comment]
Installed and working perfect, thank you very much, I will always be testing your new builds, because I really liked the way they are compiled, I will do a test with several games, to be able to point out the bugs in them, quam knows in a future we have one reicast running many dreamcast games and even exclusive games like soul calibur, virtua striker 2 and shemue.

**Comment by dmiller423** [comment]
Please close your issues if they are resolved.
