### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by madawayne** [reicast/reicast-emulator#1475]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- | 
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**
crash on start up when setting the right date and time, not reading game files properly-crazy taxi 2 cdi, resident evil 3 cdi, nor sky's of  Arcadia cdi

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
Checked the BIOS to make sure they were good, tried a hand full of game files Zip reboot recast.
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by madawayne** [comment]
Any suggestions

**Comment by Emulatorer** [comment]
watch my video how to properly setup for reicast dreamcast emulator
https://youtu.be/Cb3VQJuHiqA

**Comment by baka0815** [comment]
The problem could be with the CDI files, please use proper GDI (use TOSEC verification f.e.) or CHD ones.

**Comment by dmiller423** [comment]
Yes,  Please do not submit bug reports when you are using CDI files.
I am closing this for now,  if you have the same issue testing proper game image feel free to reopen and please submit the log as well.
