### ISSUE TITLE
Add Support for Redump.org Multibin/Cue Format

### ISSUE THREAD

**Issue by dizzzy77** [reicast/reicast-emulator#1482]
Redump.org preservation group uses a multi-bin/cue system for their dumps, using write offset correction for accuracy. Please add support.

Here's an example of the cue layout:

```
REM SINGLE-DENSITY AREA
FILE "18 Wheeler - American Pro Trucker (Europe) (En,Fr,De,Es) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "18 Wheeler - American Pro Trucker (Europe) (En,Fr,De,Es) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
REM HIGH-DENSITY AREA
FILE "18 Wheeler - American Pro Trucker (Europe) (En,Fr,De,Es) (Track 3).bin" BINARY
  TRACK 03 MODE1/2352
    INDEX 01 00:00:00
```

Here's a Magazine demo for testing: https://archive.org/download/OfficialSegaDreamcastMagazineVol.11February2001USA_201812

**Comment by dmiller423** [comment]
It's an open source project,  feel free to add the support and submit a pull request.
This is a feature request,  not an issue...   I will leave it open, but perhaps this is not really the place for it.

**Comment by MrPsyMan** [comment]
Looks like we want GDIv2...

**Comment by skmp** [comment]
This should now be in master.
