### ISSUE TITLE
New update problem. 

### ISSUE THREAD

**Issue by Coolboyslim** [reicast/reicast-emulator#1487]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Android 9. From Google store. New update all my roms now won't start just goes to Dreamcast dashboard. Love the work and just want to contribute. 

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [ ] Place an X in the box to confirm you have filled in this form

**Comment by baka0815** [comment]
Did you use the current stable version?
If yes, please try the current beta (you need to opt-in as a beta tester) or try a current build from https://builds.reicast.com/.

**Comment by Coolboyslim** [comment]
Sorry it is the latest beta I'm using. That was the update. Sinse that no roms load goes straight to dashboard. I'm using huawei mate p20 pro if that helps. Public version works perfect.

**Comment by Coolboyslim** [comment]
MODEL: LYA-L09
DEVICE: HWLYA
BOARD: LYA
New / No Label (28)

Native Interface Output

--------- beginning of system
--------- beginning of main
01-24 17:32:58.834 18572 18572 I reicast : Config dir is: /storage/emulated/0/rar/Dreamcast BIOS (1)/
01-24 17:32:58.834 18572 18572 I reicast : Data dir is:   /storage/emulated/0/rar/Dreamcast BIOS (1)/
01-24 17:32:58.935 18572 18572 D reicast : InputDevice ID: -1
01-24 17:32:58.935 18572 18572 D reicast : InputDevice Name: Virtual
01-24 17:32:58.935 18572 18572 D reicast : InputDevice Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
01-24 17:32:58.935 18572 18572 D reicast : InputDevice ID: 0
01-24 17:32:58.935 18572 18572 D reicast : InputDevice Name: fingerprint
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Descriptor: 94605cc6d11050165b0e47ce7d8b3046d370abd5
01-24 17:32:58.936 18572 18572 D reicast : InputDevice ID: 2
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Name: soundtrigger_input_dev
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Descriptor: 1cc715cbd334804aa45aa5df0419a5338477dc2b
01-24 17:32:58.936 18572 18572 D reicast : InputDevice ID: 3
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Name: minibugreport_key
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Descriptor: eb10f7ba25ce47c71082081ca1c09748fdc6fb11
01-24 17:32:58.936 18572 18572 D reicast : InputDevice ID: 4
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Name: hisi_on
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Descriptor: 0b8880f3bfb9b8911feb1902fa64f3914ea4e084
01-24 17:32:58.936 18572 18572 D reicast : InputDevice ID: 5
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Name: huawei,ts_kit
01-24 17:32:58.936 18572 18572 D reicast : InputDevice Descriptor: 44e714118b8ef2f71c12250d7321ced2278524d5
01-24 17:32:58.937 18572 18572 D reicast : InputDevice ID: 7
01-24 17:32:58.937 18572 18572 D reicast : InputDevice Name: hisi_gpio_key
01-24 17:32:58.937 18572 18572 D reicast : InputDevice Descriptor: 2ffdd6a1bf8a4cbe7b5de5f4d03609f3340c4c76
01-24 17:32:58.937 18572 18572 D reicast : InputDevice ID: 28
01-24 17:32:58.937 18572 18572 D reicast : InputDevice Name: Moga Pro HID
01-24 17:32:58.937 18572 18572 D reicast : InputDevice Descriptor: 6c53c2178517bde0c0ec2d0e8d79c90b3e7332f8
01-24 17:32:58.937 18572 18572 D reicast : InputDevice ID: 16777217
01-24 17:32:58.937 18572 18572 D reicast : InputDevice Name: hi3660_HI6403_CARD Headset Jack
01-24 17:32:58.937 18572 18572 D reicast : InputDevice Descriptor: 054029918748671911b5e0eca891db479570abdd
01-24 17:32:58.939 18572 18572 I reicast : Config dir is: /storage/emulated/0/rar/Dreamcast BIOS (1)/
01-24 17:32:58.939 18572 18572 I reicast : Data dir is:   /storage/emulated/0/rar/Dreamcast BIOS (1)/
01-24 17:32:58.940 18572 18572 I reicast : Game Disk URI: 'content://com.reicast.emulator.provider/external_root/rar/virtua_striker_2_v1.002_(m5) (1)/Virtua Striker 2 v1.002 (1999)(Sega)(NTSC)(US)(M5)[!].gdi'
01-24 17:32:58.940 18572 18572 I reicast : ARM VFP-Run Fast (NFP) enabled !
01-24 17:32:58.940 18572 18572 I reicast : Linux paging: 4096 00001000 00000FFF
01-24 17:32:58.940 18572 18572 I reicast : MAP 00800000 w/ 25165824
01-24 17:32:58.943 18572 18572 I reicast : MAP 20000000 w/ 25165824
01-24 17:32:58.944 18572 18572 I reicast : MAP 04000000 w/ 16777216
01-24 17:32:58.944 18572 18572 I reicast : MAP 06000000 w/ 16777216
01-24 17:32:58.944 18572 18572 I reicast : MAP 0C000000 w/ 0
01-24 17:32:58.944 18572 18572 I reicast : A8
01-24 17:32:58.944 18572 18572 I reicast : vmem reserve: base: 90CB0000, aram: b0cb0000, vram: 94CB0000, ram: 9CCB0000
01-24 17:32:58.944 18572 18572 I reicast : Resetting mem
01-24 17:32:58.962 18572 18572 I reicast : Mem alloc successful!
01-24 17:32:58.962 18572 18572 I reicast : Virtual cfg config:image=content://com.reicast.emulator.provider/external_root/rar/virtua_striker_2_v1.002_(m5) (1)/Virtua Striker 2 v1.002 (1999)(Sega)(NTSC)(US)(M5)[!].gdi
01-24 17:32:58.962 18572 18572 I reicast : 
01-24 17:32:58.964 18572 18572 I reicast : Malformed entry on config - ignoring @ 13(ta.HashCheckFile)
01-24 17:32:58.965 18572 18572 I reicast : Malformed entry on config - ignoring @ 14(ta.HashLogFile)
01-24 17:32:58.969 18572 18572 I reicast : Loaded /storage/emulated/0/rar/Dreamcast BIOS (1)/data/dc_boot.bin as bootrom
01-24 17:32:58.969 18572 18572 I reicast : 
01-24 17:32:58.970 18572 18572 I reicast : Loaded /storage/emulated/0/rar/Dreamcast BIOS (1)/data/dc_nvmem.bin as nvram
01-24 17:32:58.970 18572 18572 I reicast : 
01-24 17:32:58.971 18572 18572 I reicast : gdrom: Failed to open image "content://com.reicast.emulator.provider/external_root/rar/virtua_striker_2_v1.002_(m5) (1)/Virtua Striker 2 v1.002 (1999)(Sega)(NTSC)(US)(M5)[!].gdi"
01-24 17:32:58.972 18572 18572 I reicast : 
01-24 17:32:58.972 18572 18572 I reicast : 	 ARM7_TCB addr: 0xbf669000 | from: 0xbf6689c4 | addr here: 0xbf769fd4
01-24 17:32:58.975 18572 18572 I reicast : Using Recompiler
01-24 17:32:58.975 18572 18572 I reicast : Auto-selected audio backend "android" (Android Audio).
01-24 17:32:58.975 18572 18572 I reicast : Initializing audio backend "android" (Android Audio)...
01-24 17:32:58.975 18572 18572 I reicast : recSh4 Init
01-24 17:32:58.975 18572 18572 I reicast : @@	ngen_ResetBlocks()
01-24 17:32:58.975 18572 18572 I reicast : Freeing fpcb
01-24 17:32:58.975 18572 18572 I reicast : 
01-24 17:32:58.975 18572 18572 I reicast : 	 CodeCache addr: 0xbf7c3000 | from: 0xbf7c3000 | addr here: 0xbfdc3b9c
01-24 17:32:58.981 18572 18572 I reicast : readm helpers: up to BF7C3250
01-24 17:32:58.986 18572 18572 I reicast : Sh4 Reset
01-24 17:32:59.016 18572 18701 I reicast : cntx // fpcb offset: -34603008 // pc offset: -184 // pc A0000000
01-24 17:32:59.018 18572 18701 I reicast : Get MemPtr unsupported area : addr=0xA0000000
01-24 17:32:59.018 18572 18701 I reicast : Get MemPtr unsupported area : addr=0xA0000018
01-24 17:32:59.019 18572 18701 I reicast : Sh4: i-cache invalidation A0000016
01-24 17:32:59.019 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:32:59.019 18572 18701 I reicast : Freeing fpcb
01-24 17:32:59.019 18572 18701 I reicast : recSh4:Dynarec Cache clear at A0000016
01-24 17:32:59.021 18572 18701 I reicast : Get MemPtr unsupported area : addr=0x80000080
01-24 17:32:59.021 18572 18701 I reicast : Get MemPtr unsupported area : addr=0x800000A8
01-24 17:32:59.021 18572 18701 I reicast : Get MemPtr unsupported area : addr=0x800000BE
01-24 17:32:59.021 18572 18701 I reicast : Get MemPtr unsupported area : addr=0x800000C6
01-24 17:32:59.021 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:32:59.023 18572 18701 I reicast : Freeing fpcb
01-24 17:32:59.023 18572 18701 I reicast : recSh4:Dynarec Cache clear at 8C0000DE
01-24 17:32:59.048 18572 18700 I reicast : EGL config: 0xc569f580, 00000001, C4C47AE0 2861x1440
01-24 17:32:59.075 18572 18700 I reicast : OSD: 6
01-24 17:32:59.206 18572 18700 I reicast : EGL config: 0xc569f580, 00000001, C4C47AE0 3020x1440
01-24 17:32:59.207 18572 18700 I reicast : OSD: 12
01-24 17:32:59.368 18572 18701 I reicast : Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
01-24 17:32:59.369 18572 18701 I reicast : VREG = 03 ARMRST 00
01-24 17:32:59.370 18572 18701 I reicast : VREG = 03 ARMRST 01
01-24 17:32:59.648 18572 18701 I reicast : VREG = 03 ARMRST 00
01-24 17:32:59.768 18572 18701 I reicast : sh4io: Invalid read access @@ 00000030
01-24 17:32:59.769 18572 18701 I reicast : Sh4: i-cache invalidation 8C00DD78
01-24 17:32:59.769 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:32:59.769 18572 18701 I reicast : Freeing fpcb
01-24 17:32:59.769 18572 18701 I reicast : recSh4:Dynarec Cache clear at 8C00DD78
01-24 17:32:59.771 18572 18701 I reicast : bm_GetBlock(/�0���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
01-24 17:32:59.771 18572 18701 I reicast : Stale block ..
01-24 17:32:59.773 18572 18701 I reicast : bm_GetBlock(/�0���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
01-24 17:32:59.773 18572 18701 I reicast :  .. null RBI: 8C00DDA0 -- unlinked stale block
01-24 17:32:59.773 18572 18701 I reicast : DIV32S matched 1% @ 0x8C00CF78
01-24 17:32:59.773 18572 18701 I reicast : DIV32S matched 100% @ 0x8C00CF7E
01-24 17:32:59.773 18572 18701 I reicast : div32s 1/0/3
01-24 17:32:59.871 18572 18701 I reicast : Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
01-24 17:32:59.872 18572 18701 I reicast : Sh4: i-cache invalidation 8C09E6A6
01-24 17:32:59.872 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:32:59.872 18572 18701 I reicast : Freeing fpcb
01-24 17:32:59.872 18572 18701 I reicast : recSh4:Dynarec Cache clear at 8C09E6A6
01-24 17:32:59.872 18572 18701 I reicast : bm_GetBlock( �4q�
01-24 17:32:59.872 18572 18701 I reicast : P����0Q�!&H���������) failed ..
01-24 17:32:59.872 18572 18701 I reicast : Stale block ..
01-24 17:32:59.872 18572 18701 I reicast : bm_GetBlock( �4q�
01-24 17:32:59.872 18572 18701 I reicast : P����0Q�!&H���������) failed ..
01-24 17:32:59.872 18572 18701 I reicast :  .. null RBI: 8C09E6CE -- unlinked stale block
01-24 17:32:59.873 18572 18701 I reicast : Sh4: i-cache invalidation AC09D990
01-24 17:32:59.873 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:32:59.873 18572 18701 I reicast : Freeing fpcb
01-24 17:32:59.873 18572 18701 I reicast : recSh4:Dynarec Cache clear at AC09D990
01-24 17:32:59.874 18572 18701 I reicast : VREG = 03 ARMRST 00
01-24 17:33:00.009 18572 18701 I reicast : reicast git/n - 19.70 (0.00) - 50.77 - V: 25.39 (51.00, PAL480i50.00) R: 0.50+0.00 VTX: 0.00 , MIPS: 0.00
01-24 17:33:00.052 18572 18701 I reicast : new tactx
01-24 17:33:00.052 18572 18701 I reicast : new tactx
01-24 17:33:00.073 18572 18701 I reicast : DIV32S matched 1% @ 0x8C091086
01-24 17:33:00.074 18572 18701 I reicast : DIV32S matched 100% @ 0x8C09108C
01-24 17:33:00.074 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:00.091 18572 18701 I reicast : DIV32S matched 1% @ 0x8C0911E4
01-24 17:33:00.091 18572 18701 I reicast : DIV32S matched 100% @ 0x8C0911EC
01-24 17:33:00.091 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:00.091 18572 18701 I reicast : DIV32S matched 1% @ 0x8C09126E
01-24 17:33:00.091 18572 18701 I reicast : DIV32S matched 1% @ 0x8C091278
01-24 17:33:00.111 18572 18701 I reicast : VREG = 03 ARMRST 01
01-24 17:33:00.111 18572 18701 I reicast : VREG = 03 ARMRST 01
01-24 17:33:00.172 18572 18701 I reicast : VREG = 03 ARMRST 00
01-24 17:33:00.281 18572 18700 I reicast : EGL config: 0xc569f580, 00000001, C4C47AE0 3020x1440
01-24 17:33:00.282 18572 18700 I reicast : OSD: 21
01-24 17:33:00.419 18572 18701 I reicast : new tactx
01-24 17:33:02.009 18572 18701 I reicast : reicast git/n - 10.53 (0.00) - 94.98 - V: 47.49 (9.50, PAL480i50.00) R: 3.00+2.00 VTX: 0.00 , MIPS: 0.00
01-24 17:33:03.806 18572 18701 I reicast : Sh4: i-cache invalidation AC09EC6E
01-24 17:33:03.806 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:33:03.807 18572 18701 I reicast : Freeing fpcb
01-24 17:33:03.814 18572 18701 I reicast : recSh4:Dynarec Cache clear at AC09EC6E
01-24 17:33:03.823 18572 18701 I reicast : DIV32S matched 1% @ 0x8C00CF78
01-24 17:33:03.823 18572 18701 I reicast : DIV32S matched 100% @ 0x8C00CF7E
01-24 17:33:03.823 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:03.832 18572 18701 I reicast : DIV32S matched 1% @ 0x8C00D0D6
01-24 17:33:03.832 18572 18701 I reicast : DIV32S matched 100% @ 0x8C00D0DE
01-24 17:33:03.832 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:03.832 18572 18701 I reicast : DIV32S matched 1% @ 0x8C00D160
01-24 17:33:03.833 18572 18701 I reicast : DIV32S matched 1% @ 0x8C00D16A
01-24 17:33:03.836 18572 18701 I reicast : Sh4: i-cache invalidation 8C00DD78
01-24 17:33:03.836 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:33:03.836 18572 18701 I reicast : Freeing fpcb
01-24 17:33:03.836 18572 18701 I reicast : recSh4:Dynarec Cache clear at 8C00DD78
01-24 17:33:03.836 18572 18701 I reicast : bm_GetBlock(�����N�) failed ..
01-24 17:33:03.836 18572 18701 I reicast : Stale block ..
01-24 17:33:03.836 18572 18701 I reicast : bm_GetBlock(�����N�) failed ..
01-24 17:33:03.836 18572 18701 I reicast :  .. null RBI: 8C00DDA0 -- unlinked stale block
01-24 17:33:03.837 18572 18701 I reicast : DIV32S matched 1% @ 0x8C00CF78
01-24 17:33:03.837 18572 18701 I reicast : DIV32S matched 100% @ 0x8C00CF7E
01-24 17:33:03.837 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:03.892 18572 18701 I reicast : Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
01-24 17:33:03.892 18572 18701 I reicast : Sh4: i-cache invalidation 8C09E6A6
01-24 17:33:03.892 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:33:03.892 18572 18701 I reicast : Freeing fpcb
01-24 17:33:03.893 18572 18701 I reicast : recSh4:Dynarec Cache clear at 8C09E6A6
01-24 17:33:03.893 18572 18701 I reicast : bm_GetBlock(j
k
�8a���`��q�@�ᬰ�) failed ..
01-24 17:33:03.893 18572 18701 I reicast : Stale block ..
01-24 17:33:03.893 18572 18701 I reicast : bm_GetBlock(j
k
�8a���`��q�@�ᬰ�) failed ..
01-24 17:33:03.893 18572 18701 I reicast :  .. null RBI: 8C09E6CE -- unlinked stale block
01-24 17:33:03.894 18572 18701 I reicast : Sh4: i-cache invalidation AC09D990
01-24 17:33:03.894 18572 18701 I reicast : @@	ngen_ResetBlocks()
01-24 17:33:03.894 18572 18701 I reicast : Freeing fpcb
01-24 17:33:03.894 18572 18701 I reicast : recSh4:Dynarec Cache clear at AC09D990
01-24 17:33:03.935 18572 18701 I reicast : VREG = 03 ARMRST 00
01-24 17:33:04.012 18572 18701 I reicast : reicast git/n - 10.11 (0.00) - 98.86 - V: 49.43 (1.74, PAL480i50.00) R: 28.46+0.00 VTX: 0.00 , MIPS: 0.00
01-24 17:33:04.139 18572 18701 I reicast : DIV32S matched 1% @ 0x8C091086
01-24 17:33:04.139 18572 18701 I reicast : DIV32S matched 100% @ 0x8C09108C
01-24 17:33:04.139 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:04.163 18572 18701 I reicast : DIV32S matched 1% @ 0x8C0911E4
01-24 17:33:04.163 18572 18701 I reicast : DIV32S matched 100% @ 0x8C0911EC
01-24 17:33:04.163 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:04.163 18572 18701 I reicast : DIV32S matched 1% @ 0x8C09126E
01-24 17:33:04.163 18572 18701 I reicast : DIV32S matched 1% @ 0x8C091278
01-24 17:33:04.188 18572 18701 I reicast : VREG = 03 ARMRST 01
01-24 17:33:04.188 18572 18701 I reicast : VREG = 03 ARMRST 01
01-24 17:33:04.232 18572 18701 I reicast : VREG = 03 ARMRST 00
01-24 17:33:04.340 18572 18701 I reicast : DIV32S matched 1% @ 0x8C0294A6
01-24 17:33:04.340 18572 18701 I reicast : DIV32S matched 100% @ 0x8C0294AC
01-24 17:33:04.340 18572 18701 I reicast : div32s 1/0/3
01-24 17:33:06.028 18572 18701 I reicast : reicast git/n - 10.08 (0.00) - 99.22 - V: 49.61 (1.15, PAL480i50.00) R: 39.19+3.97 VTX: 0.00 , MIPS: 0.00
01-24 17:33:08.048 18572 18701 I reicast : reicast git/n - 10.00 (0.00) - 99.99 - V: 49.99 (1.00, PAL480i50.00) R: 48.01+1.98 VTX: 0.00 , MIPS: 0.00
01-24 17:33:10.069 18572 18701 I reicast : reicast git/n - 10.00 (0.00) - 99.97 - V: 49.98 (1.00, PAL480i50.00) R: 48.00+1.98 VTX: 0.00 , MIPS: 0.00
01-24 17:33:10.999 18572 18700 I reicast : EGL config: 0xc569f580, 00000001, C4C47AE0 2861x1440
01-24 17:33:10.999 18572 18700 I reicast : OSD: 42
01-24 17:33:12.080 18572 18701 I reicast : reicast git/n - 10.36 (0.00) - 96.50 - V: 48.25 (1.00, PAL480i50.00) R: 44.77+3.48 VTX: 0.00 , MIPS: 0.00
01-24 17:33:14.088 18572 18701 I reicast : reicast git/n - 10.04 (0.00) - 99.63 - V: 49.81 (1.00, PAL480i50.00) R: 49.32+0.50 VTX: 0.00 , MIPS: 0.00
01-24 17:33:16.088 18572 18701 I reicast : reicast git/n - 10.00 (0.00) - 100.00 - V: 50.00 (1.00, PAL480i50.00) R: 48.50+1.50 VTX: 0.00 , MIPS: 0.00
01-24 17:33:18.108 18572 18701 I reicast : reicast git/n - 10.00 (0.00) - 100.00 - V: 50.00 (1.00, PAL480i50.00) R: 49.01+0.99 VTX: 0.00 , MIPS: 0.00
01-24 17:33:18.359 18572 18700 I reicast : EGL config: 0xc569f580, 00000001, C4C47AE0 3020x1440
01-24 17:33:18.359 18572 18700 I reicast : OSD: 60
01-24 17:33:20.131 18572 18701 I reicast : reicast git/n - 10.43 (0.00) - 95.88 - V: 47.94 (1.00, PAL480i50.00) R: 44.48+3.46 VTX: 0.00 , MIPS: 0.00
01-24 17:33:21.878 18572 18700 I reicast : EGL config: 0xc569f580, 00000001, C4C47AE0 2861x1440
01-24 17:33:21.878 18572 18700 I reicast : OSD: 78
01-24 17:33:22.156 18572 18701 I reicast : reicast git/n - 10.33 (0.00) - 96.80 - V: 48.40 (1.00, PAL480i50.00) R: 46.42+1.98 VTX: 0.00 , MIPS: 0.00
01-24 17:33:23.040 18572 18572 I reicast : Saved /storage/emulated/0/rar/Dreamcast BIOS (1)/data/dc_nvmem.bin as nvmem
01-24 17:33:23.040 18572 18572 I reicast : 

Hope this is it

**Comment by Coolboyslim** [comment]
I'm sorry for hassle new too posting. It's odd cause public version is perfect and runs 100%. But as soon has beta is installed it won't run.. And thanks for the help it's appreciated.

**Comment by baka0815** [comment]
It looks like your GDI file can't be loaded:
``01-24 17:32:58.971 18572 18572 I reicast : gdrom: Failed to open image "content://com.reicast.emulator.provider/external_root/rar/virtua_striker_2_v1.002_(m5) (1)/Virtua Striker 2 v1.002 (1999)(Sega)(NTSC)(US)(M5)[!].gdi"``

I think that should be ``/storage/emulated/0/rar/virtua_striker_2_v1.002_(m5) (1)/Virtua Striker 2 v1.002 (1999)(Sega)(NTSC)(US)(M5)[!].gdi``? However I'm not very experienced with Android.

Could you try copying the file from the external source to your internal one and see if that works?

**Comment by Coolboyslim** [comment]
Sorry for late reply busy lol... But yea I've tried moving rom etc but no go. External is just what phone calls internal lol. Odd thing I've found is that I can't click on browse for setting rom directory it just auto finds all my games even after full uninstall. But hey the non beta works perfect.

**Comment by skmp** [comment]
@Coolboyslim we pushed a huge update yesterday. Can you update and test again?

**Comment by Coolboyslim** [comment]
Sure will do.. 
<-----Original Message----->

**Comment by Coolboyslim** [comment]
Works perfect now many thanks . 

<-----Original Message----->
