### ISSUE TITLE
Invisible Track in Sonic Adventure Clipping

### ISSUE THREAD

**Issue by Mikau28** [reicast/reicast-emulator#1489]
| Platform | Branch | Hash | CIDL |
| ---- | ---- | ---- | ---- |
| Windows 10 | RetroArch 1.7.6 Nightly/Reicast 0.1 | aefaf10 | ---- |

In the Sonic Adventure Games there is an issue when sonic enters an Loop or section that guides him on a track. The save state provided contains one instance in skydeck where sonic has to run through zig zag stairs, it appears sonic clips out of the top of the section.

I mentioned to @flyinghead that in SA2 the track in green forest also causes sonic to clip on the track from time to time. although, updating to the newest nightly and updating the core/info files lessens this quite a bit. pushing the stick after sonic enters the loop in SA2 will cause the track to stick in one place briefly.

**_Debugging Steps Tested_**

  Not much, simply pushing forward on my dualshock 4 should keep sonic running on his track until he completes the section. in SA1 save state he should ring around the section until he enters the top and clips off his track.

[Sonic Adventure SaveStates.zip](https://github.com/reicast/reicast-emulator/files/2826193/Sonic.Adventure.SaveStates.zip)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
As suspected this is due to a float precision problem in the 1/sqrt(x) op code of the x86_64 dynarec.

Note that when using the reicast libretro core, it is better to open an issue there: https://github.com/libretro/reicast-emulator/issues

**Comment by flyinghead** [comment]
No, that's fine. I will port the fix to the libretro core shortly.

**Comment by baka0815** [comment]
@flyinghead is a fix in the main reicast core necessary?

**Comment by flyinghead** [comment]
This fix doesn't apply to the master branch. However you should set `-fno-builtin-sqrtf` on all x86 and x64 platforms.
This avoids the use of RSQRTSS when `fast-math` is on (which it is)

**Comment by Mikau28** [comment]
Was that commit implemented into df4d2d9? i was able to make it to the top but he goes through the top wall. i can aim him when he comes down and hit the next section. unless i could do that before lol.

**Comment by flyinghead** [comment]
This hasn't been implemented on the libretro core yet: I just created the PR: https://github.com/libretro/reicast-emulator/pull/481
Expect it to be merged today

**Comment by Mikau28** [comment]
@flyinghead the issue has improved vastly. i think the small glitches of stopping in the middle of the track or the entire level of skydeck occurred on the original hardware as well. I've been testing the areas over and over and consider the issue closed as the game can now be completed.
