### ISSUE TITLE
Overclock option for Reicast

### ISSUE THREAD

**Issue by pepodmc** [reicast/reicast-emulator#1498]
Hello, can you add an option to overclock reicast?

Because some Dreamcast games have codes for 60 fps, like :

(Tony Hawk’s Pro Skater 2 T13006N V1.001) (This mod only works on this dump)

load up track5.bin in hexeditor and you go to offset 3979D388 you have to have 4C32 and you change that to 0900.

Even with the fullspeed option, the game has slowdowns in certain parts. I think that option only unlocks fps limiter in games, but it doesnt work as an overclock option.

Thanks

**Comment by Emulatorer** [comment]
Similar  #204? 🤔
