### ISSUE TITLE
MSAA antialiasing option for Reicast

### ISSUE THREAD

**Issue by pepodmc** [reicast/reicast-emulator#1499]
Hello, can you add an option to enable MSAA antialiasing for the emulator Reicast? 
because if (using HD texture support option) you insert textures with 1080p resolution or more, the new textures have a lot of aliasing. Original textures had lower resolution so it wasnt really noticeable; but, even if you play at 4k internal resolution, when you add new textures with a high resolution, they wil have aliasing.

Thanks for the emulator!

**Comment by Emulatorer** [comment]
Duplicate #1345? 🤔
