### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yesca4life1620** [reicast/reicast-emulator#1501]
Now I'm new at beta testing but I do understand beta is unstable. But how can a game boot up just fine & play for the most part with some minor glitches (game in question Skies of Arcadia) in r8.1. Now I just became a tester so I'm very new at this. I have the newest beta version from the play store & now the whole emulator crashes after the Dreamcast Logo loads the game in question.
It appears to be going backwards. Why is that?

**Comment by baka0815** [comment]
That may always be the case with beta versions. Some stuff changes which might unfortunately break some other stuff.
There are some differences between the beta and the latest stable and there might be one which causes this regression. Shouldn't happen but always might happen.

But this should be discussed in the forums not in this issue tracker, so I'm closing this.

**Comment by yesca4life1620** [comment]
Okay thanks...
Still getting used to the site...
You were rather helpful...
I eagerly await your next release weather beta or otherwise...
