### ISSUE TITLE
almost there

### ISSUE THREAD

**Issue by yesca4life1620** [reicast/reicast-emulator#1503]
Very close to being completely compatible with the Nintendo switch pro...
Still has a few bugs in syncing all of the buttons correctly...
Jfyi...

**Comment by baka0815** [comment]
Are you sure that you're at the right place?

**Comment by yesca4life1620** [comment]
Probably not...

**Comment by yesca4life1620** [comment]
Ballpark estimate about how often release a beta?

**Comment by yesca4life1620** [comment]
It refers to a Bluetooth controller

**Comment by baka0815** [comment]
I think I'll close this...
