### ISSUE TITLE
Can't find emu.cfg in Retroarch/Retropie (Linux) 

### ISSUE THREAD

**Issue by chairhome** [reicast/reicast-emulator#1510]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Ubuntu 18.04 LTS | ------ | ---- | yes|
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

I've installed the core through Retroarch on Retropie for Linux. I've looked around the various config folders and can't find an emu.cfg file. I've found an emulators.cfg file in the dreamcast folder of Retroarch config, but it doesn't seem to have the same type of info. Alternatively, is there a way to access the core menu while it's running? I am trying to see if my region is set incorrectly as all games (ntsc) are running at 50hz instead of 60hz. I'm going to try changing my bios also, but just wanted to know how to access emu.cfg. Thanks. 

**_Debugging Steps Tested_**

 Checked for config files and searched for emu.cfg. None found. 

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
Issues regarding the reicast libretro core should be open there: https://github.com/libretro/reicast-emulator/issues

That being said, the libretro core doesn't use an `emu.cfg` file. All core options are stored in `retroarch-core-options.cfg`

You can access the core options in retroarch Quick Menu > Options while the core is running. (Bind a key to open the retroarch menu)

**Comment by chairhome** [comment]
Sorry, I wasn't sure where to post, so thank you!

And thanks for the response, I'll definitely try these tonight.
