### ISSUE TITLE
Bug i hear dreamcast bios sound but only black on my screen

### ISSUE THREAD

**Issue by dhanial** [reicast/reicast-emulator#1512]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**
MODEL: Redmi Note 4
DEVICE: mido
BOARD: MSM8953
New / No Label (27)

Native Interface Output

--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-14 21:20:58.056 15574 15574 D reicast : Main folder: content://com.reicast.emulator.provider/external_files/720A-14F6/Emulator/Console/Dreamcast/Bios
03-14 21:20:58.061 15574 15574 I reicast : Config dir is: /storage/720A-14F6/Emulator/Console/Dreamcast/Bios/
03-14 21:20:58.061 15574 15574 I reicast : Data dir is:   /storage/720A-14F6/Emulator/Console/Dreamcast/Bios/
03-14 21:22:03.727 15574 15574 I reicast : Config dir is: /storage/720A-14F6/Emulator/Console/Dreamcast/Bios/
03-14 21:22:03.727 15574 15574 I reicast : Data dir is:   /storage/720A-14F6/Emulator/Console/Dreamcast/Bios/
03-14 21:22:03.829 15574 15574 D reicast : InputDevice ID: -1
03-14 21:22:03.829 15574 15574 D reicast : InputDevice Name: Virtual
03-14 21:22:03.829 15574 15574 D reicast : InputDevice Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
03-14 21:22:03.830 15574 15574 D reicast : InputDevice ID: 1
03-14 21:22:03.830 15574 15574 D reicast : InputDevice Name: uinput-fpc
03-14 21:22:03.830 15574 15574 D reicast : InputDevice Descriptor: 485d69228e24f5e46da1598745890b214130dbc4
03-14 21:22:03.830 15574 15574 D reicast : InputDevice ID: 2
03-14 21:22:03.830 15574 15574 D reicast : InputDevice Name: msm8953-snd-card-mtp Button Jack
03-14 21:22:03.830 15574 15574 D reicast : InputDevice Descriptor: 652d81422a52c35a5a6d7e3b5c5285d3affd5b11
03-14 21:22:03.831 15574 15574 D reicast : InputDevice ID: 3
03-14 21:22:03.831 15574 15574 D reicast : InputDevice Name: msm8953-snd-card-mtp Headset Jack
03-14 21:22:03.831 15574 15574 D reicast : InputDevice Descriptor: b6a4175a2792b5bb0355f949aea0d2724cfe89f9
03-14 21:22:03.831 15574 15574 D reicast : InputDevice ID: 4
03-14 21:22:03.831 15574 15574 D reicast : InputDevice Name: hbtp_vm
03-14 21:22:03.831 15574 15574 D reicast : InputDevice Descriptor: 793e303307c34fc398863d5f83ee4c6ea6a7c5c6
03-14 21:22:03.832 15574 15574 D reicast : InputDevice ID: 5
03-14 21:22:03.832 15574 15574 D reicast : InputDevice Name: qpnp_pon
03-14 21:22:03.832 15574 15574 D reicast : InputDevice Descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab
03-14 21:22:03.832 15574 15574 D reicast : InputDevice ID: 6
03-14 21:22:03.833 15574 15574 D reicast : InputDevice Name: gf3208
03-14 21:22:03.833 15574 15574 D reicast : InputDevice Descriptor: a5333c230f77a4debd508eb3bb4c6b3132bd3884
03-14 21:22:03.833 15574 15574 D reicast : InputDevice ID: 7
03-14 21:22:03.833 15574 15574 D reicast : InputDevice Name: ft5435_ts
03-14 21:22:03.833 15574 15574 D reicast : InputDevice Descriptor: 15880e1d16076ae7ad91867998d0c9382fd2f455
03-14 21:22:03.834 15574 15574 D reicast : InputDevice ID: 9
03-14 21:22:03.834 15574 15574 D reicast : InputDevice Name: gpio-keys
03-14 21:22:03.834 15574 15574 D reicast : InputDevice Descriptor: d2c52ff0f656fac4cd7b7a118d575e0109a9fe1c
03-14 21:22:03.839 15574 15574 I reicast : Config dir is: /storage/720A-14F6/Emulator/Console/Dreamcast/Bios/
03-14 21:22:03.839 15574 15574 I reicast : Data dir is:   /storage/720A-14F6/Emulator/Console/Dreamcast/Bios/
03-14 21:22:03.841 15574 15574 I reicast : Game Disk URI: ''
03-14 21:22:03.841 15574 15574 I reicast : ARM VFP-Run Fast (NFP) enabled !
03-14 21:22:03.841 15574 15574 I reicast : Linux paging: 4096 00001000 00000FFF
03-14 21:22:03.841 15574 15574 I reicast : MAP 00800000 w/ 25165824
03-14 21:22:03.843 15574 15574 I reicast : MAP 20000000 w/ 25165824
03-14 21:22:03.843 15574 15574 I reicast : MAP 04000000 w/ 16777216
03-14 21:22:03.843 15574 15574 I reicast : MAP 06000000 w/ 16777216
03-14 21:22:03.843 15574 15574 I reicast : MAP 0C000000 w/ 0
03-14 21:22:03.843 15574 15574 I reicast : A8
03-14 21:22:03.843 15574 15574 I reicast : vmem reserve: base: 91860000, aram: b1860000, vram: 95860000, ram: 9D860000
03-14 21:22:03.843 15574 15574 I reicast : Resetting mem
03-14 21:22:03.887 15574 15574
| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [ ] Place an X in the box to confirm you have filled in this form

**Comment by skmp** [comment]
should be fixed in 20.02b
