### ISSUE TITLE
Microphone toggle inactive, shield tv

### ISSUE THREAD

**Issue by dazzyp83** [reicast/reicast-emulator#1515]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**
not able to toggle mic in input settings

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [ X] Place an X in the box to confirm you have filled in this form

**Comment by skmp** [comment]
Is this fixed in latest master?

**Comment by dazzyp83** [comment]
Yes it it - thanks
