### ISSUE TITLE
Reicast forum index site from google play store doesn't work anymore

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1520]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

### Screenshots
![Screenshot_2019-03-24-09-03-34](https://user-images.githubusercontent.com/37603562/54873598-319a0280-4e14-11e9-926c-859de64c0471.png)
![Screenshot_2019-03-24-09-04-30](https://user-images.githubusercontent.com/37603562/54873599-3959a700-4e14-11e9-8d1b-9f9d10f451ca.png)

**Comment by skmp** [comment]
Thanks. Added a note in #1522 to update it to chat.reicast.com
