### ISSUE TITLE
Reicast latest beta can't open in my android phone :(

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1546]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
|---|---|---|---|
| Android | Google PlayStore | Beta | ---- |

**_Description of the Issue_**
After installing latest beta I can't open it anymore last beta work in my phone is
https://github.com/reicast/reicast-emulator/commit/09d9f73
Issue started in https://github.com/reicast/reicast-emulator/commit/7e11e7a

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Phone Specs_**
Android 5.1 Lollipop
Mali-450 MP4 GPU
Octacore CPU @1.4GHz
```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Videos_**
This video will tell the issue
[ScreenRecord_Video_1554773053550.mp4.zip](https://github.com/reicast/reicast-emulator/files/3056819/ScreenRecord_Video_1554773053550.mp4.zip)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
I tested builds https://github.com/reicast/reicast-emulator/commit/7e11e7a and the latest beta (https://github.com/reicast/reicast-emulator/commit/5637437) on an Android 4.4.4 device with a Mali-400 MP without issue.

I'm surprised that the build you mention is the one where the problem started. The previous one (https://github.com/reicast/reicast-emulator/commit/09d9f73) is more likely to cause issues, especially on GLES 2 devices.

Would you mind double-checking? Can you delete/hide all reicast files and start with a clean config?
Also, can you gather system logs (logcat) from the device right after the crash?

**Comment by Emulatorer** [comment]
I tried what you said but issue still happen as you watch the video :(

I can't get also logcat from the reicast as the emulator stopped before opening :/

**Comment by Emulatorer** [comment]
@flyinghead The cause of this issue is after I change my phone dpi 😅

My Screen resolution is 1280x720 (320dpi)
I change it to 240dpi and then reicast didn't work anymore this could be possible fixed 🤔

**Comment by Emulatorer** [comment]
Sorry didn't intentionally to close 😅

**Comment by skmp** [comment]
is this a dpi scaling issue?

**Comment by flyinghead** [comment]
I use the screen dpi returned by android to scale the UI. But I don't see how any value, including 0, could cause a crash.

**Comment by Emulatorer** [comment]
But r8.1 playstore version didn't crash

**Comment by dmiller423** [comment]
There have been several reports of snapdragon based devices esp. crashing in recent betas at startup.

**Comment by Emulatorer** [comment]
I still can't use the latest beta so I tried to captured the log using catlog app need root access maybe this could help somehow
@flyinghead 
[reicast_crash_log.txt](https://github.com/reicast/reicast-emulator/files/3161585/reicast_crash_log.txt)

**Comment by flyinghead** [comment]
It does help a lot, yes.

Can you confirm that changing the DPI on your device to 320 makes reicast crash, and setting it to 240 fixes it?

**Comment by flyinghead** [comment]
The error is a memory allocation error: reicast cannot allocate memory for the sh4 context and cannot continue.
I don't see how it could be related to DPI scaling, or to the first commit (https://github.com/reicast/reicast-emulator/commit/7e11e7a) where this problem started.

Have you tried stopping all other apps before starting reicast?

Does a reboot of the device help?

**Comment by Emulatorer** [comment]
@flyinghead restoring my default dpi to 320 fixes the issue though but changing it to 240dpi crashes the emulator

I tried to force stopped the other app(s) and open reicast still crash rebooting my phone doesn't help the issue

**Comment by Emulatorer** [comment]
Restoring my dpi to default (320) still crashing 😭

I think I need to reflash my stock rom os
so Im gonna close this now

**Comment by Emulatorer** [comment]
@flyinghead I find out that causes the crashing is this in my buildprop dalvik.vm.heapsize=512m but changing it to dalvik.vm.heapsize=256m fixed the issue

**Comment by flyinghead** [comment]
By increasing the heap size, you reduced the amount on non-heap memory available, which causes the memory allocation failure at startup.
