### ISSUE TITLE
Android Reicast intents stopped working

### ISSUE THREAD

**Issue by flamming-python** [reicast/reicast-emulator#1547]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Android 9 | Google Play (Beta) | ---- | No |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

One of the latest releases of Reicast to the Google Play store broke intents. It's no longer possible for anyone to launch games with shortcuts or via a front-end such as Hyperspin, for anyone who has updated to the latest version
I checked and indeed the only intent Reicast now has is NativeGLActivity, something like that. If it's possible to use it with parameters giving the location of a ROM then I don't know how. But even if it is, this is a pretty big regression and ideally the previous intent should be reinstated (MainActivity)

**_Debugging Steps Tested_**

  * Attempt to run existing shortcuts to ROMs from Android launcher (result - "App not installed" message)
  * Attempt to create new shortcuts with xShortcut app using MainActivity intent and URI to ROM file (result - "Component Unavailable (INVALID!)" message)
  * Attempt to create new shortcuts with xShortcut app using NativeGLActivity intent and URI to ROM file (result - Reicast boots to Dreamcast BIOS but not to game)

**_Logs Gathered_**

```

```

**_Screenshots_**

- [ X] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
MainActivity is no more. But NativeGLActivity supports intents.

I was able to create a shortcut to a game using xShortcut with these settings:
Target: `Activity`
Component package: `com.reicast.emulator`
Component class: `com.reicast.emulator.NativeGLActivity`
Action: `android.intent.action.VIEW`
Data (URI): `/storage/emulated/0/Download/Sturmwind.cdi`

Note that the "official" URI format is: `content://com.reicast.emulator.Emulator.provider/external_files/emulated/0/Download/Sturmwind.cdi` (which also works)
Normally, replacing `com.reicasdt.emulator.MainActivity` by `com.reicast.emulator.NativeGLActivity` in existing shortcuts should work

**Comment by flamming-python** [comment]
Tested it out myself and can confirm this works fine!
Thanks!

**Comment by skmp** [comment]
@flyinghead can we add a shim MainActivity for backwards compat?

**Comment by flyinghead** [comment]
Done https://github.com/reicast/reicast-emulator/commit/251b4d381d8da7a57b559f4b198ef4a653715974

**Comment by skmp** [comment]
<3
