### ISSUE TITLE
Disc swap

### ISSUE THREAD

**Issue by ppsspp213** [reicast/reicast-emulator#155]
Allow disc swapping as another option on the back menu icons to mount another image to switch discs, useful for cheat engines like
Codebreaker, Action Replay, GameShark etc all of which have been cracked for dongless cheat list saving.

**Comment by AbandonedCart** [comment]
https://github.com/reicast/reicast-emulator/pull/1348

**Comment by MrPsyMan** [comment]
The actual function for this is already there. Only thing missing is the UI on android supporting it.

We want the UI supporting this as soon as we split into lib/frontend.

**Comment by baka0815** [comment]
It's also only available on Android at the moment, but we don't have other GUIs atm...

**Comment by MrPsyMan** [comment]
Works on pc build (assuming building it works). I remember putting it on one of the f keys.

**Comment by AbandonedCart** [comment]
@MrPsyMan "We want the UI supporting this as soon as we split into lib/frontend."

What UI are you referring to?

**Comment by MrPsyMan** [comment]
All UIs visible while running a game. On all supported platforms.

**Comment by AbandonedCart** [comment]
Alright. "Only thing missing is the UI on android supporting it" implied that it was just Android missing the UI and the post directly before it **was** the UI, so I was making sure they were separate statements.

**Comment by skmp** [comment]
Solved after some #1765
