### ISSUE TITLE
Reicast duplicate icon on android

### ISSUE THREAD

**Issue by spielvan** [reicast/reicast-emulator#1580]
Hello, my dear, from the last builds, when they are installed, there are two iic icons of reicast on android, is this normal?

**Comment by Emulatorer** [comment]
I can confirm this issue
![Screenshot_2019-05-03-22-50-05](https://user-images.githubusercontent.com/37603562/57145478-df2a0980-6df5-11e9-9689-359447d9f39f.png)

**Comment by flyinghead** [comment]
@skmp 

https://github.com/reicast/reicast-emulator/pull/1554

Press Merge if that's not too much effort

**Comment by dmiller423** [comment]
Merged,  skmp is going to be out for a few days.

**Comment by dmiller423** [comment]
Please close this once confirmed beta build fixed.

**Comment by spielvan** [comment]
It was perfect now.
