### ISSUE TITLE
Mr Driller - Screen cut in half, PAL @ 60Hz

### ISSUE THREAD

**Issue by hiddenasbestos** [reicast/reicast-emulator#1582]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Windows 10 x64 | latest as of May 4th | c631534ee1444becced4ee1fc5a67a5bbf345370  | Downloaded from build site? yes |

**_Description of the Issue_**

Running Mr Driller PAL version in TV (either RGB or Composite) mode, game works as normal but after selecting the 60Hz option subsequent display is limited to only the top-half of the application window.

**_Debugging Steps Tested_**

Running reicast-win_x64-fast-c631534ee1444becced4ee1fc5a67a5bbf345370.exe on Windows 10 x64

Tried VGA mode and this doesn't exhibit the same problem.
Choosing 50Hz also doesn't cause this issue.

Issue also occurs on libretro core.

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

https://imgur.com/aYxoYOY

- [x] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
PR #1583 should fix this issue

**Comment by hiddenasbestos** [comment]
I compiled my own build and it's working great, thanks! (Glad it fixed so many other games, I never knew!)
