### ISSUE TITLE
Build closing reicast in Load state

### ISSUE THREAD

**Issue by spielvan** [reicast/reicast-emulator#1591]
Build afcd7a0 is closing the reicast, when I click load state, I tested with Mortal Kombat Gold, in the previous worked perfectly, other functions of the popup menu: Resume, Restart, Exit work perfectly.

**Comment by flyinghead** [comment]
@davidgfnet The modem PR broke the save states: it makes savestates incompatible if saved with modem enabled and loaded with modem disabled (or vice versa)

More importantly: modem is now disabled by default on Android and OSX at least.

**Comment by davidgfnet** [comment]
This should now be fixed, sorry for the breakage!

**Comment by spielvan** [comment]
> This should now be fixed, sorry for the breakage!

I use it on android, how can I provide this latest build 3e57c80 for android?

**Comment by davidgfnet** [comment]
It will show up in here: http://builds.reicast.com/
Once it is ready, seems only Winx64 is ready yet. It takes probably an hour or more for it to build.

**Comment by spielvan** [comment]
> It will show up in here: http://builds.reicast.com/
> Once it is ready, seems only Winx64 is ready yet. It takes probably an hour or more for it to build.

Thank you very much
