### ISSUE TITLE
Reicast beta  regression on arm32 android since flyinghead branch merge to master

### ISSUE THREAD

**Issue by Emulatorer** [reicast/reicast-emulator#1592]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Android | Playstore | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**
All my reicast game are running slow since https://github.com/reicast/reicast-emulator/pull/1523 but running smooth using r8.1-playstore

**_Log Gathered_**
Maybe this log could help
[reicast_beta_log_.txt](https://github.com/reicast/reicast-emulator/files/3165211/reicast_beta_log_.txt)
[reicast_r8.1_log.txt](https://github.com/reicast/reicast-emulator/files/3165216/reicast_r8.1_log.txt)

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip
```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [X ] Place an X in the box to confirm you have filled in this form

**Comment by Emulatorer** [comment]
@flyinghead you have a phone with arm32 like Mali-400 GPU right? It is running slow in your phone using latest beta build?

**Comment by flyinghead** [comment]
I do. I have a device with an arm32 with Mali-400 GPU running Android 4.4.4.
I also test with a Raspberry Pi.

I don't see a significant slowdown between now and before the merge.

**Comment by Emulatorer** [comment]
@flyinghead Well it's running slow on my device with Mali-450 MP GPU arm32 :(
Here's the video sample
https://drive.google.com/file/d/1A-p0o-YVhsgin9xm-dbA6YXf1xChtQkh/view?usp=drivesdk
The first video Im using is beta from playstore and the second video is the r8.1 from playstore.

You can see the difference of the speed and fps of the game I tested it in MVC2 but other my games in reicast are performing poor using latest beta started from your branch the previous beta are fine :/

**Comment by kage2051** [comment]
You could try using a lower value for scaling, a value of 100 for it means native resolution of your device. For example, on my SD625 (ARM64) tablet with 1080p screen, a scale of 70% means the games will run at ~800p on that device. This also improves speed in most devices with older or low-end processors.

**Comment by Emulatorer** [comment]
@kage2051 I will try and see if it's improve my game experience using latest beta

**Comment by Emulatorer** [comment]
@kage2051 still lag Reicast r8.1 still perform better compare to beta build started in @flyinghead branch merged to master :/

**Comment by flyinghead** [comment]
I tested MvsC2 on my device and the one parameter that fixes the stuttering audio is to disable Safe Mode.
I would also set SMC Checks to Fast although I didn't notice any change in performance with this parameter.

I still get some audio stuttering in-game but it's even worse with the play store version. I think it's due to the way haptic feedback was implemented.

**Comment by Emulatorer** [comment]
@flyinghead did you watch the video?
You notice the performance was better in r8.1 compare to latest beta build also the speed and sound is better to r8.1 :/

**Comment by kage2051** [comment]
I also get similar issues on my SD625/Adreno 506 tablet:
* Jet Grind Radio: it hangs for a second and then speeds up briefly.
* MvC2 is also a bit laggy, similar to JGR.
* High stuttering during in-game cutscenes in AITD (on another device with SD636 this doesn't happen like that).

Plus that on SD801/Adreno 330 it refuses to run any game, because of the grey screen issue.

**Comment by flyinghead** [comment]
@Emulatorer yes, I did watch the video. Yes, it's obvious the result is much better with the play store version in this case.

I spent some time testing this game on my device and looked for settings that could have an influence on performance and audio stuttering. I gave you the results of my findings.

Yet you didn't even answer to my comment. You keep repeating, over and over, that it's slower than before.

I'm sorry for you but this won't help me find a solution to the problem.

**Comment by Emulatorer** [comment]
@flyinghead can you give me the apk of reicast beta before your branch before merge to masters?

**Comment by flyinghead** [comment]
Here we go
[reicast-android-debug-69ab16a.zip](https://github.com/reicast/reicast-emulator/files/3170247/reicast-android-debug-69ab16a.zip)

**Comment by Emulatorer** [comment]
@flyinghead thanks

**Comment by Emulatorer** [comment]
Finally found a good settings but the audio still not optimized though :)
https://youtu.be/7xhwShdyfjw

(Sorry for my english)

**Comment by skmp** [comment]
@Emulatorer is this no longer an issue?
