### ISSUE TITLE
Compilation Issue on Ubuntu Budgie x64

### ISSUE THREAD

**Issue by mforan26** [reicast/reicast-emulator#1599]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Ubuntu Budgie x64 |Master| ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**
**Cloned the latest source but compilation fails with the following:**
`/home/michael/Emulators/reicast-emulator/core/rend/gl4/gldraw.cpp:421:2: error: ‘glTextureView’ was not declared in this scope
  glTextureView(depthTexId, GL_TEXTURE_2D, stencilTexId, GL_DEPTH32F_STENCIL8, 0, 1, 0, 1);
  ^~~~~~~~~~~~~
/home/michael/Emulators/reicast-emulator/core/rend/gl4/gldraw.cpp:421:2: note: suggested alternative: ‘fbTextureId’
  glTextureView(depthTexId, GL_TEXTURE_2D, stencilTexId, GL_DEPTH32F_STENCIL8, 0, 1, 0, 1);
  ^~~~~~~~~~~~~
  fbTextureId
/home/michael/Emulators/reicast-emulator/core/rend/gl4/gldraw.cpp: In function ‘void gl4DrawStrips(GLuint)’:
/home/michael/Emulators/reicast-emulator/core/rend/gl4/gldraw.cpp:465:2: error: ‘glProvokingVertex’ was not declared in this scope
  glProvokingVertex(GL_LAST_VERTEX_CONVENTION);
  ^~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/reicast.dir/build.make:1015: CMakeFiles/reicast.dir/core/rend/gl4/gldraw.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
`
Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [x] Place an X in the box to confirm you have filled in this form

**Comment by flyinghead** [comment]
Can you try to compile using the Makefile in `shell/linux`?

cmake support isn't finalized yet.

**Comment by mforan26** [comment]
Thanks for the suggestion that worked!

**Comment by baka0815** [comment]
This is also a duplicate of #1574
