### ISSUE TITLE
Cannot find bios files nightly windows 10

### ISSUE THREAD

**Issue by blubaustin** [reicast/reicast-emulator#1602]
[**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Windows 10 64bit | Nightly | ee9646ab433779464b1d85ccc1d28982150e9ef0 |

**_Description of the Issue_**

Bios files not found. Have tried playing files in the same directory, in a dc folder and in a: Bios\dc folder in the same directory to no avail

**_Logs Gathered_**
Unable to gather logs since googling around for turning on logs for windows came up with nothing.

**_Screenshots_**

``

- [ x] Place an X in the box to confirm you have filled in this form
](url
![image](https://user-images.githubusercontent.com/31782440/57587261-49f2d900-74b7-11e9-8433-e57c8182567b.png)
)

**Comment by flyinghead** [comment]
Put the BIOS file in a folder named `data`. Set reicast home directory to the parent of this folder.

**Comment by blubaustin** [comment]
That worked. Maybe could be added to the documentation since there seems to be conflicting documentation online.
