### ISSUE TITLE
Loading Riru breaks the emulator

### ISSUE THREAD

**Issue by leopard20** [reicast/reicast-emulator#1628]
Ok. I know that incompatibility with other apps and modules should be taken up with the problematic app's author, but I wasn't sure whether it's Reicast or Riru that causes this.

In case you don't know, Riru (https://github.com/RikkaApps/Riru) is a Magisk module required for those who want to install Xposed on their customized Android ROMs (in my case, Xiaomi's MIUI).

As for the problem, I don't know why when I load Riru, Reicast cannot write to the storage anymore, and thus freezes when I want to, say, change the settings or even select the reicast working directory.
I'm having this problem with Reicast alone and all my other apps work fine. So perhaps you use some deprecated storage access APIs or other stuff that cause this.

BTW, I've created an issue in Riru's repository as well. Maybe you could work it out together: https://github.com/RikkaApps/Riru/issues/42

**Comment by skmp** [comment]
Can you join our chat in http://chat.reicast.com? We're dealing with some #emudrama atm, however I'll have time to look further over the weekend during #1565

**Comment by leopard20** [comment]
> Can you join our chat in http://chat.reicast.com? We're dealing with some #emudrama atm, however I'll have time to look further over the weekend during #1565

Yeah sure. But just one more thing to mention:
According to Riru's author (https://github.com/RikkaApps/Riru/issues/42) the problem can be avoided by enabling Magisk Hide for Reicast. This probably means that you attempt to access the storage from an unauthorized location and that would require root access which you don't ask for.
