### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by TheFunSteveProYT** [reicast/reicast-emulator#1643]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 6.0 | Google Play | Hashtag (skip if unknown) | Downloaded from Google Play Store |

**_Description of the Issue_**

I have missing buttons.

**_Debugging Steps Tested_**

  * Tried to dump the bios files again, no change.

**_Logs Gathered_**

```

N/A

```

**_Screenshots_**

![Missing buttons](https://user-images.githubusercontent.com/39857279/59599657-8cdc4800-9118-11e9-836a-48f35bedc5df.png)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by Emulatorer** [comment]
Duplicate #1638
