### ISSUE TITLE
Last build (0cdd7d8) is closing reicast

### ISSUE THREAD

**Issue by spielvan** [reicast/reicast-emulator#1651]
@skmp Last build (0cdd7d8) is closing reicast, until build (d2b4511) is working normally.

**Comment by skmp** [comment]
thx, will look into it asap

**Comment by Emulatorer** [comment]
I can play now for a while just delete the config file inside DC folder but I still encounter crash by changing the video graphics textures scaling here's the log
[Reicast_crash_log.txt](https://github.com/reicast/reicast-emulator/files/3343959/Reicast_crash_log.txt)

**Comment by ghost** [comment]
This issue can be closed now see JIT: Fix & enable FBCD it for real #1684

**Comment by skmp** [comment]
@Emulatorer that is a different issue with the GL initialization logic.

**Comment by ghost** [comment]
@skmp we have same android specs and issue so I thought this can be closed 😅

**Comment by skmp** [comment]
Adding it to my to do list #1664
