### ISSUE TITLE
X11 with mesa 19 on RPI3 failure on compilation

### ISSUE THREAD

**Issue by Askmewho** [reicast/reicast-emulator#1653]
Hi I am trying to compile reicast for RPI3 but using raspbian with mesa 19. Ive set these parameters: 

  
    MFLAGS +=   -mtune=cortex-a53 -mfpu=neon-vfpv4 -mfloat-abi=hard 
    ASFLAGS +=  -mtune=cortex-a53 -mfpu=neon-vfpv4  -mfloat-abi=hard
    CFLAGS +=  -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant
    USE_GLES := 0
    USE_X11:= 1
    USE_OMX := 0
    USE_SDL := 1
    USE_ALSA= 1
    FOR_LINUX := 1

dont know where are the conditionals to "TARGET_LINUX_ARMELv7" target to read them

but if fails on : 

```
/home/pi/Desktop/reicast-emulator/shell/linux/../../core/linux-dist/x11.cpp: En la función ‘void x11_gl_context_destroy()’:
/home/pi/Desktop/reicast-emulator/shell/linux/../../core/linux-dist/x11.cpp:575:2: error: ‘glXMakeCurrent’ no se declaró en este ámbito
  glXMakeCurrent((Display*)x11_disp, None, NULL);
  ^~~~~~~~~~~~~~
mv -f .dep-obj-dreamcast-armv7h/deps/zlib/infback.Td .dep-obj-dreamcast-armv7h/deps/zlib/infback.d
/home/pi/Desktop/reicast-emulator/shell/linux/../../core/linux-dist/x11.cpp:576:41: error: ‘GLXContext’ no se declaró en este ámbito
  glXDestroyContext((Display*)x11_disp, (GLXContext)x11_glc);
                                         ^~~~~~~~~~
mkdir -p obj-dreamcast-armv7h/deps/zlib/
/home/pi/Desktop/reicast-emulator/shell/linux/../../core/linux-dist/x11.cpp:576:41: nota: suggested alternative: ‘XContext’
  glXDestroyContext((Display*)x11_disp, (GLXContext)x11_glc);
                                         ^~~~~~~~~~
                                         XContext
/home/pi/Desktop/reicast-emulator/shell/linux/../../core/linux-dist/x11.cpp:576:2: error: ‘glXDestroyContext’ no se declaró en este ámbito
  glXDestroyContext((Display*)x11_disp, (GLXContext)x11_glc);
  ^~~~~~~~~~~~~~~~~
mkdir -p .dep-obj-dreamcast-armv7h/deps/zlib/
/home/pi/Desktop/reicast-emulator/shell/linux/../../core/linux-dist/x11.cpp:576:2: nota: suggested alternative: ‘XDeleteContext’
  glXDestroyContext((Display*)x11_disp, (GLXContext)x11_glc);
  ^~~~~~~~~~~~~~~~~
  XDeleteContext
```

**Comment by Askmewho** [comment]
Ive just deleted that function and it finish and it execute ... for sure it will fault on any emulation intention.
but the main thing.. Why it use gles when i set USE_GLES := 0 , it should do GL and not GL ES. its because of "TARGET_LINUX_ARMELv7" 7??

**Comment by Askmewho** [comment]
Well, deleting the function didnt do nothing, it works... and fast, even on GLES. 
so, I found one problem: alsa its not working properly... a bit choppy and it doesnt limit the fps correctly (some times goes much higher than 100%). I will compile it with sdl, hope it works, but I need to know how to disable the GLES flag.. so far I could find it. TARGET_LINUX_ARMELv7 doesnt do nothing related to GLES.

**Comment by Askmewho** [comment]
So, right now I am attempting to use Cmake. Dont knwo why its failing on joystick, no matter if I disable it or not. This is one of the error lines

```
/home/pi/Desktop/reicast-emulator/core/linux-dist/joystick.cpp:9:61: error: ‘DC_BTN_Y’ no se declaró en este ámbito
  const u32 joystick_map_btn_usb[JOYSTICK_MAP_SIZE]      = { DC_BTN_Y, DC_BTN_B, DC_BTN_A, DC_BTN_X, 0, 0, 0, 0, 0, DC_BTN_START };
                                                             ^~~~~~~~
```

**Comment by Askmewho** [comment]
I am trying to use cmake but I am facing this issue and I dont know how to resolve it. https://github.com/reicast/reicast-emulator/issues/1322

**Comment by Askmewho** [comment]
as far has I could, these build (master) its crashing on almost any game. these two errors are very common.
```
@@	ngen_ResetBlocks()
recSh4:Dynarec Cache clear at AC00FFFE
MEM remap 0 : 0x5800 to 0xC12D800
Verify Failed  : !(state.cpu.is_delayslot && OpDesc[op]->SetPC())
 in dec_DecodeBlock -> /home/pi/Desktop/reicast-emulator/shell/linux/../../core/hw/sh4/dyna/decoder.cpp : 1073 

`trap' para punto de parada/seguimiento
```
```
Verify Failed  : ctx == NULL || rqueue == ctx
 in FinishRender -> /home/pi/Desktop/reicast-emulator/shell/linux/../../core/hw/pvr/ta_ctx.cpp : 201 

`trap' para punto de parada/seguimiento
```

**Comment by skmp** [comment]
Latest master should work with `make platform=rpi3`

**Comment by ghost** [comment]
yeah, its solved now!
