### ISSUE TITLE
cant build the last release source on armhf linux

### ISSUE THREAD

**Issue by Askmewho** [reicast/reicast-emulator#1655]
after several problem with the majority of the games crashing on armhf with my master build, ive tried the last release and it keeps defining android (it ask android.h from types.h) even when I didnt target android at any time (grome the makefile of shell/linux/

**Comment by Askmewho** [comment]
I need to undefine GLES but more important undefine _ANDROID... and I cant or the makefile it useless for doing that.. thanks for your hard work

**Comment by skmp** [comment]
I don't think armhf is supported atm. For which board is this?

**Comment by Askmewho** [comment]
What?? This emulator its on retropie from about 3 years. This is an rpi, full opengl 2.1 profile. So far the only game than runs its crazy taxy.

**Comment by skmp** [comment]
Can you try latest master? #1662 should have fixed this

**Comment by skmp** [comment]
This looks resolved, `make platform=rpi3` works
