### ISSUE TITLE
Emulator issues

### ISSUE THREAD

**Issue by TheFunSteveProYT** [reicast/reicast-emulator#1656]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 6.0 | Google Play | Hashtag (skip if unknown) | Downloaded from Google Play |

**_Description of the Issue_**

Whenever I try to open a game or bios, the emulator crashes.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

N/A

```

**_Screenshots_**

![Screenshot_20190624-171442](https://user-images.githubusercontent.com/39857279/60018073-bca0c800-96a3-11e9-8a2b-d22a8c406d08.png)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by TheFunSteveProYT** [comment]
Anything that can cause this issue?

**Comment by Emulatorer** [comment]
Duplicate #1651?
