### ISSUE TITLE
DLC Capability?

### ISSUE THREAD

**Issue by SeyelentSnipe** [reicast/reicast-emulator#1657]
To add DLC to your game on a Dreamcast, you would have to download the DLC (using the Dreamcast's built in modem) and download it onto the VMU. Depending on the game, the DLC would be usable after it was installed on the VMU. 

Could this be done on Reicast?

Below is a website giving access to DLC content. A bit busy this week, but can test if it works through a drag and drop within the VMU folder on the Galaxy Tab S4.

https://www.dreamcastlive.net/dlc

**Comment by flyinghead** [comment]
Yes, it should work. Connect to http://dc.dreamcastlive.net/dlc.html from an in-game web browser

**Comment by skmp** [comment]
@SeyelentSnipe please re-open if it does not work :)
