### ISSUE TITLE
Sonic Adventure is crashing

### ISSUE THREAD

**Issue by Vimu0** [reicast/reicast-emulator#1667]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Installed OS and version (ie. Android 8.0) | Branch (or Google Play) | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_*
MODEL: Moto G (4)
DEVICE: athene_t
BOARD: msm8952
Nougat (24)

Native Interface Output

--------- beginning of system
--------- beginning of main
07-09 18:50:25.812 27996 27996 I reicast : Config dir is: /storage/emulated/0/Download/dc_bios/
07-09 18:50:25.812 27996 27996 I reicast : Data dir is:   /storage/emulated/0/Download/dc_bios/
07-09 18:50:25.839 27996 27996 W reicast : Moto G (4) touchpad ignored
--------- beginning of crash
07-09 18:50:38.038 30513 30513 I reicast : Config dir is: /storage/emulated/0/Download/dc_bios/
07-09 18:50:38.038 30513 30513 I reicast : Data dir is:   /storage/emulated/0/Download/dc_bios/
07-09 18:50:38.138 30513 30513 W reicast : Moto G (4) touchpad ignored

**Comment by skmp** [comment]
I'm gonna close this in favor of #1700. @Sonic32XOri can you try the instructions in that ticket and try the latest beta?
