### ISSUE TITLE
Crash on Spawn: In the demon's hand

### ISSUE THREAD

**Issue by Estebanzore** [reicast/reicast-emulator#1668]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Xiaomi Mi A1 (Global ver) with Android One Ver 9| Google Play ver | Hashtag (skip if unknown) | Downloaded from build site? |

**_Description of the Issue_**

When you choose certain character, you get, at level 10 boss Vacillator, two different maps. In the ice one, there is no problem and I can finish the level and all the playthrough.

However, when getting the second map (some sort of caverns) the game crash showing that message in the screenshot

Any help for that specific trouble?

**_Debugging Steps Tested_**

  * I already tried with multiple .ISO and .CDI of the game. Every single one get the same error
  * Also I've messed around with the config and none of that helped

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(
![Screenshot_20190709-180305](https://user-images.githubusercontent.com/52754385/60990321-c5350780-a30d-11e9-9e4f-3a4612c19d8b.png)
)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by skmp** [comment]
@kostantinho can you verify this?

**Comment by kohi8** [comment]
I've tried to re-create the error dozen of times and my fight with Vacillator proceeded on the ice without finding any problem. I haven't yet encountered this cavern map.

My game is in .gdi form. 

PS. I wanted to comment when I had some evidence but seventeen days have passed with nothing.

**Comment by ghost** [comment]
I've gotten a similar bug before on a few games from using r8.1 a couple months ago. They look like this. 
![beta tester picture](https://user-images.githubusercontent.com/50502050/62109839-fac07700-b261-11e9-82ff-8e68ae7bc309.png)
![beta tester picture 2](https://user-images.githubusercontent.com/50502050/62109845-feec9480-b261-11e9-93a8-19df482c09be.png)

**Comment by kohi8** [comment]
Hmm doesn't look the same. 

When I tried Quake didn't boot. 

Can't remember the game from the second picture but I think adjusting the settings or clearing the Cache might help(?)

**Comment by ghost** [comment]
Okay thank you as always

**Comment by skmp** [comment]
Closing this as likely non-issue. Stability should have improved.
