### ISSUE TITLE
Switch to default branch "develop"

### ISSUE THREAD

**Issue by hissingshark** [reicast/reicast-emulator#1669]
Hi,

Just wanted to check if the switch to "develop" as the default branch was intended?
Automated building e.g. RetroPie expects to find the `Makefile` in `shell/Linux` in the root of the repo and in this branch `shell` has been renamed to `reicast`.

Wanted to be sure before committing changes build-side.

**Comment by skmp** [comment]
"master" points to "beta" quality, "develop" points to "alpha" quality. Develop is going under a refactor atm, so expect build breaks as things move around.

Do you really need to follow the alpha channel? We'll keep updating master once things pass QA, and then will do release on stable w/ tags.

FYI: Branch names will likely change a bit more. Will do an announcement before breaking master.

**Comment by skmp** [comment]
@hissingshark alpha/beta/stable structure is now ready. You should stay on `master` til the next release when things stabilize, imo, to avoid build breaks

**Comment by hissingshark** [comment]
Thanks for the swift clarification.
I'll specifically pull from `master` now rather than assuming it's the default.  Beta sounds more appropriate!

Many Thanks,

**Comment by skmp** [comment]
I pushed `beta` with master's tip, and will be updating that one from now on. Master will also stick around for backwards compat and maybe some fixes.

**Comment by skmp** [comment]
Feel free to join http://chat.reicast.com if you want more realtime updates

**Comment by hissingshark** [comment]
Sorry, `beta`!
And yes I will do, many thanks for that.
