### ISSUE TITLE
reicast r19.07 crashing out when selecting game after changing SMC Check from Full - Faster

### ISSUE THREAD

**Issue by ghost** [reicast/reicast-emulator#1676]
- [X] Place an X in the box to confirm you have filled in this form

**Comment by ghost** [comment]
### Screenshots
![Screenshot_2019-07-14-13-22-28](https://user-images.githubusercontent.com/37603562/61179699-e9108a00-a63a-11e9-9275-dcad395b092e.png)
![Screenshot_2019-07-14-13-22-47](https://user-images.githubusercontent.com/37603562/61179702-f3328880-a63a-11e9-8178-1387b4eb1796.png)
### Crashlog
[reicast_r19.7_crash_log.txt](https://github.com/reicast/reicast-emulator/files/3389497/reicast_r19.7_crash_log.txt)

Tested MVC2 and KOF Evolution
Working fine in Sky of Arcadia 🤔

**Comment by skmp** [comment]
`Faster` is expected to be more unstable. `Full` is the recommended option.

**Comment by ghost** [comment]
@SKMP But this make my game a little bit faster last working build is
d2b4511 issue has started in 0cdd7d8?

**Comment by ghost** [comment]
@flyinghead any help from you ?
Your the one who added that option so I think you can help this problem ^^

**Comment by skmp** [comment]
@Emulatorer should be fixed now, in `r19.07.03-2`

**Comment by ghost** [comment]
@skmp tnx I will test it later ^_^

**Comment by ghost** [comment]
@skmp confirmed this issue is final fixed via JIT: Fix & enable FBCD it for real #1684
