### ISSUE TITLE
Run Win_x64 beta ver error

### ISSUE THREAD

**Issue by nom32** [reicast/reicast-emulator#1685]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Win10 - 1903 x64 | Win_x64 beta (29f95ee) | Hashtag (skip if unknown) | Downloaded from builds.reicast.com |

**_Description of the Issue_**

When I run reicast-win_x64-fast-29f95ee.exe, it nothing happen. I can't run it, but 201bf15-2019-07-05 run ok.

Can help for that trouble?

**Comment by mohsinous** [comment]
same problem here, after 201bf15 build, windows build is broken. it did not even run

**Comment by skmp** [comment]
This should be fixed now
