### ISSUE TITLE
Cannot compile latest alpha on raspberry pi4

### ISSUE THREAD

**Issue by ITotalJustice** [reicast/reicast-emulator#1687]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| PI4 | Alpha |
| Raspbian (32) |

Can no longer compile since the changes made in #1683 Specifically in the function "void re_raise_fault". I don't know assembly but i imagine that its an error with it being 32 os maybe?

I removed the entire function and where its called as well which enabled me to compile, reicast boots fine, but the bios / games will not load as the reicast will just freeze. Switching to interp allowed me to boot into the bios logo, but not any further. Previous commits still allow for reicast to compile and boot games.

Below i posted the output of the terminal when compiled successfully when using dynamic rec. 

```
ARM7_TCB addr: 0x46000 | from: 0x45b4c | addr here: 0x22fc8
Game ID is [MK-51035]
recSh4 Init
@@	ngen_ResetBlocks()
Initializing the ARM32 dynarec
readm helpers: up to 00262250
@@	ngen_ResetBlocks()
Using Recompiler
Sh4 Reset
Auto-selected audio backend "alsa" (Advanced Linux Sound Architecture).
Initializing audio backend "alsa" (Advanced Linux Sound Architecture)...
ALSA: trying to determine audio device
ALSA: Successfully initialized "default"
ALSA: period size set to 1024
ALSA: buffer size set to 5120
Using Recompiler
cntx // fpcb offset: -68157440 // pc offset: -184 // pc A0000000
```
- [X] Place an X in the box to confirm you have filled in this form

**Comment by skmp** [comment]
#1706 fixes this. Thanks for reporting :)

**Comment by skmp** [comment]
Doing major refactoring so non-core platforms (android, windows, linux x86, linux 64) might break again. please open a ticket if this happens again, or poke me on discord
