### ISSUE TITLE
Gameplay lag and sound distortion while  playing Phantasy Star Online.

### ISSUE THREAD

**Issue by shinshura17** [reicast/reicast-emulator#1689]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| Android 7.0 |Google Play  | ---- | Downloaded from Google Play  |

**_Description of the Issue_**
Major speed reduction and sound distortion while playing Phantasy Star Online.

Add a short, concise description of the issue here

I recently updated to the latest version of the reicast on my Samsung Galaxy amp Prime 2. While playing Phantasy Star Online, there's major play lag as well as sound distortion. Do you have any suggestions on how I can improve the speed and sound so that I can have smoother gameplay?

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

(Replace this line with any issue screenshots)

- [ X ] Place an X in the box to confirm you have filled in this form

**Comment by ghost** [comment]
Advance Settings > SMS Checks > Faster
Video Settings > Scaling > 60

**Comment by ghost** [comment]
@shinshura17 no feedback/outdated?

**Comment by shinshura17** [comment]
My apologies to you for the late reply. Thanks, it really helped out. I do have another question though. I recently downloaded some pso dlc and I'm trying to upload it to my vms, but I  don't know how. Any ideas or suggestions on this matter?

**Comment by ghost** [comment]
Maybe @flyinghead or @skmp know about that 😅

**Comment by skmp** [comment]
I have never used the DLC myself, so no idea.

**Comment by skmp** [comment]
This discussion is probably best for discord, closing the ticket as the original issue was resolved
