### ISSUE TITLE
Reicast r19.07.3 does not work on my android box MX3-G

### ISSUE THREAD

**Issue by spielvan** [reicast/reicast-emulator#1700]
System Used:

MXIII-G CPU: Amlogic S812 Quad Core up to 2.0GHz (Cortex-A9)
GPU: Octa core ARM Mali-450 GPU up to 600MHz Open GL2.0, DDR3 2GB RAM

---------------------------------------------------------------------------------------------

Even the version described below worked perfectly

Version: r8.1-652-gd2d45116
Git Hash: d2b45116
Build Data: 2009-06-18 23:03:24 UTC
Target: Dreamcast

open reicast and load an example game: Mortal Kombat Gold, if in Dynarec he simply closes the reicast and goes back to the android desktop, in interpreter he loads the bios of the game and part of the opening and closes the reicast, and when this happens if I try to open reicast straight again it is on a black screen, I need to clear the background reicast in order to open it again.

If I try to open the dreamcast by reicast bios, when the bios menu will load the icons become transparent and close reicast.

**Comment by skmp** [comment]
Closing this in favor of #1709 (same issue). Are you running android 5.x?
