### ISSUE TITLE
Reicast r19.07.3-3-g29f95ee2 crash.

### ISSUE THREAD

**Issue by DitzRoom** [reicast/reicast-emulator#1701]
hi.. on Reicast r19.07.3-3-g29f95ee2, Grandia 2 game crashed after i touch start button on game menu. if change dynarec to interpreted in system app. the game can run, but very slow.

then i change to older reicast version r8.1. the game can run very smoothly.

my device : Nvidia Shield Tablet K1 (Andoid N).

**Comment by skmp** [comment]
This might be fixed by #1710, which will be included in the next beta.

**Comment by skmp** [comment]
Beta `r19.07.3-52-gfe2ba8cc` should be out within 1h, please test and report back

**Comment by skmp** [comment]
Closing this in favor of #1709. @DitzRoom do you have Android 5.x?
