### ISSUE TITLE
Reicast crashes and freeze on Android 5.0 

### ISSUE THREAD

**Issue by manoplasito** [reicast/reicast-emulator#1718]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
|Android 5.0, galaxy note 3 | Google Play Beta | Hashtag (skip if unknown) | 6a462750 |

**_Description of the Issue_**

Reicast freeze when I go to the Controls and advanced tabs on settings

Reicast crash when bios is in 0/dc/data folder. If I change to 0/dc1/data works

Reicast shows Dreamcast logo when load bios, then crash.

Never works for me screenScaling

**_Debugging Steps Tested_**
I try to edit emu.cfg to change dynarec to interpreter and still crash after Dreamcast logo.

Older version can show game when edit emu.cfg line rend.MaxFilteredTextureSize=1, rend.RenderToTextureUpscale=1. This dont work on recent builds.

**_Logs Gathered_**
I don't know how to see logs on Android
```



```

**_Screenshots_**

- [ X] Place an X in the box to confirm you have filled in this form

**Comment by ghost** [comment]
Crashing Issue is already tracking down in #1709

**Comment by skmp** [comment]
@manoplasito try r20.02b, crashes should be fixed
