### ISSUE TITLE
Reicast R19 Dynarec crash on Debian Buster Arm

### ISSUE THREAD

**Issue by OOKAMIFR** [reicast/reicast-emulator#1738]
Hello.

Hope my first issue will be complete :)

I am using Debian Buster 10 for Raspberry Pi 4 and compiled the last release from wget github command 

Issue is simply emulator can't run with Dynarec

Also made the following test : 
 - replaced biosfiles 
 - testing with same games in CDI format

Tested with Interpreter and no crash occured (but obviusly slow)

Version compiled is r19.07.4-28-g9aa83040

 - Platform 
CPU ARM
OS Linux (I use Debian Buster 10)

 - Open GL
Renderer V3D 4.2
VendorOpenGL ES 3.0 Mesa19.1.0-Devel 

I can also provide logs if someone can tell me how to have it

Thanks :)

**Comment by ITotalJustice** [comment]
Seems to be the same issue that I was having. #1727

**Comment by OOKAMIFR** [comment]
I want to compile R8.1 in order to test if linux compiler or emu is faulty but before I have to uninstall R19
Someone know how ?
Thanks for help 😊

**Comment by OOKAMIFR** [comment]
Ok
Compiled new one and now I can play games (with weird effects)
Same game in GDI make emu crash
GDI driver Maybe buggy

**Comment by OOKAMIFR** [comment]
Testing games in CDI format with Dynarec working now
Same games in GDI working only with Interpreter  (crash emu with Dynarec)
Hope this can help to solve issue

**Comment by skmp** [comment]
Closing this in favor of #1727
