### ISSUE TITLE
Super Runabout SF Edition Crashing on boot screen (WinCE)

### ISSUE THREAD

**Issue by hamzajeljeli95** [reicast/reicast-emulator#1739]
Hello There, **Reicast r19.07.4** is crashing in the WinCE screen while loading **Super Runabout - SF Edition** in both **PAL** and **NTSC** versions of the game.

Here is the log : 

--------------------------------------------------
Info: nvmem is enabled, with addr space of size 512MB

Info: p_sh4rcb: 00000164046C0000 virt_ram_base: 000001640C7C0000

RendIF: renderer: gl41
Per-pixel sorting enabled
OpenGL version: 4.3.0 - Build 20.19.15.5063
Screen DPI is 96, size 1366 x 715. Scaling by 1.00
Loaded C:\Users\Hamza\Desktop\Reicast/data/dc_bios.bin as bootrom

Loaded C:\Users\Hamza\Desktop\Reicast/data/dc_nvmem.bin as nvram

chd: chd_open failed for file D:\Games\DC Roms/Runabout SF New/Super Runabout v1.002 (2000)(Virgin)(PAL)[!].gdi: 5

GDI : 23 tracks
file[1] "track01.bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
file[2] "track02.raw": FAD:450, CTRL:0, SSIZE:2352, OFFSET:0
file[3] "track03.bin": FAD:45000, CTRL:4, SSIZE:2352, OFFSET:0
file[4] "track04.raw": FAD:132693, CTRL:0, SSIZE:2352, OFFSET:0
file[5] "track05.raw": FAD:151359, CTRL:0, SSIZE:2352, OFFSET:0
file[6] "track06.raw": FAD:174682, CTRL:0, SSIZE:2352, OFFSET:0
file[7] "track07.raw": FAD:204893, CTRL:0, SSIZE:2352, OFFSET:0
file[8] "track08.raw": FAD:217921, CTRL:0, SSIZE:2352, OFFSET:0
file[9] "track09.raw": FAD:236671, CTRL:0, SSIZE:2352, OFFSET:0
file[10] "track10.raw": FAD:263222, CTRL:0, SSIZE:2352, OFFSET:0
file[11] "track11.raw": FAD:284200, CTRL:0, SSIZE:2352, OFFSET:0
file[12] "track12.raw": FAD:306320, CTRL:0, SSIZE:2352, OFFSET:0
file[13] "track13.raw": FAD:338650, CTRL:0, SSIZE:2352, OFFSET:0
file[14] "track14.raw": FAD:360678, CTRL:0, SSIZE:2352, OFFSET:0
file[15] "track15.raw": FAD:362106, CTRL:0, SSIZE:2352, OFFSET:0
file[16] "track16.raw": FAD:363082, CTRL:0, SSIZE:2352, OFFSET:0
file[17] "track17.raw": FAD:363758, CTRL:0, SSIZE:2352, OFFSET:0
file[18] "track18.raw": FAD:364921, CTRL:0, SSIZE:2352, OFFSET:0
file[19] "track19.raw": FAD:365829, CTRL:0, SSIZE:2352, OFFSET:0
file[20] "track20.raw": FAD:366580, CTRL:0, SSIZE:2352, OFFSET:0
file[21] "track21.raw": FAD:372303, CTRL:0, SSIZE:2352, OFFSET:0
file[22] "track22.raw": FAD:377778, CTRL:0, SSIZE:2352, OFFSET:0
file[23] "track23.bin": FAD:379729, CTRL:4, SSIZE:2352, OFFSET:0
gdrom: Opened image "D:\Games\DC Roms/Runabout SF New/Super Runabout v1.002 (2000)(Virgin)(PAL)[!].gdi"
Game ID is [T7014D  50]
Enabling Extra depth scaling for Windows CE games
recSh4 Init
Found code area at 00007FF7D7800000, not too far away from 00007FF7D88A5240
Using Recompiler
Sh4 Reset
Auto-selected audio backend "directsound" (Microsoft DirectSound).
Initializing audio backend "directsound" (Microsoft DirectSound)...
Using Recompiler
cntx // fpcb offset: -135266304 // pc offset: -184 // pc A0000000
recSh4:Dynarec Cache clear at 8C0000DE
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
VREG = 03 ARMRST 00
VREG = 03 ARMRST 01
VREG = 03 ARMRST 00
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
VREG = 03 ARMRST 00
VREG = 03 ARMRST 01
VREG = 03 ARMRST 01
VREG = 03 ARMRST 00
HASH: 8C09ED16 reloc >:1:05:BD3BE51F:1E886EE6:6BDB3F70:7FB25EA3:DE0083A8
HASH: 8C0BA526 reloc >:1:04:CB0C9B99:5082FB07:50A46C46:4035B1F1:6A9F47DC
HASH: 8C0BA506 reloc >:1:04:26AEABE5:E9D01A08:C25DD887:EEAFF173:CE2BBA10
HASH: 8C0BA50E reloc >:1:0A:5785DC3D:68688650:C5E1AFB3:7F686AE5:89538042
recSh4:Dynarec Cache clear at AC0082FE
VREG = 03 ARMRST 00
MEM remap 0 : 0x5800 to 0xC149800
Error in C:\projects\reicast-emulator\libswirl\hw\holly\sb_mem.cpp:WriteBios:124: Write to [Boot ROM] is not possible, addr=c,data=636c,size=2
Verify Failed  : !(state.cpu.is_delayslot && OpDesc[op]->SetPC())
 in dec_DecodeBlock -> C:\projects\reicast-emulator\libswirl\hw\sh4\dyna\decoder.cpp : 1073 

--------------------------------------------------
And thank you reicast Dev. Team, you are doing a great job for bringing back our childhood games alive again !

**Comment by skmp** [comment]
WinCE games are not supported (see #53). You might want to try flycast (it has an experimental wince branch) or Demul.

**Comment by hamzajeljeli95** [comment]
Actually i tried them both, **FlyCast** also hangs at the WinCE Logo but Demul works with few Graphical and sound glitches.

Btw, i compared some of the Reicast SH4 source code and the FlyCast SH4 source code .. they seemed to be almost identical ..

**Comment by flyinghead** [comment]
There was a flycast issue on windows affecting WinCE games. This has been fixed.

The wince branch is no longer used though, use the master branch instead.

**Comment by skmp** [comment]
I'm gonna close this as we track the underlying issue in #53. @hamzajeljeli95 flycast is a fork of reicast with various improvements, so of course the code is similar.
