### ISSUE TITLE
Your hyperlink is dead

### ISSUE THREAD

**Issue by jzombie999** [reicast/reicast-emulator#1744]
https://github.com/reicast/reicast-emulator/releases/download/r8.1/Reicast-r8.1.apk

That hyperlink is dead.

I tried to download apk from assets (apk). It keeps saying like this 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
        <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>15270164/3fb4dc80-b695-11e8-9398-016a7af31f17</Key><RequestId>5979FD60E93157CB</RequestId><HostId>hdZl4Dk9ZzIeD3yeUD6lAdm2ShAYc+20j69QntgpWYiaarIhS3wB53+Ibbb61MFL1oug4hMm6hQ=</HostId></Error>

**Comment by skmp** [comment]
@jzombie999 i reuploaded the apks. Github somehow lost them o.O
