### ISSUE TITLE
Compile for RPi4 with 64bit failed with VFP instructions

### ISSUE THREAD

**Issue by FuyuriSeiichi** [reicast/reicast-emulator#1748]
Hi, Chankast dev,

Thank you first for the great emulator!

When I try to compile it on a raspberry pi 4 with aarch64 GCC 9.2, I made the following changes to reicast/linux/configure-platform.make :
...
# Raspberry Pi 4
...
-  ARM32_REC := 1
+ ARM64_REC := 1

And I start compile it with #make platform=rpi4, 
it fails at VFP related instruction set like these:

```
g++   -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps -MT obj-dreamcast-rpi4/hw/sh4/sh4_sched.build_obj -MD -MP -MF .dep-obj-dreamcast-rpi4/hw/sh4/sh4_sched.Td -g -O3 -D RELEASE -c -D USES_HOMEDIR -fopenmp  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant -D SUPPORT_EGL -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/rend/gles -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/vixl -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/khronos -DENABLE_MODEM -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/picotcp/include -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/picotcp/modules -DCHD5_FLAC -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/flac/src/libFLAC/include/ -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/flac/include -DPACKAGE_VERSION=\"1.3.2\" -DFLAC__HAS_OGG=0 -DFLAC__NO_DLL -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -D_7ZIP_ST -DCHD5_LZMA `pkg-config --cflags x11` -D SUPPORT_X11 -fomit-frame-pointer  -march=armv8-a+crc -mtune=cortex-a72  -fno-rtti -fpermissive -fno-operator-names -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14  -D SUPPORT_EGL -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/rend/gles -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/vixl -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/khronos -DENABLE_MODEM -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/picotcp/include -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/picotcp/modules -DCHD5_FLAC -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/flac/src/libFLAC/include/ -I/home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/deps/flac/include -DPACKAGE_VERSION=\"1.3.2\" -DFLAC__HAS_OGG=0 -DFLAC__NO_DLL -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -D_7ZIP_ST -DCHD5_LZMA `pkg-config --cflags x11` -D SUPPORT_X11 `pkg-config --cflags alsa` -D USE_ALSA -D USE_OSS -D USE_EVDEV -D USE_UDEV -D SCRIPTING /home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/hw/sh4/sh4_sched.cpp -o obj-dreamcast-rpi4/hw/sh4/sh4_sched.build_obj
/tmp/ccUAsVNi.s: Assembler messages:
/tmp/ccUAsVNi.s:573: Error: unknown mnemonic `fmrx' -- `fmrx x0,fpscr'
/tmp/ccUAsVNi.s:576: Error: unknown mnemonic `fmxr' -- `fmxr fpscr,x0'
/tmp/ccUAsVNi.s:932: Error: unknown mnemonic `fmrx' -- `fmrx x0,fpscr'
/tmp/ccUAsVNi.s:935: Error: unknown mnemonic `fmxr' -- `fmxr fpscr,x0'
```

Do you have any suggestions?
Thank you.

**Comment by FuyuriSeiji** [comment]
I can certainly compile it with CFLAGS="... -DARM_SOFTFP", but it certainly wouldn't be a ideal solution.
I'm all ears for any suggestions.
Thank you

**Comment by ITotalJustice** [comment]
It’s because the way the configure is set up, if it detects it’s a pi4, it compiles as 32 bits armv7. Hence why you have the asm error you’re seeing.

You can (I think) change [this](https://github.com/reicast/reicast-emulator/blob/d350e68e859eba7fbc546fef1331f2825517a062/reicast/linux/configure-platform.make#L87) to ARM64_REC := 1.

Also change [target Linux ](https://github.com/reicast/reicast-emulator/blob/d350e68e859eba7fbc546fef1331f2825517a062/reicast/linux/configure-platform.make#L91) to armv8.

Also you can just run make to compile, the detect platform checks the for the cpu used. Also if what I suggested fixes your problem, I could add another check (after detecting the cpu) for if it’s 32 / 64 bit, then set the flag to something like pi4v8

Edit: I really should read issues properly before replying haha, it looks like you’ve already tried my first suggestion. You can always try the second still, failing that, try and compile as a generic armv8 device.

**Comment by FuyuriSeiichi** [comment]
Hi, ITotalJustice, 

Thank you for your reply.

Here is what I actually change to make it compiled.
` # Raspberry Pi 4
 else ifneq (,$(findstring rpi4,$(platform)))
     PLATFORM_LINUX := 1
-    ARM32_REC := 1
+#    ARM32_REC := 1
+    ARM64_REC := 1
     USE_X11 := 1
     SUPPORT_EGL := 1
 
-    CFLAGS +=  -D TARGET_LINUX_ARMELv7 -DARM_HARDFP -fsingle-precision-constant
-
+    CFLAGS += -D TARGET_LINUX_ARMv8 -march=armv8-a+crc -mtune=cortex-a72 -O2 -pipe
`

After it's compiled, I was greeted by the message on execution:

`GLX: Open GL 4.3 not supported
Fatal error : GLX: Open GL 3.0 not supported

 in glx_Init -> /home/sbbg/Shared/reicast-emulator/reicast/linux/../../libswirl/utils/glinit/glx/glx.cpp : 116 

Trace/breakpoint trap`

well, I guess that's another story then.
