### ISSUE TITLE
Reicast r20.02 still crashing on android 6.0 using dynarec

### ISSUE THREAD

**Issue by ghost** [reicast/reicast-emulator#1779]
Reicast r20.02 crashlog
[reicast-crashlog.txt](https://github.com/reicast/reicast-emulator/files/4142381/reicast-crashlog.txt)
### Screenshots
![Screenshot_20200201-170552](https://user-images.githubusercontent.com/37603562/73590043-b9629a00-4518-11ea-8d03-346edbe4bd0c.png)
![Screenshot_20200201-172842](https://user-images.githubusercontent.com/37603562/73590048-c1bad500-4518-11ea-9c53-1df0e156d771.png)

**Comment by skmp** [comment]
This is an emulation error - can you try a CHD or GDI?

**Comment by skmp** [comment]
Was the same game image working before?

**Comment by ghost** [comment]
@skmp Yes MVC2 cdi image work flawlessly in reicast r19

**Comment by TundraMeadow** [comment]
Same here... it has not been working since the last update.
![Screenshot_20200202-000452](https://user-images.githubusercontent.com/57765528/73601868-e1b5bd00-4547-11ea-98f9-38877cb8b35e.png)
![Screenshot_20200202-000535](https://user-images.githubusercontent.com/57765528/73601870-e9756180-4547-11ea-8709-e7c9d66758c1.png)

**Comment by ghost** [comment]
Another log from reicast data
[log.txt](https://github.com/reicast/reicast-emulator/files/4143486/log.txt)

**Comment by skmp** [comment]
@TundraMeadow your issue is related to #1781, I moved your post there. Can you post the exact phone model there? thanks

**Comment by ghost** [comment]
I tried the apk hotfix from here https://github.com/reicast/reicast-emulator/issues/1781#issue-558676235
but reicast still crashing :(

here's the log 
[reicast-crashlog.txt](https://github.com/reicast/reicast-emulator/files/4144302/reicast-crashlog.txt)

**Comment by ghost** [comment]
Hang and freeze in reicast boot using r20.02b
![Screenshot_20200203-103131](https://user-images.githubusercontent.com/37603562/73647015-9e795c80-46b5-11ea-9d95-3505928e355e.png)
crashlog 
[reicast-log-2020-02-03-10-33-31.txt](https://github.com/reicast/reicast-emulator/files/4147440/reicast-log-2020-02-03-10-33-31.txt)

**Comment by ghost** [comment]
Reverting this commit 4189cd4 maybe can fixed this issue?

**Comment by skmp** [comment]
@Emulatorer what game is that? also, what hardware?

Can you please join discord at http://chat.reicast.com ?

We can probably this faster with chat instead of github :)

**Comment by ghost** [comment]
@skmp can you give me the apk of reicast
before 4189cd4? I will test it and see if it's work.

I will try to join on discord later :)

**Comment by ghost** [comment]
Crashing still happen in the lastest beta
