### ISSUE TITLE
Adreno 3xx drivers crash

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1781]
The gpu driver in these devices is buggy, and gets triggered by our usage of VAOs. Might be related to #1780.

Error sequence:
---
Driver prints
`ioctl fd 30 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur`
or similar.

Then the driver returns false in eglSwapBuffers indicating it has failed. We try to teardown the context and re-create it, but the driver doesn't like us calling eglMakeCurrent(... NONE), and then android won't let us re-initialize.

In #1778 I go further and recreate the android view container, which does allow for re-initialization, but the driver still gives up.

Debugging the trigger:
---
It seems that the crash is related to our usage of VAOs. Falling back to GLES2, which doesn't use VAOs avoids the driver crash. Not sure we setup the ES3 context correctly, see #1780.

Proposed solution:
- Integrate the improved recovery mechanism to master
- Alert the user when an unrecoverable driver crash occurs
- Use a blacklist to force GLES2 in those devices

HOTFIX 
---
Forces GLES2 context

APK: http://reicast-builds.s3.amazonaws.com/builds/heads/skmp/oppo-fixes-06ac421/reicast-android-debug-06ac421.apk

Affected hardware:
---

GPUs
- Adreno 304
- Adreno 306
- Adreno 308
- Adreno 330

Driver Versions
- 140 AU
- OpenGL ES 3.0 V@140.0 AU@(GIT@la10634f51b)

Devices
- One plus one
- Galaxy A3 (A300FU)
- Galaxy J5
- Others?

**Comment by skmp** [comment]
_Originally posted by @TundraMeadow in https://github.com/reicast/reicast-emulator/issues/1779#issuecomment-581089641_

Same here... it has not been working since the last update.
![Screenshot_20200202-000452](https://user-images.githubusercontent.com/57765528/73601868-e1b5bd00-4547-11ea-98f9-38877cb8b35e.png)
![Screenshot_20200202-000535](https://user-images.githubusercontent.com/57765528/73601870-e9756180-4547-11ea-8709-e7c9d66758c1.png)

**Comment by TundraMeadow** [comment]
My cellphone model is the very first J5 to come to the market. No root btw.

**Comment by skmp** [comment]
That's Adreno 306.

**Comment by skmp** [comment]
@TundraMeadow can you try http://reicast-builds.s3.amazonaws.com/builds/heads/skmp/adreno-3xx-fixes-5aac6b7/reicast-android-debug-5aac6b7.apk ?

**Comment by skmp** [comment]
Fixed by #1784

**Comment by TundraMeadow** [comment]
@skmp I tried to install but it did not work (rogue translation would be like "The app was not installed") 😭 I guess I will need one of those high end Xiaomi now... at any rate, thank you for answering ✌☮

**Comment by skmp** [comment]
It should work, the fix is verified in many devices.
