### ISSUE TITLE
Homebrew selfboot cd's

### ISSUE THREAD

**Issue by ppsspp213** [reicast/reicast-emulator#179]
Does reicast support these or is it gdrom only?
I've tried running a few homebrew demo's but they either crash to the reicast 
menu or stall on a white screen after showing the Dreamcast logo.
Is this because my images are either currupt or broken, I think I read something about
the 1ST_READ.BIN needing to be scrambled, is their anyway to verify my images are legit without burning them and testing on a real DC.
Reicast also seems to skip the MR IP.BIN logo's, is this done for speed?

**Comment by blackman91** [comment]
Does Homebrew work on reicast now? I tried beats of rage but I only get white screen.

**Comment by astonmartin260** [comment]
I don't know

**Comment by blackman91** [comment]
I get sound but white screen in all the homebrew I have tried, it is very similar to this issue:
https://github.com/reicast/reicast-emulator/issues/1020
