### ISSUE TITLE
Update chd/chdr/chdv5 code

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#18]
@rtissera has made an updated lib from the old chd code that supports v5. We should switch to it - https://github.com/rtissera/libchdr

Related: #676

**Comment by baka0815** [comment]
I tried merging https://github.com/rtissera/libchdr and got that compiling after a while, however it reports that the CHD would be broken - but chdman says it's fine (looks like I did something wrong).
Our chdr implementation is a C++ version (like the current MAME one), but the library from @rtissera is backported to C.

I take a look at that tomorrow if the v5 stuff can be merged in our C++ version instead of moving to C for that.

**Comment by baka0815** [comment]
Ok, my (experimental) branch (https://github.com/baka0815/reicast-emulator/tree/chdr) boots CHDv5 files which were created using "zlib (Deflate)" or "cdzl (CD Deflate)".
At least Crazy Taxi works, F355 Challenge - Passione Rossa v1.001 however doesn't work (the GDI from which I created the CHD works)...

**Comment by skmp** [comment]
I also spent some time to get this working -- https://github.com/reicast/reicast-emulator/tree/skmp/upgrade-chdr. It depends with #1206 a bit, around the include paths. Also doesn't compile for android or windows.

**Comment by skmp** [comment]
@baka0815 do you have flac support in your changes? what is the difference between zlib and cdzl?

**Comment by baka0815** [comment]
No FLAC or LZMA yet. You can pass 'zlib' and 'cdzl' to chdman.
'zlib' is about the same implementation as in previous versions, but with a different header, 'cdzl' has a base and a subcode decompressor and a little different structure.

**Comment by baka0815** [comment]
Libchdr also differs from the current mame implementation, so we probably shouldn't use it as external? I don't know if @rtissera is still working on it, because uncompressed isn't working and there are a lot todos in the code.

**Comment by baka0815** [comment]
We could fork and modify the code?

**Comment by skmp** [comment]
@baka0815 @rtissera forked our code to start with :p. I think it is best having it as an external lib - then it is easier for other projects to reuse it too.

Afair the MAME drop is harder to work with

**Comment by baka0815** [comment]
@skmp Yes, MAME has **way** more dependencies!

However as we would need some bug fixes in @rtissera's work (uncompressed CHDv5 don't work, zlib compression in CHDv5 doesn't work, his code references ``GDROM_TRACK_METADATA_TAG`` as ``'CHTD'`` while MAME uses ``'CHGD'`` and maybe more) we would either need "upstreaming" our work to @rtissera's branch or fork his work into the main reicast-emulator project, make our necessary changes and reference the lib from there (and later on try "upstreaming").

**Comment by rtissera** [comment]
Feel free to fork and submit PR I will make my best to merge them.

Le lun. 23 juil. 2018 à 16:21, Christoph <notifications@github.com> a
écrit :

**Comment by baka0815** [comment]
@rtissera I created a first cleanup PR https://github.com/rtissera/libchdr/pull/9.

**Comment by baka0815** [comment]
@skmp some of my changes got merged into https://github.com/rtissera/libchdr so you might give the lib support another try.
There is also a pull request waiting from @inolen after that uncompressed files should start working.

**Comment by skmp** [comment]
Sounds like great work! I’ll have my branch working in windows over the weekend, updating it will be trivial!

**Comment by baka0815** [comment]
@skmp also take a look at my changes in https://github.com/reicast/reicast-emulator/blob/055c3599b6cfa99279542dc2d29c6e5032995ded/core/imgread/chd.cpp#L101

This is to support ``GDROM_OLD_METADATA_TAG`` and ``GDROM_TRACK_METADATA_FORMAT``.
See https://github.com/baka0815/reicast-emulator/commit/37f0ff62db5e41043cd79ca618481dacaeb7eed3#diff-cb507bb17d74342aa45b6e4d10d607af

See https://github.com/mamedev/mame/blob/1d4f72b5fec0d8c5388222f48f4ac95bf3cb567c/src/lib/util/cdrom.cpp#L1127 ff. for reference.

**Comment by i30817** [comment]
Something 'interesting' (or maybe not) you might not know right now is that retroarch inbuilt support for chd is crashing the application when you try to scan some MAME roms, namely those that aren't a 'cd' but are chds (harddrive roms for example).

Possibly the scanner treats every chd as if it was a cd and tries to extract a serial and crashes when it finds a different thing than expect, i didn't dig in but that's my feeling.
