### ISSUE TITLE
wglSwapLayerBuffers cripples Intel integrated graphics video output on Windows 10

### ISSUE THREAD

**Issue by theurgus** [reicast/reicast-emulator#1813]
It is at it says on the tin. The latest alpha branch is unusable on my Intel Ivy Bridge integrated GPU as the menu takes literally 10 seconds to process events. Using the Very Sleepy profiler, I've tracked the problem to the wglSwapLayerBuffers function call causing the video driver's client library to wait for something through WaitForMultipleObjects. I'm not a graphics guy, so I've simply replaced the offending call with a plain SwapBuffers and the problem seems gone, though I don't know if it breaks anything else in the process.

**Comment by skmp** [comment]
`wglSwapLayerBuffers` is the correct way to flip the screen, afaik. What kinds of speeds are you getting? Maybe it waits for vsync?

**Comment by theurgus** [comment]
Well, it seems that a single frame gets rendered in 10 seconds or more. I can't tell you the exact numbers as I can't get past the menu to get to the FPS counter.

This is speculative, but from [what I've read](https://docs.microsoft.com/en-us/windows/win32/opengl/overlay--underlay--and-main-planes) on wglSwapLayerBuffers, the function has to do with overlays - you know, those abominations from the 90s where the GPUs only ever worked fullscreen, so you had to set your window's background to some punch-through color so that the GPU's output is visible? 

There's also [a remark](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wglswaplayerbuffers#remarks) for the function itself: apparently, you have to do some feature checks before using it.

As for whether it's the correct way, I have no idea, but I've literally never seen this function before, as all books and tutorials I've seen don't bother using anything than SwapBuffers anyway =/

**Comment by skmp** [comment]
Grepping the internet a bit more it seems that `SwapBuffers` should be the same as `wglSwapLayerBuffers(hdc, WGL_SWAP_MAIN_PLANE)`. Sadly, documentation does not seem very clear, not without knowing how the entire GDI stack works. 

I'm open to switching it if it fixes your problem - can you make a PR for it? Leave the `wglSwapLayerBuffers` commented out with a note about perf.

I'll test on my laptop later today and if it works fine I think we're safe to merge

**Comment by theurgus** [comment]
The thing is, there's doesn't seem to be a GDI stack anymore: if I'm right about what overlays do, those are now emulated, with Windows video output now composited through render-to-texture. Maybe the function is just emulated poorly. The Sleepy profiler is somewhat unclear on what's happening. I'll run some tests on VTune and also another Intel GPU and a Geforce one, then I'll either report back here or in a PR.

On a side note, how do I test for regressions? I guess something like FifoCI is too much to askfor, but is the emulator at least deterministic so I could jury-rig some record/replay tool instead of testing each game by hand?

**Comment by skmp** [comment]
Sadly we only do manual testing for now. I had some scripts that run the emulator with a large set of games and uploaded the results to youtube, however that never made it to CI. The emulator is overall semi-deterministic. nullDC had a deterministic mode, however that was a LONG time ago and it's likely things are broken in subtle ways around determinism at this point.

Generally, we have an army of beta testers (~ 15K) via google play, and we hear back if things are majorly broken for them. Any merge to beta does a googe play beta release automatically.

I want to revamp the CI and add stuff like fifoci at some point, but lack of time. We do support TA dumps and re-loads, or at least we did before the major refactors. I also want to add support for CORE dump support.

Both of these are major pieces of work though, and we need to figure out the infrastructure angle as well. 

For more information you can look at #1225 #1559 #1560 (among others)

**Comment by theurgus** [comment]
Well, I kind of expected that. I've actually been doing some research on how to give a boost both to the UI and the regression testing department since last week, so I'll hopefully present a highly technical, somewhat controversial proposal to the project the next week. I just need to give it some more thought (and quite a bit of code) so it won't be rejected outright.

Anyway, thanks for the answer. I'll do some more research and a proper follow-up on the issue at hand then.

**Comment by skmp** [comment]
:D


You might want the http://dev.reicast.com dev discord

**Comment by skmp** [comment]
Closing this as it is resolved @theurgus looking forward to those proposals :)
