### ISSUE TITLE
black screen on last alpha

### ISSUE THREAD

**Issue by LuisFellp** [reicast/reicast-emulator#1850]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

| Platform | Branch | Hash | CIDL |
| ------ | ------ | ---- | ---- |
| Android 10 | Alpha | 12154b2 | Downloaded from build site? Yes |

**_Description of the Issue_**

when i start the emulator, i get stuck at a black screen

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

![Screenshot_20200328-103044_reicast](https://user-images.githubusercontent.com/33043774/77825465-e3cb7080-70df-11ea-9502-d1c3bf64d311.jpg)

- [X] Place an X in the box to confirm you have filled in this form

**Comment by skmp** [comment]
Should be fixed with #1877
