### ISSUE TITLE
Overclocked mode

### ISSUE THREAD

**Issue by ppsspp213** [reicast/reicast-emulator#204]
Would it be possible to add a setting to set the cpu / gpu clock speed for faster gameplay in intense games for when they drop below 50/60 fps, ppsspp and mupen64 offer something similair, apprently the Dreamcast can be overclocked up to 250Mhz. I'm not sure what benefit this would have over being able to set the framerate limit value though most of the games I run without fps limit run miles quicker but without an in-game fps overlay there's no way of knowing it's true running fps value, in epsxe I can get up to 380fps. tbh I don't see a need for frameskip running it overclocked then framelimiting it to 60fps seems like a better solution and produces smoother gameplay over frameskip skipping frames, in ppsspp if you go over 3-5 skipped frames games actually start to look more sluggish  because of the start / stop jumping motion of skipped frames.

**Comment by skmp** [comment]
Let's close this for now, and re-open if we want to implement it.
