### ISSUE TITLE
Internet support

### ISSUE THREAD

**Issue by Karaulov** [reicast/reicast-emulator#233]
Someday will add support for Internet(Dreamcast Online Games)?

**Comment by hyssein** [comment]
3 years later still waiting but you do have a very good emulator gotta give credit where credit is due

**Comment by AbandonedCart** [comment]
@Blaze08 This request is 4 years old. It's safe to assume it wasn't being prioritized over regular game functionality.

**Comment by skmp** [comment]
@Karaulov this should now work
