### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#24]
Requires rooted device. I also don't have a mac or iphone, but i'll probably be able to have access for porting usage at some point. Also, gb_away is working at it

**Comment by skmp** [comment]
https://www.youtube.com/watch?v=ANmL7LvNzdw ~ to keep everyone up to date

**Comment by skmp** [comment]
https://www.youtube.com/watch?v=wjOtWBH_u0E ~ to keep everyone up to date

**Comment by skmp** [comment]
The iOS/OSX work has been merged into master (as of a9fc0f5aa804946ec38ee98f5b6efebe016e0e6b). We still lack a proper UI and input code for iOS. Eta is the jun hackcamp.

**Comment by LoungeKatt** [comment]
Everything is buildable with the recent updates to the project. It crashes instantly, though. I am trying to figure out if that is on my end or in the code.

**Comment by pipikaka111** [comment]
Its been a long time since people have been trying to build reicast for iPhone

**Comment by LoungeKatt** [comment]
@pipikaka111 not sure what you mean. I build it alongside every Android build I test.

**Comment by pipikaka111** [comment]
I'm talking about the iOS version. It never came out

**Comment by LoungeKatt** [comment]
Didn't come out and not being built are two completely different things. It didn't come out because it isn't ready, or at least not enough for public release.

**Comment by pipikaka111** [comment]
Ok thx for the heads up. Do you think I can beta test it a compiled build ? I don't have a Mac.

**Comment by LoungeKatt** [comment]
An iOS version exists (at least in source), so we shouldn't need this issue about starting one.
