### ISSUE TITLE
BIOS auto-start setting is ignored

### ISSUE THREAD

**Issue by ppsspp213** [reicast/reicast-emulator#243]
I had a brief look at GL2JNIView and saw that immersize sticky was added some time ago, i'm on 4.4.2 and i'm not show the initial reminder bubble message before enabling immersize mode, system bars are always visable.

BIOS Auto start 'off' setting is ignored also, cdda cdi's are not playable? 
MIL-CD's went to the music player with v1.022 (1999)(Sega)(US)(M6)_va2_4, by the way what happens if you use a custom gdi of the utopia boot disc with modified 3rd track using utopia's 1ST_READ.BIN and IP.BIN on the above BIOS?

**Comment by skmp** [comment]
@ppsspp213 what is the exact issue here? Is this still a problem? Re-open if so
