### ISSUE TITLE
Grandia 2 boot crash fixed.... But starts again at next event 

### ISSUE THREAD

**Issue by hubrisnxs** [reicast/reicast-emulator#253]
So I was jumping for joy when I tried just now to get the log for the grandia 2 boot crash that occurred on every device and every rom, leaving Sandras house in mirimu. I never played this game, and was enjoying it considerably.. 

Anyway, unfortunately, two mandatory events later in game, where you have to talk with the village chief before sleeping in the inn, leaving his house again causes a reboot. Now, with the sandra bug, it didn't have a log upon reboot, but this one did.... A short short one that I don't see could be really it, but here you go. 
http://reicast.loungekatt.com/report/logs/1392013003800.txt

I would be more than happy to send you game saves if it could help or if that isn't really the log from the boot.. Thx and sorry for long post. I just really really really want to play this game, and Skies, that your emulator allowed me to first experience.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#59
