### ISSUE TITLE
[Enhancement] NTSC and PAL broadcast format

### ISSUE THREAD

**Issue by psennermann** [reicast/reicast-emulator#273]
In my opinion, in the video menu, an option for selecting NTSC (60 fps) or PAL (50 fps) should be added; this could be useful for having less slowdowns on high demanding games.

**Comment by blackman91** [comment]
So how do you change the dc_nvmem.bin? I have the red dreamcast logo but it seems all the games only go up to 50 fps.

**Comment by LoungeKatt** [comment]
It's been a long time, but I think it was a HEX edit.

**Comment by blackman91** [comment]
I got over the 50 fps cap by changing the broadcast and region dc in reicast settings to NTSC-J and using the corresponding bios. Teated with power stone 2 on Androis Android 7 and it definitely works.
