### ISSUE TITLE
Desktop osx port

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#28]
Depends on #26, and we also need UI

**Comment by hooby3dfx** [comment]
so now that ppl are building on linux x86 what known issues are there for building on osx?
i tried awhile ago and ran into build errors in libasound (under the linux-deps dir) - does osx have all the same dependencies?

**Comment by LoungeKatt** [comment]
OSX requires its own set of dependencies or a lot of compatibility (macports / homebrew) substitutes.

**Comment by skmp** [comment]
(We do have a basic OSX build now that works, so closing this)
