### ISSUE TITLE
Shenmue flickering sky on PoverVR Gpu

### ISSUE THREAD

**Issue by psennermann** [reicast/reicast-emulator#289]
I have an Asus tablet with PoverVR Gpu (SGX544MP) and in Shenmue the sky is flickering (it's like sme sky textures get applied and removed very fast).
This is how it looks like:

![screenshot_2014-02-16-13-57-21](https://f.cloud.github.com/assets/6342467/2180298/bbe76afc-970f-11e3-9e5b-76b7ca25e2cc.jpg)

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#38
