### ISSUE TITLE
Reicast doesn't load any game

### ISSUE THREAD

**Issue by psennermann** [reicast/reicast-emulator#293]
With the last revisions available 17b1d51 and 540fd32 Reicast doesn't load anymore my games.
When I select a game to load it always loads the bios instead: it shows the Dreamcast logo (without the red or blue dot moving), then the set date/time screen and after that the bios management setup (where you handle "memory card" and so on).
I tried to move the games (cdi format) from the SD card to the internal memory, but the emulator always loads the bios instead of the game.
My system is an Armv7 1.2 ghz quad core with Android 4.2.2

Games loaded fine in 65db3be

**Comment by makerz23** [comment]
Hi I have a galaxy s6 edge and have done everything I can think of the game shows it's there but when I try and open it it loads dreamcast start up but doesn't load game it goes straight to menu again why is this?
