### ISSUE TITLE
Clock keeps resetting

### ISSUE THREAD

**Issue by ppsspp213** [reicast/reicast-emulator#307]
Back to 1998 or it keeps crashing reicast on the next run if the time has advanced by a few minutes, it also causes games to stall when trying to read memory cards if I do manage to get in-game it'll ask me to create a new save even though the old one is still on the card. It seems to be totaly random, I try reproducing it and sometimes it'll run as normal without any problem and update the clock accordingly.

**Comment by JazzMaster** [comment]
its not fixed. pc wise anyways.

**Comment by hooby3dfx** [comment]
yes, i believe the solution at the time was to inject the system time from the android platform into the core.
ill reopen the issue so that a more robust solution can be done which would solve it for pc, libretro, etc.

**Comment by hooby3dfx** [comment]
Out of curiosity, were you using reicast through libretro on PC?

**Comment by dubsmachine** [comment]
Having this issue on Android, tried a few different builds and I can't fix it.
Tried clock before system time, clock after system time, same as system time but nothing works!!

**Comment by AbandonedCart** [comment]
This has finally been resolved across platforms.
