### ISSUE TITLE
PS3 Controller not being properly identified

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#314]
We get the right stick values for controllers that have one. The code to go from motion to button and button to motion is there now. 

Should it be an optional replacement for the left stick, substitute for the dpad, a useless appendage on the controller? Thoughts? Anyone?

**Comment by skmp** [comment]
@ppsspp213  Is this still an issue with current master?

**Comment by wurz311** [comment]
No idea, no longer have PS3 controller to test.

**Comment by skmp** [comment]
Alright, let's close this and make a new issue if it appears again
