### ISSUE TITLE
Fix all moga issues

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#360]
@MrPsyMan reported that both modes were not working correctly in r6. 
can we get the hardware for whoever wants to pick this up?

List of affected devices:
Moga Pocket BT - reported not working 

state of Moga support has been posted http://forums.reicast.com/index.php?topic=77.0

**Comment by hooby3dfx** [comment]
goal of this issue still stands. i will update description and close/reference other moga issues.

**Comment by skmp** [comment]
@hooby3dfx Is this still relevant now?

**Comment by AbandonedCart** [comment]
Moga has since abandoned their controller support, so Mode B works as a BT controller using Android's controller API and mode A is more or less a lost cause. With that, it is working.
