### ISSUE TITLE
Failsafe titles for testing functionality

### ISSUE THREAD

**Issue by AbandonedCart** [reicast/reicast-emulator#363]
We should probably come up with some benchmark games that are known to use 90 - 100 % of the available features so situations like a game that only supports the Dpad doesn't make working features appear broken, or at least specific games for specific features that are supposed to work in them. A few I can think of:

Microphone:
Seamen

Controller / Bumpers / VMU:
DOA 2
Soul Calibur

**Comment by skmp** [comment]
Would be nice to include that to #1102

**Comment by AbandonedCart** [comment]
Closing in favor of https://github.com/reicast/gamedb/issues/3
