### ISSUE TITLE
Team communication & coordination

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#365]
I've been kind of MIA lately, and we don't really have a stable way to coordinate. 

Current ideas
- forums w/ dev boar (gotta fix them, get them pretty)
- skype/other im. Or maby I should look into a nice irc client.

and leave the issue tracker for .. issues :)

**Comment by skmp** [comment]
Link to #1102

**Comment by skmp** [comment]
After 3+ years, it feels like the tracker kind-of-works-okay for a dev forum, any objections to using it like that?. There's also the forum at http://dcemulation.org/phpBB/viewforum.php?f=86, towards we should re-direct users that just need support/community. If you register there, poke me and I'll add you to the reicast staff team.

I idle at both the irc and slack channels, though neither of them is really alive. I would love to have a realtime chat that works. Any proposals on how to get this done? Most of my dev-related chats are over whatsapp or fb messenger these days 😭 

I guess we can use emails for PMs for now? 

I'll look into the shared email thingy again, and there's also social (FB, Twitter), etc things that would be nice to be less centralized.

**Comment by LoungeKatt** [comment]
![Discord](https://cdn.neow.in/news/images/uploaded/2017/12/1512670052_discord87mil_story.jpg)

**Comment by skmp** [comment]
That’s more of a gamer oriented platform, isn’t it?

**Comment by LoungeKatt** [comment]
https://discordapp.com/open-source

**Comment by skmp** [comment]
Discord has emerged as the de-facto chat. http://chat.reicast.com. Closing this ~
