### ISSUE TITLE
Note 3 - android 4.4 ( snapdrago 800 ) - Shenume - Notebook broken

### ISSUE THREAD

**Issue by mirek190** [reicast/reicast-emulator#386]
*edit by @skmp*
Depth precision issues are causing this problem. It might be possible to work around them, but there's no easy for fix now

---

Look at it 

http://i62.tinypic.com/f550uf.png

Notebook is broken I can not  read it instructions, numbers, etc.
The game is unplayable now.

**Comment by psennermann** [comment]
Since this issue is over 5  years old, I think it won't ever be fixed, but I also wanted to report that "Redream" (another Android Dreamcast emulator) doesn't have this problem (which affects Samsung Galaxy Tab S2 as well), so I don't think it would be so impossible to fix it in Reicast...

**Comment by flyinghead** [comment]
![shenmue-notebook-android](https://user-images.githubusercontent.com/16261910/64192322-bb95cf00-ce7a-11e9-89a2-737faaf227bb.png)

**Comment by psennermann** [comment]
Your image is useless, this issue affects only some devices...

**Comment by flyinghead** [comment]
This problem affects all devices that use per-triangle sorting. I added the per-strip option specifically for this but apparently someone removed it...

**Comment by psennermann** [comment]
If you can plese re-add it (as an option I think it wouldn't hurt anything), otherwise at the moment the game is almost unplayable...
