### ISSUE TITLE
Add all those slow features we support as options.

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#394]
We do support clipping, rtt and modvols, but they are too slow and thus disabled.

Unfortunately this affects playability on games that occasionally require them.

If we add them as options the users will at least be able to switch them on when they are required, then off again. That's better than something like a black screen making a game unplayable, right?

@skmp what do you think?

**Comment by skmp** [comment]
4 years later, I think we should add them as options now. If anyone is willing to pickup this I can help identify which #defines do what

**Comment by mar753** [comment]
Render to texture: https://github.com/reicast/reicast-emulator/pull/1460

**Comment by skmp** [comment]
This has mostly been implemented.
