### ISSUE TITLE
Wireless control input, no root

### ISSUE THREAD

**Issue by ppsspp213** [reicast/reicast-emulator#403]
What can be used for wireless control input?, atm i'm using USB/BT Joystick Center Gold and nothing is picked up in Reicast or Dolphin, I can't set to native ps3 output as i'm not rooted, no device id is shown.
PPSSPP recognises it as something called "built-in.name of button" , mupen64ae shows it as "KEYCODE_BUTTON_name of button"

**Comment by skmp** [comment]
@LoungeKatt can we close this?

**Comment by LoungeKatt** [comment]
It's extremely old and there have been a lot of restructures in how this works, including some that will be part of Android Studio. The voices in my head say yes.
