### ISSUE TITLE
D2 [NTSC-U] exception.

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#410]
During the (semi-interactive) intro of the game you're greeted with this:

Unhandled exception at 0x006afcd1 in reicast.exe: 0xC0000005: Access violation writing location 0x30cefff0.

The line throwing the initial exception is 1293 in file ta_vtx.cpp : cv[1].y=sv->y2;

After that the exception mess continues elsewhere.

That's on Win x86 with dynarec enabled.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#63
