### ISSUE TITLE
Updated phone to 4.4.2, potentially caused performance issue?

### ISSUE THREAD

**Issue by jose325i** [reicast/reicast-emulator#416]
My LG G2 (Snapdragon 800/Adreno 330) just got an OTA update from 4.2.2 to 4.4.2. Adreno drivers went from v45 to v66. Reicast used to run absolutely butter smooth with no frame drops whatsoever on 4.2.2. I updated to r6 at the same time, but immediately went back to my known good previous build, only to find r6 was not the issue. Old build lags the same. No background apps running.

Now on 4.4.2, I see the issue most often on Sonic Adventure 2. It is playable speed, but before it was butter. Now it has "hitching" or frameskipping. I'm sure my old phone did not skip this often, I'll compare them tomorrow. Checking unstable opts does not help.

Maybe the internal frameskipping is being weird, or my processor is not staying at high clock speed? When I uncheck limit fps the game and music run very fast, and the graphics don't seem to hiccup/skip frames anywhere near as much.

Any way I can do further tests? Some sort of performance log?

**Comment by tabnk** [comment]
Same as issue as me. I'm have a RK3288 with Mali-T764 on Android 4.4.2. ALL games with frame rate stuttering.

**Comment by skmp** [comment]
Hmm, that is interesting. Speed limit isn't enforced based on FPS, it is enforced using time information from the audio. I guess we really need some kind of telemetry / remote analytics to cover these problems.... It's just impossible to write fool proof code on android.

**Comment by tabnk** [comment]
Frame-rate Stuttering on various android devices (Tegra 4, Xiaomi Pad (Tegra K1) and Nvidia Shield Tablet (Tegra K1) ) all should be on android 4.4.2.

Check out the videos

Tegra 4
https://www.youtube.com/watch?v=0wo-h4MVqN4

Xiaomi Pad (Tegra K1) 
https://www.youtube.com/watch?v=m7nek82B3o8

Nvidia Shield Tablet (Tegra K1) -  Even on the MOST powerful GPU.
https://www.youtube.com/watch?v=tSzV7GZr4eI

None of the above can run at full speed (60fps) when LIMIT FPS is on.

**Comment by skmp** [comment]
@tabnk is this still an issue?

**Comment by skmp** [comment]
Closing in favor of #602
