### ISSUE TITLE
Tokyo Xtreme Racer 2 (NTSC-U) - gauges and rest of ui not showing.

### ISSUE THREAD

**Issue by racedriver420** [reicast/reicast-emulator#426]
![screenshot_2014-03-27-21-18-21](https://cloud.githubusercontent.com/assets/7085444/2543181/9a38f3ea-b5ef-11e3-90fa-ea3ccb5bb73e.jpg)
Would like to notify that most of tokyo xtreme racer 2's user interface is missing.
Have tried all the settings and have had zero sucess.
This kinda renders the game unplayable since the menu to go back to garage is broken too.

Running Galaxy s2 with cyanogenmod 10.3

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#62
