### ISSUE TITLE
Grandia 2 has jumpy/glitchy animation on spells that use FMVs

### ISSUE THREAD

**Issue by mckimiaklopa** [reicast/reicast-emulator#428]
It is jumpy even though frameskip is off.basically ,the animation when there is an FMV in a spell is that it renders lets say frame 2,than renders frame 1,than renders frame4 than frame3 and so on causing the feel of being jumpy.Happens on cdi and gdi rips of the ntsc version.the opening FMV is fine though

**Comment by skmp** [comment]
Videos are affected in most games, and it is very likely the same bug.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#61
