### ISSUE TITLE
Emulator crashes while setting the time/after the time setting menu

### ISSUE THREAD

**Issue by rexatlanti** [reicast/reicast-emulator#429]
If i start the emulator im in the time setting menu. If I dont change the time and go on "select" the emulator crashes. If i want to change time the emulator crashes after i pressed up or down at the day, month or year. I cant change the time. If i try to play Grandia II the emulator crashes after the ubisoft screen. But that doesnt matter cause i couldnt even save because i cannot access the main menu. The system im trying to run the emulator on, is a a "Asus Memopad FHD 10" modelnumber "ME302" with android 4.3

**Comment by skmp** [comment]
@rexatlanti can you reproduce this with a build from http://builds.reicast.com?

**Comment by Zetchzie** [comment]
This nhappens on windows too I can go all the way to the end and spip setting the time but when it starts to load the menu it crashes if you press up or start it crashes im using Intel HD graphics

**Comment by AbandonedCart** [comment]
This appears to have been fixed. If the issue is still present, please reopen.
