### ISSUE TITLE
Grandia 2 grey background on battle

### ISSUE THREAD

**Issue by mckimiaklopa** [reicast/reicast-emulator#430]
My device
samsung s duos 2
Videocore IV hw gpu
broadcom chipset

1.2 ghz dual core
![screenshot_2014-04-03-20-44-28](https://cloud.githubusercontent.com/assets/5818289/2603452/2ded2c2a-bb2f-11e3-81ac-152250271698.png)
Happens regardless of reicast version or setting

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#60
