### ISSUE TITLE
Game won't boot

### ISSUE THREAD

**Issue by cloud1250x4** [reicast/reicast-emulator#433]
With a previous build, my game was booting (sonic advance 2) and now the only thing I can get to boot is the bios////

I have delete the old dc folder and created a now one (to clear old config and things like that) but no luck.. it's still doesn't work :/

I've got a n htc one running on miui v5, the sd card is emulated by the system

**Comment by Akkuddus** [comment]
SOMEONE HELP ME PLEASE! 
I got sonic adventure 2 going rom ready to play but when I load the game it takes me back to the home screen whyyyyyyyy? I have bios and I could load it up so whyyyyyyyy isn't this game working
Please help!

**Comment by LoungeKatt** [comment]
Have you read through the other issues about games not loading to make sure it isn't similar? I ask because there have been a few different reports that end up being the same cause - kitkat devices need the BIOS stored on the internal sdcard.

**Comment by Akkuddus** [comment]
WAT THE HECK IS A KIT KAT
I have a Sony xperia m2!

**Comment by LoungeKatt** [comment]
The m2 is your hardware. Kitkat is a version of Android, the software.

**Comment by Akkuddus** [comment]
Oh
Well my version is 4.2.2 
But that still doesn't tell how to fix the problem?

**Comment by LoungeKatt** [comment]
Yes, but the question was if you had looked at the other issues with the emulator immediately crashing to see if that information solved yours.

**Comment by Akkuddus** [comment]
Where should I look?

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/661
https://github.com/reicast/reicast-emulator/issues/653
https://github.com/reicast/reicast-emulator/issues/612

Usually, the best way to see if a solution has already been posted is to look through the titles of other issues and see if any sound similar (usually closed ones have more answers).

While that is the most likely cause of your issue, you are welcome to post a log if none of that information solves it.

**Comment by Akkuddus** [comment]
WAT are these numbers for?

**Comment by LoungeKatt** [comment]
Links. You click them to see the details for that issue number.

**Comment by Akkuddus** [comment]
Man if your a youtuber can make a video of all the problems/issues.That happed r6/r7

**Comment by Akkuddus** [comment]
Listen man when you make reicast have r8 please 
Make sure that it doesn't have the problem that I have!

**Comment by LoungeKatt** [comment]
Asking for a video of all issues across two versions is a bit much. It won't help to resolve the issues, will cost valuable time that could have been used to resolve them, and will only demonstrate what most issues have already documented well enough for the contributors to understand.

Your issue, at least what it appears to be from what little information was provided, is not the emulator. It is the new permissions being enforced by newer Android versions. You can downgrade the entire phone or simply put the BIOS on the internal sdcard (sdcard0, /storage/emulated/0, /data/media/0).

I recommend seeking help on the forums (http://forums.reicast.com/). That way, other users may be able to sit down one-on-one and walk you through setup.

**Comment by Akkuddus** [comment]
Thanks man I appreciate it Wat you said

**Comment by Akkuddus** [comment]
Hey do you know when r8 is coming out?  If you do could you make sure that you don't have to downgrade software?

**Comment by LoungeKatt** [comment]
r7 has to be released before any plans for r8. No version requires that you downgrade software, but that is one way to avoid dealing with Android permission changes. It is a bit extreme when the alternative is to simply move the file from one folder to another one.

**Comment by Akkuddus** [comment]
WAT is the permission changes?

**Comment by LoungeKatt** [comment]
https://www.google.com/

**Comment by Kdog5611** [comment]
So lets just say someone cannot physically move the dc folder from external storage to internal? Every plan on even trying to fix that?

**Comment by LoungeKatt** [comment]
It sounds like you haven't been following, so there have been quite a few attempts to resolve it. The sad truth is that the Android system does not allow it. Perhaps your frustration would be well directed at Google's feedback system. They deserve to know it was more of a regression than a security fix.

**Comment by Kdog5611** [comment]
Well thats funny because ppsspp is in my internal storage and it works
totally fine with all the folders being in external.

**Comment by LoungeKatt** [comment]
If this were a PSP emulator and handled files the same way, that would be a fair argument. Your games can be on the external storage card, though. It is only the BIOS that can't. Last I knew, PPSSPP emulated the BIOS and did not need files. An emulated version for reicast, aptly named reios, is in the works.

**Comment by Kdog5611** [comment]
Well lets hope that gets done.

**Comment by LoungeKatt** [comment]
That is a good reason for the new crowdfunding campaign. It will allow things like this to get completed long before they would being left to the time restraints @skmp faces.

**Comment by Rose2234** [comment]
![tmp_30069-screenshot_2015-08-11-00-35-182019328046](https://cloud.githubusercontent.com/assets/9696516/9187640/5dde5670-3fc2-11e5-8522-ba34df820e2b.png)

**Comment by Rose2234** [comment]
![tmp_30069-screenshot_2015-08-11-00-59-48-1021450156](https://cloud.githubusercontent.com/assets/9696516/9187821/7075f138-3fc4-11e5-94d2-65393e8d45a3.png)

**Comment by Rose2234** [comment]
![tmp_30069-screenshot_2015-08-11-01-00-02953717000](https://cloud.githubusercontent.com/assets/9696516/9187824/7c452290-3fc4-11e5-8ddb-d2cf419ff0bb.png)

**Comment by Rose2234** [comment]
![tmp_30069-screenshot_2015-08-11-01-00-10-1471615828](https://cloud.githubusercontent.com/assets/9696516/9187827/87d28242-3fc4-11e5-8972-00b89ee65ee8.png)

**Comment by LoungeKatt** [comment]
@Rose2234 I'm not sure what you're trying to show here. The report button would have included your basic device information, but it should probably be in an issue other than the crowdfunding discussion.

**Comment by Rose2234** [comment]
What do you mean by that it will require additional information

**Comment by Rose2234** [comment]
Why make a app with no support from the devs

**Comment by Rose2234** [comment]
I want the old build back

**Comment by LoungeKatt** [comment]
@Rose2234 What were you doing when this happened? What do you mean by no support? Your issue is being addressed within hours of the report. There is only so fast we can respond. What old app? Are you using the newest version? The screenshot of the app appear to be an older build.

**Comment by Rose2234** [comment]
No its a newer build r7 and the one in the  play store is r6

**Comment by LoungeKatt** [comment]
Correct. The version in the play store is r6, but new builds are published each time there are changes to the code. If you are using a build downloaded a few month ago, there is a chance it will have issues that may have been fixed in a build published last week.

**Comment by Rose2234** [comment]
I understand

**Comment by Rose2234** [comment]
I have tried that build to in the play store without any luck

**Comment by LoungeKatt** [comment]
I am looking into it now. The error doesn't match up to the newest version, but I did track down the newest version of what was running when the crash happened.

**Comment by Rose2234** [comment]
Okay I didn't think you would look in to it tonight. I apologize if I
gotten a little bit up set at ya.

**Comment by LoungeKatt** [comment]
Alright, I have added an extra check to make sure it doesn't try to sort a list that doesn't exist. That should prevent the error if it wasn't already fixed by other changes along the way.

http://reicast-builds.s3.amazonaws.com/builds/heads/master-83d525d/reicast-android-debug-83d525d.apk will include the fix I just added.

**Comment by Rose2234** [comment]
Is it because I'm running a custom firmware?

**Comment by LoungeKatt** [comment]
It shouldn't be. It looks like it may have tried to sort a list of files that didn't exist. It would only be a problem if the version I posted above crashes for the same reason. That would mean there is a file in one of the folders that is causing it to happen.

**Comment by Rose2234** [comment]
What files though

**Comment by LoungeKatt** [comment]
That is something I wouldn't be able to tell you. It doesn't look in any folders that start with "." and it would only be looking on the sdcard. It would likely be something with a really unusual name to cause any sort of issue. Files like "%*&($@*ad         //\\\\fkhasd##)(@!#(____3843.bin"

**Comment by Rose2234** [comment]
Okay I did that and then it says the same error please put dc_boot in the
the data folder I did that and then it recreates new folder on sdcard0 and
sdcard1

**Comment by Rose2234** [comment]
AGAIN

**Comment by LoungeKatt** [comment]
You need a folder. There should be a folder inside that named data. For example /sdcard/dc/data
The BIOS goes in the data folder and you pick /sdcard/dc in the emulator.

**Comment by Rose2234** [comment]
Yeah I did that about 30 fucking times.but it will recreate a new folder
where ever it wants to.

**Comment by LoungeKatt** [comment]
Some improvements to setting up the BIOS are being written and tested.
https://github.com/reicast/reicast-emulator/pull/733 is the PR for the changes.

**Comment by Rose2234** [comment]
Why could this be implemented in the earlier bulds

**Comment by LoungeKatt** [comment]
The earlier builds didn't use a BIOS locator. That is a relatively new replacement for the browse button. It has only been recently that KitKat / Lollipop permission changes forced even that to be redesigned.

Things improve over time. That is the nature of technology. The entire reason to have live ongoing test builds is so that things that may not go wrong for the person that wrote a feature can be found by those that may use it on different hardware, with different content, or in a different way.

**Comment by Rose2234** [comment]
I'm have a whole fuck ton of problems

**Comment by LoungeKatt** [comment]
I can understand the frustration, but it would be appreciated you not post profanity.

**Comment by Rose2234** [comment]
Why is it recreating the same folders over and over again

**Comment by LoungeKatt** [comment]
That usually happens when you try to select data as the folder instead of the folder that the data folder is inside. With the new builds, you should be able to select the BIOS file from a list, so it shouldn't even have that file browser window anymore.

**Comment by Rose2234** [comment]
It does its say Drive or browse

**Comment by LoungeKatt** [comment]
When you click browse, you should go to settings. In settings, clicking the Locate on the right next to system path will find the BIOS

**Comment by Rose2234** [comment]
I did that but it always shows my CTR rom for psx .its a .bin file even
when when change the path it gives me a error saying this folder is assumed

**Comment by skmp** [comment]
(@LoungeKatt, you are my hero and an example for all of us)

**Comment by Rose2234** [comment]
What!?!?

**Comment by LoungeKatt** [comment]
@skmp :P

@Rose2344 it should only show files that start with dc_

If your BIOS isn't listed, it may be the wrong name or not on the internal sdcard. Make sure the files are dc_boot and dc_flash

**Comment by LoungeKatt** [comment]
This is how it should look. The highlighted buttons are what I clicked.

![screenshot_2015-08-11-08-48-22](https://cloud.githubusercontent.com/assets/1173913/9198303/2d63fc60-4009-11e5-94d1-0e47af3339c5.png)
![screenshot_2015-08-11-08-48-48](https://cloud.githubusercontent.com/assets/1173913/9198306/2fe04b24-4009-11e5-8c35-5841e423ed80.png)

**Comment by Rose2234** [comment]
I don't have those options

**Comment by LoungeKatt** [comment]
The selections depend on what is on your device. If you don't have at least one dc_boot.bin, that means either the BIOS isn't on your sdcard (not /extsdcard or /sdcard1) or doesn't have the right name.

**Comment by gamery** [comment]
Hi I'm new member I have a problem with using reincast when I try to boot a game I pushed back to desktop and game won't load I'm using Lyf wind 6 on Android 5.1.1

**Comment by gamery** [comment]
Help me
