### ISSUE TITLE
Reicast Gamepad Support

### ISSUE THREAD

**Issue by jawknee720** [reicast/reicast-emulator#438]
Running reicast with HTC One.  Absolutely love this emulator.  Runs perfect.  I recently purchased a Moga Pocket BT gamepad so I could maximize the experience, but I can't get the controller to work with Reicast.  I've even tried using Tincore keymapping, but the one YouTube video showing how to do it was in Russian.  Anyone have any advice or tips to get this gamepad running with reicast?  I'd really appreciate it.

**Comment by hooby3dfx** [comment]
closing as dup of https://github.com/reicast/reicast-emulator/issues/360
