### ISSUE TITLE
Shenmue, crashes when trying to move to another location.

### ISSUE THREAD

**Issue by RioRenFuku** [reicast/reicast-emulator#441]
Every time I try to leave the house, pick up the kimono over the bed of the Rio. Or even anywhere to go to the next location, the emulator crashes on the menu. If you disable the game is very dynarec hangs, but the transition between locations is successful. Also, if not included in the setting of the emulator "unstable Optimization" when you try to start a new game or load, the phone just turned off. Use sony xperia L

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#58
