### ISSUE TITLE
Ooga Booga white screen

### ISSUE THREAD

**Issue by thealexcraft** [reicast/reicast-emulator#444]
Whenever I try to start the game Ooga Booga, it does the logo startup thing, then the screen goes white. Is this fixable? If so, please tell m how or do an update, this is my favorite childhood game. Thank you.

**Comment by tonyt900** [comment]
I have been getting a white screen after I  select armada from the reicast browser screen. any advice?

**Comment by hooby3dfx** [comment]
That is expected for now in any game using Windows ce.

**Comment by hooby3dfx** [comment]
closing as dup of https://github.com/reicast/reicast-emulator/issues/53
