### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ac3theone** [reicast/reicast-emulator#445]
http://reicast.loungekatt.com/report/logs/1398181697438.txt

**Comment by ac3theone** [comment]
Hi reicast/reicast-emul,

I&#39;d like to add you to my professional network on LinkedIn.

- Richardo

Accept: https://www.linkedin.com/blink?simpleRedirect=0MdzAScjoUd30NczARcjwSdPARfkh9rCZFt65QqnpKqipTjSNCljdUmzRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CgQbjhNsSVJrjpFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=p3gJd75PrCRJdCAJsDBHcSkQfmhFpipTin17k5kUoC9Fu6AVkjxKpDdTd6hakmVjmBsTbntTkncJiiRahkl8sQJPsPdDe35hqnEMkztzemNUu3kOlmhSgBFVm31PgQRoejtklTcQlS5qpjxWrD5xe5tqpBBGrDdPek9Dp4hgi5hzi5hTk7cQq4UVcl1Fokpfdj5qhQBJsQ9WiC5WcRp6hC9OqzxBskxSlk51gl5voQV1i3xHpCpAhB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CgQbjhNsSVJrjpFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5976815945761460224_500&amp;markAsRead=This email was intended for reicast/reicast-emul reicast/reicast-emulator. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CgQbjhNsSVJrjpFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ac3theone** [comment]
Richardo Jonas would like to connect on LinkedIn. How would you like to respond?

Accept: http://www.linkedin.com/blink?simpleRedirect=c3oVdz4Se3gMcj8Vdj4UdzsVdjR4imVLqnhxt6BSrCACtQZIpBkPu5EZumlbp6lOomxP9zANnT1UplZSrCAZqSkCsClArCBJpn8Jt71BoSdxbm8JpTpKqlZJrmZzbmNJpjRDrCBHoS5Ot2pBt6BSrABDpl9BsD0ZoioSbmoRq3wOt3pFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=

View Richardo Jonas&#39;s profile: http://www.linkedin.com/blink?simpleRedirect=3ANnT1UplZSrCAZqSkCsClArCBJpn8Jt71BoSdxbm8JpTpKqlZJrmZzbmNJpjRDrCBHoS5Ot2pSs6UZt2oSbmoRq3wOt3pFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBc3ATd3sPdOQSem8OcjsVpmkVcPAPcS4UomoUp64SoPgOe6kQc35AoCcQpj4QpmoSbjsTczkUej4PbmB2cylVr71BszRIqm5JpioMdz0MczRAqioMdzAScjoUd30NczARcjwSdPARfmhFpOoVclZMu6lvtCVFfmJB9C9RsSVRbmoJoS9BrlZJrmZzbmNJpjRDrCBHoS5Ot2pLrSsZt2oSbmoRq3wOt3pFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=3oJpzlEe39QdCAJsDBHcSkQfmhFpipHnRgTnRZ8tBplt6ZvrlByoz5Pq75li79CcCxIrC5geltVgnd3hltctDh3qORVsl4Pu4YQjj5Fc64Ti6xvlz5vemUUdRAQuz1FqklTiRwPuD54oCl2snxisBdnbl5or2QQtnoUoj9xt7ppbjxmilxOjBhImm58rB4OrBhGiz1yrQdPl7delRkRqAd1c3pdcClSlk51gmsNd3BFnThSpPxPhl51fmhFrSMCej5vs7xBnTpKqjRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2oSbmoRq3wOt3pFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5976815945761460224_500&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Cej5vs7xBnTpKqjRHpipIsBlBoSBSsCljsClJrThPtmcZoioSbmoRq3wOt3pFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ac3theone** [comment]
Richardo Jonas would like to connect on LinkedIn. How would you like to respond?

Accept: http://www.linkedin.com/blink?simpleRedirect=0MdzAScjoUd30NczARcjwSdPARfkh9rCZFt65QqnpKqipTjSNCljdUmzRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CcQbmBQd7FOcjtFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=

View Richardo Jonas&#39;s profile: http://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CcQbmBQd7FOcjtFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kMejsQdPcTbjoVoz8NdPBBpjAPejcPojxxpzxAojpzd38UpjgMcmhyoPhBcjhBpzoJdPsOdjwVcjcJqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0SejoNdzwQc34OejkNe3oTejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CcQbmBQd7FOcjtFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=1zd2RFt3hWsz4TqiROumIPpjgZp6BB9B5IpB4UtldgoQxJjnpRlQwNc4J5ijxepmFEtSVgrk4MpmRGemtOlkFbbjcRqStytS9xkjlRkjpAekgTiP5CjkZEjBwNoAFcgP9dhj93ilFVr7lOp3sMkQFyl5gNdD0UikZBqnAOc7B3oj5FnS9kdApCtmJnozdBpzxipT4QjntRtjdGt5tVtllItyRclmdhbnplgk51tQtQt5AUsldztCp7kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CcQbmBQd7FOcjtFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5976815945761460224_500&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CcQbmBQd7FOcjtFbn9VqPdBd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5976815945761460224_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by hooby3dfx** [comment]
@ac3theone more info or this will be closed. template: https://gist.github.com/hooby3dfx/69c9d0f2f0db09edc961#file-reicast-bug-template

**Comment by rrrh** [comment]
Closed (since 3 years old), please reopen if problem still exists.
