### ISSUE TITLE
Detect boot discs, CDIs and show a warning

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#454]
Utopia and other "backup" boot disks generally don't work, and should not be used. Same goes for repackaged versions of games to CDIs and such. We do support booting CDIs, as it is useful for homebrew and such, but hacked game releases are outside the scope of the project.

We could also show a warning for windows ce games that are known to not work.

**Comment by AbandonedCart** [comment]
Closing this in favor of https://github.com/reicast/reicast-emulator/issues/493 (cleanup ahoy!)
