### ISSUE TITLE
18 Wheeler American Pro Trucker no 2D graphics

### ISSUE THREAD

**Issue by Processeur** [reicast/reicast-emulator#471]
Hi,

on Xperia Z stock rom 4.3.1 with 0.r6[6ad8c9a] there is no 2D graphics.
No score, No menu, only 3d on 18 Wheeler American Pro Trucker.

Bye

**Comment by skmp** [comment]
Is this happening on any other hardware? @Processeur is this happening with current master?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#57
