### ISSUE TITLE
no on screen buttons

### ISSUE THREAD

**Issue by qlive97archos97b** [reicast/reicast-emulator#480]
Hello, I installed the latest version of reicast and buttons or controls are not seen, tried all options and do not see the onscreen controls.

I'm playing in qlive97 (archos platinium 97b)
The characteristics of tablet:
Display • 9.7’’: 2048 x 1536 pixels, IPS,
Android 4.2, "Jelly Bean"
Processor:
 • Quad-core ARM Cortex-A9 1.6GHz (rk3188)
 • Quad-core GPU Mali 400 MP4
RAM • 2GB RAM)
thanks for your attention

**Comment by tabnk** [comment]
I'm ordering a RK3288 TV box soon but unsure the compatibly.Anyone encounter problem with mali-t764 GPU while using reicast ?

**Comment by hooby3dfx** [comment]
repeat - @qlive97archos97b does this happen on r6 from the play store?

**Comment by qlive97archos97b** [comment]
yes, this happens on r6 from the play Store

**Comment by qlive97archos97b** [comment]
hello, how long it will take to repair this mistake ?. Store version gives the same error

**Comment by Guns29** [comment]
I have the galaxy s8 and having the same problem when touching the screen I can fill the buttons but they are not displayed on screen tryed all opinions but nothing can some one help

**Comment by skmp** [comment]
@Guns29 are you using the beta? see #1208

**Comment by AbandonedCart** [comment]
This has been resolved. Please reopen if it resurfaces.

**Comment by hung14** [comment]
I'm also having this problem the on screen control still there.just isnt visible, using Xperia xz premium and newest build on playstore.

**Comment by AbandonedCart** [comment]
@hung14 Please see the response to the other post you made about it.

**Comment by gdance** [comment]
I was experiencing this issue on my Samsung Galaxy s7 phone and in order to get the buttons to show I had to download a reicast button image file from the following link and put it in the same directory that I put my reicast bios file(probably in the data directory).

https://github.com/reicast/reicast-emulator/issues/115
