### ISSUE TITLE
Old r7 release sprint

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#490]
The release is scheduled for FRIDAY, 17:00 GMT

[r7-rc branch](https://github.com/reicast/reicast-emulator/tree/r7-rc) | [Pending issues](http://github.com/reicast/reicast-emulator/issues?milestone=3&state=open)

This is a thread to coordinate testing, and see what's broken.

Keep in mind that
- Things that already have their own issues should have these issues updated, instead of posting them here. Update them, and ref the update from here.
- Bugs NOT introduced since r7 don't belong here, even if they are regressions. If you find any, you should create separate issue for it.
- For any reported bugs, they should be [git bisect-ed](http://webchick.net/node/99). _pretty please_
- I've referenced many interesting issues that need testing, and
- It's a good idea to go a pass over all existing issues and update them with "still happens on r7-rc" or "seems fixed in r7-rc"
- We need to do some limited play testing
- r8 is scheduled in 3-4 weeks, so only _important_ things need to be fixed for r7
# Known issues
## r5 regressions
- Crazy Taxi-PAL (#224) and Virtua Striker 2 (#383)
## r7 regressions
- Soul Calibur, The camera doesn't line up correctly on the beginning of a practice match (#?)
- Soul Calibur, "Thin legs" (#?)
## General breakage
- MOGA (#290, #439, #360)
- Native Interface, OSD does not show up. The ingame menu works though (#?).

Irrelevant for r7 release window, but still worth to notice
- Depth handling is very problemagic, ex Dynamite Cop.
- Many major memory leaks ( f1ef4877b8d6ca20f4b102e19320b2e5cb1e739f fixed some, there's #252, #254, others ?)
# How are we gonna push this?

First to Google play, perhaps staged deployment to check for major unexpected breakage, then to OUYA.

Let's get the ball rolling!

**Comment by skmp** [comment]
Aalllriiightt, #614 and #615 seem to be the only ones left. I can tackle #615 within the next week, @LoungeKatt is #614 still relevant? Does the UI part work on all cases/android versions?

**Comment by LoungeKatt** [comment]
Archiving this since it is 3 years old and the issues it referenced were closed.
