### ISSUE TITLE
Toukon Retsuden 4

### ISSUE THREAD

**Issue by kkaalldd** [reicast/reicast-emulator#511]
With dynarec enabled, the characters in Toukon Retsuden 4 act very strangely indeed - heads and limbs swing and rotate .

https://code.google.com/p/nulldc/issues/detail?id=261&q=label%3APriority-High&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary%20emu

**Comment by skmp** [comment]
@kkaalldd is this still happening with current master?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#56
