### ISSUE TITLE
Maple: Add light gun support

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#513]
Does anyone think this would be worthwhile for light gun titles?

**Comment by blackman91** [comment]
That would be amazing, just check this namco gun emulation of Resident Evil Survivor on mobile:
https://youtu.be/K94Eo8S42vw

**Comment by baka0815** [comment]
We could use the mouse for that on Desktop.

**Comment by blackman91** [comment]
https://github.com/reicast/reicast-emulator/commit/601fafa

There is hope now guys.

**Comment by skmp** [comment]
Should be implemented after #1523
