### ISSUE TITLE
Button Mapping issues

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#52]
Some users report that they are unable to map the emulated analog triggers to digital buttons on their controllers when using "touch button->controller button" mapping software.

It's also next to impossible to support multiple key presses simultaneously for games that require them.

What do we do for these cases?

**Comment by skmp** [comment]
@LoungeKatt is this still an issue?

**Comment by skmp** [comment]
(Closing, ticket cleanup. Please report in discord if still an issue)
