### ISSUE TITLE
When i play one game the game stops working in a few minutes

### ISSUE THREAD

**Issue by Wanler** [reicast/reicast-emulator#521]
Hello :) , Well one problem.
I playing perfect resident evil code veronica, all fine, but approximately a 20-minute game, it stops working.Losing the progress and reload the game :(
The game is frozen, it can do nothing, only output from the emulator.
It is as if it had limit to play the game. Lol
I would like if they found the problem, arranged it please.
It is a wonder this project :D Thanks!

**Comment by SacaSoh** [comment]
Hey guys, since the last time I reported I didn't test it on the new builds. Well, today I got the "2015-01-16 20:48:03" build and loaded the save game that I was able to replicate the freeze multiple times: there was no freezes or crashes in 2hrs of continuous gameplay.

**Comment by devinator12** [comment]
Problem still present on my end using Nvidia Shield Handheld. Tested with build #4a917a0
Tested with Gauntlet Legends. (Quite happy that game runs now)

**Comment by LoungeKatt** [comment]
@devinator12 have you tried resetting the BIOS and changing the time to one minute ahead of the real time? There was an issue a while back with the BIOS time getting corrupted that could cause a freeze. It's possible that resurfaced.

**Comment by devinator12** [comment]
@LoungeKatt When i did the upgrade i removed the previous version and installed the new one. When i booted it prompted for a new date and time. Is that the reset you meant or should I dump my bios again?

**Comment by LoungeKatt** [comment]
Should be able to delete the nvram to cause it to prompt for time

**Comment by devinator12** [comment]
New logs http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1421526379466.txt

**Comment by SacaSoh** [comment]
Well... I didn't change anything at the system, but the issue resurfaced: it freezes consistently in 20 min of gameplay. 

I'll confirm the time to freeze  and try to generate logs. 

How do I change the clock to 1 minute ahead? I think that to set the clock I had to put it 5 min behind or it won't set...

**Comment by SacaSoh** [comment]
Just confirmed: still freezing after 20 min of gameplay.

**Comment by skmp** [comment]
I actually saw a freeze aswell while running on tegra. I guess this needs to be further investigated?

**Comment by hooby3dfx** [comment]
Same, while testing soul calibur.

**Comment by LoungeKatt** [comment]
Psychic Force hasn't done this. Ironically, that was one of the ones that didn't render correctly a while back. It has to be either a specific type of texture causing it or the OSD, because those are the two differences.
With a shield portable, it may be good to test a game that froze in native mode (OSD is disabled) to rule that out.

**Comment by devinator12** [comment]
@LoungeKatt I did that test with OSD disabled.

**Comment by BonzaiThePenguin** [comment]
For me it freezes within seconds, either at the Sega screen, at the 50/60Hz screen, or at the load save file screen. Downgraded to the Play Store version and it works correctly. Pretty sure it has nothing to do with this freeze, as it's clearly of a different nature, but whatever.

**Comment by LoungeKatt** [comment]
@BonzaiThePenguin now that you have included that the freeze happens instantly, it is a little clearer that it may be an unrelated issue.

**Comment by BonzaiThePenguin** [comment]
I was able to reproduce the freeze-after-20-minutes bug in the 9/11/14 build, but not in the 10/22/14 build.

**Comment by BonzaiThePenguin** [comment]
> It would be better to update to the newest test version, as debug popups are now working.

Are "debug popups" the messages that appear when glCheck fails? I'm getting those popups for the entirety of stage 3 of Sonic Adventure 2 Hero mode (first Tails stage), but it's impossible to pin down the source with the current design since glGetError returns the most recent error *since the last time glGetError was called*. This means if you call glGetError, run a ton of OpenGL commands, then call glGetError again, the error it returns could have come from any one of those commands.

If you're going to use glGetError for that, use it after *every* OpenGL call that can set the error flag, not just glDrawArrays and a handful of state changes.

**Comment by LoungeKatt** [comment]
The debug popups are not intended to provide the user anything more than a warning that a crash is most likely inevitable. The content of each error when it happened is saved to the master log. Having seen the error, the user now knows something did go wrong and the crash was not the emulator "randomly returning to the menu" and can submit that log.
It was never meant to imply you are to fix it on your own.

**Comment by LoungeKatt** [comment]
@hooby3dfx @skmp we should probably resolve this before attempting anything for #594. This one we have all seen and will prevent any false positives trying to locate what's going on with that one.

**Comment by glac81** [comment]
I have got the same problem with Shenmue, jet grind radio and sonic adventure 1.

**Comment by SacaSoh** [comment]
Still freezing after 20min of gameplay on shield porta le. Logs:http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1425071178982.txt

How do I enable the hle BIOS? Just add the bios.UseReios=1 to emu.cfg?

**Comment by LoungeKatt** [comment]
That will work for the time being. I have the settings toggle in the pulls, but I either need to finish updating the travis file to support Lollipop or revert a few things to merge it. It isn't far off.

**Comment by skmp** [comment]
Can you try http://reicast-builds.s3.amazonaws.com/builds/heads/master-c25ce04/reicast-android-debug-c25ce04.apk? Looks like dupplicate of #622

**Comment by Dio94** [comment]
Hi,
Just saying
With the last build from http://builds.reicast.com/
( 73a585a 2015-10-09T10:21:39.000Z ).

Now i have been able to let the game play for more than an hour without freezing the app or even the phone like it did before.
:+1:

**Comment by sabula310** [comment]
at crazy but it counie to stop working
