### ISSUE TITLE
Forced Widescreen VS True Widescreen

### ISSUE THREAD

**Issue by dallenc** [reicast/reicast-emulator#525]
Don't get me wrong but I am definitely a huge fan of the work you guys have put in thus far. Compatibility is by far excellent for an emulator in alpha.

Just out of curiosity but are you guys planning on implementing a forced widescreen mode? Not sure if it's just a simple matter of adding a few lines of code or a total recoding of the framework.

As it stands, this is the only issue deterring me from using the app more often on my mobile device.

**Comment by blackman91** [comment]
Does someone know if it is possible to use these codes on reicast?
https://segaretro.org/List_of_Dreamcast_widescreen_codes

For games that don't support the reicast widescreen hack.

**Comment by AbandonedCart** [comment]
> The following is a list of codes for the Sega Dreamcast _**cheat devices**_, allowing games to run in 16:9 anamorphic widescreen.
