### ISSUE TITLE
Resident evil code veronica: Saves sometimes not loaded on the vmu menu

### ISSUE THREAD

**Issue by Vlakipn** [reicast/reicast-emulator#528]
I don't know if it is related with freeze issue, but after freezing, next time when i started game i've lost 3 saves.

They dissapear and appear randomly when you opwn memory card in game. Wierd...
Check video ive made. Explains...

http://youtu.be/z8NJaOV8mYQ

**Comment by helloray** [comment]
I have the same issue. Also happens in Record of Lodoss War when you saving

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#54
