### ISSUE TITLE
Dpad and Analog stick both mapped to dpad

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#529]
I think this is a regression; reported on forum:
http://forums.reicast.com/index.php?topic=225.0

**Comment by Kuzummjakk** [comment]
Turnin off compatability mode and Custom Key Layout did it for me.

**Comment by DaJokerNikka** [comment]
When i turn compatability mode off my buttons are thrown off from what i mapped, and a few buttons like the right trigger stop working...

**Comment by LoungeKatt** [comment]
@DaJokerNikka Do you make sure to remap them after you turn it off?

**Comment by Grareven** [comment]
guys, can you please explain how to do this step by step.
Thanks in advance

**Comment by metallserge** [comment]
[problem was solved, tl;dr]
I've also noticed problem with reicast on xiaomi pad 4 + gamepad iPega PG-9037 in Skies of Arcadia:
while driving ship, analog stick was working as movement - good, d-pad as looking at sides - good
but left and right triggers were not working at all
I tried to make some changes in input control settings, but then I got d-pad behavior for analog stick while triggers were working

and then I found this thread and referenced article:
- my version is r6 [382f2e5], russian language
- in input menu pressed on Controller A -> pressed button on pad (don't know whether it is needed)
- then:
> In the Input menu go to 'Customize Physical Controls (Launch Editor)'
> Then set Enable Custom Layout to ON
> There is another option below that called 'Use Joystick for D-Pad Input' - set that to OFF
- i.e. first option is ON, second is OFF
- NO other changes were performed, just went to games list, started Skies, loaded save when I'm at ship and checked that all buttons, triggers and stick working fine
