### ISSUE TITLE
Implement autoconf or whatever building stuff is standard for lunix/osx/etc

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#535]
The current makefile based building works well for lots of embedded targets, but it is not sufficient for targeting unixish platforms. I believe autoconf is the most portable way to go about this? There's also CMake & friends, which manage to be awful to implement and not native to any platform.

**Comment by randomstuff** [comment]
I tend to think that autotools are quite horrible to use (you have some m4 macro which generates some unreadable shell scripts which generates some other stuff…). In comparison, cmake is not so bad.

**Comment by skmp** [comment]
I'm generally alergic to cmake as it is sometimes really hard to get it installed. I've run into many cases where a project requires a newer cmake version than the one available though the package system (usually, debian) which always leads to an interesting adventure. 

I guess though, no one really likes writing autoconf scripts these days, and cmake is better than nothing

**Comment by randomstuff** [comment]
I must say I ,ever had this issue (but I'm mainly using Debian testing so I tend t have quite revent versions of cmake). One solution would be to to try to target a not-bleeding-edge versions of cmake (?). See #695 for a initial/crude version of a cmake build script.

**Comment by skmp** [comment]
Closing in favor of #1383
