### ISSUE TITLE
Evolution 2 Far Off Promise crash

### ISSUE THREAD

**Issue by RossMeikleham** [reicast/reicast-emulator#538]
After completing the second dungeon and returning to the hotel in town and talking to the manager to advance the game, the screen goes dark before loading the next scene and crashes.

Attempting to get a log using the TestSuite wasn't working after this crash, every other time it worked fine even after the train crash which is rather strange, so I had to use adb + logcat to get the log for this particular crash. The log for the crash is [here](http://reicast.loungekatt.com/report/logs/Evolution2LobbyCrash.txt)

I've uploaded a vmu file close to where the crash happens [here](https://www.dropbox.com/s/fx86l2nvbpmoqam/vmu_save_A1.bin?dl=0). After loading the game walk left, and just downwards from the stairs should be the hotel manager, talk to him and select "Yeah, let's hit the sack". The screen should then go dark and then the game should crash before the next cutscene loads. 

One time It didn't crash and the next scene actually loaded. After it finished I saved the game, exited and got a log of the pass [here](http://loungekatt.com/ReicastBot/report/logs/1412441292199.txt).

I thought this crash was similar to  #168 but the difference being in the logs for this crash, before segfaulting there is this

```
I/newdc   ( 9699): Fatal error : Unhandled parameter
I/newdc   ( 9699):  in ta_main -> jni/../jni/../../../core/hw/pvr/ta_vtx.cpp : 509 
```

I decided to start a new game and got a [log](http://loungekatt.com/ReicastBot/report/logs/1412437983164.txt) of the train crash referenced in #168 just to check if these issues were the same, and sure enough the same Fatal error  occurs, but I'm unsure if it is of any actual importance to the crash.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#53
