### ISSUE TITLE
Resident Evil Code Veronica: Heat/water effect is wrong

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#546]
This is a known issue, adding it for documentation.

It is caused by the missing support for Render to texture on the rendering code.

We need a brave contributor to take a look at this :)

----

Thanks to @Vlakipn for the videos

 "heat/watter effect" graphic glitch.
Output should be like here on 3:40
http://youtu.be/SmbZIUZc2sk

Instead of it is like this:
http://i.imgur.com/mUzl4ly.jpg

It also happens in submarine area where there is similar effect of floating and screen gets same like in heat effect.

Related to: #10

**Comment by danny199012** [comment]
Heres my vmu just before picking golden guns uphttps://www.dropbox.com/s/d4gof88u3we38bz/vmu_save_A1.bin?dl=0

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#52
