### ISSUE TITLE
PVR: Modifier Volumes are not implemented

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#548]
This causes lack of shadows in many games, and breaks gameplay in a few cases like #94

**Comment by BonzaiThePenguin** [comment]
They *are* implemented, it's just commented out for some reason. I re-enabled it and it didn't seem to affect my framerate at all – the person who originally disabled it probably had a device that switched to a software rendering fallback for PVR, which destroyed their framerate. However, it does add a bunch of tiny black dots all over the place.

I highly suggest hooking up the PVR Rendering toggle button again.

**Comment by GamerPro7000** [comment]
How we revive The PVR on reicast ? Please help me.

**Comment by sabula310** [comment]
well did you tryed to get the file in reicast website

**Comment by GamerPro7000** [comment]
No You can Give me the link of the reicast site ?

**Comment by GamerPro7000** [comment]
And The File ?

**Comment by BonzaiThePenguin** [comment]
PVR isn't guaranteed to work on all phones, which is why they removed it in the first place. I provided an experimental build with the feature re-enabled, which happens to render shadows as a bunch of little dots on my phone. On other phones the results may be completely different.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/94
https://github.com/reicast/reicast-emulator/issues/1049

Leaving these here as a reference, so this can serve as the main issue.
