### ISSUE TITLE
PVR: Implement fog using lookup tables [$150]

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#549]
Reicast uses a curve-matching approximation to make fog calculations faster. This is not accurate compared to what the Dreamcast does, though. It is also likely that the exponential matching code is buggy too.

We need a brave contributor to take a look in the current code, make sure it works as intended and possibly implement lookup-based fog as an option. nullDC [implements](https://github.com/skmp/nulldc/blob/master/nulldc/plugins/drkPvr/ps_hlsl.fx#L153) fog using a lookup texture and a bit of shader code.

---

 That's why fog is wrong almost everywhere

**Comment by flyinghead** [comment]
This has been implemented in #1449
