### ISSUE TITLE
Input issues with analog vs dpad, TUVVA integrated Physical Controls Tablet

### ISSUE THREAD

**Issue by Reznaut** [reicast/reicast-emulator#558]
Running rc6 reicast

All the games I've tried have bugs making most of them unplayable, some of them unenjoyable. These games are:

1) Quake 3: left joystick isn't independent from digital pad (this happens with all the games on reicast with this tablet, not outside reicast though)
2) Unreal Tournament: gameplay graphics flicker ridiculously, everywhere
3) Toy Commander: crashes after bios swirl
4) Half Life: crashes after bios swirl
5) Soul Calibur: background flickering, no character shadows; many other things work right
6) Street Fighter 3, 3rd strike: characters appear as a jumbled mess, character select also gets messed up
7) Air Force Delta: the whole screen gets squeezed onto the left side of the tablet's screen
8) Lemans 24: crashes after the game's first intro video
9) Rez: there's a static image of multicolored interference that seems to sit between the flying dude and everything else in front of him; this also happened on my smartphone the Samsung Epic 4G which is a Galaxy S 1

All the games that don't crash run at the same speed they run on the real machine though, which is pretty cool.

This tablet runs OpenArena perfectly, detects all buttons and both joysticks. N64 from Paul Lamb runs Starfox, SM64, Goldeneye without an issue, detects all buttons and both joysticks. FPSE runs Omega Boost and Wipeout 3 without an issue, detects all buttons and left joystick.

The tablet that's running these games has physical controls that are (usually and in the most part) autodetected by reicast so there isn't much of a setup. See it here: http://www.tuvva.com/pages/power-play-gametab-techspecs ; there's a few left on amazon too.
Specs: 
RK3066 Dual Core ARM Cortex A9 1.6GHz CPU
Quad Core ARM Mali 400MP4 GPU
1GB DDR3 RAM
Android 4.1.1; Kernel 3.0.8+

You guys rock! Thanks!

**Comment by Moonmadness** [comment]
I'm still having the analog/D-Pad overlapping issue with my Ipega PG-9052 controller. If I start by gently pushing left stick toward any direction then it is recognized as an analog stick even if I go all the way to a direction, but if I give a quick tap in any of the four main directions it acts like a D-Pad even if it still works as a stick at the same time.
I have only Custom Layout on, and it's the only way to have my controller fully working.
The issue doesn't occur with my other BT controller (Speedlink Myon).

By the way congratulations for the job done, framerate dramatically increased on my phone since r6. It's soooo smooth now!

**Comment by LoungeKatt** [comment]
Every bit of information points to that being a hardware incompatibility.

**Comment by Moonmadness** [comment]
That's probably the case. I pointed it out since it only overlaps in a specific occasion and it may help troubleshooting controller issues.
Anyone with other Ipega models to see if it's brand specific?

**Comment by Kuzummjakk** [comment]
Turning off compatability mode and Custom Key Layout did it for me. I use an ipega controller as well.

**Comment by DaJokerNikka** [comment]
When i turn off compatability mode i lose my right trigger for my ps4 controller. I can move around but the controls i mapped don't stick, and i lose a few buttons. I'm guessing there is no way to fix that...

**Comment by LoungeKatt** [comment]
@DaJokerNikka Do you make sure to remap them after you turn it off?

**Comment by DaJokerNikka** [comment]
Yeah it just doesn't work. When i turn on compatability my controls are
really wonky but my analog works, and vise versa when it's off.

**Comment by LoungeKatt** [comment]
Are you using sixaxis or directly connecting to the emulator?

**Comment by skmp** [comment]
(Cleaning up old tickets)
