### ISSUE TITLE
error running on android on command line

### ISSUE THREAD

**Issue by ricardo85x** [reicast/reicast-emulator#560]
Hi

I am trying to run a rom from command line using this:

am start --user 0 -n com.reicast.emulator/.GL2JNIActivity -a android.intent.action.VIEW -eu Uri "file:///storage/sdcard1/ROMs/DREAMCAST/Ikaruga.chd"

But I got:

Starting: Intent { act=android.intent.action.VIEW dat=file:///storage/sdcard1/ROMs/DREAMCAST/Ikaruga.chd cmp=com.reicast.emulator/.GL2JNIActivity (has extras) }

Are there any thing wrong with this line?

I am using Android 4.4 on Nvidia Shield

**Comment by skmp** [comment]
@LoungeKatt, we also have another request at http://forums.reicast.com/index.php?topic=1435.0. And I also need it for automated testing. Perhaps we should add an "official" way to handle this?

**Comment by LoungeKatt** [comment]
It should already be working. Once I looked back, the mistake is calling GL2JNIActivity directly when the handler in in MainActivity.
am start --user 0 -n com.reicast.emulator/.MainActivity -a android.intent.action.VIEW -eu Uri "file:///path/to/game/Game File.chd"
Just tested it and it booted up and ran with no issues.

**Comment by ricardo85x** [comment]
yes. It is working now. Except that exiting the emulator through the usual menu attempted to boot back to the game, as LoungeKatt told.

**Comment by LoungeKatt** [comment]
Thanks. I never did go back and add a flush. I'll get that in shortly.
