### ISSUE TITLE
pushing r7

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#571]
Let's release current master as r7

Version: r7-rc1-22e95de
Apk: http://reicast-builds.s3.amazonaws.com/builds/heads/master-22e95de/reicast-android-debug-22e95de.apk
Source: https://github.com/reicast/reicast-emulator/releases/tag/r7-rc1
(Will be updated as needed)

In case you have issues, please note which version you tried. Otherwise we can't help. 

Unless there are any serious objections, I'll build and upload tonight to Google Play, reicast site, ouya & amazon stores. -> +1 day to get some more feedback (11/12)

**Comment by skmp** [comment]
So, to resume the release process.


a
![1](https://cloud.githubusercontent.com/assets/393266/5488082/7eaf30a8-86b9-11e4-92ab-53aaae9a3d11.jpg)


b
![2](https://cloud.githubusercontent.com/assets/393266/5488085/7eb29dc4-86b9-11e4-9c0e-cd0dec243e99.jpg)


c
![3](https://cloud.githubusercontent.com/assets/393266/5488086/7eb435a8-86b9-11e4-8ab9-822e8ee3a3a7.jpg)


d
![4](https://cloud.githubusercontent.com/assets/393266/5488083/7eb11850-86b9-11e4-9691-421a08569a4b.jpg)


e
![5](https://cloud.githubusercontent.com/assets/393266/5488084/7eb2716e-86b9-11e4-9f61-ae43d2531331.jpg)

f
![i3 cimgpsh_orig](https://cloud.githubusercontent.com/assets/393266/5458242/e0ae1f0e-8550-11e4-8fac-9653deb0769e.jpg)

g
![neutralcolors-flat-](https://cloud.githubusercontent.com/assets/5016840/5492102/5cd340c2-86e7-11e4-8ba9-7febc62d6173.jpg)


I decided to replace the screenshots w/ less offensive ones, avoid the sega/sonic (sonic is also a trademark) and, after carefull re-reading of the play store terms, to avoid colliding with any dreamcast ports released to the store.

A safe selection to get screenshots seems
- Shenmue
- Rez
- Power Stone
- Virtua Tennis
- Skies of Arcadia
- Ikaruga

Which banner *design* (irrespective of screenshot content) do you guys like most?

**Comment by skmp** [comment]
I prefer g myself most

**Comment by skmp** [comment]
@MrPsyMan @LoungeKatt @hooby3dfx notification spa

**Comment by LoungeKatt** [comment]
Spam yoself foo. I am torn between g and b. I like the ones that have some background "noise" but more screenshots in the back seem a little too noisy as the banner

**Comment by hooby3dfx** [comment]
Lol @ f.

I like g as well.
Might want to avoid virtua tennis (there is a title on store).
Rez screen would be awesome.

**Comment by skmp** [comment]
Oh, missed virtua tennis. Removed.

**Comment by skmp** [comment]
@skouts can you do a version of g without the screen glare?

**Comment by skouts** [comment]
![g-no-glare](https://cloud.githubusercontent.com/assets/5016840/5667883/e9afd432-9773-11e4-983a-d6a33e27ec95.jpg)

**Comment by vgturtle127** [comment]
G without the screen glare looks great, and is probably my favorite. And by probably I mean most definitely.

I also like it better when the phones don't have any reflection at the bottom and the logo does, but only a little.

The logo is really good as well.

Just curious, but what is the faint white-ish stuff in the background? It looks like part of a controller or something, but I wanted to make sure I was getting it right.

**Comment by LoungeKatt** [comment]
@vgturtle127 its a controller on the left and the front (port) side of the system on the right. I'm not sure the system is obvious at first, but it looks good.

**Comment by vgturtle127** [comment]
OK. But what is the dot to the right of the top mobile device? Lol. If it is just for design sake, that's fine.

**Comment by LoungeKatt** [comment]
That is the far right button of the controller from the left side, if you are talking about the dot between the logo and the screenshot.

**Comment by vgturtle127** [comment]
OK. I was just making sure. It looks awesome. I like the logo too, who designed that?

**Comment by skouts** [comment]
Glad you like it , I created the graphic, don't know about the logo.

**Comment by hooby3dfx** [comment]
So with various issues fixed we should talk r7!

**Comment by skmp** [comment]
I'll be in a coding camp w/ lots of coworkers on Jun1 ~ 7th, so that's my release window "plan"

**Comment by skmp** [comment]
Lots of hardware to test on, and also at the same time setup a better forum - poking with (discourse)[http://try.discourse.org/], setup the crowdfunding campaign, and do general UI/etc fixing.

**Comment by vgturtle127** [comment]
Will we get a Win32 build with r7? Just curious. If I build it, I always feel like the problems are all caused by me. :laughing:

**Comment by donaldpipowitch** [comment]
So, any plan when r7 will be released?

**Comment by mk8itra1n** [comment]
Mann I want an iOS version already!!!!

**Comment by LoungeKatt** [comment]
If you need help with building, please post on the forum or if you encounter errors, it's best to add to or start a new issue for the iOS version.

As for an "official" release, that will likely come once it is functional beyond just running.

**Comment by mk8itra1n** [comment]
I do need some help. I have a Mac and iOS and I'm a tech guy so I'm sure I'll get the hang of it quick. I've got a jailbroken iPad 2 i want to test it out on

**Comment by mk8itra1n** [comment]
Xcode 7 is now free from Apple so I want to build it on there

**Comment by vgturtle127** [comment]
When will the crowdfunding begin? Approximately. I want to make sure I can donate some when it comes time. I have to set aside money for that and Fallout 4. :smiley:

**Comment by blackman91** [comment]
I have the same quesion about the crowdfunding

**Comment by shinshura17** [comment]
Hi. I just recently installed R7 onto my Samsung amp Prime 2. I put all the files where they need to be and it's not working.

**Comment by LoungeKatt** [comment]
This is a known issue with outdated versions.

**Comment by shinshura17** [comment]
@Loungecatt, is there a way to correct it? How would I go about fixing this problem or would I have to try and get one of the other builds?

**Comment by skmp** [comment]
So, we need to start moving on this. I managed to switch to part time at work, so I should regularly have time for reicast from next week. I generally try to get work done on fridays, but no promises yet :)

**Comment by skmp** [comment]
"r7" is now public as open beta for reicast. Should follow up from #1150 and organize #1148

**Comment by skmp** [comment]
r7 has been released ~> https://github.com/reicast/reicast-emulator/releases/tag/r7
