### ISSUE TITLE
Game:Maken X freezes after stage 4 cutscene. Can we remove the cutscene or fix issue?

### ISSUE THREAD

**Issue by etinkin** [reicast/reicast-emulator#582]
All Nulldc based emulators have tis issue with maken x. 
The only version that maken x is fully playable on is a version of nulldc for pc that is incompatible with windows vista/7/8

I'm downloading dreamcast tools right now, and am going to try and find a way to remove the cutscene from the game so it is fully playable.

I have never done anything like this before, so if someone can offer advise it'd be appreciated

**Comment by skmp** [comment]
A savegame for testing would be really handy, too.

**Comment by devinator12** [comment]
I would recommend you extract the save from a actual Dream Cast. 

Simply removing the cut scene will not bypass the problem as it will introduce another. The disc will check for missing files. If it cannot load the file it will kick back to the Dream Cast Bios.

I will look into this later.

**Comment by etinkin** [comment]
Here are the saves.

https://www.sendspace.com/file/eqy9tq

**Comment by LoungeKatt** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1420432251458.txt

**Comment by LoungeKatt** [comment]
The save loaded fine. Played through the level it was on, went to the next one, and it freezes when there is a desk full of credit cards and IDs. I took the log after sitting on that for a minute to verify it was frozen.

@devinator12 Not sure what you are talking about, but if you are referring to taking out the cutscene, you want an ISO from actual hardware. The save doesn't include cutscenes. If the cutscenes are individual files, you don't delete it. You replace it with an empty (or shorter) clip. That is an ooooold trick. That is also the part that I was saying was best for the forums. The freeze, on the other hand, is an issue.

**Comment by etinkin** [comment]
. "The save doesn't include cutscenes. If the cutscenes are individual files, you don't delete it. You replace it with an empty (or shorter) clip." I was thinking this. It worked on the ripped psp games I used to play as a teenager all day. My only thing is I'm not even sure if http://www.theisozone.com/downloads/dreamcast/other/dreamcast-tools/ 
will suffice or if I'll be going in circles not  knowing anything about Dc ripping.

**Comment by LoungeKatt** [comment]
I have a feeling this may be linked to a few other freezes recently. None of them seem to generate an error, though, and the app itself is still functional.

I need to verify the error toast isn't freezing the emu thread. I think most issues like this predate it, but it's something to verify.

**Comment by etinkin** [comment]
You sure man? reicast r4/5 had the same issue with maken x, as well as all nulldc emulators that are vista/7/8 compatible. This has been an issue for at least 3 years.

**Comment by LoungeKatt** [comment]
It should just crash with the new code.

**Comment by etinkin** [comment]
So is it not reading the error?

**Comment by skmp** [comment]
Crash?

**Comment by LoungeKatt** [comment]
@skmp It's not a crash, it's a freeze. It should crash, but it doesn't seem to. That is the part I am unsure about being related to the freeze itself or the change from dialogs to toasts causing it.

**Comment by skmp** [comment]
I don't really see why it should crash, but while testing the game, I noticed that there are no voices in the new game intro. Is that how it's always been @etinkin?

**Comment by LoungeKatt** [comment]
@skmp a true freeze should ANR on Android. It seems like it isn't locking the thread is what I was saying.

**Comment by etinkin** [comment]
This problem is pretty old unfortunately @skmp 

See: http://www.snesorama.us/board/showthread.php?63888-%28DC%29-Maken-X
http://ngemu.com/threads/maken-x-u-help.108943/

Hell I was even having the same problem on the pc emu last year :https://code.google.com/p/nulldc/issues/detail?id=269

**Comment by skmp** [comment]
So, it never was really fixed then?

I'll investigate after r7 release. Gotta focus a bit on that first.

**Comment by skmp** [comment]
@etinkin is this still an issue on current master?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#51
