### ISSUE TITLE
reicast shuts down as soon as you try to select an ISO folder

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#584]
@Illegal-Machine commented on 0783875 19 hours ago
This doesn't load. A fresh install boots the menu, but it shuts down as soon as you try to select an ISO folder. Mine was on the sd card

Neither do the last 3 to be honest... Tested on Nvidia Shield portable. 

(Moved to issues, since the commit only served as a timestamp)

**Comment by LoungeKatt** [comment]
@Illegal-Machine Please use this issue to provide further details, rather than commenting on new commits. I was unable to duplicate the issue and your comments are vague, so it would be beneficial to have a single place to gather details over spreading this across changes.

**Comment by LoungeKatt** [comment]
It wasn't anything against you. It makes sense assigning it a time, but it can get confusing mixed in with the changes. Sometimes there are others with a similar issue at a different time, and they may have additional info, too. Chances are they wouldn't have seen the comment, though.

Are you able to type a folder into the box and access it that way? 
What Android version is it? I am assuming it is KitKat, which would fit with a lot of sdcard issues.

**Comment by gary36arms** [comment]
I'm having the same problem with my hudl 2, everything is where it should be as I've got it running perfect on my note 2. On the hudl when I try and load BIOS or .cdi file it just goes black and forces reicast to close. I did mess with some of thebsettings and managed to get the DC boot up screen at about 5fps and then crashes. On a side note though, excellent work on the emu so far.

**Comment by gary36arms** [comment]
Oh yeah and I keep getting the data folder respawning inside its self ie data/data/data

**Comment by LoungeKatt** [comment]
It makes plenty of sense when you stop to think about the requirements. You must have the bios in a data folder. Chances are, you did not know that the very first launch. Instead you had "/sdcard/Dreamcast" and selected that. The emulator made the folder "/sdcard/Dreamcast/data" for you. The common sense reaction would be go move the bios files into that folder. For some reason, the typical response is to keep selecting the new folder and creating another "data" inside it. There are various warnings, but usually hitting dismiss or back is favored over reading them.

**Comment by gary36arms** [comment]
So seeing as I can't get it working on my hudl 2 is this purely a hardware compatibility problem? It's a shame, it runs amazing on my note 2 so would be awesome on my hudl with an otg cable and a 360 pad.

**Comment by gary36arms** [comment]
When was the newest version released

**Comment by LoungeKatt** [comment]
Every time new changes are added, http://builds.reicast.com is updated.
Glad to hear it @Illegal-Machine, I think the reason I never had the same results could be linked to some things I was waiting to push through in the pull requests. There were a few extra checks for the folders.

**Comment by gary36arms** [comment]
Cool, well the latest build works on my hudl2 just slowly which I don't really understand as it absolutely kills my note 2 in all benchmarks I've tried and runs smoothly on the note.

**Comment by LoungeKatt** [comment]
@gary36arms you may want to check on the forums for anyone else that may have the same device and may have some suggestions on how to get it running faster.

It sounds like the issue is resolved, so I am closing this one. @Illegal-Machine if it starts up again, you can always still post here and we can open it back up.
