### ISSUE TITLE
Shenmue disk 3 issue

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#586]
from the reicast email 

"I play shenmue with this but when I go warehouse no.8 in 3rd disk it's closed"

Can we somehow verify this? @MrPsyMan ?

**Comment by hooby3dfx** [comment]
Can you get their game save?

**Comment by skmp** [comment]
Send an email, hopefully we hear back

**Comment by skmp** [comment]
Closing this as it is really old
