### ISSUE TITLE
Issues with Galaxy Tab 4 7.0

### ISSUE THREAD

**Issue by XShadowX01** [reicast/reicast-emulator#587]
So since the 30/12/14 update ive been having issues getting Reicast to work.
With the 30/12/14 update, Reicast would just crash when I loaded a game, yes i had everything in their respective directories, but it would just crash.
With this new update (Jan. 15 2015) it seems to not crash anymore, but Sonic Adventure 2 freezes, and by that I meen random lockups, no sound no nothing just a still image, I tried Sonic Adventure and that one seems to work fine. I also tested Soul Calibur and it still has graphical glitches, BUT speed actually seems to have improved! Thumbs up to that. ^-^ Well the games seem to be working on my Galaxy S2 but speed went down on that, I havent experimented much on it, and its an old phone too so theres all that, they used to work well on my GS2 don't know what can really be the issue but oh well, just reporting an issue of SA2 freezing on the G Tab 4, hope that can get fixed. ^-^  Love this Emulator btw.

**Comment by LoungeKatt** [comment]
Sonic Adventure and Soul Caliber both have open issues. You may want to look those over to make sure this isn't a duplicate.
Samsung crashes resulted from most devices using sdcard1 as external, while they use extSdCard. They are also known for having strict pass or fail rendering. Many warnings on other devices are errors on a Samsung. This is something being addressed via testing on a Note 4.

**Comment by XShadowX01** [comment]
Hey thanks for the reply, so leaving issues like graphical glitches and stuff aside, there was this "bug" mostly sure due to Samsungs system not really the app itself in my opinion, where games wouldn't launch, but I had the bios and games on the external SD Card, so I moved the bios into the Tab 4's internal memory, "emulated" sdcard0, and the games worked fine and didn't crash. I had the idea of moving Sonic Adventure 2 into the internal mem, but it still crashed, i haven't been able to reach the title screen. On the other had, Sonic Adventure 1 seemed to have minor lag but with todays update i didn't notice any, Soul Calibur actually improved, I lagging menu and playable gameplay, and now i have minor lag in menus and a bit faster gameplay, and i saw less graphical glitches, but the glitches vary from stage to stage and i basically just tested the game for crashing, and  only did the first fight.

**Comment by hooby3dfx** [comment]
so if i read this issue correctly, the actual problem is that sonic adventure 2 crashes.

**Comment by XShadowX01** [comment]
Yes, and well i've been of reicast for a month now, so I don't know if this has been fixed, I had 2 devices to test it with,  a Note 2 and a Tab 4 7.0, and on both devices the game crashed after the intro or just at the "SEGA" or "SONIC Team" screens. I was able to get to City Escape once but froze near the end. This was during the last updates of December and January.
