### ISSUE TITLE
Create form for error reports

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#588]
It might be handy to create a simple google form or other template so that when people report issues or bugs either here on github or on the forums we have more detailed reports. Maybe we could also put it directly in the emulator. 
Example:
**Issue type** (selection)
-Emulation problem
-Crash
-Feature request (maybe this could link to the forum)
-Other
**Specific game** (text input)
**Mobile device model** (text input)
**Mobile device OS version** (text input)
**Emulator version** (text input)
**Steps to reproduce** (text input)
**Logs**
**Screenshot**

**Comment by LoungeKatt** [comment]
I have a form set up, we just don't use it for anything but logs. All we'd need is a gui popup with the extra fields and it could generate the issue.

**Comment by hooby3dfx** [comment]
for now lets point new bug reports to use this format:
https://gist.github.com/hooby3dfx/69c9d0f2f0db09edc961#file-reicast-bug-template

**Comment by AbandonedCart** [comment]
3 years later, this is now a proper thing.
