### ISSUE TITLE
crashes on startup HTC one m8

### ISSUE THREAD

**Issue by dcfan** [reicast/reicast-emulator#589]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1421605933546.txt

**Comment by LoungeKatt** [comment]
Moga hasn't updated their library for Lollipop yet. A temporary solution is being tested.

**Comment by dcfan** [comment]
Is there a specific thread so I'll Know when there is a solution?
Thx

**Comment by LoungeKatt** [comment]
There is a pull request for the workaround, but depending on whether or not we can use that, moga support for LP may have to be temporarily disabled. There will be some form of solution to get it running over the next few days.

**Comment by LoungeKatt** [comment]
A temporary fix was added to resolve this until Moga updates.

**Comment by dcfan** [comment]
Okay where Do I find das this fix I'm new sorry =/

**Comment by LoungeKatt** [comment]
http://builds.reicast.com
