### ISSUE TITLE
LG G3 D855 Lollipop - Crashing when attempting to load game or BIOS 

### ISSUE THREAD

**Issue by mattwillmart** [reicast/reicast-emulator#591]
Here's the log it generated: http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1421783639705.txt

**Comment by LoungeKatt** [comment]
@skmp this one is a memory allocation issue.

**Comment by mattwillmart** [comment]
Let me know if there's any more info I can provide. For what it's worth, Reicast worked great when I had CM12 installed on here. Switched to stock and used the same games and BIOS files.

**Comment by LoungeKatt** [comment]
Thanks. Luckily, there is a lot more memory to work with than devices that have had this issue before.

**Comment by mattwillmart** [comment]
Yeah, I've got the 3 gigs of RAM variant too. :)

**Comment by Marcthesparta** [comment]
Hey, I own the Xiaomi Mibox Pro enhanced (2 GB RAM, CPU is Amlogic S802H and GPU is Mali450MP6), and I have the same issue. I can select the bios folder, but whenever I select the game folder, Reicast FCs on me. I tried to load the bios with the touch button mapping and it loaded fine.

I tried reicast r6 (play store version), and about 4/5 other builds, and encountered the same issue (some r7, newest builds, including a build that fixed this same issue, but with a galaxy note 3 snapdragon variant).

**Comment by kingpinzero** [comment]
Got same issue using Galaxy s5 sm-g900f running official Lollipop rom. On kitkat is fine.

**Comment by LoungeKatt** [comment]
Many of the Lollipop crashes are the Moga. The one here is a memory issue. If you check the log and don't have a memory section at the bottom, chances are it is that.

**Comment by kingpinzero** [comment]
I got the memory section at the bottom btw, i dont use moga or any external controllers. It just shut down (not even FC) after i load something. Paths are ok.

**Comment by LoungeKatt** [comment]
Ok. The Moga listener fires to check for one, so that would have been an issue either way. If you get a chance, please post your log. It will be easier finding safe regions with more occupied ones listed.

**Comment by LoungeKatt** [comment]
It appears this is also an issue with the Note 3 on Lollipop

https://github.com/reicast/reicast-emulator/issues/616

**Comment by skmp** [comment]
Try e2a70294d76de4b02750337e1dc684b8aa7c0100 http://reicast-builds.s3.amazonaws.com/builds/heads/feat/no-direct-memmap-e2a7029/reicast-android-debug-e2a7029.apk, It doesn't use the memory optimization

**Comment by mainadmin** [comment]
Works for me finally :) No more Dalvik javascript error.

**Comment by Drunkguy101** [comment]
Dumb question ~ how does one execute a game /bios from this build?

**Comment by skmp** [comment]
This is resolved
