### ISSUE TITLE
Touch buttons themes+new original buttons.png

### ISSUE THREAD

**Issue by Marcthesparta** [reicast/reicast-emulator#595]
I made some touch buttons themes.Here is the link to download them.Enjoy! :)

http://goo.gl/5JmZ1I

**Comment by LoungeKatt** [comment]
This should probably be in the forums.

**Comment by Marcthesparta** [comment]
Yes I know but I don't know where is the forum >,< :D

**Comment by LoungeKatt** [comment]
http://forums.reicast.com
