### ISSUE TITLE
Infinite loops in the code?

### ISSUE THREAD

**Issue by BonzaiThePenguin** [reicast/reicast-emulator#597]
I'm reviewing the 'while' loops in Reicast right now to see if any of them can cause the app to freeze up like I've been experiencing, and while this one is probably unrelated, it looks like this can be an infinite loop:

https://github.com/reicast/reicast-emulator/blob/08bed69c95ce2af30b26fb3da92b7d27936b1e17/core/hw/sh4/modules/dmac.cpp

In `DMAC_Ch2St` there are two while loops, and if in either one of them `(p_addr+len)>RAM_SIZE` is false, `len` is never updated so that branch will always evaluate to false every time and `while (len)` will always be true.

**Comment by BonzaiThePenguin** [comment]
`u32 FindMask(u32 msk)` in this file needs to be looked at closer too:

https://github.com/reicast/reicast-emulator/blob/b1f88f258b2b47318e56735504b1783fe9b59e6d/core/hw/mem/_vmem.cpp

It will result in an infinite loop if mask is not a power of two (or zero), and counting the leading zeroes can be done faster anyway. Not yet sure if it's possible for a non-POT value to be passed in with the current code. Also it's called repeatedly by `_vmem_map_block` on a constant value, which is inefficient.

**Comment by BonzaiThePenguin** [comment]
The for loops seem to be okay.

**Comment by skmp** [comment]
For dmac, there's a break; in the false case that exists the loop. FindMask is specified that way (it's only used during initialization w/ constants known to be masks)

**Comment by BonzaiThePenguin** [comment]
...You're completely right. I read that code like 50 times making sure I didn't miss anything, but somehow overlooked that break every time. D'oh!
