### ISSUE TITLE
Almost There

### ISSUE THREAD

**Issue by XShadowX01** [reicast/reicast-emulator#598]
Hello, i just got a Galaxy Note 2 and it works better than in my Tab 4 c: well, the first game i tested on the Note 2 was SA2 and it was working flawlessly untill i loaded City Escape, i have no idea what happened but, the game was waaaaayyyyy tttoooo fast and extreamly lagging audio, then the game crashed. I then launched the app again but changed some setting, i enabled widescreen and change video to HDMI and when i loded the game it crashed, i though it might have been the  widescreen since it also crashed the first time on the game, so i diabled it and tried again but it still crashed, then i just said then the video option, so i switched it to VGA and the game worked but froze again except in a later part, then i switched to Component and the game worked again but froze at the loading screen of city escape, SA1 worked great with minor graphical glitches, and Soul Calibur worked well untill i reached stage 7 against Nightmare and it  frozed, so if there is something i can do for SA2 thatd be great, i also tied the video thing in the Tab 4 but still froze before Title Screen...

**Comment by LoungeKatt** [comment]
Adding this to https://github.com/reicast/reicast-emulator/issues/594 since too fast and choppy audio are the same items mentioned there. In the future, please try to use a title that fits the issue.
