### ISSUE TITLE
Shenmue Hangs on Debug Version [d24e15d]

### ISSUE THREAD

**Issue by glac81** [reicast/reicast-emulator#599]
When watching the intro, game hangs when Ryo is talking to his almost dead father. Tried with dynarec on and off (with dynarec off it hangs event before, after Ryo enters the dojo). All other hacks were off too.
I have tested with r6 and it has worked past that point, but the graphics were way more glicthy.
My phone is a nexus 4 with andoroid 5 installed.

**Comment by LoungeKatt** [comment]
You may want to check #594 and #521 to make sure this isn't the same issue but a different game.
If neither sounds similar, please post a log.

**Comment by glac81** [comment]
It sounds pretty similar to #521, but different from #594. I haven't played other games with the same problems yet. Sorry, my mistake for not reading all the open issues. I looked only for Shenmue related problems.
Tech Romancer and Crazy Taxy last much longer so that   I haven't noticed this issue before. Only with Shenmue for now. And it does seem like a memory leak problem.

**Comment by LoungeKatt** [comment]
If it is like #521, chances are you won't see any signs in the log. That one seems to be a universal issue. I'm going to close this one for now with it referenced there. If it keeps happening after #521 is resolved, feel free to open it back up.
