### ISSUE TITLE
Soul Calibur glitch cx

### ISSUE THREAD

**Issue by XShadowX01** [reicast/reicast-emulator#600]
So I was playing Soul Calibur and Yoshimitsu's legs glitched cx just thought Id post about it, it really doesnt bother me, i think its funny, this only happens with him, with the exception of Inferno on Yoshimitsu's form I dont know if its just me but his legs just seem apart too. I took 2 screen shots of Inferno but there not good, not showing his legs i meen by that. Oohh, and im also on the release of 21-12-2014 because all the newones to date after that just wont boot SA2 to play.

![20150206224250](https://cloud.githubusercontent.com/assets/10568607/6090906/6ee7c302-ae54-11e4-8b19-f4635ee28b2d.jpeg)

![20150206225305](https://cloud.githubusercontent.com/assets/10568607/6090912/fef7d770-ae54-11e4-9d6c-4683c13950c3.jpeg)

![20150206225307](https://cloud.githubusercontent.com/assets/10568607/6090913/1112508e-ae55-11e4-8ace-5e945a35b910.jpeg)

![20150206225314](https://cloud.githubusercontent.com/assets/10568607/6090914/268e8112-ae55-11e4-97df-df45b952dece.jpeg)

**Comment by hooby3dfx** [comment]
Known issue, please close this.
Fix is under investigation.

**Comment by XShadowX01** [comment]
Oki dokkii /^-^

**Comment by LoungeKatt** [comment]
(#83)

**Comment by hooby3dfx** [comment]
And yes it is hilarious :)
