### ISSUE TITLE
Gauntlet Legends - stuck on title screen

### ISSUE THREAD

**Issue by tonyt900** [reicast/reicast-emulator#603]
I can get to the title screen of gauntlet legends and the game does not move forward. It does not seem to be frozen. What should I try?

**Comment by hooby3dfx** [comment]
What build are you using?

**Comment by tonyt900** [comment]
I'm sorry, I'm not 100% sure what you mean by build. I'm using: 
Guantlet Legends v1.003. 
Reicast r6. 
Phone: Galaxy Note 4.

**Comment by hooby3dfx** [comment]
The version of the app on the play store will not run that game.
It was fixed recently but the fix is not released yet to the store.

**Comment by gfig** [comment]
Gauntlet Legends: latest build # 2015-08-12 02:07:04 commit #71c2cb4 -- works fine until you get to the 2nd stage(portal) on first level area. I'm going to try and tweak some settings and see if anything works. 

Using Xperia Z3


![screenshot_2015-08-12-09-30-54 1](https://cloud.githubusercontent.com/assets/6752036/9227598/6d82e35e-40e2-11e5-9923-8b7ed2c7347f.png)
