### ISSUE TITLE
Fade-in and out not working in the widescreen

### ISSUE THREAD

**Issue by sergiobenrocha2** [reicast/reicast-emulator#608]
The extend sides in the widescreen does not follow the fade-in and fade-out from the 'original' screen (well, there is no fade for the sides), so sometimes you see the scenario already rendered in the sides, but in the center it's black yet.

Testing the master build e82d6a8 (2015-02-26) in android, samsung S4 mini (GPU: adreno 305), Sonic Adventure.

**Comment by neko68k** [comment]
If the game doesn't render offscreen like that, wide-screen mode will not
enable it to do so. This is part of the game, not the emulator.

**Comment by skmp** [comment]
I guess we could detect full screen fades somehow though

**Comment by tabnk** [comment]
This fade in/out issue also happened on other game such as Dead Or Alive 2, etc.

**Comment by skmp** [comment]
Closing this as there's no obvious way to resolve it. Widescreen mode is a hack, and some glitches are to be expected.
