### ISSUE TITLE
Add V-Sync Mode in Reicast - (Remove screen tearing or stuttering)

### ISSUE THREAD

**Issue by tabnk** [reicast/reicast-emulator#611]
Do consider adding V-Sync to Reicast, it will help us with higher end of android device to run reicast at it full speed without having screen tearing or stuttering,

**Comment by skmp** [comment]
I would guess EGL vsync's by default...?

**Comment by tabnk** [comment]
Is the ES GL V-SYNC same as nullDC PowerVR V-SYNC ?
![vsync](https://cloud.githubusercontent.com/assets/10874582/6633101/e986bd54-c97d-11e4-92d3-dcc38210501b.png)



From Mali ARM doc, it sound like the V-sync is not activate by default ?

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0555b/CHDDHGHBx.html

**Comment by kingosticks** [comment]
I was under the impression that eglSwapInterval controls vsync. And it's
enabled in the source (but not configurable). But it's historically often
ignored by mali firmware. It's certainly

**Comment by skmp** [comment]
VSync gets only set on pandora it seems. It doesn't look like any setting is applied for android, and just uses the OS default. Right @LoungeKatt ?

**Comment by tabnk** [comment]
Is it something we can do within android firmware setting to control the V-Sync?

**Comment by LoungeKatt** [comment]
@kingosticks eglSwapBuffer is buffer refresh rate -> https://www.khronos.org/registry/egl/sdk/docs/man/html/eglSwapInterval.xhtml

@skmp We do not alter the V-Sync at all on the Android side. We should investigate any warnings from Choreographer, though. http://developer.android.com/reference/android/view/Choreographer.html

@tabnk It isn't that simple. https://nayaneshguptetechstuff.wordpress.com/2014/07/01/what-is-vsyc-in-android/

**Comment by MrPsyMan** [comment]
Dreamcast also uses two frequency variations, 50hz and ~59.9hz (not 60). This means that tearing cannot be avoided either way.

I'm under the impression that the thread opener has reicast set at 50hz (probably default flash setting), therefore the tearing.

**Comment by skmp** [comment]
I digged a bit deeper. VSync should work automatically on android. We render whenever the OS tells us to, and I don't have any code that overrides this. @tabnk which version of android are you using? On which hardware? Stuttering can also be caused from the audio sync.

**Comment by tabnk** [comment]
Andriod OS 4.4.2 and (Samsung Note 3 and others).

**Comment by tabnk** [comment]
I'm will not exclude audio sync causing the issue. When playing game on reiicast, audio is always faster than the graphic.

**Comment by LoungeKatt** [comment]
VSync is configured in the kernel and monitored by Choreographer.  @tabnk Are you using a custom kernel or third party build, such as CM?

**Comment by tabnk** [comment]
Stock Galaxy Note 3 firmware. Dont have choreographer warnings.

**Comment by LoungeKatt** [comment]
If there are no warnings, that means it isn't getting held up. The downside is that not being held up means it is more likely what @MrPsyMan said with a 50Hz reicast trying to render in a platform-imposed 60Hz environment.

**Comment by tabnk** [comment]
Setting is NTSC and Dreamcast Logo is Red.  Reicast isn't 60Hz already ?

**Comment by skmp** [comment]
The renderer is async, should be able to handle this kind of variations
well enough.

**Comment by tabnk** [comment]
Btw, during in game 3D cut scenes the audio/music is always faster than graphic. In order words, audio/music completed before 3D graphic.

**Comment by davidgfnet** [comment]
What about VSync on linux? In my computer it goes at 120 fps at least :D Loading games takes half a second. Is it a Mesa related issue? I'm not sure whether reicast asks for vsync whenever it swaps buffers. Thanks!

**Comment by tabnk** [comment]
Never mind
