### ISSUE TITLE
recast not booting bios or games from sd card. crashes instead

### ISSUE THREAD

**Issue by thiskid12345** [reicast/reicast-emulator#612]
i have a samsung galaxy tab s 8.4. but i moved my bios and games to my sdcard and changed the directory. and restarted the app. but for some reason when i put it on the micro sdcard the games nor the bios dont load. i tried testing it on the latest dev build and on the r6 version on google play. is there any way i can solve this issue?

**Comment by LoungeKatt** [comment]
You can put the games on the external storage, but the BIOS needs to be stored in the internal. It is an issue with how Samsung links to the external storage.

**Comment by thiskid12345** [comment]
ohhhhh shooot thanks it works like a charm again now

**Comment by LoungeKatt** [comment]
Glad to hear you're back up and running. I would love to say it won't always be like that, but Samsung is one of the manufacturers trying to do away with external storage.

I am going to close this one, but you're welcome to open it up again if it stops working.
