### ISSUE TITLE
April team irc meetup?

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#618]
So, @MrPsyMan @LoungeKatt  @hooby3dfx @bwRavencl  @ptitSeb @angelXwind @neko68k how about we organize a meetup on #reicast?

Gotta organize r7 and a couple more things, and have fun :p

Thinks to talk about
- r7. WE NEED TO GET IT OUT.
- Handling crashes / etc
- App analytics?
- Testing (both automated, and via testers)
- Release cycles / procedures / whatever
- Cookies. Lots of them.
- Linux status (it works now, no jits)
- Fundraising (I'm really gonna go for it this month)
- Popcorn

Whatdya think? Sometime between 2-7 April ? I'm mostly available these dates (will be travelling 8-10, 21-23).

**Comment by skmp** [comment]
Actually, I think april 1st is the perfect date for r7, so I guess the release will have to come sooner than later. (nulldc v1.0.0 was released april 1st, 2007)

**Comment by hooby3dfx** [comment]
haha.
my take is that in order to ship r7 for android we would need to prioritize the stability issues and then verify across many devices/testers. we should have enough man power given the amount of reports. 
re: meeting next week is best for me. i volunteer to organize/track the issues, maybe in a shared private google doc sheet. we need to see what it will take to get the current latest code stable.

**Comment by hooby3dfx** [comment]
omfg yes https://huboard.com/reicast/reicast-emulator/

**Comment by skmp** [comment]
that DOES look sweet.

On Tue, Mar 31, 2015 at 5:16 AM, Bryan Barnes <notifications@github.com>
wrote:

> omfg yes https://huboard.com/reicast/reicast-emulator/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/618#issuecomment-87919187>
> .
>



-- 
~skmp

**Comment by hooby3dfx** [comment]
ok, i have loaded a few priority items up in there ;p

**Comment by hooby3dfx** [comment]
maybe we can do a screen share? also @LoungeKatt @skmp lets move any issues in trello to huboard.

**Comment by LoungeKatt** [comment]
I switched phones and forgot about Trello. I think everything I posted there was solved / forgotten

**Comment by neko68k** [comment]
I am available for maybe an hour or two on the first and second and most of
the day on the 6th and 7th.

**Comment by angelXwind** [comment]
I'm unavailable from 07:59 to 14:33 UTC-4 on 04/01, but other than that I should be fine with any other date.

**Comment by skmp** [comment]
6th looks like a strong contender!

http://doodle.com/i4q5hk5fec2vytf6 !

**Comment by skmp** [comment]
I'm inclined to go for monday 3am GMT. @LoungeKatt it works for you?

**Comment by LoungeKatt** [comment]
I have to figure out when that is but it should.

**Comment by LoungeKatt** [comment]
11 PM Sunday for me and @hooby3dfx. Yeah, that's fine for me.

**Comment by hooby3dfx** [comment]
thats actually 10 pm!

**Comment by hooby3dfx** [comment]
So reschedule?

**Comment by LoungeKatt** [comment]
Google: 3:00 AM Monday, Greenwich Mean Time (GMT) is 11:00 PM Sunday

**Comment by hooby3dfx** [comment]
yes i realized that :)
but that was still in the past and @skmp wasnt there!

**Comment by LoungeKatt** [comment]
Bet Google told him it was 4. Blame Google.

**Comment by skmp** [comment]
I ended up without internet at all for a couple of days. Re-schedule for next week? I'm available all days.

**Comment by hooby3dfx** [comment]
New doodle?

**Comment by skmp** [comment]
Meh, I suck at organizing, sometimes. April is gone.

**Comment by LoungeKatt** [comment]
I got drowned in the vr jam and would have missed it anyway, lol.
