### ISSUE TITLE
Shenmue crash..

### ISSUE THREAD

**Issue by stodag** [reicast/reicast-emulator#62]
Please fix the shenmue crash at the beginning, tried 3 different devices, same prob.

I'm requestin this as there's a guy by them name of cyclonmaster who compiled the latest source code/apk (of course I tested it) Seems the graphics are now OK(thx btw), but unplayable due to force close of the app, just after you walk outside. thx

If your aware of the then ignore this, this was just fyi.

**Comment by jacobmischka** [comment]
Thank you for the tip in turning off dynarec

**Comment by monkeyme5** [comment]
No problem buddy

Date: Tue, 6 Oct 2015 21:24:41 -0700
