### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#621]
The current master has lots of issues with Android TV.

After some short testing
- On first emulator startup, you have to configure the bios. After going on the browser, I can no longer start a game as the brower that opens only has "select folder". Only tested with no dreamcast images installed. This has also occasionally happened on my phone.
- I can't map the start button
- I can't map the analog (for RT/LT)
- I can't navigate the "ingame" menu using a joystick
- On my test device, there is some weird dithering going on
- I use dvi, speed limit doesn't work _unless_ I use the controller-headset port. I guess audio's not playing at all?

**Comment by vgturtle127** [comment]
I thought Android TV was more for things like Amazon Fire TV and the Razer Forge? You said you used it on your phone? Can you just compile it for any device like Android?

If so, I could probably help test via emulation and real hardware.

What is your test device, by the way?

You also said something about DVI, and the 3.5mm combo port? Do you mean HDMI or something? Sorry for all the questions, just clarifying.

**Comment by LoungeKatt** [comment]
@skmp I still haven't gotten the hardware, so I haven't been able to fix the issues yet. :/

**Comment by LoungeKatt** [comment]
~~On first emulator startup, you have to configure the bios. After going on the browser, I can no longer start a game as the brower that opens only has "select folder". Only tested with no dreamcast images installed. This has also occasionally happened on my phone.~~
  ("Only tested with no dreamcast images installed" - Srsly?! It can't find the non-existent file? NSS...)
I can't map the start button
I can't map the analog (for RT/LT)
~~I can't navigate the "ingame" menu using a joystick~~
  You have to assign the joystick to a port first, same as it's been for months
On my test device, there is some weird dithering going on
~~I use dvi, speed limit doesn't work unless I use the controller-headset port. I guess audio's not playing at all?~~
  Sounds like a DVI issue. It works fine with HDMI and DVI is not an Android TV connection.

**Comment by vgturtle127** [comment]
DVI doesn't support sound, either. So that's a problem. :laughing:

**Comment by LoungeKatt** [comment]
@vgturtle127 good point. Speed limit is tied to the audio, so that would explain it.

**Comment by vgturtle127** [comment]
@LoungeKatt I was gonna say, an odd thing to see on an Android device. :laughing:

**Comment by LoungeKatt** [comment]
Does mapping the start button mean the Dreamcast start button or that the hardware start button cannot be mapped to something? Which hardware was used?

It is possible that the Shield start button (which is now capacitive) may not return a key value and may need a motion detection.

**Comment by skmp** [comment]
@LoungeKatt with #1091 merged, what tasks need followup issues for this?

**Comment by LoungeKatt** [comment]
Good question. I don't know if enabling Android TV actually changed. If so, that. If not, it would fall into the rest of the Android umbrella.

**Comment by skmp** [comment]
@vgturtle127 HDMI and DVI are electrically compatible. There's also plenty of HDMI screens without audio support (eg, monitors). @LoungeKatt I can ship you one of the spare shields Keith sent me a couple of years back. I don't have an immediate use for all of them.

**Comment by LoungeKatt** [comment]
I have one of each lol.

**Comment by LoungeKatt** [comment]
It's supported. It's working. All that's needed would be to submit the required stuff on Google Play to get them to allow listing it. Other than that, Puffin Browser TV works pretty good to access the builds.reicast.com site and install that way.

**Comment by skmp** [comment]
@LoungeKatt do you have access to the android listing to try to fix it? I don't have the time to take a look at that right now :|

**Comment by LoungeKatt** [comment]
My email would have to be listed in Dev Console -> Settings -> Users & permissions
I would need at least Global "View app information" and then everything under RELEASE MANAGEMENT and STORE PRESENCE for just the app.

**Comment by AbandonedCart** [comment]
The support is there, so the issue need not be.
