### ISSUE TITLE
Cannon Spike violet screen

### ISSUE THREAD

**Issue by dayara** [reicast/reicast-emulator#628]
http://loungekatt.sytes.net:3194/ReicastBot/report/logs/1428124471898.txt

**Comment by blackman91** [comment]
Man this is one of the games I want to play so bad using reicast, such a good arcade game, it even has Mega Man as a playable character!
https://github.com/reicast/reicast-emulator/issues/898

**Comment by skmp** [comment]
Closing this in favor of #898
