### ISSUE TITLE
multiplayer (setting controller A and B)

### ISSUE THREAD

**Issue by masterfork** [reicast/reicast-emulator#631]
Hello friends,

First off, thanks for the amazing emulator!

I did post this issue in the Bug Reports forum on the website (http://forums.reicast.com/index.php?topic=1475.0). I've tried this in a few of the latest builds, but it seems as though I cannot assign a second player to a separate USB controller. Each time I attempt to assign controller B, it tells me that the device is already assigned. I have tried this with the Gamestop Red Samurai controllers, and with two Logitech F310s. In game, both controllers act as if they are player one (duplicate commands). 

This is on the MK808b plus android stick running Finless 1.1. I may be missing some critical info, please let me know if there is anything else I should provide. 

Thanks!

**Comment by LoungeKatt** [comment]
Is it only happening with two matching controllers? Or is it with one Red Samurai and one Logitech, too?

**Comment by masterfork** [comment]
So I tried that today, and I get some very odd behavior. When one logitech and one samurai are connected and assigned (successfully) - with all buttons mapped, everything appears to work normally (like in Marvel vs Capcom 2 - character select screen is no problem, Gauntlet Legends same thing) until I actually get in game. I've tried difference variations in the controller options (compatibility mode, etc), but using the d-pad or analog stick simultaneously seems to trigger some type of sticking in the code... It's hard to describe - none of the face or shoulder buttons do this. But if the directional controls are used simultaneously, they freeze up (one gets stuck to the left, for example, the other up). If left alone for a little while it seems to normalize, and if I don't touch the second controller, the first one acts normally. 

I'm doing this without any special IME, both are detected without issue in android.

**Comment by LoungeKatt** [comment]
That sounds like https://github.com/reicast/reicast-emulator/issues/562

It also sounds like the matching controllers may not be differentiated in the emulator. Whether that is an issue with the way Android is identifying them to the emulator or how the emulator is storing them will need to be verified to decide how to resolve it.

**Comment by masterfork** [comment]
Oh yes, I see, that does seem to be the same issue!

I am unsure if this is helpful in the least, but emulators which also suffer from the same issue include superretro16 and epsxe. There are a few emulators that seem to be able to differentiate between same-type controllers, such as mupen64 plus, snes9x, nostalgia.NES and I haven't had any sticking issues with multiplayer input. I'm just trying to be thorough and hopefully somewhat helpful!

Thanks again for the quick responses and the hard work on this emulator!
