### ISSUE TITLE
Propeller Arena (black sky)

### ISSUE THREAD

**Issue by dayara** [reicast/reicast-emulator#636]
Screenshot: https://www.dropbox.com/l/NFS02xi2S9i00hHjWsBmPp

Log: http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1428880225221.txt

**Comment by skmp** [comment]
@dayara can you re-test this?

**Comment by dayara** [comment]
Not yet.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#50
