### ISSUE TITLE
Non-CD Audio in Metropolis Street Racer Doesn't Play / Graphic Glitches in Demos

### ISSUE THREAD

**Issue by PeteBurgess** [reicast/reicast-emulator#65]
Metropolis Street Racer is completely playable however...
- non-CD audio doesn't play (engine noise, button press confirmation, etc.)
- In game demos (go to "Options", "Demos") graphics are hugely glitched. Doesn't really matter, but may as well report it whilst I'm reporting the audio.

**Comment by PeteBurgess** [comment]
Somewhere along the line the non-CD audio got fixed. Haven't been following the builds religiously but in the Android build I pulled yesterday from the build bot it's working fine.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#27
