### ISSUE TITLE
Booting BIOS from micro SD card crashes to home screen

### ISSUE THREAD

**Issue by Nospine** [reicast/reicast-emulator#653]
Ever since I bought the Nvidia Shield portable when it came out I've had issues with not being able to run the emulator. 

My Shield portable is running Android KitKat 4.4.2 and I'm
using a Sandisk Ultra 64GB Class 10 MicroSDXC formatted as NFTS.

Not too long ago I bought an Nvidia Shield Tablet and decided to install the emulato, only to be greeted by the same problem as my previous device.

I have the 32GB LTE Shield Tablet running Android Lollipop 5.0.1 and I'm using a Sandisk Extreme Pro 32GB Class 3 MicroSDHC formatted as FAT32.

Now, with all that out of the way... After fiddling around with my files and MicroSD card on the Shield Tablet I decided to move my reicast folder (which has the BIOS files it in) to the device's internal storage, and to my surprise, it's working perfectly now! This also holds true for the Shield Portable.

I know that the basic cause of this problem is the use of a microSD card, but I wouldn't be able to delve into the code to figure out why it happens.

Thanks.

**Comment by LoungeKatt** [comment]
It's a permission issue. You would need to root and modify the device.

**Comment by Nospine** [comment]
Thing is, I have FPse and My Boy! which are both emulators that need s BIOS file to be able to run, and they can boot it just fine from the microSD

Then again, I wouldn't know if that even matters, but I am aware that Android has been a tad wonky with SD card usage.

**Comment by LoungeKatt** [comment]
It depends if it only reads the BIOS or if it needs to interact with it. With reicast, there is a lot of stuff that happens in the same folder as the BIOS. With FPse, the BIOS is a read-only file.

The BIOS can be stored in the application files folder on the external (/Android/data/com.reicast.emulators/files or something similar), but that depends on whether all of the hassle is worth saving the 1 - 2 MB for the BIOS.

**Comment by AbandonedCart** [comment]
This has since been somewhat addressed and Android limitations more clearly documented.
