### ISSUE TITLE
Unreal Tournament won't render properly

### ISSUE THREAD

**Issue by ThEMarD** [reicast/reicast-emulator#659]
Heyyo, 

The problem I'm facing is with Unreal Tournament graphical bugs or rendering bugs. I'm using a OnePlus One running Cyanogenmod cm12.1 (based on 5.1.1).

On r6 from the Google Play Store? The game loads and works but has serious graphical issues with missing polygons. Menus load fine.

http://imgur.com/jTZgXUx

On r6 on a ci build from July 2014 I get a black screen. Menus load fine.

http://imgur.com/74hqDTv

On the latest ci build (5/18/2015) the menus do not load and in game is just a blue screen but audio tells me the game is still going.

http://imgur.com/4vbB7Je

I also have an HTC One M7 on 5.0.2 so I can also try that device as well later tonight.

**Comment by LoungeKatt** [comment]
Adding this on to the previous Unreal Tournament graphics report

https://github.com/reicast/reicast-emulator/issues/164
