### ISSUE TITLE
GPD Q9 GamePad LT & RT problem

### ISSUE THREAD

**Issue by franikku** [reicast/reicast-emulator#662]
Daytona USA for Dreamcast it's currently showing many graphical glitches running on last version of Reicast (downloaded from the official Reicast builds page). In older builds the game worked properly... some reason? My device is a GPD Q9, the latest version of GPD's Android console/tablet.

**Comment by LoungeKatt** [comment]
Is this a graphics or controller issue? It is labeled as one and described as the other.

**Comment by rrrh** [comment]
Please reopen if still an issue
