### ISSUE TITLE
License compatibility issue

### ISSUE THREAD

**Issue by coadde** [reicast/reicast-emulator#672]
Hi guys, i found a license compatibility issue in reicast code.
One of them is from main folder [https://github.com/reicast/reicast-emulator/blob/master/LICENSE] and another one from shell folder [https://github.com/reicast/reicast-emulator/blob/master/shell/LICENSE].

AFAIK, a 4-clause BSD license is a GNU-Incompatible license because contains the “obnoxious BSD advertising clause” [https://www.gnu.org/licenses/license-list.html#OriginalBSD], there's an article that explains about it [https://www.gnu.org/philosophy/bsd.html].

Therefore, it should be solved with a GPL-Compatible license [https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses] like the Modified BSD license (sometimes referred to as the 3-clause BSD license [https://www.gnu.org/licenses/license-list.html#ModifiedBSD]) or release all the code under a lax, permissive non-copyleft free software license.

**Comment by LoungeKatt** [comment]
It is fine posting to a very similar issue without requiring a new one.

**Comment by coadde** [comment]
ok, i'll post a new one without it then

**Comment by coadde** [comment]
Could you reopen this issue again?

**Comment by LoungeKatt** [comment]
Is there a reason it needs a new / open issue? 

@skmp handles licensing exclusively, so it is not something that can be addressed as a team.

**Comment by coadde** [comment]
@LoungeKatt the reason is the clause number 3 in the original BSD License text included in shell folder from reicast code [https://github.com/reicast/reicast-emulator/blob/master/shell/LICENSE#L11]:

```
3. All advertising materials mentioning features or use of this software
must display the following acknowledgement:
This product includes software developed by the reicast team.
```

The clause presented a legal problem for those wishing to publish BSD-licensed software which relies upon separate programs using the GNU GPL. It' s incompatible with the GPL, which does not allow the addition of restrictions beyond those it already imposes.

But if @skmp handles licensing exclusively and this issue can't be opened and / or create a new one because it isn't something that can be addressed as a team, should i send a email to @skmp instead? What is your suggestion to get a way to solve it?

**Comment by coadde** [comment]
Some minutes ago, i was checking all files in shell folder and i have paid attention there aren't code from it merging with the main code to be considered a license compatibility issue (just Makefiles and "ui specific" code). So, sorry for the incovenience.

**Comment by LoungeKatt** [comment]
It sounds like the only issue would be if you were intending to use the code from reicast in another application without specifically labeling it as such or releasing your own build of the application as something other than reicast. 

Even if the licenses are not identical, it is possible to license the core of an application and the wrapper or shell with a completely different license, so long as the more restrictive license were a child of the other licensed code or kept completely separate to prevent overlapping a more restrictive license with a less restrictive one. In this case, it only becomes more restrictive.

It is not that the issue cannot be opened or created, but rather if there was any purpose in it being an issue and not a direct email. After reading the other issue this was originally posted with, it should make sense why the license for the shell would include that requirement and why @skmp would now be handling those things directly. A previous application took the entire shell with minimal changes, renamed it, and then released it as a different app with no reference to reicast.

Android contains a lot of applications that are both BSD and GPL. Each part retains its original license by simply labeling the relevant parts with the relevant license. If something you are doing feels like it could create a legal issue, it is probably something you shouldn't be doing anyway.
