### ISSUE TITLE
Three Dreamcast Games That Have Emulation Problem

### ISSUE THREAD

**Issue by vus7294** [reicast/reicast-emulator#679]
I'm Newbie When is using a Dreamcast Emulator Reicast.
I've waiting for Reicast NAOMI Build, So I'll show some picture.
![screenshot_2015-07-01-19-53-44](https://cloud.githubusercontent.com/assets/13133961/8453163/b09569cc-202c-11e5-83bd-f232d66d99cf.png)
this is Silent Scope. My favorite gun shooting game. But LOL. scope is crashed. Nice. and Beautiful. This is One of emulation problem.
![screenshot_2015-07-01-19-54-54](https://cloud.githubusercontent.com/assets/13133961/8453177/ea4371e6-202c-11e5-9504-2e2831c18b56.png)
Street fighter 3 double impact. select a game(i've choosed new generation) and black screen. it's no freeze. sound is ok. but black screen and unplayable.
![screenshot_2015-07-01-19-55-41](https://cloud.githubusercontent.com/assets/13133961/8453197/27e0c35a-202d-11e5-8c7d-73f04b706041.png)
Three. Castle Shikigami 2. a LOW FPS. per 2 fps? unplayable. simple. emulation problem.

can you see the picture? my first post, and i hope naomi and atomiswave emulate in reicast. just hope.

**Comment by hooby3dfx** [comment]
Interesting, thanks for reporting and including screenshots.

Have you tried on another Android device?

**Comment by vus7294** [comment]
i only tested on GALAXY SIII LTE 4.4.4 and i don't have PC version ToT

**Comment by vus7294** [comment]
> Interesting, thanks for reporting and including screenshots.
> 
> Have you tried on another Android device?

i tested galaxy s3 lte 4.4.4. and i tested reicast version post on facebook.

**Comment by shinra358** [comment]
Add street fighter III double impact to the list. Bottom of the screen is chopped off and sprite layers are missing in-game.

**Comment by ManuTounu** [comment]
Hello ! I'm a french user of Recalbox (using Reicast) on PC x64.
I opened a post in the Recalbox forum about the problem in Silent Scope ("Scope Crashed").
And so, the admins of this forum sent me the link to your own post.
I would like to know if this bug can be resolved, because I love this game too 😉.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#72
