### ISSUE TITLE
Can't play while VMU on screen

### ISSUE THREAD

**Issue by Moonmadness** [reicast/reicast-emulator#681]
I can't use anymore neither my bluetooth controller nor on-screen controls when the VMU screen is on the top-right side of the screen. Obviously annoying when games require you to react to the VMU screen changes (like cham finding in Skies of Arcadia).

**Comment by hooby3dfx** [comment]
hmm i wonder if it gets focus... thanks for reporting this.

**Comment by LoungeKatt** [comment]
The menu shell probably still has focus after it's closed by popping out the window. The VMU window isn't given focus. I made sure of that while adding focus to the other popups.

**Comment by AbandonedCart** [comment]
Verified that this is working. Please reopen if you find it is not.
