### ISSUE TITLE
Feature request: change screen orientation

### ISSUE THREAD

**Issue by Moonmadness** [reicast/reicast-emulator#682]
It's pretty annoying that reicast switches to normal landscape mode by default when you start a game. I play with bluetooth controllers and it forces me to turn the phone upside down only for reicast, and it often leads to volume buttons randomly pressed.
I'm actually using apps to force reicast into reverse landscape mode but if you could at least choose your own screen orientation it would be cool.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/commit/20193681f0379942f64f1cf1d8b24fb804fe7331 should solve the issue without needing to add the mess required for custom orientation options.

**Comment by Moonmadness** [comment]
I thought you did it on purpose to avoid sensor orientation (for any reason whatsoever), but that works as well :)

**Comment by LoungeKatt** [comment]
At the time it was set, sensor flags weren't supported because the emulator still supported GB.
