### ISSUE TITLE
[Request] Map function to controller

### ISSUE THREAD

**Issue by Moonmadness** [reicast/reicast-emulator#683]
I think it would be nice if you could map fast-forward/turbo toggle to a button of your controller instead of having to bring up the menu each time. You could do the same for other functions too, like frameskip or savestates if they will be there one day.

I also noticed that I cannot exit the in-game menu with the menu button anymore. I have to go back to the main menu and press start to close it (in the submenus like Debug etc nothing happens at all with any button whatsoever).

**Comment by LoungeKatt** [comment]
Mapping debug functions means losing those buttons for the emulator. It would end up causing more confusion than anything.

The menus were linked together to reduce the number of items in each menu. 

I am not sure what you mean by nothing happening with any button. You open the menu and either tap an option or navigate with the direction pad and use X / A / whatever the hardware select button is on your controller to select an item. It is not intended to be part of playing a game. They are "emergency" options and testing features.

**Comment by LoungeKatt** [comment]
If I am following what you are trying to say, https://github.com/reicast/reicast-emulator/pull/684 should resolve the issue or at least let you quit the debug menu from a submenu.

**Comment by AbandonedCart** [comment]
Closing this, as it would cause more instability than functionality and the included issue has been solved.
