### ISSUE TITLE
Android TV support and publishing

### ISSUE THREAD

**Issue by LoungeKatt** [reicast/reicast-emulator#685]
I believe I have added everything that was missing for the app to meet all of the publishing requirements of Android TV, so now all that should be required are screenshots. The banner for the app should be the same as the one used in the listing and the leanback intent should qualify it under the "Pricing & Distribution" tab.

Do we need new screenshots or are we resizing the ones already used for phones?

This should be ready to release alongside r7 and should cover most of the requirements to support also releasing it on the Shield store. https://devconsole.nvidia.com/User/Create

**Comment by mk8itra1n** [comment]
Any ETA on r7? Drkraziel said something about mid June but that passed by so I'm wondering when r7 will be released?
