### ISSUE TITLE
Lots of Rez issues on Fire HD 6

### ISSUE THREAD

**Issue by LotadTheGreat** [reicast/reicast-emulator#687]
Okay. Rez is a really good (and sadly not very known) game, and it seems to be the only game on this emulator to have multiple bugs/issues. I'll list the ones I've found: 
·The effect where it distorts the screen a bit (used whenever you go to the next layer level for a second) or any fading effect has this really glitchy picture filling the screen whenever those effects happen. This is probably the least important bug.
·Lines disappearing. So whenever you have a lot of lines on the screen at once (like the later parts of Area 1-3 and most of Area 4) the lines/wireframes disappear. I have no clue why this is happening, but I'm guessing it's line overload.
·Here's the big one. The game is VERY glitchy in Area 5. Like random flashing blue and white polygon barf, stuttering, and a crash very early in the level. Once you pass through the second Gate of Truth, the game's video stutters, but the audio goes fine (it even receives button input). Sometimes you will get a few seconds of polygon barf. Sometimes you will get normal video for a split second. But either way, it crashes, making the game unbeatable. Which doesn't mean it's the best (which in any other case I would be saying it like that), but that you literally can't beat it.  

Here are the logs. I don't know what's in them.
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1436247847237.txt

**Comment by twinaphex** [comment]
The really glitchy picture you get is because of the lack of RTT in the GL renderer. With reicast libretro I at least implemented this and made it a toggleable setting.

Anyway, even with that, there are still random crashes in Rez.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#46
