### ISSUE TITLE
missing new line character when load a button.png on linux (log in console)

### ISSUE THREAD

**Issue by sl1pkn07** [reicast/reicast-emulator#688]
Hi when launch reicast on linux, in console show this line:

    OSD: 6
    Error opening /home/sl1pkn07/.reicast/data/buttons.pngInvalid GD-DMA start, SB_GDEN=0.Ingoring it.
    VREG = 03 ARMRST 00

seems like missing a new line character

to fix this need add in line https://github.com/reicast/reicast-emulator/blob/master/core/rend/gles/gles.cpp#L1886 a new line character, like

		printf("Error opening %s\n", filename);

then now show that line like:

    OSD: 6
    Error opening /home/sl1pkn07/.reicast/data/buttons.png
    Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
    VREG = 03 ARMRST 00

i'm not sure if is a good fix. but working.

greetings

**Comment by LoungeKatt** [comment]
Pretty sure that was a typo, since most of the other printf commands do have a newline.

**Comment by LoungeKatt** [comment]
Here is a pull with the change - https://github.com/reicast/reicast-emulator/pull/689

**Comment by skmp** [comment]
Fixed in 115ee47efc71fecbbed0ac6cc5c17aac09169e22
