### ISSUE TITLE
nexus 7 (2012) tegra 3 android 5.1.1

### ISSUE THREAD

**Issue by publicorderkeeper** [reicast/reicast-emulator#696]
I have a very unpleasant problem on my nexus 7.Grandia 2 v 1.001 has awful texture flickering and squares istead of shadows. It looks like all model is cut in half. This version of the game was tested on mali 400 and it is worked fine. Hope on your feedback. I really love dreamcast and hope that that bug will be fixed soon)

**Comment by publicorderkeeper** [comment]
If only someone fix this problem or am I hopping for nothing...

**Comment by Holzhaus** [comment]
So the game was working fine at some point? You can try to [bisect the issue](http://webchick.net/node/99) and find out what commit broke the game.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
I don't quite sure what you mean... I have awful graphic bugs on my tegra 3 and It is not working fine at any point.

**Comment by publicorderkeeper** [comment]
And more interesting thing: shenmue works well(as well as it works on other devices wit mali, power vr etc.) unlike grandia 2. By the way, awful graphic glithes I have in game skies of arcadia too.

**Comment by skmp** [comment]
@rrrh mind leaving a comment withn the reasoning when closing tickets? This one is obviously old and osbolete, but leaving reasoning makes it easier to track the issue trail a few years down the line

**Comment by publicorderkeeper** [comment]
It is too bad that this issue hasn't been fixed. I've been waiting and hoping till this very moment...
