### ISSUE TITLE
[Linux] Reicast crash

### ISSUE THREAD

**Issue by mac1202** [reicast/reicast-emulator#698]
Hi trying to run reicast on manjaro x86_64 because I read that the linux got a lot of improvement. Unfortunately I got the same result that when I try several month ago, reicast crash.
I use the reicast-git version available on arch linux user repositery. Here's the output of terminal : 

    Home dir is: /home/mac/.reicast/
    Personality: 00000000
    Updated personality: 00000000
    Linux paging: 00001000 00001000 00000FFF
    evdev open: No such file or directory
    MAP 00800000 w/ 25165824
    MAP 20000000 w/ 25165824
    MAP 04000000 w/ 16777216
    MAP 06000000 w/ 16777216
    MAP 0C000000 w/ 0
    A8
    vmem reserve: base: 18740000, aram: 38740000, vram: 1C740000, ram: 24740000
    Resetting mem
    Mem alloc successful!Using 'Téléchargements/Shenmue_PAL_DC-DCP/cd1/2003-11-23-Shenmue-cd1-pal-DCP.cdi' as cd image

    Malformed entry on config - ignoring @ 36(ElfFile)
    Found 4 matching FB configs.
    Chosen visual ID = 0x21
    Loaded /home/mac/.reicast/data/dc_bios.bin as bootrom

    Loaded /home/mac/.reicast/data/dc_flash.bin as nvram

    Using Recompiler
    Auto-selected audio backend "alsa" (Advanced Linux Sound Architecture).
    Initializing audio backend "alsa" (Advanced Linux Sound Architecture)...
    recSh4 Init
    Freeing fpcb

             CodeCache addr: 0x49e000 | from: 0x49e000 | addr here: 0x49cb20
    GL context version: 3.3
    OSD: 6
    Error opening /home/mac/.reicast/data/buttons.png

    Session 1 has 2 track(s)
    Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 451     LBA: 0
    Track position: 352800
    Saving  Track:  2  Type: Audio/2352  Pregap: 0    Size: 615     LBA: 601
    Track position: 1413552

    Session 2 has 1 track(s)
    Saving  Track:  3  Type: Mode2/2336  Pregap: 150  Size: 325062  LBA: 12466
    Track position: 3210432
    gdrom: Opened image "Téléchargements/Shenmue_PAL_DC-DCP/cd1/2003-11-23-Shenmue-cd1-pal-DCP.cdi"
    Initialising empty vmu...
    Initialising empty vmu...
    Sh4 Reset
    cntx // fpcb offset: -67371008 // pc offset: -184 // pc A0000000
    Get MemPtr unsupported area : addr=0xA0000000

    Unimplemented opcode: 00000800 next_pc: A0000016 pr: 00000000 msg: Unknown opcode
    Fatal error : iNimp reached

     in cpu_iNimp -> ../../core/hw/sh4/interpr/sh4_opcodes.cpp : 66

    [1]    29065 trace trap (core dumped)  reicast

I got the same output if I launch it without a game. Am I doing something wrong ?

**Comment by sergiobenrocha2** [comment]
Maybe it's related to #706 ?

It's working here, built for amd64 (xubuntu 14.04), tested with sonic adventure

**Comment by RicardoASilva** [comment]
I have the exact same issue with the same console output with the raspberry pi 2 version, i tried from the retropie setup script and installing from the git source and have the same problem with either.

**Comment by skmp** [comment]
It looks like your bios is corrupted/ wrong

**Comment by mac1202** [comment]
Yeah that was the problem thanks for helping.
