### ISSUE TITLE
Shenmue 2 Crash

### ISSUE THREAD

**Issue by rica32** [reicast/reicast-emulator#707]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1438050110401.txt

**Comment by skmp** [comment]
Huh, that is a quite interesting crash. Build number? What triggers the crash?

**Comment by rica32** [comment]
Happens when arrive at aberdeen/and when pass for Worker´s Piers/and even when that guy challenge for a game...
I have the build from the 2015-07-27 day.
I just could slip past aberdeen and get into that challenge because I set "Dynarec" OFF. (It lags so much, but at least i could get there :P )

Sorry for my bad english, I´m Portuguese :) (and ricardo11943 from twitter, xd)

**Comment by skmp** [comment]
Thanks for the report. Can you upload a savegame somewhere so we can test from that point? (Google drive or dropbox will work)

**Comment by rica32** [comment]
Sorry, but whats the file format ? Or name ?

**Comment by rica32** [comment]
Here ! https://www.dropbox.com/sh/aiablkoos0f7k1t/AABfvWMhAMSpTEkKqXXNXuA7a?dl=0
I didn´t know that we can upload our VMU for cloud :D
(My Device is a 1Life Smart Sky 4.5 Dual Sim ;) )

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#44
