### ISSUE TITLE
Seaman broken after update

### ISSUE THREAD

**Issue by zadarren** [reicast/reicast-emulator#711]
Hi,

One of the recent updates has caused graphical errors in seaman - loads fine but colour glitches when switching to food inventory screen.  Not sure which update caused this - it used to work almost perfect bar some wire frame showing but now its in playable.

**Comment by skmp** [comment]
That's quite interesting. Can you get a screenshot of it?

**Comment by zadarren** [comment]
Had to factory format my device - shield tablet - using latest build, problem still persists.
![20150729171214](https://cloud.githubusercontent.com/assets/13546177/8962915/3a0f9b98-3615-11e5-9f2b-fe32d0522ad4.jpeg)
![20150729171202](https://cloud.githubusercontent.com/assets/13546177/8962916/3ecbb31a-3615-11e5-96a1-33441229e4a8.jpeg)

**Comment by skmp** [comment]
Just to make sure this isn't some android upgrade, can you try w/ r6 just to make sure it still works as expected there? (And also upload a correct screenshot!). I don't recall doing any major changes the past months on rendering, but so many things have been done so...

**Comment by hooby3dfx** [comment]
also happening on shield portable (4.4.2) as well with the latest reicast build.

**Comment by hooby3dfx** [comment]
fyi i will cry if this stays broken ;p
http://forums.reicast.com/index.php?topic=1548.0

**Comment by skmp** [comment]
Maybe we can bisect it? It is just visual glitches?
Am 28.08.2015 07:16 schrieb "Bryan Barnes" <notifications@github.com>:

**Comment by LoungeKatt** [comment]
There should be seamen all over the screen...

**Comment by hooby3dfx** [comment]
Giggity

Yes just visuals, 3d objects have this weird wireframe shading effect.

I'll attempt a bisect.

**Comment by skmp** [comment]
![motivate-the-truth-dcemulation](https://cloud.githubusercontent.com/assets/393266/9546369/6d80fc94-4d92-11e5-93af-592922cdb527.jpg)

**Comment by zadarren** [comment]
Went on holiday for a few weeks so had some time to play with my semen, literally every build is the same 😮 the wireframe effect dosent distract too much from the game really, but the visual 2d stuff is a game breaker...

**Comment by zadarren** [comment]
Issue still persists on latest build.....any news?

**Comment by hooby3dfx** [comment]
We need to find the build where this broke.

You can help by picking an older rev from the build bot that doesn't have
the bug, and then skip a few revs to find the one that added the bug. Then
just narrow down to the exact version.

**Comment by Holzhaus** [comment]
`git bisect` can be of help here.

**Comment by blackman91** [comment]
So is this ever going to get fixed? Seaman is perfect for mobile.

**Comment by blackman91** [comment]
It seems this bug is not present in stable r6 from the playstore. Can anyone else confirm? BTW I cloned the stable r6 so that anyone can install it alongside the r7 dev builds without issues:
https://www.mediafire.com/file/ppdm7y5d25dkrp5/reicast_r6_r6.apk/file

**Comment by LoungeKatt** [comment]
That is the exact purpose of the purple "Regression" tag.

**Comment by blackman91** [comment]
Also in latest r7 beta from here https://github.com/reicast/reicast-emulator/issues/1208 this bug happens:
![screenshot_20180710-015808](https://user-images.githubusercontent.com/6578180/42494157-0b41d030-83e5-11e8-9291-f8bc77d5f693.png)

The text is not visible in the sign like in stable r6:
![screenshot_20180710-014016](https://user-images.githubusercontent.com/6578180/42494196-2408635e-83e5-11e8-9a95-59c40e405ece.png)

**Comment by skmp** [comment]
@blackman91 can you please collect all information we have so far and make a new ticket in https://github.com/reicast/gamedb/issues? Thanks :)

**Comment by blackman91** [comment]
Sure:
https://github.com/reicast/gamedb/issues/9

**Comment by skmp** [comment]
Alright, closing this then
