### ISSUE TITLE
Auto-assign first controller

### ISSUE THREAD

**Issue by AbandonedCart** [reicast/reicast-emulator#725]
I recently purchased the NES30 Pro (8bitdo) and it is plug and play with reicast, once it is assigned to the first port. A lot of controllers, such as Moga, the Shield controller, etc, are already configured to work out of the box. It seems like it would be convenient to check for the number of available controllers and if it is only one and is supported by an existing profile, assign it to the first port (unless otherwise set by the user). Any reason not to do this?

**Comment by skmp** [comment]
This sounds good @LoungeKatt

**Comment by AbandonedCart** [comment]
I'm somewhat sure this is implemented or will be as part of the next set of changes.
