### ISSUE TITLE
Nvidia Shield Portable, kitkat 4.4.2, reicast r7, dc_boot.bin... Nothing loading

### ISSUE THREAD

**Issue by tnap1979** [reicast/reicast-emulator#726]
So I have a shield portable, I've been holding off on the official lollipop update due to some app incompatibilities.. But my current issue with reicast is that no matter where and what.. Its not loading or locating the bios files.. I have stored multiple copies of the bios files in multiple places to aid in the loading.. But reicast is still not loading.. Any idea's??

**Comment by LoungeKatt** [comment]
Are they on the internal sdcard and not an external?

**Comment by tnap1979** [comment]
Yes, I have them stored in sdcard/dc/data/ also in Android/data/com.reicast.emulator/
Also in sdcard/emu/bios/dc/

**Comment by tnap1979** [comment]
See, I didn't buy my shield portable for its intended purpose.. I bought it strictly as a portable emulation system.. Dreamcast so far is the one emulator I haven't gotten success in.. All my other new and SNES and GBA and all those work, hell even retroarch works

**Comment by hooby3dfx** [comment]
i also bought the shield portable for this very reason but hadn't had
issues with r5/r6 running on it. can you use the stable version?

**Comment by LoungeKatt** [comment]
You may also want to try a new copy of the BIOS. If it isn't locating it, that may be a corrupt file. Is it named correctly?

**Comment by tnap1979** [comment]
OK, so I've finally gotten it all working :-)
After trying 4 Diff reicast apks, and about 7 Diff copies from Diff sources for bios..
Finally booted bios, configured vmu, and test loaded marvel vs capcom 2, everything's smooth and playable minus a varying levels of sprite glitches in the characters, but its still fully playable, and makes me remember the true gaming days :-)

**Comment by tnap1979** [comment]
I'm about to collect my sources and post them here for other reicast shield combo users

**Comment by tnap1979** [comment]
OK, so here is what I followed
HTTPS://WWW.YouTube.com/watch?v=g8cKeJcwgXw

I used his apk linked in video, and his bios package, copied the mentioned 3 bios files, installed apk
Moved the bios files to (internal) sdcard/DC/data/, pointed reicast to sdcard/roms/dreamcast/
Launched reicast, loaded bios, configured time to 5 min before my real time,
Wiped vmu 1&2 and formatted and loaded back to main DC bios screen,
Exited reicast, rebooted shield, wiped dalvik and cache,
Rebooted, relaunched reicast, launched "marvel vs capcom 2.cdi" and VOILA!!
Finally.. Respective dreamcast emulation on my shield portable...
I'm back in happy emulation land again but portable instead of desktop
I hope my experience helps others get going with shield portable and reicast

**Comment by LoungeKatt** [comment]
You might not want to be so detailed in your description. It is illegal to obtain your BIOS anywhere other than your own console.
