### ISSUE TITLE
Sonic adventure 2 

### ISSUE THREAD

**Issue by paulaz2** [reicast/reicast-emulator#735]
Sonic adventure 2 force close on stage 3 on infinix hot x507

**Comment by Holzhaus** [comment]
We won't be able to fix that bug without any log files.

**Comment by skmp** [comment]
Also a savegame would be helpful. We need to automate that part on a "report-a-bug" part on the reicast site methinks... More of a reason to dedicate time to the project

**Comment by skmp** [comment]
Closing this as it doesn't have enough information. Please test with #1208 and report there / open a gamedb issue. Thanks.
