### ISSUE TITLE
Fix input on rpi2

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#737]
_note to self_

**Comment by Holzhaus** [comment]
Did commit 990470e19a6a0e0801c1ba274b1cbc86f29b171c fix this? Can I close this issue?

**Comment by Holzhaus** [comment]
Possibly related: While testing PR #720, I noticed that input on the ODROID feels clunky with an XBox 360 pad. Playing [Incoming](https://www.youtube.com/watch?v=izu9KeR-llQ) is almost impossible, since you can't hold the fire button (thus need to press it repeatedly).

**Comment by skmp** [comment]
I tried to quick fix it, but I think it needs more thinking, so let's leave
it open. Input has always been such a huge problem on nulldc/reicast -.-

On Tue, Aug 11, 2015 at 7:21 PM, Jan Holthuis <notifications@github.com>
wrote:

> Possibly related: While testing PR #720
> <https://github.com/reicast/reicast-emulator/pull/720>, I noticed that
> input on the ODROID feels clunky with an XBox 360 pad. Playing Incoming
> <https://www.youtube.com/watch?v=izu9KeR-llQ> is almost impossible, since
> you can't hold the fire button (thus need to press it repeatedly).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/737#issuecomment-129977531>
> .
>



-- 
~skmp

**Comment by skmp** [comment]
Closing as part of ticket cleanup. Please report in chat.reicast.com if still an issue
