### ISSUE TITLE
Unreal tournament 

### ISSUE THREAD

**Issue by paulaz2** [reicast/reicast-emulator#741]
Unreal tournament shows graphic bugs on in game on infinix hot x507

**Comment by LoungeKatt** [comment]
Is your issue already covered in https://github.com/reicast/reicast-emulator/issues/90 or https://github.com/reicast/reicast-emulator/issues/164? If so, please close this one and add any details you may have to one of those. If not, can you describe what the bugs look like? Is it missing parts, tearing, distortion, or something else?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#74
