### ISSUE TITLE
Crashing to desktop when you enter a battle on Note 4 (Grandia II)

### ISSUE THREAD

**Issue by MrYoso** [reicast/reicast-emulator#749]
I am using a Note 4 N910c with 5.0.1 Lollipop OS installed. This is non-root.

I am also using the default config of the emulator.

I've tried running Grandia II on the latest build and it boot fine. Only problem on my part is whenever a battle starts, the emulator will crash to the menu of the phone. This always happen on my part. I do not have any problems with the other games I've tried. Only this game gives me the crashing problem. I did not encounter any crashing back when I still use the R6 build working on lollipop.

**Comment by LoungeKatt** [comment]
Can you provide a log of when it crashes? If it doesn't prompt you to send one, there is a menu option to get one. It is the last option in the list.

**Comment by MrYoso** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1439624860429.txt

**Comment by skmp** [comment]
Please test and follow up in #1208. Thanks.
