### ISSUE TITLE
Regession introduced in commit 417dfc5

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#750]
Commit 417dfc5d8f3396a3b5035b2ba0164c4aa3e14b78 broke ODROID support.
Last working commit was 7ec1a12580da2e3e7d195f4bb1be31b1843cc5b2.

Compilation works fine, but reicast always crashes:
http://pastebin.com/JGKzMgCS

**Comment by Holzhaus** [comment]
I get compilation erros, so I can't bisect further.

**Comment by LoungeKatt** [comment]
Looks to be the same crash I get on iOS. I couldn't verify when it started because it wouldn't build until that last commit for it. EXC_BAD_ACCESS code 2 happens at the same spot, though.

**Comment by Holzhaus** [comment]
Strange, I updated [some packages](http://pastebin.com/0Q8gha4p)
and now it works. It's not that the previous version were old - i usually update at least once a week.

**Comment by skmp** [comment]
This happened because of some wrong offsets on the asm files. A full rebuild with master should fix the issue

**Comment by skmp** [comment]
We don't generate dep files for the makefiles so sometimes old stale code lingers...

**Comment by LoungeKatt** [comment]
@skmp I was having issues with the ngen asm, but that was sorted out with that HUGE move of everything. I have a feeling it is a different issue I had, but close in proximity to the same process. I did a clean after moving everything, so there may still be an issue with iOS.

**Comment by skmp** [comment]
This should be fixed on master, after f83130b84ba6353c72a7400c8a304f382d84eca2. @Holzhaus can you verify and close?

**Comment by Holzhaus** [comment]
@skmp As I said, it works for me since 5 days ago. Your fix looks like something MacOS/iOS-specific, so maybe @LoungeKatt can be of help, since I don't own any Apple devices.

**Comment by skmp** [comment]
This is fixed :)
