### ISSUE TITLE
[Linux] VMU files are always full

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#758]
The VMU is always reported to be full. Unfortunately, this makes it impossible to save any game. Is this a bug or just not implemented yet?

**Comment by LoungeKatt** [comment]
It happens from time to time on Android. Have you tried going through the BIOS and formatting the VMU like it were actual hardware?

**Comment by Holzhaus** [comment]
No, I'll try that tomorrow. Thanks.

@skmp I guess there's no easy way to format them when creating the files?

**Comment by skmp** [comment]
It should already be done. On the source there's a minimal formated vmu
hardcoded (as 100 bytes or so zlib'd).

On Mon, Aug 17, 2015 at 4:19 AM, Jan Holthuis <notifications@github.com>
wrote:

> No, I'll try that tomorrow. Thanks.
>
> @skmp <https://github.com/skmp> I guess there's no easy way to format
> them when creating the files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/758#issuecomment-131659252>
> .
>



-- 
~skmp

**Comment by LoungeKatt** [comment]
@skmp I notice on a fresh install that works. The "time to time" is if I update the build and don't clear the cards first, but even then it isn't consistent.

**Comment by Holzhaus** [comment]
Just tested. It works when resetting the VMUs in BIOS. Thanks a lot.

Can I close this?

**Comment by LoungeKatt** [comment]
@Holzhaus Glad that worked, but not long before you arrived @skmp was trying to get around needing that step. @skmp perhaps it isn't being copied the same way as it is on Android?

**Comment by Holzhaus** [comment]
OK, I'll reopen then ;-)

**Comment by LoungeKatt** [comment]
Haha, fair enough. I'll see if I can spot the "one of these things that's not like the other.. :musical_note:"

**Comment by sergiobenrocha2** [comment]
Same problem here, I had to erase them in the bios.

**Comment by AbandonedCart** [comment]
Yes

**Comment by baka0815** [comment]
If I understand that right, the problem is, that the empty VMU needs to be formatted throught the BIOS instead of being directly usable, right?

**Comment by MasterGamingYT** [comment]
Yes

**Comment by AbandonedCart** [comment]
I believe that issue was solved. The issue was that when updating to a new version, you had to "eject" the VMU before the update or it would corrupt.

**Comment by baka0815** [comment]
Ok, found the bug.
I'm going to prepare a PR.
