### ISSUE TITLE
[Soul Calibur] Broken font rendering in Main Menu

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#759]
The fonts in the main menu look broken:

![Soul Calibur Main Menu](http://i.imgur.com/iDHLhQ5.png)

Using latest upstream commit https://github.com/reicast/reicast-emulator/commit/a90a2cf91c1f2329ae5ea182d7283a3825ce1133 on Linux x86_64, but this also happens on my ODROID-C1.

**Comment by LoungeKatt** [comment]
Still looks better than it did on my old TV

**Comment by meveric** [comment]
It's not only in the menu, also in game.. And on the mission map and so on.
Happens also on the ODROID-U3 as well as ODROID-XU3..

**Comment by skmp** [comment]
@Holzhaus on what hardware? It renders okay here

**Comment by randomstuff** [comment]
I have the same graphic glitches here on Linux x86_64.

**Comment by ptitSeb** [comment]
I also have the same broken fonts on the Pandora.

**Comment by skmp** [comment]
Urf, perfect, yet another of those issues I cannot reproduce -.-


On Mon, Aug 24, 2015 at 11:03 AM, ptitSeb <notifications@github.com> wrote:

> I also have the same broken fonts on the Pandora.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/759#issuecomment-134103062>
> .
>



-- 
~skmp

**Comment by Holzhaus** [comment]
My Laptop specs: http://pastebin.com/FN1atZ1j
Hardware specs of the ODROID C1 can be found [here](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G141578608433).

**Comment by necrosisbb** [comment]
I built reicast last night from head on opensuse 13.1 x86_64 (though need to apply the recent linux compilation fix) and tested with soul calibur and get exactly the same font issue as noted here. Just to say I can grab any additional logs and hardware info tonight for you guys to assist with this bug if that helps.

**Comment by vretro** [comment]
Issue present on Raspberry Pi2

**Comment by philenotfound** [comment]
Have it too, Linux x86_64 with radeon (HD5450)

**Comment by twinaphex** [comment]
It happens with certain TV types, I don't remember which but if you set TV type to either RGB or VGA then it will output the graphics fine.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#64
