### ISSUE TITLE
[Linux] X11 window doesn't resize properly

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#761]
Currently, x11 window resizing isn't implemented yet.

I'm able to catch window resize events and query the new size of the window, but since I don't have any OpenGL experience, I don't know how to make the video output fill the new window size.

**Comment by Holzhaus** [comment]
Here's a patch for the holzhaus/linux-input-overhaul branch:
http://pastebin.com/5V51L1vd

What works:
- Press F11 to toggle fullscreen
- Resizing windows by dragging corners, changing the WM tiling, double-clicking the window title bar or toggling fullscreen
- Print the new size when the window has been resized

But the window content stay the same.

**Comment by skmp** [comment]
I'd expect to need a new glViewport and to update the X/Y from the emulator side. I'll check

**Comment by skmp** [comment]
Try adding a `glViewport(0, 0, screen_width, screen_height);` after gl_swap in https://github.com/reicast/reicast-emulator/blob/648710950762d3b0facf137ab8301c5b750d1763/core/rend/gles/gles.cpp#L1864 and see if it fixes thing. Window size should be updated on every present if [this code](https://github.com/reicast/reicast-emulator/blob/648710950762d3b0facf137ab8301c5b750d1763/core/rend/gles/gles.cpp#L630) works
