### ISSUE TITLE
Reios crashing on Linux

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#799]
While testing #798, I experienced reios crashes.

Here's the output and GDB backtrace: http://pastebin.com/wakANfSQ

Using latest upstream/master version and deleted/moved `~/.reicast` before starting reicast.

**Comment by skmp** [comment]
Reios only supports booting a game ot elf, not booting to 'bios'
Am 22.08.2015 19:07 schrieb "Jan Holthuis" <notifications@github.com>:

**Comment by skmp** [comment]
Let's close this as it's not an issue, but a feature atm

**Comment by Holzhaus** [comment]
Can we print an error message that an image is needed instead of just crashing?

**Comment by skmp** [comment]
It actually does that, via msgboxf, which just printfs instead of showing a
linux error dialog

On Fri, Aug 28, 2015 at 3:05 PM, Jan Holthuis <notifications@github.com>
wrote:

> Can we print an error message that an image is needed instead of just
> crashing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/799#issuecomment-135769003>
> .
>



-- 
~skmp

**Comment by skmp** [comment]
See https://github.com/reicast/reicast-emulator/blob/master/core/reios/reios.cpp#L572 and https://github.com/reicast/reicast-emulator/blob/master/core/reios/reios.cpp#L580. It doesn't gracefully recover after that, but the termination of the app is always crashtatic right now... the JIT has no clean way to exit (so, this is a larger scope problem)

**Comment by skmp** [comment]
Msgboxf handling on linux is [main.cpp:55](https://github.com/reicast/reicast-emulator/blob/master/core/linux-dist/main.cpp#L55). On windows it is a simple messagebox ([winmain.cpp:163](https://github.com/reicast/reicast-emulator/blob/master/core/windows/winmain.cpp#L163)). Android shows an alert of toast.

**Comment by skmp** [comment]
I don't know if linux has a common enough mechanism to show a simple message dialog though

**Comment by Holzhaus** [comment]
I was actually working on a GUI (using wxwidgets), but I didn't manage to get the GL parts running (presumably because stuff is in another thread). I can push them to a branch if you want to have a look.

**Comment by skmp** [comment]
I think SDL makes more sense than wX -- wX is effing huge (and we don't
really need complicated UI). What's your take on SDL? :p

On Sat, Aug 29, 2015 at 2:02 PM, Jan Holthuis <notifications@github.com>
wrote:

> I was actually working on a GUI (using wxwidgets), but I didn't manage to
> get the GL parts running (presumably because stuff is in another thread). I
> can push them to a branch if you want to have a look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/799#issuecomment-135976506>
> .
>



-- 
~skmp
