### ISSUE TITLE
In appveyor buildbot doesn't present build result (*.zip with *.exe etc).

### ISSUE THREAD

**Issue by ofry** [reicast/reicast-emulator#800]
For sample, https://ci.appveyor.com/project/skmp/reicast-emulator/branch/master/job/l0ul3u5ydwy91af0/artifacts

The build job does not contain any artifacts.

**Comment by ofry** [comment]
Thanks.

**Comment by Holzhaus** [comment]
I'll write some api parser to add the URLs to the reicast ci builds page.

**Comment by Holzhaus** [comment]
Damn, that doesn't work. AppVeyor doesn't have a JSONP API.

**Comment by skmp** [comment]
Just FYI, http://builds.reicast.com now has the windows zips
