### ISSUE TITLE
Split up core/rend/gles/gles.cpp and reduce ifdefs

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#802]
Currently, `core/rend/gles/gles.cpp` seems to be a big mess.

We should split it up into separate files for WGL, GLX, and so on.

**Comment by skmp** [comment]
No. We need a new implementation (for various rather boring reasons). Thr
current code needs to go away, so not much improving it
Am 23.08.2015 17:02 schrieb "Jan Holthuis" <notifications@github.com>:

**Comment by Holzhaus** [comment]
That is also a solution :wink:

**Comment by Holzhaus** [comment]
By the, I'd like to be able to do this:
1. If reicast was compiled without X11 support, use framebuffer (like we already do)
2. If reicast was compiled with X11 support and
  - XOpenDisplay(NULL) returns non-`NULL` -> use X11 (like we already do)
  - XOpenDisplay(NULL) returns `NULL` ->  use framebuffer

**Comment by Holzhaus** [comment]
@skmp `gles.cpp` has more than 2000 lines. We should probably split this file up, so that each file can be dealt with on its own and it becomes a bit less of the mammoth task.

**Comment by skmp** [comment]
It is best left like that. gles.cpp is one of the few files I don't own complete copyright, and I'd like to have that contained and not spread over (and worked on).

**Comment by Holzhaus** [comment]
Could we split it up but keep it in a dedicated subfolder? That ways the "tainted" code won't be spread. I had a talk with @Twinaphex and we definitely need to make some changes there to get libretro working.

**Comment by twinaphex** [comment]
You can just go ahead and close this issue, the libretro fork already runs anyway and with little to no motivation to really improve this by the author there is no sense in keeping this open.
