### ISSUE TITLE
[Linux/x86] Sonic Adventure 2 strange bug

### ISSUE THREAD

**Issue by Holzhaus** [reicast/reicast-emulator#809]
@Yrij-Zhavoronkov reported this bug in the [Reicast on Linux thread](https://github.com/reicast/reicast-emulator/issues/427).

> Record video with strange bug for you?
> https://yadi.sk/i/YBn-G8j0iboYb
> x86 build haven't this bug..

**Comment by Yrij-Zhavoronkov** [comment]
Linux/x86 - worked correctly, Linux/amd64 or Linux/x86-64.

**Comment by skmp** [comment]
Can you upload a vmu on dropbox or somewhere else? How do we get to the
point to test the issue?

On Tue, Aug 25, 2015 at 5:32 PM, Юрий Жаворонков <notifications@github.com>
wrote:

> Linux/x86 - worked correctly, Linux/amd64 or Linux/x86-64.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/809#issuecomment-134628577>
> .
>



-- 
~skmp

**Comment by Yrij-Zhavoronkov** [comment]
<b>Skmp</b>, What? I dn't understend what's you want... Do you begining learning Russian? )

**Comment by Holzhaus** [comment]
The save game files (vmu) from `*/.reicast`.

**Comment by skmp** [comment]
vmu save game. It is vmu_data_A1.bin or vmu_data_A2.bin or something like that.

**Comment by Yrij-Zhavoronkov** [comment]
vmu save game != vmu ) Upload save game (пришите сейв от игры) - this is understood.  
Please: https://yadi.sk/d/kvBfpLFdifrCQ

**Comment by skmp** [comment]
Mirrored in https://drive.google.com/folderview?id=0B6gSdFz3bTVyfkdfbUNsVmk1QjctQVpRelJlVl9mSm1CYkxvT2RzbVJpOGY1SUZiSmFveDA&usp=sharing. Thanks!

**Comment by Yrij-Zhavoronkov** [comment]
<b>Skmp</b> что нового? 
en_EN what's new?

**Comment by Yrij-Zhavoronkov** [comment]
What's new?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#43
