### ISSUE TITLE
Game loading problems (HTC One M8)

### ISSUE THREAD

**Issue by cmexp** [reicast/reicast-emulator#812]
Log here: http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1440618699791.txt

Issue: When I load the Dreamcast BIOS, it boots to the BIOS just fine. However, no games will work. They crash to the menu right after the DC logo splash screen. I got a game to work once (the first Sonic Adventure game) but I couldn't get any games to work after that (including SA), even after restarting my phone. Sadly, I can't supply you with a log for this. The BIOS by itself loads just fine, no matter what.

**Comment by skmp** [comment]
Can you please try using the beta in #1208 and report there? Thanks.
