### ISSUE TITLE
Add Windows release builds *.exe

### ISSUE THREAD

**Issue by ofry** [reicast/reicast-emulator#813]
Hello.

Thanks for adding Windows builds artifacts, but I can't run *.exe without installed Visual Studio, because this exe required MSVCP120D.dll

Please add release build :)

Thanks.

**Comment by skmp** [comment]
We cannot do release builds because they take too much time. I'll convert
the projects to static link though

On Thu, Aug 27, 2015 at 11:23 AM, ofry <notifications@github.com> wrote:

> Hello.
>
> Thanks for adding Windows builds artifacts, but I can't run *.exe without
> installed Visual Studio, because this exe required MSVCP120D.dll
>
> Please add release build :)
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/813>.
>



-- 
~skmp

**Comment by skmp** [comment]
Okay, done, try out 435f104 or wait for ed143ec to build

**Comment by ofry** [comment]
ed143ec: same problem (required VCOMP120D.dll).

**Comment by skmp** [comment]
Hmm, openmp can only be linked dynamically. Oh well

On Thu, Aug 27, 2015 at 11:49 AM, ofry <notifications@github.com> wrote:

> ed143ec
> <https://github.com/reicast/reicast-emulator/commit/ed143eccc9167f9158ae2ac5d7a5a66d0764793a>:
> same problem (required VCOMP120D.dll).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reicast/reicast-emulator/issues/813#issuecomment-135367548>
> .
>



-- 
~skmp

**Comment by skmp** [comment]
Does https://www.microsoft.com/en-us/download/details.aspx?id=40784 help?

**Comment by ofry** [comment]
No, this doesn't help. I downloaded and installed x86 and x64 versions, rebooted PC, and tried to launch reicast. Same error.

OS: Windows 8 x64

**Comment by williansti** [comment]
I uploaded what you need, make your tests! http://www.mediafire.com/download/103l92cdovvud62/Reicast+2015-09-04+for+windows+x64.zip

**Comment by ofry** [comment]
Thanks. It's workinig, but it's still debug build :)

**Comment by ofry** [comment]
Maybe try to connect with Orphis? His buildbot already compiling DeSmuMe, PPSSPP, PCSX2 and JPSCP.

**Comment by ofry** [comment]
http://buildbot.orphis.net/

**Comment by williansti** [comment]
http://builds.reicast.com/

**Comment by kinhkongtuxat** [comment]
@williansti Can you give me a link x86 . I also corrupted files MSVCP120D.dll

**Comment by williansti** [comment]
hello unfortunately i have not, please download the package which posted here in a previous answer above.

**Comment by skmp** [comment]
Windows release builds take too long right now (30+ minutes) and that's why they are disabled. They also aren't much useful, you should be using another emulator on windows. There are excellent choices w/ demul, makaron and nulldc (and possibly more I'm not aware of)

**Comment by blackman91** [comment]
I have the same issue with both windows builds MSVCP120D.dll missing and I cannot install could you upload the mediafire link again? Link is dead and the official windows downloads do not work to make it work.

**Comment by blackman91** [comment]
How to install the latest reicast build from here on windows?
http://builds.reicast.com/

**Comment by blackman91** [comment]
Nevermind I figured out guys, if you get the same error just put the build exe inside a folder with this and it will run:
<img width="498" alt="reicastpc" src="https://user-images.githubusercontent.com/6578180/43626048-d0d3a728-96b5-11e8-8e9b-db269643de17.png">

**Comment by AbandonedCart** [comment]
It seems this simply requires documentation on the installation process for Windows.

**Comment by skmp** [comment]
Should be fixed after #1523
