### ISSUE TITLE
Pause on task switch (android, others?, maybe via savestates?)

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#825]
We need to find a nice way to do this. The nicest way is via savestates, but suspending and resuming the thread could work as well and is much simpler to implement.

**Comment by hyakki-** [comment]
or have an option for both, sometimes switching tasks causes android to close apps after awhile so thread suspend won't be as effective if the app gets closed :), save states would still work if app gets closed, you could also do something similar to what epsxe does like popup a dialog "do you want to resume game?" when you re-open reicast --

but really either option is better then none.

**Comment by AbandonedCart** [comment]
Now working for Android without the imminent need for a savestate.
