### ISSUE TITLE
Reicast crash

### ISSUE THREAD

**Issue by rica32** [reicast/reicast-emulator#828]
Just crashes on start of shenmue 2, Android lollipop.

**Comment by rica32** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1441717940316.txt

**Comment by LoungeKatt** [comment]
That may be the image. Some cdi files have been known not to work. If it required a boot disk on the system, it won't work on the emulator.

**Comment by rica32** [comment]
But I can play it on another phone '-' on Android 4.2.2
Em 08/09/2015 16:31, "TwistedUmbrella" <notifications@github.com> escreveu:

**Comment by LoungeKatt** [comment]
That's odd. It doesn't appear to show any errors that would cause a crash. I'll look at the log again.

**Comment by LoungeKatt** [comment]
After another look, there may be an issue with the Mali hardware. I'll have to do some searching but there have been other issues with that that may be related.

**Comment by rica32** [comment]
If I could help, just say it :)
Em 09/09/2015 06:06, "TwistedUmbrella" <notifications@github.com> escreveu:

**Comment by rica32** [comment]
Oh, and this just happens when I have the "Force v6 GPU Configs" ON
Em 09/09/2015 10:17, "Ricardo Carvalho" <ricahabbo@gmail.com> escreveu:

**Comment by LoungeKatt** [comment]
Try with that off. That is attempting to use a very duct taped version of forcing EGL 3 that still needs to be fixed up.

**Comment by rica32** [comment]
When I set it off it plays fine (Just the crash #707 previously reported by
me...)
Em 18/09/2015 12:30, "TwistedUmbrella" <notifications@github.com> escreveu:

**Comment by skmp** [comment]
Can you try with the latest beta from #1208 and report there? Thanks.

**Comment by AbandonedCart** [comment]
Closing this, since Shenmue has it's own anthology of issues.
