### ISSUE TITLE
New Soulcalibur Bugs

### ISSUE THREAD

**Issue by Processeur** [reicast/reicast-emulator#83]
Hi,

I don't know if the last zip source is impacted, but in the one publish on Friday (or Saturday I don't remember) there's now new graphical bugs in Soul Calibur:

-Lost of the 3D (Have to close the emu and restart the game).
-Character can hit you from very far ( very very far).
-Some parts of second costume of Cervantes disappear.
-Characters physics change during the game. (For instance Maxi is normal at start of fight and finish very thin, very fun too see)

I am in the very last levels of mission battle, I don't know if these bugs affect only the  mission battle or the whole game, but I would be very surprise that whole would not be affected.

Sorry for my poor english

Cheers

PS: In another hand DOA 2 is nearly perfect now ;)

**Comment by hooby3dfx** [comment]
well, we are F'ed. lol
bisection sunday is underway and something scary is going on. i built/tested revs down to r5 (actually r4 by accident) and the issue is still happening... 
just double checked my build/test process and the builds are clean.
as a sanity check i just got the r5 apk and it is not happening there (thank god). 
i think this must be an artifact of updated build tools...?!

**Comment by hooby3dfx** [comment]
so i am using ndk r9c in windows to build, and always getting the issue.
do you know what r5 was built with?
im wondering if this commit causes the issue: 35b38e3a7845872237a6a3544b21d724a8722dbd

**Comment by LoungeKatt** [comment]
Have you tried found forward instead of back? r9c is pretty old in Android terms

**Comment by LoungeKatt** [comment]
Stupid auto correct. Going forward.

**Comment by LoungeKatt** [comment]
I'll have to give it a try again. I'm on r9d (64-bit)

**Comment by hooby3dfx** [comment]
just built old rev with r8b and the issue is gone.
going to try to build latest and see what happens.

**Comment by hooby3dfx** [comment]
aaaand thats it folks!
there must be some kind of gcc thing going on. building the latest code
with ndk r8b resolves this issue!!
@skmp @loungekatt any ideas?

**Comment by LoungeKatt** [comment]
To find the gcc changes so it will build with newer versions. A lot of corporations do the "you need to use this version from 2006 to build" with full firmware and such, but it's not really practical for a single app.

**Comment by hooby3dfx** [comment]
an activity for a rainy day might be to next see which ndk version causes
the issue to come back.

Android NDK, Revision 9c (December 2013) - yes funky legs

Android NDK, Revision 9b (October 2013)

Android NDK, Revision 9 (July 2013)

Android NDK, Revision 8e (March 2013)

Android NDK, Revision 8d (December 2012)

Android NDK, Revision 8c (November 2012)

Android NDK, Revision 8b (July 2012) - no funky legs

**Comment by hooby3dfx** [comment]
strange that it doesnt seem to affect other games very much...

**Comment by LoungeKatt** [comment]
I have to find where I hid the game then I'll verify 9d.

**Comment by hooby3dfx** [comment]
I would expect it to still happen in that rev.

**Comment by skmp** [comment]
This was fixed w/ the upgrade to r10d in #617
