### ISSUE TITLE
Grandia 2 freeze

### ISSUE THREAD

**Issue by Moonmadness** [reicast/reicast-emulator#830]
When I get on the Skyway Station for the first time all I get is a pixelated mess like this: ![screenshot_2015-09-10-22-36-05](https://cloud.githubusercontent.com/assets/13020077/9800373/ec41b29c-580c-11e5-94cd-04b51caad659.png)
It goes on for minutes and it slows down the entire phone until I finally manage to exit the emulator.

**Comment by skmp** [comment]
Can you upload a save game nearby, please?

**Comment by Moonmadness** [comment]
Sure. Here's the save file on VMU A2: https://db.tt/SNHYK9kF
You just need to exit the inn and go to the Skyway Station.

**Comment by skmp** [comment]
Thanks *makes mental note to save it on reicast's gdrive*. I'll take a look whenever I have time~

**Comment by asbel123** [comment]
i just finsh the game on my samsung galaxy s4 and s6 edge beacuse i am using reicast version from play store and i got no graphics problem on exynoss it works perfect and sound.

**Comment by sabula310** [comment]
Omarsupercool8@gmail.com

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#75
