### ISSUE TITLE
[platform=lincpp] failed build with gcc 5.2.0

### ISSUE THREAD

**Issue by ghost** [reicast/reicast-emulator#834]
[platform=lincpp] failed build with gcc 5.2.0

../../core/linux-dist/evdev.cpp:287:65:   required from here
/usr/include/c++/5.2.0/tuple:1172:70: error: use of deleted function 'EvdevControllerMapping::EvdevControllerMapping()'
         second(std::forward<_Args2>(std::get<_Indexes2>(__tuple2))...)

**Comment by skmp** [comment]
Interesting. I'll take a look. Why do you want lincpp specifically?

**Comment by coadde** [comment]
I would it as optional building way for another users

**Comment by namelivia** [comment]
I was also getting that error when building the linux version using gcc 6.1.1
In my case I solved it deleting the const keyword for every member of the `EvdevControllerMapping` struct defined in `/core/linux-dist/evdev.h`

**Comment by skmp** [comment]
Should be resolved now
