### ISSUE TITLE
Shutdown on 4.3

### ISSUE THREAD

**Issue by 47iscool** [reicast/reicast-emulator#838]
It happens randomly. But it shuts the phone down every time on Sonic Adventure international when trying to enter chao garden. I have even tried the one on GP and one of thebsvn version s as well.

**Comment by Holzhaus** [comment]
Please give more details (Version, OS?, VMU Saves and/or Logs)

**Comment by skmp** [comment]
If the phone physically shuts down this suggests a hardware malfunction. Do you have all of the latest updates and running an official/stable android version? It could also be problematic hardware - you definitely need to report this to the manufacturer. Reicast pushes some hardware to it's limits ... :)

**Comment by 47iscool** [comment]
Well uh it's A cheap one, ZTE Z667G running Android 4.3. It says the kernal version is 3.4.0+

Sometimes its random but it always shuts down when going to chao garden. The phone is 1.2 Ghz quad core and runs games at full speed or close to it. This issue also happens randomly on SA2. At least we know it isn't a game-specific issue.

**Comment by Holzhaus** [comment]
May be automatic shutdown due to overheating or something like that. Unless you find something in the logs that indicate this is due to Reicast doing something fishy, I don't think we can do something about it.

**Comment by Holzhaus** [comment]
By the way, you could run a benchmark app to verify that.

**Comment by 47iscool** [comment]
I will get a benchmark app.

Not sure where the logs are stored though.

**Comment by 47iscool** [comment]
Can't be a heat issue. It gets pretty heated with Sonic Dash, more than RC.

BTW, is this nulldc?

**Comment by Holzhaus** [comment]
It's the improved fork. nullDC is dead.

**Comment by Holzhaus** [comment]
Could still be a hardware malfunction or some software bug that causes a kernel oops or something. Maybe Sonic Dash does not use the affected software/hardware parts but reicast does.

Under no circumstances should reicast crash your phone. At most, it should display a message like "Reicast crashed/closed unexpectedly/has been killed because it tried to do something stupid".

**Comment by 47iscool** [comment]
How can I submit a log?

**Comment by Holzhaus** [comment]
@LoungeKatt might know. I'm not an Android expert ;-)

**Comment by 47iscool** [comment]
BTW my phone is not rooted.

**Comment by LoungeKatt** [comment]
In the sliding menu on the left, there is an option (I believe the last one) that will walk you through it.

**Comment by 47iscool** [comment]
It says something about copying to files or or clipboard or something.

Either way I don't see any logs anywhere on the SD nor is there any text copied to the clipboard.

What am I doing wrong?

**Comment by LoungeKatt** [comment]
It should have prompted you to open them web browser. You'd come back here, long click, and choose paste. The logs will be saved in the same folder as your BIOS is stored.

**Comment by 47iscool** [comment]
Okay that worked thanks.

2000 r--p 00001000 b3:17 1128       /system/lib/libemoji.so
404f2000-404f3000 rw-p 00002000 b3:17 1128       /system/lib/libemoji.so
404f3000-40524000 r-xp 00000000 b3:17 1171       /system/lib/libjpeg.so
40524000-40525000 r--p 00030000 b3:17 1171       /system/lib/libjpeg.so
40525000-40526000 rw-p 00031000 b3:17 1171       /system/lib/libjpeg.so
40526000-40539000 r-xp 00000000 b3:17 1132       /system/lib/libexpat.so
40539000-4053a000 ---p 00000000 00:00 0 
4053a000-4053c000 r--p 00013000 b3:17 1132       /system/lib/libexpat.so
4053c000-4053d000 rw-p 00015000 b3:17 1132       /system/lib/libexpat.so
4053d000-40587000 r-xp 00000000 b3:17 1022       /system/lib/libEGL.so
40587000-40589000 r--p 00049000 b3:17 1022       /system/lib/libEGL.so
40589000-4058f000 rw-p 0004b000 b3:17 1022       /system/lib/libEGL.so
4058f000-40592000 rw-p 00000000 00:00 0 
40592000-405df000 r-xp 00000000 b3:17 1025       /system/lib/libGLES_trace.so
405df000-405e0000 r--p 0004c000 b3:17 1025       /system/lib/libGLES_trace.so
405e0000-405e1000 rw-p 0004d000 b3:17 1025       /system/lib/libGLES_trace.so
405e1000-40613000 r-xp 00000000 b3:17 1264       /system/lib/libstlport.so
40613000-40615000 r--p 00031000 b3:17 1264       /system/lib/libstlport.so
40615000-40616000 rw-p 00033000 b3:17 1264       /system/lib/libstlport.so
40616000-4061d000 r-xp 00000000 b3:17 1027       /system/lib/libGLESv2.so
4061d000-4061e000 r--p 00006000 b3:17 1027       /system/lib/libGLESv2.so
4061e000-4061f000 rw-p 00007000 b3:17 1027       /system/lib/libGLESv2.so
4061f000-40621000 r-xp 00000000 b3:17 1196       /system/lib/libnativehelper.so
40621000-40622000 r--p 00001000 b3:17 1196       /system/lib/libnativehelper.so
40622000-40623000 rw-p 00002000 b3:17 1196       /system/lib/libnativehelper.so
40623000-40628000 r-xp 00000000 b3:17 1201       /system/lib/libnetutils.so
40628000-40629000 r--p 00004000 b3:17 1201       /system/lib/libnetutils.so
40629000-4062a000 rw-p 00005000 b3:17 1201       /system/lib/libnetutils.so
4062a000-40634000 r-xp 00000000 b3:17 1275       /system/lib/libui.so
40634000-40635000 r--p 00009000 b3:17 1275       /system/lib/libui.so
40635000-40636000 rw-p 0000a000 b3:17 1275       /system/lib/libui.so
40636000-40637000 r-xp 00000000 b3:17 1156       /system/lib/libhardware.so
40637000-40638000 r--p 00000000 b3:17 1156       /system/lib/libhardware.so
40638000-40639000 rw-p 00001000 b3:17 1156       /system/lib/libhardware.so
40639000-4063a000 r-xp 00000000 b3:17 1269       /system/lib/libsync.so
4063a000-4063b000 r--p 00000000 b3:17 1269       /system/lib/libsync.so
4063b000-4063c000 rw-p 00001000 b3:17 1269       /system/lib/libsync.so
4063c000-40669000 r-xp 00000000 b3:17 1155       /system/lib/libgui.so
40669000-40670000 r--p 0002c000 b3:17 1155       /system/lib/libgui.so
40670000-40671000 rw-p 00033000 b3:17 1155       /system/lib/libgui.so
40671000-40694000 r-xp 00000000 b3:17 1075       /system/lib/libcamera_client.so
40694000-4069c000 r--p 00022000 b3:17 1075       /system/lib/libcamera_client.so
4069c000-4069d000 rw-p 0002a000 b3:17 1075       /system/lib/libcamera_client.so
4069d000-4069e000 r--p 00000000 00:00 0 
4069e000-406a3000 r-xp 00000000 b3:17 1076       /system/lib/libcamera_metadata.so
406a3000-406a4000 r--p 00004000 b3:17 1076       /system/lib/libcamera_metadata.so
406a4000-406a5000 rw-p 00005000 b3:17 1076       /system/lib/libcamera_metadata.so
406a5000-406f5000 r-xp 00000000 b3:17 1232       /system/lib/libsqlite.so
406f5000-406f6000 ---p 00000000 00:00 0 
406f6000-406f7000 r--p 00050000 b3:17 1232       /system/lib/libsqlite.so
406f7000-406f8000 rw-p 00051000 b3:17 1232       /system/lib/libsqlite.so
406f8000-407e8000 r-xp 00000000 b3:17 1162       /system/lib/libicuuc.so
407e8000-407f1000 r--p 000ef000 b3:17 1162       /system/lib/libicuuc.so
407f1000-407f2000 rw-p 000f8000 b3:17 1162       /system/lib/libicuuc.so
407f2000-407f6000 rw-p 00000000 00:00 0 
407f6000-407fa000 r-xp 00000000 b3:17 1147       /system/lib/libgabi++.so
407fa000-407fb000 r--p 00003000 b3:17 1147       /system/lib/libgabi++.so
407fb000-407fc000 rw-p 00004000 b3:17 1147       /system/lib/libgabi++.so
407fc000-40921000 r-xp 00000000 b3:17 1161       /system/lib/libicui18n.so
40921000-40922000 ---p 00000000 00:00 0 
40922000-40929000 r--p 00125000 b3:17 1161       /system/lib/libicui18n.so
40929000-4092a000 rw-p 0012c000 b3:17 1161       /system/lib/libicui18n.so
4092a000-409e1000 r-xp 00000000 b3:17 1103       /system/lib/libdvm.so
409e1000-409e5000 r--p 000b6000 b3:17 1103       /system/lib/libdvm.so
409e5000-409eb000 rw-p 000ba000 b3:17 1103       /system/lib/libdvm.so
409eb000-409ee000 rw-p 00000000 00:00 0 
409ee000-409f0000 r-xp 00000000 b3:17 1697       /system/vendor/lib/libqc-opt.so
409f0000-409f1000 r--p 00001000 b3:17 1697       /system/vendor/lib/libqc-opt.so
409f1000-409f2000 rw-p 00002000 b3:17 1697       /system/vendor/lib/libqc-opt.so
409f2000-409fc000 r-xp 00000000 b3:17 1224       /system/lib/libselinux.so
409fc000-409fd000 r--p 00009000 b3:17 1224       /system/lib/libselinux.so
409fd000-409fe000 rw-p 0000a000 b3:17 1224       /system/lib/libselinux.so
409fe000-40a03000 r-xp 00000000 b3:17 1026       /system/lib/libGLESv1_CM.so
40a03000-40a04000 r--p 00004000 b3:17 1026       /system/lib/libGLESv1_CM.so
40a04000-40a05000 rw-p 00005000 b3:17 1026       /system/lib/libGLESv1_CM.so
40a05000-40a07000 r-xp 00000000 b3:17 1023       /system/lib/libETC1.so
40a07000-40a08000 r--p 00001000 b3:17 1023       /system/lib/libETC1.so
40a08000-40a09000 rw-p 00002000 b3:17 1023       /system/lib/libETC1.so
40a09000-40a0e000 r-xp 00000000 b3:17 1157       /system/lib/libhardware_legacy.so
40a0e000-40a0f000 r--p 00004000 b3:17 1157       /system/lib/libhardware_legacy.so
40a0f000-40a10000 rw-p 00005000 b3:17 1157       /system/lib/libhardware_legacy.so
40a10000-40a12000 r-xp 00000000 b3:17 1298       /system/lib/libwpa_client.so
40a12000-40a13000 r--p 00001000 b3:17 1298       /system/lib/libwpa_client.so
40a13000-40a14000 rw-p 00002000 b3:17 1298       /system/lib/libwpa_client.so
40a14000-40a63000 r-xp 00000000 b3:17 1227       /system/lib/libsonivox.so
40a63000-40a64000 r--p 0004e000 b3:17 1227       /system/lib/libsonivox.so
40a64000-40a65000 rw-p 0004f000 b3:17 1227       /system/lib/libsonivox.so
40a65000-40a6a000 rw-p 00000000 00:00 0 
40a6a000-40a7e000 r-xp 00000000 b3:17 1101       /system/lib/libdrmframework.so
40a7e000-40a81000 r--p 00013000 b3:17 1101       /system/lib/libdrmframework.so
40a81000-40a82000 rw-p 00016000 b3:17 1101       /system/lib/libdrmframework.so
40a82000-40a83000 r--p 00000000 00:00 0 
40a83000-40b47000 r-xp 00000000 b3:17 1088       /system/lib/libcrypto.so
40b47000-40b48000 ---p 00000000 00:00 0 
40b48000-40b54000 r--p 000c4000 b3:17 1088       /system/lib/libcrypto.so
40b54000-40b5a000 rw-p 000d0000 b3:17 1088       /system/lib/libcrypto.so
40b5a000-40b5c000 rw-p 00000000 00:00 0 
40b5c000-40b8f000 r-xp 00000000 b3:17 1235       /system/lib/libssl.so
40b8f000-40b90000 ---p 00000000 00:00 0 
40b90000-40b92000 r--p 00033000 b3:17 1235       /system/lib/libssl.so
40b92000-40b95000 rw-p 00035000 b3:17 1235       /system/lib/libssl.so
40b95000-40c0d000 r-xp 00000000 b3:17 1183       /system/lib/libmedia.so
40c0d000-40c0e000 ---p 00000000 00:00 0 
40c0e000-40c25000 r--p 00078000 b3:17 1183       /system/lib/libmedia.so
40c25000-40c26000 rw-p 0008f000 b3:17 1183       /system/lib/libmedia.so
40c26000-40c31000 r-xp 00000000 b3:17 1241       /system/lib/libstagefright_foundation.so
40c31000-40c32000 r--p 0000a000 b3:17 1241       /system/lib/libstagefright_foundation.so
40c32000-40c33000 rw-p 0000b000 b3:17 1241       /system/lib/libstagefright_foundation.so
40c33000-40c35000 r-xp 00000000 b3:17 1064       /system/lib/libaudioutils.so
40c35000-40c36000 r--p 00001000 b3:17 1064       /system/lib/libaudioutils.so
40c36000-40c37000 rw-p 00002000 b3:17 1064       /system/lib/libaudioutils.so
40c37000-40c3b000 r-xp 00000000 b3:17 1230       /system/lib/libspeexresampler.so
40c3b000-40c3c000 r--p 00003000 b3:17 1230       /system/lib/libspeexresampler.so
40c3c000-40c3d000 rw-p 00004000 b3:17 1230       /system/lib/libspeexresampler.so
40c3d000-40c40000 r-xp 00000000 b3:17 1063       /system/lib/libaudioparameter.so
40c40000-40c41000 r--p 00002000 b3:17 1063       /system/lib/libaudioparameter.so
40c41000-40c42000 rw-p 00003000 b3:17 1063       /system/lib/libaudioparameter.so
40c42000-40c44000 r-xp 00000000 b3:17 1276       /system/lib/libusbhost.so
40c44000-40c45000 r--p 00001000 b3:17 1276       /system/lib/libusbhost.so
40c45000-40c46000 rw-p 00002000 b3:17 1276       /system/lib/libusbhost.so
40c46000-40c8e000 r-xp 00000000 b3:17 1159       /system/lib/libharfbuzz_ng.so
40c8e000-40c8f000 r--p 00047000 b3:17 1159       /system/lib/libharfbuzz_ng.so
40c8f000-40c90000 rw-p 00048000 b3:17 1159       /system/lib/libharfbuzz_ng.so
40c90000-40cc0000 r-xp 00000000 b3:17 1160       /system/lib/libhwui.so
40cc0000-40cc1000 ---p 00000000 00:00 0 
40cc1000-40cc4000 r--p 00030000 b3:17 1160       /system/lib/libhwui.so
40cc4000-40cc5000 rw-p 00033000 b3:17 1160       /system/lib/libhwui.so
40cc5000-40d3b000 r-xp 00000000 b3:17 1044       /system/lib/libRS.so
40d3b000-40d3c000 ---p 00000000 00:00 0 
40d3c000-40d3e000 r--p 00076000 b3:17 1044       /system/lib/libRS.so
40d3e000-40d3f000 rw-p 00078000 b3:17 1044       /system/lib/libRS.so
40d3f000-40dbf000 r-xp 00000000 b3:17 1066       /system/lib/libbcc.so
40dbf000-40dc0000 ---p 00000000 00:00 0 
40dc0000-40dc4000 r--p 00080000 b3:17 1066       /system/lib/libbcc.so
40dc4000-40dc5000 rw-p 00084000 b3:17 1066       /system/lib/libbcc.so
40dc5000-40de5000 rw-p 00000000 00:00 0 
40de5000-40e0a000 r-xp 00000000 b3:17 1067       /system/lib/libbcinfo.so
40e0a000-40e0b000 r--p 00024000 b3:17 1067       /system/lib/libbcinfo.so
40e0b000-40e0c000 rw-p 00025000 b3:17 1067       /system/lib/libbcinfo.so
40e0c000-41592000 r-xp 00000000 b3:17 1029       /system/lib/libLLVM.so
41592000-415c0000 r--p 00785000 b3:17 1029       /system/lib/libLLVM.so
415c0000-415c2000 rw-p 007b3000 b3:17 1029       /system/lib/libLLVM.so
415c2000-415c7000 rw-p 00000000 00:00 0 
415c7000-415c8000 r--p 00000000 00:00 0 
415c8000-415d1000 r-xp 00000000 b3:17 1047       /system/lib/libRScpp.so
415d1000-415d2000 ---p 00000000 00:00 0 
415d2000-415d3000 r--p 00009000 b3:17 1047       /system/lib/libRScpp.so
415d3000-415d4000 rw-p 0000a000 b3:17 1047       /system/lib/libRScpp.so
415d4000-415e4000 r--s 00000000 00:0b 5562       /dev/__properties__
415e4000-415e5000 r--p 00000000 00:00 0 
415e5000-415eb000 rw-p 00000000 00:00 0 
415eb000-415ec000 r--p 00000000 00:00 0 
415ec000-415ee000 rw-p 00000000 00:00 0 
415ee000-419f2000 rw-p 00000000 00:04 7614       /dev/ashmem/dalvik-heap (deleted)
419f2000-41abf000 rw-p 00404000 00:04 7614       /dev/ashmem/dalvik-heap (deleted)
41abf000-495ee000 ---p 004d1000 00:04 7614       /dev/ashmem/dalvik-heap (deleted)
495ee000-497ee000 rw-p 00000000 00:04 7615       /dev/ashmem/dalvik-bitmap-1 (deleted)
497ee000-499ee000 rw-p 00000000 00:04 7616       /dev/ashmem/dalvik-bitmap-2 (deleted)
499ee000-4c499000 rw-p 00000000 00:04 7617       /dev/ashmem/dalvik-mark-stack (deleted)
4c499000-4c59a000 rw-p 00000000 00:04 7618       /dev/ashmem/dalvik-card-table (deleted)
4c59a000-4c5a8000 rw-p 00000000 00:00 0 
4c5a8000-4c5a9000 ---p 00000000 00:04 7619       /dev/ashmem/dalvik-LinearAlloc (deleted)
4c5a9000-4c8ab000 rw-p 00001000 00:04 7619       /dev/ashmem/dalvik-LinearAlloc (deleted)
4c8ab000-4c8da000 rw-p 00303000 00:04 7619       /dev/ashmem/dalvik-LinearAlloc (deleted)
4c8da000-4d5a8000 ---p 00332000 00:04 7619       /dev/ashmem/dalvik-LinearAlloc (deleted)
4d5a8000-4d5ad000 rw-p 00000000 00:00 0 
4d5ad000-4d5ae000 r--s 00000000 b3:17 926        /system/framework/core.jar
4d5ae000-4d913000 r--p 00000000 b3:17 927        /system/framework/core.odex
4d913000-4d94e000 rw-p 00000000 00:04 7620       /dev/ashmem/dalvik-aux-structure (deleted)
4d94e000-4d94f000 r--s 00000000 b3:17 924        /system/framework/core-junit.jar
4d94f000-4d956000 r--p 00000000 b3:17 925        /system/framework/core-junit.odex
4d956000-4d957000 rw-p 00000000 00:04 7621       /dev/ashmem/dalvik-aux-structure (deleted)
4d957000-4d958000 r--s 000000

**Comment by 47iscool** [comment]
Now that I think about its not really shutting down because I have to remove the battery to get it to power back on.

Any ideas what could cause this? Also the led power light blinks when it happens.

**Comment by skmp** [comment]
Can you please retest with the latest beta from #1208? Thanks :)
