### ISSUE TITLE
apk works awesome but my issue is the reicast r7 apk won't locate extSdCard on my android lollipop tablet using a 64 GB card

### ISSUE THREAD

**Issue by villanueva84** [reicast/reicast-emulator#844]
Issue is fixed with new apk this emulator is great thank you for building it

**Comment by skmp** [comment]
So is this an issue or not?

**Comment by villanueva84** [comment]
No is not anymore the online apk update fixed it I was using the playstore
apk. Thank you. I did find that some crashes on the games are caused by the
save states vmu_save_A1 and the A2 or the cfg cause when I play some games
with the save states they close on me but when i delete them the games
won't crash. Marvel vs Capcom 2 does this and so did house of the dead 2.
But is all good cause I am able to play them this emulator is great.

**Comment by Holzhaus** [comment]
In that csse I'll close this.
