### ISSUE TITLE
Crash on emulator launch

### ISSUE THREAD

**Issue by Fullmetal5** [reicast/reicast-emulator#847]
Running reicast built from commit 915d6b26d67ebda19e6029eb3547b6c6295cb7ef on Linux
Attempting to launch reicast will immediately crash with this message
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

I tried compiling older releases to see if they work but the builds kept failing.

**Comment by sl1pkn07** [comment]
same here

**Comment by olegantonyan** [comment]
Similar problem after building `fix/softrend-fugly-casts` 
```
Unimplemented opcode: 0000FFFF next_pc: AC008302 pr: AC00043C msg: Unknown opcode
Fatal error : iNimp reached

 in cpu_iNimp -> ../../core/hw/sh4/interpr/sh4_opcodes.cpp : 66 
```
https://gist.github.com/olegantonyan/be8ec1b32c220ad35e79

**Comment by sl1pkn07** [comment]
please add the patch to fix/softrend-fugly-casts branch

if not: https://github.com/reicast/reicast-emulator/issues/896

**Comment by sabula310** [comment]
Omarsupercool8@gmail.com
