### ISSUE TITLE
Software Renderer

### ISSUE THREAD

**Issue by RinMaru** [reicast/reicast-emulator#851]
So I'm just wondering If there was a software renderer to be implemented would this be able to run on hardware that doesn't support OpenGL 3.  I use linux and only got OpenGL 2.

**Comment by Holzhaus** [comment]
Can't say a lot about the [Software renderer](https://github.com/reicast/reicast-emulator/blob/master/core/rend/soft/softrend.cpp). On the other hand: Have you tried GLES or is that also not supported?

**Comment by Zetchzie** [comment]
I have intel i915. I just know (nulldc beta) ran very well on my windows. I use linux know. I figure a software renderer would allow me to use reicast. I know nothing about coding so sorry if I'm asking the impossible lol

**Comment by Holzhaus** [comment]
According to [the Gentoo wiki](https://wiki.gentoo.org/wiki/Intel#Feature_support), the Intel 915 only has OpenGL 1.4. Are you sure you have that? If you have 4th Gen Intel card instead,(which does support OpenGL 2.1 AND OpenGL ES 2.0), you could compile reicast with USE_GLES=1 and thus use the GLES renderer instead.

**Comment by Zetchzie** [comment]
yeah only i915 but wouldnt a software renderer not need that?

**Comment by Holzhaus** [comment]
Yes, it wouldn't need that, but I don't know the current state of the Software renderer (Does it work on Linux? @skmp might shed some light on this). On the other hand, I *know* that the GLES renderer works.

**Comment by Zetchzie** [comment]
I've seen ppl running it on linux through command line after compiling it. If there's a stable version for linux I do not believe so.

**Comment by ptitSeb** [comment]
i915 is able to run GL2.0 (or GLES2), but many extension are missing (so
you cannot run Portal2 on Linux for example).

2015-10-15 18:40 GMT+02:00 Ryan <notifications@github.com>:

**Comment by Holzhaus** [comment]
Well, running reicast via commandline (without x11) doesn't mean there's a software renderer involved. I browsed though the code and found [this](https://github.com/reicast/reicast-emulator/blob/915d6b26d67ebda19e6029eb3547b6c6295cb7ef/core/rend/gles/gltex.cpp#L335):

```C
#if HOST_OS == OS_WINDOWS
	//[...]
#else
	die("Softrend only works for windows");
#endif
```

I don't know how much work is needed to make it work on linux, too. I think @skmp has more information about that.

**Comment by Zetchzie** [comment]
Oh I thought you meant Reicast in general then idk if SR even works in linux.
