### ISSUE TITLE
Crash to emulator menu on booting games

### ISSUE THREAD

**Issue by M-a-r-k** [reicast/reicast-emulator#852]
I'm using a Huawei G620S phone and Reicast from http://reicast-builds.s3.amazonaws.com/builds/heads/master-73a585a/reicast-android-debug-73a585a.apk
Same issue with the Play Store version.

On selecting a game to boot (GDI image/files) the emulator crashes back to the game selection menu.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1445189091187.txt

If I disable Dynarec Options, on booting a game I get this error message (which seems to repeat over and over) on screen:

```
Fatal error: iNimp reached
in cpu_iNimp -> jni/../jni/../../../core/hw/sh4/interpr/sh4_opcodes.cpp : 66
```

**Comment by skmp** [comment]
Can you please test with the latest beta from #1208 and report there? Thanks :)
