### ISSUE TITLE
Metropolis Street Racer no engine sound or other sound effects R6

### ISSUE THREAD

**Issue by mrspidey** [reicast/reicast-emulator#856]
I didn't see this posted, but in Metropolis Street Racer / MSR the engine and other sound effects don't come through. The radio music plays just fine but not sound effects. The game plays like a dream otherwise but it is quite weird not having any sound effects. Is there any quick-fix or a setting that can change this? Is there a nightly build that has this fixed?

**Comment by julianwki** [comment]
I recently tried reicast the first time with MSR and also got no sound effects. Any suggestions?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#76
