### ISSUE TITLE
Can't start reicast arch linux

### ISSUE THREAD

**Issue by kuipumu** [reicast/reicast-emulator#857]
I compiles reicast trought the git repositor, added boot_bin and flash_bin in the data folder in /home/user/.reicast/data and even in /home/user/.config/reicast/data and when y try to run

sudo reicast /home/user/shenmue1.cdi

y get 

Config dir is: /root/.config/reicast/
Data dir is:   /root/.local/share/reicast/
Personality: 00000000
Updated personality: 00000000
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 7A3A0000, aram: 9a3a0000, vram: 7E3A0000, ram: 863A0000
Resetting mem
Mem alloc successful!Using '/home/cesar/shenmue1.cdi' as cd image

libwebsockets test server - (C) Copyright 2010-2013 Andy Green andy@warmcat.com - licensed under LGPL2.1
Initial logging level 7
Library version: 1.3 c11b847
IPV6 not compiled in
libev support not compiled in
 static allocation: 4488 + (16 x 1024 fds) = 20872 bytes
 canonical_hostname = archposthumus
 per-conn mem: 184 + 1554 headers + protocol rx buf
 Listening on port 5678
Malformed entry on config - ignoring @ 38(ElfFile)
Found 10 matching FB configs.
Chosen visual ID = 0x24
Unable to find bios in 
/root/.local/share/reicast/data/
Exiting...
No nvmem loaded
reios: Init
Did not load bios, using reios
Using Recompiler
Auto-selected audio backend "alsa" (Advanced Linux Sound Architecture).
Initializing audio backend "alsa" (Advanced Linux Sound Architecture)...
recSh4 Init
Freeing fpcb

```
     CodeCache addr: 0x4a8000 | from: 0x4a8000 | addr here: 0x4a6680
```

Session 1 has 1 track(s)
Saving  Track:  1  Type: Audio/2352  Pregap: 150  Size: 300     LBA: 0  
Track position: 352800

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Pregap: 150  Size: 340366  LBA: 11700  
Track position: 1408800
gdrom: Opened image "/home/cesar/shenmue1.cdi"
Initialising empty vmu...
Initialising empty vmu...
Sh4 Reset
evdev: Trying to open device at '/dev/input/event0'
GL context version: 3.1
evdev: Found 'HuiJia  USB GamePad' at '/dev/input/event0'
evdev: reading mapping file: 'controller_generic.cfg'
btn_a = BTN_SOUTH (304)
btn_b = BTN_EAST (305)
btn_c = BTN_C (306)
btn_d = BTN_THUMBL (317)
btn_x = BTN_NORTH (307)
btn_y = BTN_WEST (308)
btn_z = BTN_Z (309)
btn_start = BTN_START (315)
btn_escape = BTN_SELECT (314)
btn_dpad1_left = BTN_DPAD_UP (544)
btn_dpad1_right = BTN_DPAD_DOWN (545)
btn_dpad1_up = BTN_DPAD_LEFT (546)
btn_dpad1_down = BTN_DPAD_RIGHT (547)
btn_trigger_left = BTN_TL (310)
btn_trigger_right = BTN_TR (311)
axis_dpad1_x = ABS_HAT0X (16)
axis_dpad1_y = ABS_HAT0Y (17)
axis_dpad2_x = ABS_HAT1X (18)
axis_x = ABS_X (0)
axis_y = ABS_Y (1)
axis_trigger_left = ABS_Z (2)
axis_trigger_right = ABS_RZ (5)
evdev: Using 'Generic Controller' mapping
evdev: range of axis 0 is from 0 to 255
evdev: range of axis 1 is from 0 to 255
evdev: range of axis 2 is from 0 to 255
evdev: range of axis 5 is from 0 to 255
evdev: Controller 2 disabled by config.
evdev: Controller 3 disabled by config.
evdev: Controller 4 disabled by config.
Legacy Joystick input disabled by config.

cntx // fpcb offset: -68157440 // pc offset: -184 // pc A0000000
## REIOS: Booting up

reios: loading ip.bin from FAD: 11850
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 11873, len: 2048
Found 1ST_READ.BIN at 0000BD
filename len: 14
file LBA: 28996
file LEN: 2695540
Freeing fpcb
recSh4:Dynarec Cache clear at AC0082FE
Sh4: i-cache invalidation AC0082FE
Freeing fpcb
recSh4:Dynarec Cache clear at AC0082FE
VREG = 03 ARMRST 00
VREG = 03 ARMRST 00
new tactx
OSD: 6
Error opening /root/.local/share/reicast/data/buttons.png
DIV32S matched 1% @ 0x8C0098D8
DIV32S matched 100% @ 0x8C0098DE
div32s 1/0/3
DIV32S matched 1% @ 0x8C009A36
DIV32S matched 100% @ 0x8C009A3E
div32s 1/0/3
DIV32S matched 1% @ 0x8C009AC0
DIV32S matched 1% @ 0x8C009ACA
reicast git/n - 14.67 (0.00) - 68.17 - V: 40.86 (83.00, NTSC480i59.95) R: 0.49+0.00 VTX: 0.00 , MIPS: 0.00
reios_sys_misc - r7: 0x00000000, r4 0x00000000, r5 0x00000064, r6 0x00000140
Sh4: i-cache invalidation AC00E0DA
Freeing fpcb
recSh4:Dynarec Cache clear at AC00E0DA

GDROM:  HLE GDROM_INIT
GDROM:  CMD INIT PRM:18
reicast git/n - 9.98 (0.00) - 100.15 - V: 60.04 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
Freeing fpcb
recSh4:Dynarec Cache clear at AC00FFFE
Sh4: i-cache invalidation AC003FFE
Freeing fpcb
recSh4:Dynarec Cache clear at AC003FFE
reicast git/n - 10.02 (0.00) - 99.84 - V: 59.85 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.79 (0.00) - 102.18 - V: 61.25 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.22 (0.00) - 97.86 - V: 58.66 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.93 (0.00) - 100.67 - V: 60.34 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.01 (0.00) - 99.88 - V: 59.87 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.87 (0.00) - 101.30 - V: 60.73 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.09 (0.00) - 99.11 - V: 59.41 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.10 (0.00) - 98.98 - V: 59.34 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.02 (0.00) - 99.79 - V: 59.82 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.94 (0.00) - 100.63 - V: 60.32 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.06 (0.00) - 99.40 - V: 59.59 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.01 (0.00) - 99.90 - V: 59.89 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 9.86 (0.00) - 101.45 - V: 60.82 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
reicast git/n - 10.01 (0.00) - 99.87 - V: 59.87 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00
Fatal error : death by escape key
 in input_x11_handle -> ../../core/linux-dist/x11.cpp : 77 

and all i get is a blackscreen.

What can i do?, im not too much experienced in compiling and coding in linux, i am kinda new to this OS.

**Comment by Holzhaus** [comment]
From your log output:

```
Unable to find bios in 
/root/.local/share/reicast/data/
Exiting...
```

Also, don't run reicast as root (i.e. don't use `sudo`).

**Comment by MikaXII** [comment]
HS : 
Did you try to use PKGBUILD in [AUR repository](https://aur.archlinux.org/packages/reicast-git/) of reicast emulator ? It's better to use PKGBUILD than manually compilation on Arch.

**Comment by Pupiloho** [comment]
I fixed it, as Holzhaus write i didn't put the bios file where it should be, now it starts, but now i got graphic glitches in Shenmue, slowdowns and bad renderer eyes on ryo head and other stuff, another question i could not find, how can i acess settings without a gamepad?. Thanks. really appreciated.

**Comment by MikaXII** [comment]
The AUR package compile from master branch is not the [latest stable release](https://github.com/reicast/reicast-emulator/releases/tag/r6). Maybe you can edit your pkgbuild to compile from the latest stable release like this
`source=(reicast::"git+https://github.com/reicast/reicast-emulator.git")`
to
`source=(reicast::"git+https://github.com/reicast/reicast-emulator.git#tag=r6")`

[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=reicast-git#n15)

**Comment by Pupiloho** [comment]
Thanks, i ran from that PKGBUILD and y already have installed r6 version (reinstalled anyway) run trought konsole and only could run trought sudo (same error )

terminate called after throwing an instance of 'std::logic_error'
what(): basic_string::_S_construct null not valid
Aborted (core dumped)

Everything fine from the emulator, but i still get graphical glitches and sometime if i close the konsole i still get frames from windows gone.

I saw trought AUR repository that there is a r7 (unstable version) that is more recent but when i try to compile it i get these error.

../../core/rend/gles/gles.cpp:594:20: fatal error: Wingdi.h: No such file or directory
compilation terminated.
Makefile:89: recipe for target 'obj/rend/gles/gles.build_obj' failed
make: *** [obj/rend/gles/gles.build_obj] Error 1


[PKGBUILD.txt](https://github.com/reicast/reicast-emulator/files/31219/PKGBUILD.txt)

That is the PKGBUILD from the AUR ropisitory, i can't figure out what is the problem 
(sorry if i didn't write coherently i don't now too much english), Thanks for your help.

**Comment by Holzhaus** [comment]
> but when runnign reicast i dosen't link the controller to js2 and event 18, instead reicast links to js0 and event 0, how can i fix this?

Have you specified this in your `emu.cfg`? Run `man reicast` and read the Controls section.

> if i run sudo reicast-joyconfig i get the following message
> ```
> Can't import evdev module. Please install it.
> You can do this via:
>   pip install evdev
> ```
i have already evdev, don't know if is executed or not.

Run `yaourt -S  python-evdev`.

**Comment by Pupiloho** [comment]
Installing python-evdev solved joyconfig issue, but the emu.cfg config is not been readed, put it in the exact same folder with the evdev id of the controller and the mapping created, dosen't load the mapping neither the device, joystick legacy is off, but no config is being readed i even tried to override the config by using the -config command, im using xboxdrv. i don't know what else i can do to set the settings. Thanks, your help has been really helpful, really apreciated.

**Comment by skmp** [comment]
Closing as part of ticket cleanup. Please report in chat.reicast.com if still an issue. Latest master should work just fine
