### ISSUE TITLE
[linux] reicast config folder should be store in /home/.config/ folder

### ISSUE THREAD

**Issue by legluondunet** [reicast/reicast-emulator#861]
Hello,

now on Linux the config files are stored in the .config folder. Perhaps it should a good thing to store reicast config files in that folder instead of the /home/.reicast?

regards.

LGDN.

**Comment by Holzhaus** [comment]
[This is already the case.](https://github.com/reicast/reicast-emulator/commit/c24a5faf5bd3cb8f1ec9f9039910fe36ec4b58fd)

**Comment by legluondunet** [comment]
I eraser the /home/legluondunet/.reicast folder and now it works. 

Thank you Holzhaus
