### ISSUE TITLE
[linux] [ubuntu] reicast-joyconfig ask for evdev module

### ISSUE THREAD

**Issue by legluondunet** [reicast/reicast-emulator#864]
Hello,

when I launch reicast-joyconfig.py, I obtain this error message:

Can't import evdev module. Please install it.
You can do this via:
pip install evdev

I don't understand this message.

Thank you for your help.

LGDN

Config:
Ubuntu 15.10 Wily 64 bits
NVIDIA  GeForce GTX 770
official Ubuntu Nvidia drivers 340.93 resolution 1920x1080
Processor Intel i5-3570 3,4 Ghz
8 Go RAM

**Comment by Holzhaus** [comment]
http://installion.co.uk/ubuntu/wily/universe/p/python-evdev/install/index.html

**Comment by legluondunet** [comment]
So on Ubuntu I had to do:
$ sudo apt-get install python-evdev

Thank you Holzhaus
