### ISSUE TITLE
Resident Evil 2 Support

### ISSUE THREAD

**Issue by Edher-Ivan** [reicast/reicast-emulator#872]
Don't Works Resident Evil 2 I't is Closes

**Comment by Holzhaus** [comment]
Please post a logfile.

**Comment by KabutoKun** [comment]
Resident Evil 2 is one of the WinCE games for Dreamcast, it won't work with reicast for some time.

**Comment by Edher-Ivan** [comment]
OK Man, I would like in the near future to work with REICAST.

**Comment by vgturtle127** [comment]
I think this can be closed since this is a bit of a larger scope than an issue.

**Comment by ghost** [comment]
@skmp this game still unplayable in Reicast? This game always crash :(
Here's the log 
[Resident Evil 2 Crashlog.zip](https://github.com/reicast/reicast-emulator/files/3446530/Resident.Evil.2.Crashlog.zip)
