### ISSUE TITLE
Play says "please insert game disc" despite commandline showing gdrom was loaded

### ISSUE THREAD

**Issue by keithzg** [reicast/reicast-emulator#876]
I'm a bit baffled by what I'm missing here; I've compiled Reicast on a Kubuntu 15.10 machine (64-bit install) and I can see in the terminal output that it's loading the .gdi file that I've specified as an argument to ./reicast.elf:

```
GDI : 3 tracks
file[1] "track01.bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:-8
file[2] "track02.raw": FAD:600, CTRL:0, SSIZE:2352, OFFSET:0
file[3] "track03.bin": FAD:45000, CTRL:4, SSIZE:2352, OFFSET:-8
gdrom: Opened image "/home/keithzg/.reicast/discs/game.gdi"
```

but when I then select Play from the Dreamcast menu, it goes ahead and tells me "Please insert game disc." I've also installed Reicast through RetroPie and on there the very same files run just fine (albeit slowly), so since using someone else's configs I have it working fine on Linux I'm assuming I'm just missing something obvious, but I (clearly) can't figure out what that might be.

**Comment by skmp** [comment]
Check that the region of the bios matches the region of the game

**Comment by skmp** [comment]
Closing this. Such questions should be placed in the forum, http://forum.reicast.com from now on. Thanks.
