### ISSUE TITLE
Crash - Wacky Races GDI

### ISSUE THREAD

**Issue by SuperL2** [reicast/reicast-emulator#878]
Hi,

Has any work been done on reicast to improve Wacky Races? I have a GDI of it, and it crashes the emulator. 

This is one of my favorite games, I would really like to know if any work has been done on this game to make it run better.

**Comment by SuperL2** [comment]
Please, if Wacky Races was on the docket for fixes in Reicast, that would make me so happy. It's one of my favorite games, and I would like nothing more than to play it.

**Comment by hooby3dfx** [comment]
it seems to be loading alright for me on r6, maybe you have a bad image?

there do seem to be some bad rendering issues on the game and menus though
resulting in a mostly black screen with some artifacts.

**Comment by SuperL2** [comment]
Can those rendering issues be fixed? Are those on the docket for Reicast? Please, oh, please, can the developers put this game on their to-do list.

**Comment by skmp** [comment]
@SuperL2 is this still an issue? Should be moved to gamedb

**Comment by SuperL2** [comment]
No one has said anything about it being fixed. I wasn't even aware reicast was still being worked on.

I would still love nothing more than for it to be fixed if possible, though.

**Comment by skmp** [comment]
Can you please test with the build from #1208?

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#106
