### ISSUE TITLE
Dynarec Galaxy s5 5.0 (bug)

### ISSUE THREAD

**Issue by jvabbdac** [reicast/reicast-emulator#879]
If Dynarec is on, crash after bios and go back to emu configure menu. Dynarec off, works fine, but very slow. Version: reicast-android-debug-f5f3332.apk

**Comment by jvabbdac** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1449633608326.txt

**Comment by jvabbdac** [comment]
This problem still on current CI version.

**Comment by sabula310** [comment]
it depend on the game roms is what your telling is that correct

**Comment by jvabbdac** [comment]
No... all kind roms. If you have a S5 (stock rom 5.0), just give a try

**Comment by sabula310** [comment]
---------- Forwarded message ----------

**Comment by skmp** [comment]
Is this still an issue with the latest beta from #1208? Please re-test and report there.
