### ISSUE TITLE
VMU not saving on 5.0

### ISSUE THREAD

**Issue by 47iscool** [reicast/reicast-emulator#880]
Recently aquired a better phone an LG Power which almost the same specs but has 5.0 Lollipop on it and doesn't shutoff like the 4.3 I have. Works great for the most part.

For some reason though it will not save to VMU. Could the issue be related to the new external_SD that 5.0 has? It also won't keep the clock setting and makes me set them on every boot.

**Comment by 47iscool** [comment]
Transferred to the internal phone storage and it now saves to vmu.

**Comment by 47iscool** [comment]
Okay I set the clock and now it doesn't require setting each time.

**Comment by skmp** [comment]
Can you retest with #1208 and report there if this still an issue?
