### ISSUE TITLE
fail build on linux

### ISSUE THREAD

**Issue by sl1pkn07** [reicast/reicast-emulator#883]
with GCC 5.3.0 on d8dabb713d9a9aeef090297593206af51de01273

    Platform: x64 sse4_1
    Makefile:314: *** mixed implicit and normal rules: deprecated syntax
    Makefile:319: warning: overriding recipe for target 'obj-dreamcast-x64'
    Makefile:315: warning: ignoring old recipe for target 'obj-dreamcast-x64'
    Makefile:318: *** mixed implicit and normal rules: deprecated syntax
    Makefile:319: warning: overriding recipe for target 'sse4_1/%.build_obj'
    Makefile:315: warning: ignoring old recipe for target 'sse4_1/%.build_obj'
    Makefile:323: warning: overriding recipe for target 'obj-dreamcast-x64'
    Makefile:319: warning: ignoring old recipe for target 'obj-dreamcast-x64'
    Makefile:322: *** mixed implicit and normal rules: deprecated syntax
    Makefile:323: warning: overriding recipe for target 'sse4_1/%.build_obj'
    Makefile:319: warning: ignoring old recipe for target 'sse4_1/%.build_obj'
    make: *** No rule to make target '../../core/%.S', needed by 'obj-dreamcast-x64'.  Stop.
    make: Leaving directory '/tmp/makepkg/reicast-emulator-git/src/reicast-emulator/shell/linux'

greetings

**Comment by Marc34** [comment]
Same problem on Linux Mint.

**Comment by Holzhaus** [comment]
Please try again with latest master.

**Comment by sl1pkn07** [comment]
same

**Comment by Holzhaus** [comment]
What version of GNU Make are you using?

**Comment by Shoegzer** [comment]
@Holzhaus please re-open - it's still failing.  I get:

make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Error 1
make: *** Waiting for unfinished jobs....

**Comment by Marc34** [comment]
Now there is some build process, but it fails with this message :

make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Erreur 1

**Comment by sl1pkn07** [comment]
g++   -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_LINUX_x64 -D TARGET_NO_AREC -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_X11 -fopenmp -msse4.1   -fexceptions -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_X11  -D USE_EVDEV -D USE_JOYSTICK -D USE_ALSA -D USE_OSS -D USE_PULSEAUDIO -DTARGET_SOFTREND ../../core/rend/soft/softrend.cpp -o obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj
    ../../core/rend/soft/softrend.cpp: In member function '__m128 softrend::shuffle_pixel(__m128)':
    ../../core/rend/soft/softrend.cpp:1167:77: error: invalid cast of an rvalue expression of type '__m128i {aka __vector(2) long long int}' to type '__m128& {aka __vector(4) float&}'
    return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1, 0)));
                                                                             ^
    Makefile:317: recipe for target 'obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj' failed
    make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Error 1

**Comment by skmp** [comment]
The other issue looks some conflict with your compiler. I'm on fedora 22 and the code compiled alright. Can you try replacing the ref cast with a c++ reinterpret cast there?

**Comment by sl1pkn07** [comment]
with clang 3.7

http://sl1pkn07.wtf/paste/view/db5ef2c3

**Comment by skmp** [comment]
@Shoegzer  @sl1pkn07 how about w/ branch fix/softrend-fugly-casts ? openmp and glibc still are requirement

**Comment by sl1pkn07** [comment]
fix/softrend-fugly-casts build ok. but https://github.com/reicast/reicast-emulator/issues/847 still fail

**Comment by olegantonyan** [comment]
gcc 4.8.3 openSUSE 13.2, latest master (0e4949e7bdc66b564c9ec8880f8084f95d0e587e) same error
```
../../core/rend/soft/softrend.cpp: In member function ‘__m128 softrend::shuffle_pixel(__m128)’:
../../core/rend/soft/softrend.cpp:1167:77: error: invalid cast of an rvalue expression of type ‘__m128i {aka __vector(2) long long int}’ to type ‘__m128& {aka __vector(4) float&}’
   return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1, 0)));
                                                                             ^
Makefile:317: recipe for target 'obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj' failed
make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Error 1
```

**Comment by xobs** [comment]
Commit 9bd7e1e2b6e8ec353845c2e871f463534e3c4f5e fixes building on Fedora F23.

**Comment by maximu** [comment]
Same problem in Arch linux with GCC 5.3

**Comment by Maturion** [comment]
Still have this problem. I'm on Mint 17.3.
This is where it fails:
`../../core/rend/soft/softrend.cpp: In member function ‘__m128 softrend::shuffle_pixel(__m128)’:
../../core/rend/soft/softrend.cpp:1167:77: error: invalid cast of an rvalue expression of type ‘__m128i {aka __vector(2) long long int}’ to type ‘__m128& {aka __vector(4) float&}’
   return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1, 0)));
`

**Comment by Marc34** [comment]
same problem in Ubunutu 16.04 :

g++   -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_LINUX_x64 -D TARGET_NO_AREC -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_X11 -fopenmp -msse4.1   -fexceptions -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_X11  -D USE_EVDEV -D USE_JOYSTICK -D USE_ALSA -D USE_OSS -DTARGET_SOFTREND ../../core/rend/soft/softrend.cpp -o obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj
../../core/rend/soft/softrend.cpp: In member function ‘__m128 softrend::shuffle_pixel(__m128)’:
../../core/rend/soft/softrend.cpp:1167:77: error: invalid cast of an rvalue expression of type ‘__m128i {aka __vector(2) long long int}’ to type ‘__m128& {aka __vector(4) float&}’
   return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1, 0)));
                                                                             ^
Makefile:317: recipe for target 'obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj' failed
make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Error 1

**Comment by Marc34** [comment]
still failing...

**Comment by sabula310** [comment]
well did you have supported for 5.1.1 android and if you do try to see the
problem with code ing error finder and check for support of game it a lot
depend on device fix this support problem and you well find your problem

**Comment by ProfessorKaos64** [comment]
I can confirm Pull Request #914 fixes the error [noted above](https://github.com/reicast/reicast-emulator/issues/883#issuecomment-192726124) this issue for me on Debian 8. I could not build it on my meager 5$ USD a month VPS on digital ocean (yes I have swap enabled), but on my desktop rig, it built fine. I build using pbuilder as well for clean testing.
