### ISSUE TITLE
sys/cdefs.h is required, but is not a standard header

### ISSUE THREAD

**Issue by FlyingJester** [reicast/reicast-emulator#886]
It seems that several files depend on sys/cdefs.h which is not available on musl Linux systems.

**Comment by skmp** [comment]
It looks like cdefs is part of glibc. Do you have an alternative header to propose?

From a quick grepping it's not used from reicast code but from some 3rd party deps (lws and some android-only code)

**Comment by skmp** [comment]
Closing as part of ticket cleanup. Please report in chat.reicast.com if still an issue
