### ISSUE TITLE
Android Reicast Improved Touch Buttons part 2

### ISSUE THREAD

**Issue by williansti** [reicast/reicast-emulator#887]
inspired by Marcthesparta i also did my version of, Touch Buttons... i am sharing it is perhaps useful to the project or not.

![buttons](https://cloud.githubusercontent.com/assets/10545674/11963529/b99bcee6-a8ce-11e5-8e98-b87f92609eb3.png)
![screendreamwti](https://cloud.githubusercontent.com/assets/10545674/11963533/c18970a4-a8ce-11e5-920c-3a418d3efcee.png)

Previously: https://github.com/reicast/reicast-emulator/issues/115
Download: http://www.mediafire.com/view/u1n4jnun761n09t/buttons.png

**Comment by blackman91** [comment]
Please reupload, link dead.

**Comment by LoungeKatt** [comment]
You can also save the image directly from the post

**Comment by williansti** [comment]
@blackman91 @LoungeKatt sorry my friends, as i did not see interested in mod, i ended up erasing it in cleaning my mediafire, a time ago, If anyone ever got download, please resubmit here

**Comment by williansti** [comment]
It's been a long time since I've used reicast, i'm going to make time for this month to, test a new version and recreate this mod in an improved way.

**Comment by AbandonedCart** [comment]
Closing this as something for the forums. Great work on the buttons, though!
