### ISSUE TITLE
[Linux x64][GDI]Grandia II unable to load saved games with DC bios.

### ISSUE THREAD

**Issue by gamax92** [reicast/reicast-emulator#891]
Whenever I go to load a saved game using the real DC bios, it'll fade out to black from the title screen and then nothing will happen.
I'll start to see lines like this.
`reicast git/n - 10.00 (0.00) - 100.00 - V: 59.95 (inf, NTSC480i59.95) R: 0.00+0.00 VTX: 0.00 , MIPS: 0.00`
Note the "inf", music carries on for a little bit, starts to loop a short section, and then stops entirely.
Doing a New Game works properly and I've been playing on that normally with minimal issues.

When REIOS is used instead of the real bios, Load Game works just fine and allows me to continue.

I'm using Ubuntu 15.10 x64, on the fix/softrend-fugly-casts branch since master won't compile.

EDIT: Retested, issue is still present on latest commit 76b09876f8b8c99a7a1e6d0d61b06e9a5decdc0e, tested on Arch Linux x64

**Comment by skmp** [comment]
Is this still an issue? Is this game specific? I think it belongs to http://forums.reicast.com or the gamedb.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#105
