### ISSUE TITLE
GetRTC_now() does not set timeinfo.tm_isdst and may give time an hour off

### ISSUE THREAD

**Issue by gamax92** [reicast/reicast-emulator#892]
In `core/hw/aica/aica_if.cpp`, when calculating `"the known dc date"` timeinfo.tm_isdst is never set and results in a RTC time that is an hour off.

Also, Why calculate the time since 1998-11-27, and then add in the time between 1950-1-1 to 1998-11-27, just calculate the time difference since 1950-1-1.

**Comment by skmp** [comment]
Is this still an issue in latest master? @gamax92 can you make a PR that fixes it? Thanks :)

**Comment by baka0815** [comment]
The file hasn't been touched since 2013-12-28, so it's very likely the behavior is still the same.
https://github.com/reicast/reicast-emulator/blob/a5cf5406cbbaf9dd849a56871ad48ddec0676377/core/hw/aica/aica_if.cpp#L26

**Comment by skmp** [comment]
Should be fixed after #1523
