### ISSUE TITLE
Reicast attempts to read modified track names when opening GDI

### ISSUE THREAD

**Issue by elsonrodriguez** [reicast/reicast-emulator#894]
When trying to run Quake, it attempts to load Quatrack01.bin, instead of track01.bin.

```
open("Quatrack01.bin", O_RDONLY)        = -1 ENOENT (No such file or directory)
```

Renaming the files to include the first three letters of the .gdi file works. Is this the intended behaviour?

**Comment by AbandonedCart** [comment]
Massive improvements have been made that (at least most likely) resolved this. Please reopen if the issue is still there.
