### ISSUE TITLE
Elemental Gimmick Gear text corrupted.

### ISSUE THREAD

**Issue by blackman91** [reicast/reicast-emulator#899]
The game boots fine but the text during gameplay is corrupted and unreadable, this happens in all revisions, this is one of the best dreamcast action rpgs, hope it gets fixed.

**Comment by blackman91** [comment]
As of today the same happens in the reicast dev builds but the text is fine in the stable version.

**Comment by blackman91** [comment]
Comparation:

Reicast from the playstore:
![screenshot_20180516-231514](https://user-images.githubusercontent.com/6578180/40156654-5e6c6ebe-5960-11e8-8083-47b4c78cc011.png)

Recent dev builds:
![screenshot_20180516-230937](https://user-images.githubusercontent.com/6578180/40156665-6c850420-5960-11e8-846a-7b9ddfbf1753.png)

**Comment by blackman91** [comment]
Could you add the same labels to this issue too please, it is a similar regression:
https://github.com/reicast/reicast-emulator/issues/1000

**Comment by LoungeKatt** [comment]
One image per issue is plenty. The point is to aid a text explanation, not replace it.

**Comment by skmp** [comment]
@blackman91 can you please migrate all screenshots & text to gamedb#8? I'll close this to declutter the core tracker.

**Comment by skmp** [comment]
thx

**Comment by blackman91** [comment]
This is fixed now, if you have this problem try latest reicast beta:
http://builds.reicast.com/

Great job reicast team.
