### ISSUE TITLE
Fix regression on Gauntlet Legends [TMU->Reg_TCNT]

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#9]
It freezes while loading. Register related IIRC.

Update. It's TMU->Reg_TCNT.

**Comment by skmp** [comment]
Fixed. 

The issue was me forgetting to implement interrupts for tmu, then remembering having it done. Ta-duh.

**Comment by hooby3dfx** [comment]
Sweet, tested last night.
Does this fix anything else?
