### ISSUE TITLE
Unreal Tournament Split Screen Rendering Bug

### ISSUE THREAD

**Issue by bwRavencl** [reicast/reicast-emulator#90]
The rendering in single player mode works with minor glitches.

Launching a split screen game with two or more player results in a black screen before spawning:
![screen](https://f.cloud.github.com/assets/775727/1861727/9c0b77c2-77c6-11e3-9b4b-94676f70a1fb.png)

After pressing the necessary buttons to begin the match only a few elements are visible, like the weapon and player models of enemies:
![screen1](https://f.cloud.github.com/assets/775727/1861765/38086d74-77c7-11e3-868e-fa392b69f037.png)

When pausing the game, rendering seems to work just fine in the menu apart from minor glitches (note no split screen is being used for the menus):
![screen2](https://f.cloud.github.com/assets/775727/1861774/5198d0a8-77c7-11e3-8e10-9eb48cc4f620.png)

This is another example of the same issue this time with three player split screen:
![screen3](https://f.cloud.github.com/assets/775727/1861780/75497c8c-77c7-11e3-8f39-10c32559aaac.png)

This issue exists on both my devices Nexus 5, as well as my Transformer Prime tablet. A disabled dynarec makes no difference.
I'm willing to look into this, but I have no clue where to start looking as there are no suspicious Logcat messages either.
Maybe somebody here has some idea what could be the source of this problem!

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#29
