### ISSUE TITLE
Force GPU v6 configs crash

### ISSUE THREAD

**Issue by rica32** [reicast/reicast-emulator#904]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1455050906118.txt

**Comment by LoungeKatt** [comment]
Does the device you are using have EGL 3? If not, why not use the default configuration?

**Comment by sabula310** [comment]
no but i have android 5.1.1 software update

**Comment by LoungeKatt** [comment]
Android 5.1.1 doesn't change the hardware. If there is no EGL 3, an EGL 3 call will cause a crash.

**Comment by rica32** [comment]
I don´t know if it has, sorry :P 
But it doesn´t crash if I set that option off. When i try play Shenmue 1 i cant get outside of the house, cause it crashes.

**Comment by LoungeKatt** [comment]
That most likely means the device doesn't have the hardware support. While EGL 3 is currently not as promising as an upgrade sounds on it's own, a device that can support it will at least still run the emulator when it is enabled.

**Comment by AbandonedCart** [comment]
This has been since discarded and will be replaced by wizardry in the flyinghead branches
