### ISSUE TITLE
Ubuntu 15.10 nvidia - X Error of failed request

### ISSUE THREAD

**Issue by salcin** [reicast/reicast-emulator#906]
Hi,

I have compiled reicast on my RetroPie in 64 bit without error. But when I launch reicast I get this error :

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Value in failed request:  0x0
  Serial number of failed request:  31
  Current serial number in output stream:  32

```

I use the nvidia-304 proprietary driver which works welll with other emulators as ppsspp or mupen64plus.

`$ ldd /opt/retropie/emulators/reicast/bin/reicast
        linux-vdso.so.1 =>  (0x00007ffd307cb000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f31c3294000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f31c3090000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f31c2e71000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f31c2b37000)
        libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f31c2842000)
        libGL.so.1 => /usr/lib/nvidia-304/libGL.so.1 (0x00007f31c2524000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f31c21a2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f31c1e9a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f31c1c82000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f31c18b8000)
        /lib64/ld-linux-x86-64.so.2 (0x00005625ce6bb000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f31c1697000)
        libnvidia-tls.so.304.131 => /usr/lib/nvidia-304/tls/libnvidia-tls.so.304.131 (0x00007f31c1493000)
        libnvidia-glcore.so.304.131 => /usr/lib/nvidia-304/libnvidia-glcore.so.304.131 (0x00007f31bf0a9000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f31bee97000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f31bec92000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f31bea8c000)
`

[EDIT]

It seems that newer X servers disable indirect GLX by default for security reasons. src: [https://devtalk.nvidia.com/default/topic/891349/quadro-k600-x_glxcreatecontext-issue/?offset=6](url)

If I add Option "AllowIndirectGLXProtocol" "True" at my xorg.conf and i run xfce with startxfce +iglx i get a other error: X Error of failed request:  BadAlloc (insufficient resources for operation)

[/EDIT]

Thank you in advance.

**Comment by skmp** [comment]
(Closing as part of ticket cleanup. Should work fine in master, if not report back in chat.reicast.com)
