### ISSUE TITLE
Reicast won't recognize or boot games anymore

### ISSUE THREAD

**Issue by Gyurn** [reicast/reicast-emulator#909]
Hey all, was using r6 on my Nvidia Shield Tablet K1, 5.1.1, it played all my .gdi/.cdi files, and now it won't even recognize most of the .gdi/.cdi, and it won't boot most that it does recognize (instant crash to home).  AND the L2 and R2 buttons of my shield controller won't map anymore.  

I'm very confused what happened??

Games that auto crash, Grandia 2.gdi, Shenumue.gdi, Shunumue2.gdi, Sonic Adventure.gdi, Evolution.gdi, legacy of kain.gdi

Games that aren't recognized anymore, Codeveronica.gdi, Marvel v Capcom2.gdi, Skies of Arcadia.gdi,

Games it still boots, RE3.cdi, SonicAdventure2.gdi, Phantasystar2.gdi, soulcalibur.cdi, evolution2.gdi

It's so weird, the only thing I could think of that I did was delete redundant files on my SD Card with ES File Explorer, but I've reinstalled Reicast r6, and a development version r7 including the bios each time, and I get the same results...  

Any of those more tech savvy then me please help!  My last resort is a factory reset and reinstall everything... 

**EDIT**  
I must've done something to the .gdi files themselves, I replaced them and they run again.  I also did a clean install on my Shield.  

However the L2 and R2 are still unresponsive

**Comment by LoungeKatt** [comment]
The L2 and R2 are an ongoing issue. It's been a while, so I forget which was which. They are either a button on the Dreamcast and an axis on Android or the other way around. Regardless, getting them to work is trying to simulate the action for the Dreamcast using the one from Android. Android is not very fond of simulating user input and tends to believe any attempt would only be used in malware.

**Comment by PeteBurgess** [comment]
There is a proper controller API for Shield. I was going to have a crack at it but I'm a c# guy, and a very basic one at that. My intention was to do something along the lines of "if hardware == Shield then auto-assign controller 1, controller 2 if present, controller 3..." etc. However, being tragically crap at this sort of thing, I couldn't quite follow the flow of what gamepads got assigned where.

**Comment by LoungeKatt** [comment]
@PeteBurgess How would that differ from the current setup outside of moving the Java code to C#? 
If it is C#, then that is intended for Unity. It would still require converting the trigger values, as well.

**Comment by PeteBurgess** [comment]
Well I wouldn't do it in C#, I'd try to stick to Java as they're really not that different, but I'd struggle - that's my point. As for how it differs, I'd be using the actual Shield controller API so, in an ideal world, R2 and L2 would map correctly. Currently when you go into the menus to map buttons you can only select L1 and R1, L2 and R2 do nothing.

Either way it's pretty academic as I just don't have the skillset to do it, which is a shame as an upscaled Metropolis Street Racer on a large TV sounds rather lovely.

**Comment by skmp** [comment]
Closing this - reopen if issue is still relevant
