### ISSUE TITLE
Shenmue (PAL) [Maple-Storage/IRQ]

### ISSUE THREAD

**Issue by MrPsyMan** [reicast/reicast-emulator#91]
There's an error condition on maple when switching to 60Hz on the start of the game.

The storage device (that's the VMU normally) will not initiate because a related interrupt is either not sent or ignored.
As a result, loading the game save becomes impossible and saving will corrupt the whole VMU.

The storage device initiates properly at 50Hz when the frequency switch does not happen.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#30
