### ISSUE TITLE
A new reicast logo design with concentric circles

### ISSUE THREAD

**Issue by maz-1** [reicast/reicast-emulator#911]
I made a reicast icon with concentric circles instead of polygons :

![reicast](https://cloud.githubusercontent.com/assets/5277060/14014731/568b7cc4-f1ef-11e5-9672-1baf6b057e32.png)
[reicast.svg.zip](https://github.com/reicast/reicast-emulator/files/187637/reicast.svg.zip)

I would like to know your advice.

**Comment by Fantomas228** [comment]
I think its very nice, good job.

**Comment by Zetchzie** [comment]
it looks nice but i see a "G" but if you try to look at it as a swirl then it looks right lol

**Comment by hooby3dfx** [comment]
Maybe rotate 45 degrees to the right and get rid of the sharp edge in the
middle?

**Comment by maz-1** [comment]
@hooby3dfx 
You mean 45 degrees clockwise?

**Comment by gamax92** [comment]
It doesn't really look like a swirl anymore and more like the letter G, and the sharp corners in the center aren't helping that.

**Comment by LoungeKatt** [comment]
The original console logo didn't look... robotic. I'm not sure that really says Dreamcast emulator.

![Dreamcast logo](http://vignette4.wikia.nocookie.net/sonic/images/6/66/Sega-dreamcast-logo.jpg/revision/latest?cb=20110115032043)

**Comment by AbandonedCart** [comment]
Closing this as something for the forums. Nice logo!
