### ISSUE TITLE
Launch the bios/game and enter the date/time every time (RetroPie)

### ISSUE THREAD

**Issue by lcsjunior** [reicast/reicast-emulator#922]
Every time I go to emulate a game with reicast have to set date/time in (RetroPie - Raspberry Pi).

Recent discussion:
https://retropie.org.uk/forum/topic/364/every-time-i-play-dreamcast-displays-the-setting-screen-time-date/45
1 - I've done the step of five minutes in many ways
http://wiki.reicast.com/index.php/Help

2 - I tested with another BIOS

3 - Already test module RTC

They may suggest a starting point to solve this?!

**Comment by sergiobenrocha2** [comment]
It's a known issue, see #863

**Comment by Elenedeath** [comment]
i found a fix, the save of this file "dc_nvmem.bin" is not implemented on reicast without this you cant save the date and time.
i put a "dc_nvmem.bin" create with "nulldc" emulator on the reicast data folder and never have the date settings

i try this on windows emulator and on my retropie and work great

**Comment by Elenedeath** [comment]
i found a fix need to see https://github.com/reicast/reicast-emulator/issues/863

**Comment by AbandonedCart** [comment]
This has finally been resolved across platforms.
