### ISSUE TITLE
Crash on input with GPD XD

### ISSUE THREAD

**Issue by nuclearsandwich** [reicast/reicast-emulator#928]
Not yet sure what other details to provide. Here are the logs

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1463239320278.txt

**Comment by Smoker1** [comment]
Works fine on my XD. Might be the Settings you are using. Dont know how I have mine working. Did give me Problems at one point, but now works great. 
Is Reicast still being worked on???? Last CI Build was back on May 22nd.

**Comment by AbandonedCart** [comment]
This appears to be resolved. Please reopen if it is not.
