### ISSUE TITLE
Capcom vs Snk 2 is fixed. Any plans to fix Cacom vs Snk 1_

### ISSUE THREAD

**Issue by RaduNastase** [reicast/reicast-emulator#935]
So, CVS2 work virtually perfect, but CVS1 still has those glitches around the characters (lines that appear when moving). Any chance in fixing those in the near future? Thanks!!

Oh, and is there any way to increase compatibility with Adreno GPUs? Many 3D games (Project Justice, Doa) have more graphical glitches on Adreno compared to Mali ).

Thanks again!

**Comment by sabula310** [comment]
Omarsupercool8@gmail.com

**Comment by sabula310** [comment]
Omarsupercool8@gmail.com
---------- Forwarded message ----------

**Comment by RaduNastase** [comment]
You mean in CVS1 you don't have some sublte vertical lines around your character wile moving? Like in this video 

https://www.youtube.com/watch?v=eV0Amp7Jfu8

**Comment by LoungeKatt** [comment]
I don't think that comment was intentional. It looks like a copy of the post made in #938

**Comment by Naccarato** [comment]
I noticed regression from NullDC to Reicast for Capcom vs SNK.  The healthbar/Super meter is missing pixels (Looks like dithering with transparency mixed together).  The KO is also clipping polygons.  It's in the video posted, though it's hard to notice the health bar issues, but you can notice them flashing.

**Comment by RaduNastase** [comment]
If it helps any of the devs, i found out that if i enable High Internal Resolution in Retroarch while playing the PSX version of CVS1, i get the exact same graphical glitches around the characters. On the other hand, the glitches are gone when i leave the option disabled and run the game in native resolution.

**Comment by RaduNastase** [comment]
So, did the latest September builds fix the CVS1 gfx glitches? (can't test right now as i'm on an old "work phone" for a few weeks) Thanks!

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#81
