### ISSUE TITLE
games won't load

### ISSUE THREAD

**Issue by xTMODx** [reicast/reicast-emulator#936]
I am trying to load Soul Calibur or Dead or Alive in gdi format but it wont load. Boot to bios works perfectly.
My device is Galaxy Note 4 Exynos running android 6.0.1 latest reicast build.
The bios files are on the internal storage and games are on my external storage but with games on the internal storage it isnt working too. Is there anything i can try?

**Comment by Zetchzie** [comment]
same issue with Sonic Adventure 1/2 in gdi. using latest nightly on LG G2

**Comment by LoungeKatt** [comment]
Try another format. GDI is a bit tricky due to the additional required files and instability.

**Comment by xTMODx** [comment]
Ok i tested it from another (source) so the one that match the tosec db "Soul Calibur v1.001 (1999)(Namco)(PAL)(M4)[!]" seems to work and before i had "Soulcalibur (Europe) (En,Fr,De,Es)" that match the redump db and it didnt work, both are in gdi format. Will test more stuff from both db.

**Comment by TheBurgerGuy** [comment]
@xTMODx hey what android version are you Using And phone

**Comment by xTMODx** [comment]
"My device is Galaxy Note 4 Exynos running android 6.0.1 latest reicast build."

**Comment by TheBurgerGuy** [comment]
I have Samsung Galaxy Note 4 Android 5.1.1  The only one it's Running flawless is MVC2 others were fine but don't know what happened..

**Comment by xTMODx** [comment]
do you have the qualcomm or the exynos version of the note 4?

**Comment by TheBurgerGuy** [comment]
I believe qualcomm

**Comment by xTMODx** [comment]
do you have the model number N910F (Qualcomm) or N910C (Exynos) there are other model number maybe you can tell me and i will say you if it is qualcomm or exynos

**Comment by TheBurgerGuy** [comment]
It's SM-N910T

**Comment by xTMODx** [comment]
http://pdadb.net/index.php?m=specs&id=6722&view=1&c=samsung_sm-n910t_galaxy_note_4_lte-a_samsung_muscat it has the qualcomm cpu

**Comment by TheBurgerGuy** [comment]
Yep it does. I don't understand what that means,

**Comment by xTMODx** [comment]
"I have Samsung Galaxy Note 4 Android 5.1.1 The only one it's Running flawless is MVC2 others were fine but don't know what happened.." i dont understand what exactly is your problem?

**Comment by TheBurgerGuy** [comment]
Ok so I have sonic adventure 2 I stopped playing with the settings, the Game runs Extremely smooth but too fast to play. Mission Confidential ran great but not anymore neither does Capcom vs snk 2 millenum fight 2001 does even run anymore. I just moved all my games to the Extension SD card and sa2 Runs Flawless?

**Comment by xTMODx** [comment]
you mean the problems start after update reicast?

**Comment by TheBurgerGuy** [comment]
No I think the problems started when I had My games on Actual phone Memory instead of Microsd. Though I can't run the official reicast from Play store I'm running The one from Lollipop link on YouTube

**Comment by xTMODx** [comment]
You can try to download here http://builds.reicast.com/ the latest build apk for your phone and test it
You should also test the frame limiter if it runs too fast.
For me it works both fine on microSD and on the internal storage.

**Comment by TheBurgerGuy** [comment]
I'll take a look at it

**Comment by xTMODx** [comment]
You can also try another region if you can, because for me the pal soul calibur game runs with more glitches than the ntsc version.

**Comment by TheBurgerGuy** [comment]
I'm going to try different bios maybe that's it

**Comment by xTMODx** [comment]
no no the bios, i mean different region of the game itself

**Comment by TheBurgerGuy** [comment]
I'm going to see what region is

**Comment by TheBurgerGuy** [comment]
Ok so I got the us region game and doesn't run fast all it does it make the sound choppy

**Comment by LoungeKatt** [comment]
Some games are slightly different for each region. It is recommended you use a BIOS for the same region as the game. Since there isn't an actual issue with the emulator, or at least not one that can be specifically documented as anything "broken", this issue is being closed.

**Comment by haderach7777** [comment]
i tried lot of game, and all my game won't boot on last version of reicast(73e2691), my phone is the galaxy note 4 sm-n910f. Can you help me?? It is a problem with the options?

**Comment by LoungeKatt** [comment]
Is everything properly configured? Working BIOS? Valid game image?

**Comment by TheBurgerGuy** [comment]
I have everything Working flawless @Loungekart Update Software to Android 6.0 Marshmallow and have Samsung Galaxy Note 4 everything is Epic. Also sonic adventure 2 I's working Full speed and Not Extremely fast So 2 thumbs up from me bud

**Comment by haderach7777** [comment]
thanks TheBurgerGuy, i will try tu update to marshmallow

**Comment by TheBurgerGuy** [comment]
Is there a way I can send you a recording of how recast runs on Marshmallow ?

**Comment by haderach7777** [comment]
yes, you can send the video to http://dl.free.fr/ , you just have to clic to ''parcourir'', "envoyer" and to copy the link here, thanks in advance

**Comment by TheBurgerGuy** [comment]
https://www.dropbox.com/sh/flw7twqg1686ymd/AADyuppbjEH-s8S-yWJv2U4Ra?dl=0

**Comment by haderach7777** [comment]
sonic run great on your video, but your note is the galaxy note 4 sm-n910t, mine is the galaxy note 4 sm-n910f(european)

**Comment by TheBurgerGuy** [comment]
Your device has a manual update my brother ready I looked it up to upgrade to 6.0.1

**Comment by TheBurgerGuy** [comment]
You need to download Samsung kies 3 on your computer and then Update manually and the download is about 1.4 Gigabyte and then your phone will be at full force bro

**Comment by haderach7777** [comment]
i will try update later, thank you for all your help TheBurgerGuy

**Comment by TheBurgerGuy** [comment]
No problem man and your welcome
