### ISSUE TITLE
Bt gamepad

### ISSUE THREAD

**Issue by GunneR007** [reicast/reicast-emulator#937]
Reicast crashes when opening here is the log and hope use can fix this 

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1465931757072.txt

**Comment by GunneR007** [comment]
Edit to let use know that I'm using a moga controller and it crashes  because of that

**Comment by AbandonedCart** [comment]
This has been resolved, but please reopen if it resurfaces.
