### ISSUE TITLE
Reicast on Samsung Galaxy Note 4 Android lollipop 5.1.1

### ISSUE THREAD

**Issue by TheBurgerGuy** [reicast/reicast-emulator#938]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1466121650279.txt

The bios boot but when load Games it doesn't work at all.

http://reicast-builds.s3.amazonaws.com/builds/heads/feat/no-direct-memmap-e2a7029/reicast-android-debug-e2a7029.apk

This version Of Reicast Boots bios and Works But he problem is That It runs the general part too Fast and not really playable. Though if there were some modifications For this I believe it would work Smooth. I would use my device for any Feedback if possible thanKS again keep up the good work.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1466479212116.txt

**Comment by TheBurgerGuy** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1466121650279.txt

**Comment by TheBurgerGuy** [comment]
The bios boot but when load Games it doesn't work at all.

**Comment by TheBurgerGuy** [comment]
http://reicast-builds.s3.amazonaws.com/builds/heads/feat/no-direct-memmap-e2a7029/reicast-android-debug-e2a7029.apk

**Comment by TheBurgerGuy** [comment]
This version Of Reicast Boots bios and Works But he problem is That It runs the general part too Fast and not really playable. Though if there were some modifications For this I believe it would work Smooth. I would use my device for any Feedback if possible thanKS again keep up the good work.

**Comment by TheBurgerGuy** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1466479212116.txt

**Comment by TheBurgerGuy** [comment]
This is the report

**Comment by LoungeKatt** [comment]
Are you sure it is a valid game? I am using the same device and do not have this issue.

I am searching the logs, but have not found an exact reason it doesn't work yet.

**Comment by TheBurgerGuy** [comment]
I'm running Sonic Adventure 2 And tried Certain setting and It runs So fast it's unplayable I have Samsung Galaxy Note 4 5.1.1 Version Don't know if there Is a better Setting for t his Device.

**Comment by TheBurgerGuy** [comment]
Ok so I downloaded reicast R7 R7 Version From Facebook Link and That one doesn't run Sonic Adventure 2 in a playable Way it plays too Fast There's no lag but too fast sorry for redundancy Anyways I downloaded Mvc2 For dreamcast and It runs Flawlessly No choppyNess sprites Are In tact Not like before and Also try another

**Comment by LoungeKatt** [comment]
Sounds like a configuration issue. Disabling audio, using turbo mode, etc will make it play too fast. You may want to try resetting data and going through initial setup again.

**Comment by TheBurgerGuy** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1466550123102.txt.   this is the log when I run the game on software render mode I tried All other options and This is the closest it will run, but too fast cleared cache and data still no work. I know it can't be the device it runs Mvc 2 flawlessly

**Comment by TheBurgerGuy** [comment]
Tried Mission confidential and Capcom vs snk 2 Millennium fight Flawless maybe it's the rom if you any sonic Adventure 2 rom but don't know for sure.

**Comment by LoungeKatt** [comment]
If other games work, then try ripping a new copy of the ROM.

Sonic Adventure has been known to have issues.

**Comment by TheBurgerGuy** [comment]
I'm having Issues With house of dead 2 Any ideas I keep getting error Codes when it's played.

**Comment by LoungeKatt** [comment]
It is extremely hard to determine the cause of error codes without the error codes.

If it is not the same issue, please post to one that is similar or start a new one if no similar issues exist.

**Comment by TheBurgerGuy** [comment]
Ok
