### ISSUE TITLE
House Of Dead 2 Error Messages

### ISSUE THREAD

**Issue by TheBurgerGuy** [reicast/reicast-emulator#939]
The game Is Playable but has Error logs pop up during game play. Also ends game after game Play. I'm using samsung Galaxy Note 4 Android 5.1.1. Also I Noticed When Converting CDI ---> GDI games work better in a Way but but still non playable though.

**Comment by LoungeKatt** [comment]
Can you post the error messages?

Make sure your BIOS and disk image are from the same region, which shouldn't be an issue when using a BIOS created from your own console and legal back-ups of games you have purchased.
(Just a friendly reminder that requesting support for pirated games is a legal issue and support is provided with the assumption that all games discussed are images of purchased hard copies)
