### ISSUE TITLE
Sonic Adventure 2- Boss shadow missing

### ISSUE THREAD

**Issue by jose325i** [reicast/reicast-emulator#94]
I was playing through Sonic Adventure 2 on reicast r5 and everything was mostly great (other than the flickering z-buffer issue on 2-3 stages). Runs full speed, thanks for all the hard work!

However, I got to the King Boom Boo boss battle and the shadow is missing, making the boss impossible to beat. I will upload my vmu save to dropbox and post a link to it later(dropbox is down right now). With the save, just go to story mode and select "hero story" and it will take you straight to the boss battle.

Tested on:
1. HTC One S- Snapdragon S4/Adreno 225
2. LG G2- Snapdragon 800/Adreno 330

Picture of correct shadow:
http://imagizer.imageshack.us/v2/800x600q90/545/nrei.png

**Comment by BonzaiThePenguin** [comment]
Here's a build that re-enables PVR rendering. It seems to work fine, and King Boom Boo is completely playable. Really don't understand why the option was permanently removed, to the point that there's a toggle button in the app that does nothing – I seriously just uncommented a single line of code and re-compiled it.

http://ivideoapp.com/random/reicast-debug.apk

Note that this is based off the source from 10/22/2014, as some of the newer versions have weird bugs and crashes that have not yet been fixed.

**Comment by BonzaiThePenguin** [comment]
The line of code is `//DrawModVols();` in core/rend/gles/gldraw.cpp, if anyone wants to compile it themselves. The shadow volumes it renders are far from perfect, but it's better than nothing.

**Comment by hooby3dfx** [comment]
thanks! hopefully @skmp can weigh in on this one.

**Comment by neko68k** [comment]
The reasons it's disabled are it's very slow on many devices and the
quality ranges from kinda visible speckles to totally invisible to
completely broken. Better to leave it out and save the support requests for
issues that are more pressing.
On Jan 26, 2015 6:52 PM, "hooby3dfx" <notifications@github.com> wrote:
>
> thanks! hopefully @skmp can weigh in on this one.
>
> On Sat, Jan 24, 2015 at 8:03 AM, Mike McFadden <notifications@github.com>
> wrote:
>
> > The line of code is //DrawModVols(); in core/rend/gles/gldraw.cpp, if
> > anyone wants to compile it themselves. The shadow volumes it renders
are
> > far from perfect, but it's better than nothing.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/reicast/reicast-emulator/issues/94#issuecomment-71315661>

**Comment by GamerPro7000** [comment]
+BonzailThePenguin your application for debugging PVR reicast does not work on my android device can you help me?

**Comment by BonzaiThePenguin** [comment]
> +BonzailThePenguin your application for debugging PVR reicast does not work on my android device can you help me?

I cannot. All I did was re-enable the feature, I can't do much to change this part of it:

> The reasons it's disabled are it's very slow on many devices and the
quality ranges from kinda visible speckles to totally invisible to
completely broken.

**Comment by strider-97** [comment]
I know this is old but I don't know how you passed some levels without it kicking you out,I played one misson with tails(in Sonic adventure 2) it didn't work so i fixed it, It ran great until I played the evil story as eggman (first mission) it freezes at the loading screen and exits me to the menu of the app is there any tip to fix this problem ? Please help me if you know a solution.

**Comment by skmp** [comment]
This should be fixed now. Re-open if it is still an issue
