### ISSUE TITLE
Add background process / pausing support for android

### ISSUE THREAD

**Issue by haderach7777** [reicast/reicast-emulator#940]
This has been discussed in the past, @LoungeKatt knows how to make the OS not kill the application, @skmp knows how to add the pausing functionality.

~Do we have any other tickets for this?~ Merging with #152

---

Was

Title: reicast stop working when i push the power button

Desc:
Hello everyone! my phone is samsung galaxy s3 gt-i9300, and when i want to pause my phone, when i play a game, i push the power button of my phone, and when i want to come back to my game, reicast stop working and galaxy s3 come back to the home menu. Can you do something for futur release?? (implant save states or something like this??)

**Comment by BiYao** [comment]
This emulator cannot be run in the background.

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/issues/301

**Comment by blackman91** [comment]
Relevant:
https://github.com/reicast/reicast-emulator/issues/152

**Comment by skmp** [comment]
Merging with #152
