### ISSUE TITLE
Error invalid convertion when i use make install

### ISSUE THREAD

**Issue by JamesAndresCM** [reicast/reicast-emulator#943]
Hi, I receive this message when i try to compile using make under archlinux ..

`Platform: x64 sse4_1
mkdir -p obj-dreamcast-x64-sse4_1/rend/soft/
g++   -I../../core -I../../core/deps -I../../core/khronos  -D TARGET_LINUX_x64 -D TARGET_NO_AREC -fsingle-precision-constant -g -O3 -D RELEASE -c -D USES_HOMEDIR  -frename-registers -fno-strict-aliasing -ffast-math -ftree-vectorize -fomit-frame-pointer -D SUPPORT_X11 -fopenmp -msse4.1   -fexceptions -fno-rtti -fpermissive -fno-operator-names -D SUPPORT_X11  -D USE_EVDEV -D USE_JOYSTICK -D USE_ALSA -D USE_OSS -DTARGET_SOFTREND ../../core/rend/soft/softrend.cpp -o obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj
../../core/rend/soft/softrend.cpp: En la función miembro ‘__m128 softrend::shuffle_pixel(__m128)’:
../../core/rend/soft/softrend.cpp:1167:76: error: conversión inválida de una expresión r-valuada de tipo ‘__m128i {aka __vector(2) long long int}’ al tipo ‘__m128& {aka __vector(4) float&}’
   return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1,0)));
                                                                            ^
make: *** [Makefile:318: obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Error 1
`

the file that contain the error is core/rend/soft/softrend.cpp, I ve seen that the problem maybe is value of return, but i can't understand all the code...

**`return (__m128&)_mm_shuffle_epi8((__m128i&)v, _mm_set_epi8(R(0x80,2,1,0)));**`

please help me

**Comment by 7oxicshadow** [comment]
known issue. there is a branch of code that fixes this but it has never been merged into the master branch

For ease, the following commit works (although the author does consider it a bit hacky)

https://github.com/reicast/reicast-emulator/pull/900/commits/dbde54e27ad0d2533db7eb59989818f562969399

**Comment by JamesAndresCM** [comment]
Thank you for your help, now it works!

**Comment by TheBurgerGuy** [comment]
What is The current build I would like to test it out

**Comment by LoungeKatt** [comment]
@TheBurgerGuy Full details about where to get builds, how to build yourself, etc are included in the readme which can be viewed by going to the main repository page and scrolling down.

**Comment by baka0815** [comment]
Refer to reicast.com (or builds.reicast.com) for current builds.

Closing this as @JamesAndresCM said it's working.
Please reopen if not.
