### ISSUE TITLE
Unable to open emu.cfg then SIGSEGV and crash

### ISSUE THREAD

**Issue by edgarsuit** [reicast/reicast-emulator#944]
I've got reicast loaded on my Shield Tablet K1, but it crashes to the Android desktop any time I try to boot a game. I can successfully boot the BIOS and interact with it, etc, but games won't load. I'm running the latest build from builds.reicast.com.

I've moved the BIOS files and the ROM files to internal memory. Here are the last few lines of the log file when I attempt to boot Grandia II:

07-12 11:18:22.157 22729 22729 I reicast : Opening file: '/sdcard/reicast/Grandia II (Europe).gdi'
07-12 11:18:22.157 22729 22729 I reicast : ARM VFP-Run Fast (NFP) enabled !
07-12 11:18:22.157 22729 22729 I reicast : Linux paging: 00001000 00001000 00000FFF
07-12 11:18:22.157 22729 22729 I reicast : MAP 00800000 w/ 25165824
07-12 11:18:22.157 22729 22729 I reicast : MAP 20000000 w/ 25165824
07-12 11:18:22.157 22729 22729 I reicast : MAP 04000000 w/ 16777216
07-12 11:18:22.157 22729 22729 I reicast : MAP 06000000 w/ 16777216
07-12 11:18:22.157 22729 22729 I reicast : MAP 0C000000 w/ 0
07-12 11:18:22.157 22729 22729 I reicast : A8
07-12 11:18:22.157 22729 22729 I reicast : vmem reserve: base: 7F200000, aram: 9f200000, vram: 83200000, ram: 8B200000
07-12 11:18:22.157 22729 22729 I reicast : Resetting mem
07-12 11:18:22.201 22729 22729 I reicast : Mem alloc successful!
07-12 11:18:22.201 22729 22729 I reicast : Virtual cfg config:image=/sdcard/reicast/Grandia II (Europe).gdi
07-12 11:18:22.201 22729 22729 I reicast : 
07-12 11:18:22.202 22729 22729 I reicast : Warning: Unable to open the config file '/emu.cfg' for reading (No such file or directory)
07-12 11:18:22.202 22729 22729 I reicast : Creating new empty config file at '/emu.cfg'
07-12 11:18:22.202 22729 22729 I reicast : Error : Unable to open file for saving 
07-12 11:18:22.202 22729 22729 I reicast : Error : Unable to open file for saving 
07-12 11:18:22.202 22729 22729 I reicast : Error : Unable to open file for saving 
07-12 11:18:22.202 22729 22729 I reicast : Error : Unable to open file for saving 
07-12 11:18:22.202 22729 22729 I reicast : SIGSEGV @ 0xa01fb030 (fault_handler+0x0x683940) ... 0x0 -> was not in vram

**Comment by edgarsuit** [comment]
Figured it out, the ROM dump I was using was crap. I got a new dump and it's working great now!

**Comment by LoungeKatt** [comment]
Glad to hear it was an easy fix.
