### ISSUE TITLE
Marvel vs. Capcom 2 randomly freezes.

### ISSUE THREAD

**Issue by TooDamnCringy** [reicast/reicast-emulator#947]
Whenever battling during 3rd or 4th stage, it randomly freezes. I try to leave game, but it doesn't work. So I closed reicast and went back. It ran back again as nothing had happened. But the freezing keeps popping up.

**Comment by TooDamnCringy** [comment]
It's on android by the way.

**Comment by twinaphex** [comment]
The dynarec will randomly crash for this game yes. It's yet one of those dynarec bugs that nobody bothered to fix, setting up some nonprofit is apparently far more important than showing a little love to fans of your emulator.

In reicast libretro I take care of this by using the 'cached interpreter' JIT, this is a lot slower but at least you can run the game without any crippling crashes.

**Comment by robertybob** [comment]
@twinaphex Does the Libretro build now officially have better compatibility vs. standalone Reicast?

**Comment by RaduNastase** [comment]
Ok, but is there an actual reicast core for Android? As far as i know there is not.

**Comment by twinaphex** [comment]
@robertybob Well I baked in the generic JIT and when Marvel Vs Capcom 2 is detected, it will switch to that instead. So I guess yeah. 

Anyway, I was booted from the team here so I guess for further questions you have, you can go to the libretro repo.  As for Reicast for Android, I'll try looking into it. I just never got to it before.

**Comment by LoungeKatt** [comment]
There is a core for Android, but having skimmed some of the comments made on other issues, I am not the least bit surprised that removal happened. It does not, however, prevent submitting changes. It would only prevent direct modification of the repository.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#82
