### ISSUE TITLE
keyboard freeze after press esc key.

### ISSUE THREAD

**Issue by asakous** [reicast/reicast-emulator#948]
I'm using Armbian  on orange Pi PC and it's ok to play games under SDL2 framebuffer mode
but if I quit the game by press esc key, the keyboard immediately freeze but OS still working .  I still can ssh to connect the host.
here is my test
[https://www.youtube.com/watch?v=dwameC76m8I](url)

**Comment by baka0815** [comment]
Is this still an issue?

**Comment by skmp** [comment]
(Closing, ticket cleanup. Please report in chat.reicast.com if still an issue)
