### ISSUE TITLE
Please explain how to download

### ISSUE THREAD

**Issue by Anuysh** [reicast/reicast-emulator#949]
I have a windows vista 32-bit os. I loved the dreamcast and would like to try your emulator. but it's confusing to me. when I tried to unzip nullDC_104_r136.7z to program files, kept getting error on all files stating that the computer couldn't open the file. Thanks for your time

**Comment by caleb90** [comment]
Where are you downloading it from?
Reicast builds are located at
http://builds.reicast.com/
You would need the Win_x86 version

**Comment by baka0815** [comment]
This is an issue tracker, not a support forum. Use forum.reicast.com for support.
