### ISSUE TITLE
I have a Samsung Note 5 

### ISSUE THREAD

**Issue by TheBurgerGuy** [reicast/reicast-emulator#951]
It runs Well with only sonic adventure 2 . It says it handles 64 bit apps don't know what that is But I'll test stuff out if you guys want Android 6.0.1

**Comment by TheBurgerGuy** [comment]
Hi just wondering if you have any beta test I'll Run For you guys on Samsung Note 5

**Comment by LoungeKatt** [comment]
You can download betas at http://builds.reicast.com/
