### ISSUE TITLE
Compilation error with 'make' Linux

### ISSUE THREAD

**Issue by Joffr3y** [reicast/reicast-emulator#952]
Hello, 
I have an error during the compilation:
`make: *** [Makefile:318: obj-dreamcast-x64/linux-dist/evdev.build_obj] Error 1`
http://pastebin.com/Nj60tL2s

With this corrective dbde54e
`make: *** [Makefile:318: obj-dreamcast-x64-sse4_1/linux-dist/evdev.build_obj] Error 1`
http://pastebin.com/JsgPAeCH

Config:
OS: Arch Linux x86_64
Kernel Release: 4.6.4-1-ARCH
Make 4.2.1

Thanks

**Comment by lollo78** [comment]
Compilation issue also on Ubuntu 16.04:`
make: *** [obj-dreamcast-x64-sse4_1/rend/soft/softrend.build_obj] Errore 1`

**Comment by sl1pkn07** [comment]
try build with cmake instead

**Comment by Pollito001** [comment]
Im build with cmake  but reicast is really slow compared when we compile with make in /shell/linux/, But now have compile error.

**Comment by jojotango** [comment]
Yes when I build with Cmake it works thanks

**Comment by randomstuff** [comment]
@Pollito001 Did you use the `Release` type in your cmake build?

**Comment by rrrh** [comment]
Hi @jojotango 
May I ask if this is still an issue? Wanted to have a look at the issue but both pastbins are "page removed" over time.

**Comment by skmp** [comment]
(closing this as it is most likely fixed. Please open a new ticket if it still an issue)
