### ISSUE TITLE
Official Reicast Website is down?

### ISSUE THREAD

**Issue by DoctorHerobrine** [reicast/reicast-emulator#955]
This isn't an issue with the emulator, is the official website down? I'm getting error 503 Service Temporarily Unavailable when trying to access the website.
![untitled](https://cloud.githubusercontent.com/assets/21069130/17718058/c1ba0dee-6409-11e6-9130-fb3be5bf7f80.png)

**Comment by Zetchzie** [comment]
its been doing that for a month now. only thing that opens is the builds section.

**Comment by skmp** [comment]
Restarted the server

**Comment by Holzhaus** [comment]
It works now. Closing.
