### ISSUE TITLE
Assign right controller as left controller / dpad

### ISSUE THREAD

**Issue by ruthan** [reicast/reicast-emulator#958]
Hello,
i wanted to play Quake 3 and UT Dreamcast version, its working, but i have controlls isssue, 
i have 2 stick gamepad - Gamesir 3 and i want to use dpad for movement, after that its akward to play,
because for  mouselook is used  hardcoded leftstick..
   I would be much better if i have possiblity to map contollers left stick to real controller right stick,
after that i would be able use both stick like on modern console, but dpad and rightstick would be also nice..

**Comment by LoungeKatt** [comment]
I'm not sure I understand the issue, but all hardware controls should support mapping to the virtual controls of reicast using the configuration menu.

**Comment by AbandonedCart** [comment]
Merging this into https://github.com/reicast/reicast-emulator/issues/1103
