### ISSUE TITLE
Shenmue Crash

### ISSUE THREAD

**Issue by ask519** [reicast/reicast-emulator#960]
Game crashes on disc 3 whenever you enter old Warehouse no. 8 to meet Gui Zhang. This is required to progress in game

Device: Xiaomi Mi Pad 1 (Tegra K1 - quadcore version)
OS: MIUI 7 (Android 4.4.4)

**Comment by dreamboyn81** [comment]
还有莎木2。。。

**Comment by twinaphex** [comment]
There are random crashes ever since a specific revision of nullDC, and apparently nobody knows how to fix it.

**Comment by VarelaPet** [comment]
I have the same problem, so it seems to be something general. In my case, my device is a Minix Neo U1 with Android 5.1.1 Lollipop. Please, I beg you to fix it so one of the best games on the Dreamcast's catalogue is fully playable.

**Comment by VarelaPet** [comment]
I wanted to share with you the specific moment in which the game fatally crashes and doesn't allow you to continue.

https://www.youtube.com/watch?v=D7neI8VCMY4

It happens after Ryo goes to get his pay at the Alpha Trading Office, (minute 6:50:55 in the video). After that moment, the game crashes and you cannot continue playing. I will also upload my saved game file, just in case that helps.

Thanks in advance.

**Comment by VarelaPet** [comment]
Hello again. A guy at Shenmue Dojo has helped me out with this. Here is the answer:

I just finished Shenmue 1 with Reicast on an AFTV2.

You can get past the warehouse 8 crash on CD3. In my case I experienced the crash as well, but on the next load I talked to the lunch lady, but let the prompt to look after her sister time out (she takes it as a - no) - and then just entered the old warehouse district, without delivering the meals to the guards, past eight pm. That way the game would not crash and allowed me to continue.

Reicast build used was either

f5f3332 or
73e2691

Can't remember. :)

Have fun continuing the game.

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#84
