### ISSUE TITLE
lastest CI builds crash on GPD XD

### ISSUE THREAD

**Issue by ldaneels** [reicast/reicast-emulator#967]
I'm having a hard time using the new Reicast CI builds (released yesterday) on my GPD XD.
I am using the LegacyRom by Skelton.
Each time I try to set up the emulator it crashes, whether I try to set bios / GDI paths or to tweak general settings.
The most recent stable release works just fine (although that is beside the point, I would like to take advantage of 2+ years of progress on the emulator, if only for Mars Matrix) & the first time I used the new CI build (released a few days ago), it worked fine, but since I restarted the GPD, I can't get Reicast to behave (I also did try to reinstall the same CI build I used previously to no avail)...
Any help would be greatly appreciated.

**Comment by LoungeKatt** [comment]
Please post a log. This is not only a device-specific issue, but it is not a major manufacturer or common device.

**Comment by ldaneels** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1474228583976.txt
Hi that would be a good idea indeed. Hopefully that is the log.

**Comment by EPe9686518** [comment]
I too have the same issue on my GPD XD, which is a fantastic device for emulation and can run most dreamcast games at max res and full speed. Also runs most PSP games great too. As noted above, the official stable release worked fine with no crashes, but all of the recent CI builds I have tried work perfectly fine at first (I have tested 10 to 20 games on them with no issues and run great and much faster than the official build), then when you go back to the emulator after a reboot of the device, the bios, games, nothing will load. It starts to, but always crashes with an error and a log. Then seemingly randomly, you will try it and it will load games just fine and have no issues. I will try to post my log as well

**Comment by EPe9686518** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1474556077804.txt

**Comment by EPe9686518** [comment]
One more log. Emulator was working fine, rebooted the device, and same problem, game crashed with this error.

http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1474556420006.txt

**Comment by LoungeKatt** [comment]
Thanks for the logs. I am looking into this one now.

**Comment by ldaneels** [comment]
Hi, thanks for the help, the new version works perfectly.
Cheers,

Loic

**Comment by EPe9686518** [comment]
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1474974019486.txt

**Comment by tstee** [comment]
Same problem here.

**Comment by LoungeKatt** [comment]
It looks like there is something unusual about the GPD gamepad. It is common for "third-party" device manufacturers to use specialized layouts or even hacky configurations. This is similar to the Xperia Play's touchpads. The fix will require investigating the device's key layout and make take a little time.

**Comment by EPe9686518** [comment]
That makes sense, as the GPD does use a gamepad software to emulate either a PS3 or a Xbox 360 controller. Also makes sense why Idaneels isn't experiencing any issues now, as hes using LegacyRom by Skelton firmware and not the default, which his might not have that gamepad software.

**Comment by ldaneels** [comment]
Hey there, I would like to say that while I do use the LegacyRom by Skelton, as far as I'm aware, I am still using the android Gamepad app (sure does look like it, at least), so I don't think it would have any impact. Also, the Nullpad version does not work for me, so I'm using a overclocked 1.8 version without Nullpad.

**Comment by LoungeKatt** [comment]
A friend finally got one of these, but unfortunately has no issue with it so far. He did mention wanting to update the builds because it ships with HappyChic, which was the all-in-one app previously cited for stealing open source content without respecting the licensing. I am not sure if they publish the code, as per the license, but at least stopped disguising the project as their own. I will hopefully get a chance to see how the current builds do in the near future.

**Comment by ldaneels** [comment]
I have tried both recent releases and I have had no trouble whatsoever.
Now, if only Rez's jumbled graphics could be fixed, I'd be in heaven :)
At any rate, thanks for the new builds, I have noticed some improvements overall on GPD XD.

**Comment by TheBurgerGuy** [comment]
What is the link of this latest version you have I'm having issues on my Samsung Galaxy Note 5, It recently updated to 7.0 android so now it like does this spin with the camera  on some games

**Comment by uhbandduhn** [comment]
Try http://builds.reicast.com/ or building from source.

**Comment by ldaneels** [comment]
yep, you got to it before I did :)
At any rate, I tried both the one from the 15th and the one from the 18th. I couldn't see any difference between the two, but both were performing better than last year's latest build.

**Comment by skmp** [comment]
Closing as this seems resolved now. Please re-open if it is still an issue.
