### ISSUE TITLE
Gamepad!!!

### ISSUE THREAD

**Issue by Dank200088** [reicast/reicast-emulator#969]
why you do not simultaneously support two triggers Rt and Lt physical gamepad ?
you simultaneously press these buttons in your controller

**Comment by LoungeKatt** [comment]
The code is designed to handle them at the same time, but the system may limit how quickly it registers, since Android only supports a single instance of the motion handler.

https://github.com/reicast/reicast-emulator/blob/master/shell/android/src/com/reicast/emulator/GL2JNIActivity.java#L240
