### ISSUE TITLE
error accessing configurations.

### ISSUE THREAD

**Issue by MezaCorleehone** [reicast/reicast-emulator#970]
It does not allow access to configuration.
the emulator stops.

![screenshot_2016-09-20-17-51-38 1](https://cloud.githubusercontent.com/assets/17937166/18691616/5158565c-7f5a-11e6-81bc-de08d025c5aa.png)

**Comment by BiYao** [comment]
Click settings will automatically exit   me too

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/pull/975 will fix this issue.
