### ISSUE TITLE
Crash when open settings in latest Android builds.

### ISSUE THREAD

**Issue by skelton** [reicast/reicast-emulator#974]
The last buiñds it worked fine was the one from 12th septiember. Yested on NVIDIA shield tabket, shield tv, gpd xd and redmi note 2 all android.
Log
http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1474661272580.txt

**Comment by LoungeKatt** [comment]
https://github.com/reicast/reicast-emulator/pull/975 should fix this issue.
