### ISSUE TITLE
Shenmue: Hang On and Space Harrier

### ISSUE THREAD

**Issue by VarelaPet** [reicast/reicast-emulator#979]
Hi there!
Thanks for fixing the sound in Hang On on your latest build (now you can play it with sound), but Space Harrier still throws you out to the emulator's menu when you try to play it in the You Arcade. Can that be fixed?
Thanks in advance,

Device: AndroidTV Minix Neo U1
OS: Lollipop 5.1

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#104
