### ISSUE TITLE
Audio broken in OTOIRE Sequencer

### ISSUE THREAD

**Issue by hooby3dfx** [reicast/reicast-emulator#98]
This game:
http://segaretro.org/O.to.i.Re:_Dreamcast_Sequencer

None of the music tracks play. 

This game supports the mic, so I was hoping to use it to test. 

The mic recording screen is pretty advanced and has an audio graph which I can see move with mic support!

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#32
