### ISSUE TITLE
Error in Building [Android]

### ISSUE THREAD

**Issue by AntiSaby47** [reicast/reicast-emulator#981]
I'm trying to Build the Android project. This is the error log that I get.

`-pre-build:
     [exec] Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml
     [exec] $TARGET_ARCH_ABI is [armeabi-v7a]
     [exec] $TARGET_ARCH_ABI is [x86]
     [exec] $TARGET_ARCH_ABI is [mips]
     [exec] [armeabi-v7a] SharedLibrary  : libsexplay.so
     [exec] [x86] SharedLibrary  : libsexplay.so
     [exec] [armeabi-v7a] SharedLibrary  : libdc.so
     [exec] [x86] SharedLibrary  : libdc.so
     [exec] [mips] SharedLibrary  : libdc.so
     [exec] D:/Softwares/Android/NDK/android-ndk-r11c/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.exe: warning: shared library text segment is not shareable
     [exec] jni/../jni/../../../core/deps/libwebsocket/context.c:125: error: undefined reference to 'getdtablesize'
     [exec] collect2.exe: error: ld returned 1 exit status
     [exec] make: *** [obj/local/armeabi-v7a/libdc.so] Error 1
     [exec] make: *** Waiting for unfinished jobs....
     [exec] D:/Softwares/Android/NDK/android-ndk-r11c/build//../toolchains/x86-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld.exe: warning: shared library text segment is not shareable
     [exec] jni/../jni/../../../core/deps/libwebsocket/context.c:125: error: undefined reference to 'getdtablesize'
     [exec] collect2.exe: error: ld returned 1 exit status
     [exec] make: *** [obj/local/x86/libdc.so] Error 1
     [exec] ./obj/local/mips/objs/dc/jni/__/__/__/core/deps/libwebsocket/context.o: In function`libwebsocket_create_context':
     [exec] D:\AntiSabyProductions\Projects\Android\Reicast\shell\android/jni/../jni/../../../core/deps/libwebsocket/context.c:125: undefined reference to `getdtablesize'
     [exec] collect2.exe: error: ld returned 1 exit status
     [exec] make: **\* [obj/local/mips/libdc.so] Error 1

BUILD FAILED
D:\AntiSabyProductions\Projects\Android\Reicast\shell\android\custom_rules.xml:11: exec returned: 2

Total time: 32 seconds`

**Comment by LoungeKatt** [comment]
Are you performing a clean before building? Just ran a test build with no issues, so it appears it may be an issue in the local compile process.

**Comment by AntiSaby47** [comment]
I tried clean before the build too. It always fails at the same line like in the log above.

**Comment by mrcmunir** [comment]
I can confirm on this is broken by recents NDK problem linker in libwebsockets any solution?

**Comment by LoungeKatt** [comment]
I think this has long been resolved.
