### ISSUE TITLE
Bluetooth Headphone (android), cause reicast to become slideshow

### ISSUE THREAD

**Issue by hyakki-** [reicast/reicast-emulator#984]
When using Reicast for Android (5-6x), with any bluetooth headset will cause the game to slow to slide show speed, however when using wired headphone or none, the game is 100% speed and plays fine, so I think the audio buffer needs to be increased for BT support, I can only test on Snapdragon SOCs so it might not be affecting other devices.

ppsspp and other emulators have a workaround (since they were also effected by the same issue) found by increasing the buffer size., however this might need to be an option so it doesn't effect normal playback.
github.com/hrydgard/ppsspp/pull/8846/commits/1307554a5f632497232f789f0daffdd3dc97d1ac

**Comment by AbandonedCart** [comment]
Is this still an issue?

**Comment by skmp** [comment]
(Closing as part of ticket cleanup. Please report in chat.reicast.com if still an issue)
