### ISSUE TITLE
How to build a max 720p res. build of Reicast?

### ISSUE THREAD

**Issue by Roet-Ivar** [reicast/reicast-emulator#989]
I wonder how much work it would require to make an android build that forces internal resolution to a max of 1280x720 720p? My understanding is that the resolution is based on the device screen resolution?

If I could get some pointers whew to start I'd like to test for myself and learn something!

**Comment by skmp** [comment]
Hello,

I do not think this is possible right now. 

It's probably best to ask those things in the forum (http://forum.reicast.com/)
