### ISSUE TITLE
Shenmue 2/Test Drive Le Mans crashing

### ISSUE THREAD

**Issue by dreamesper** [reicast/reicast-emulator#991]
Hey everyone, new to github here. I have been following the REICAST project for years and love all the work that you do. Plus, the new builds are fantastic for Android so thanks for that!

Question:  Are there any plans on getting a new build worked on so that games like SHENMUE 2 & TEST DRIVE Le MANS boot & run properly? I use a gpd xd and when I load these two games up, Shenmue 2 does NOT get passed the intro on the boat... with Le MANS, the main intro to the game fails to load & crashes.

These are two fantastic games for Dreamcast that I wish would receive more input so that they play properly. Any news would be awesome, thanks everyone!

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#103
