### ISSUE TITLE
Intel Atom DualCore 1.6ghz slow

### ISSUE THREAD

**Issue by andreol263** [reicast/reicast-emulator#992]
Well, i've tested Ikagura and Legacy of Kain:Soul Reaver on the latest build of Reicast and they are running pretty slow(40-50 fps), there's nothing i can do to improve the speed? my cpu is not fast enough?

Thanks in advance

**Comment by AbandonedCart** [comment]
Features have been added to overcome some speed issues, but there will always be some that are simply the device. Closing this for now, but please reopen if you find that the speed slows down from a previous build (meaning something we did slowed it down).
