### ISSUE TITLE
Can't configure analog stick for external controller

### ISSUE THREAD

**Issue by ZalgoNoise** [reicast/reicast-emulator#994]
I have an android compatible Nyko Playpad Pro bluetooth controller and it works perfectly well with Reicast but I cannot program the analog controls. It doesn't show up in config, only the DPad keys. 

Thank you for your excellent work on this emulator. No complains about anything else.

**Comment by AbandonedCart** [comment]
Merging this into https://github.com/reicast/reicast-emulator/issues/1103
