### ISSUE TITLE
Rez with persistent interference pattern.

### ISSUE THREAD

**Issue by Reznaut** [reicast/reicast-emulator#995]
Rez on reicast has the graphical glitch below. Happens with gdi and cdi PAL game images. Happens on LG G4 and also in an old Samsung Epic Galaxy S. Also happened on a TUVVA android tablet. Anyone else with the same issue or a fix? 

The interference pattern is always there and does not move. It does not affect the lateral edges on widescreen, the flying dude, or the bad guys.

Running : reicast-android-debug-aca9cb6

![capture _2016-12-27-20-47-58](https://cloud.githubusercontent.com/assets/9502674/21512027/33af0646-cc76-11e6-91b5-032758f9d818.png)

**Comment by Reznaut** [comment]
The interference pattern is always there and does not move. It does not affect the lateral edges on widescreen, the flying dude, or the bad guys.

**Comment by skmp** [comment]
Is this still an issue with the latest beta from #1208? Also should be moved to gamedb

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#102
