### ISSUE TITLE
Volgarr the Viking crash

### ISSUE THREAD

**Issue by NivekGreece** [reicast/reicast-emulator#999]
I downloaded it for free from the official site of the game here: http://volgarr.rkd.zone
I even checked the help forums inside the site but i found nothing. I tried the game on nulldc on pc and works ok. Many people said that works on their dreamcast.
For me it crashes on android reicast r6 and r7 (i tried 4-5 builds) and no luck.
Thank you for your time.
Marios.

**Comment by Sarkie** [comment]
What about the latest? http://builds.reicast.com/

**Comment by NivekGreece** [comment]
Yep i already tried them :(

**Comment by hooby3dfx** [comment]
Aw, such a good game!

**Comment by NivekGreece** [comment]
Just some info.. i'm on nvidia shield k1 rooted, stock rom 1.4.
Tested on latest g.play and latest builds. Bios and everything else in place. I already played zombie revenge with success! So i know it works :P 
Thanks again for your time :)

**Comment by blackman91** [comment]
Latest build can run this game, so this should be closed, download from here:
http://www.volgarrtheviking.com/dreamcast/

**Comment by skmp** [comment]
This issue was moved to reicast/gamedb#101
